package com.iii.pel.forms.PILP003_APAC;

public interface PILP003_APAC_SQLConstants {
	// Base_Curr changes PREMIAGDC-0030 : Added by Shankar Bodduluri : 25/03/09	
	//String preFormsql_C1 = "SELECT PARA_VALUE FROM FP_PARAMETER WHERE PARA_ID = 'BASE.CURR'";
	String preFormsql_C1 = "SELECT PARA_VALUE FROM FP_PARAMETER WHERE PARA_ID = ?";
	
	String when_new_forms_instance_sql_C1 = "SELECT DECODE(NVL(CLASS_FACIN_YN,'N'),'N','D','I') FROM PM_IL_CLASS WHERE CLASS_CODE = (SELECT POL_CLASS_CODE FROM PT_IL_POLICY WHERE POL_NO = ? AND POL_DS_TYPE ='2') ";
	
	String when_new_forms_instance_sql_C4 = "SELECT NVL(PS_VALUE, 0) FROM PP_SYSTEM WHERE PS_TYPE  = 'ILCALCMTHD' ";
	
	String when_new_forms_instance_sql_C5 = "SELECT SUB_ACNT_NAME FROM FM_SUB_ACCOUNT WHERE SUB_ACNT_CODE  = ? ";
	
	String P_VAL_SYSTEM_query = "SELECT PS_CODE_DESC,PS_BL_CODE_DESC,PS_VALUE FROM PP_SYSTEM WHERE PS_TYPE = ? AND PS_CODE = ?";
	
	String L_VALIDATE_POL_NO_sql_C1 = "SELECT POL_SYS_ID,POL_CASH_YN,POL_DIVN_CODE,POL_CUST_CODE FROM PT_IL_POLICY WHERE POL_NO = ? AND POL_DS_TYPE ='2' AND NVL(POL_STATUS,'N')!= 'N' ";
	
	String L_VALIDATE_APPRV_DATE_sql_C1 = "SELECT MAX(PC_PAID_DT) FROM PT_IL_PREM_COLL WHERE PC_POL_SYS_ID  = ? AND NVL(PC_PAID_FLAG, 'N') = 'Y' ";
	
	String L_VALIDATE_APPRV_DATE_sql_C2 = "SELECT PC_PAID_DT FROM PT_IL_PREM_COLL WHERE PC_POL_SYS_ID = ? AND PC_PAID_DT IS NOT NULL AND NVL(PC_PAID_FLAG,'N') = 'Y' ";
	
	String FETCH_CUSTOMER_LOV_QUERY = "SELECT CUST_CODE,CUST_NAME FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM WHERE  DECODE (PS_VALUE,2,CCLAS_CODE, CCLAS_TYPE)IN ('006','001')AND PS_CODE = 'CASH' AND PS_TYPE = 'LOV_CUST')AND CUST_FRZ_FLAG = 'N' AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM PM_CUST_DIVN WHERE CDIV_DIVN_CODE = NVL (NULL,CDIV_DIVN_CODE) AND CUST_APPL_ALL_BRAN_YN = 'N'))OR (CUST_APPL_ALL_BRAN_YN = 'Y')) AND ROWNUM<21";
	
	String FETCH_CUSTOMER_LOV_SUGGESTION_LIKE_QUERY = "SELECT CUST_CODE,CUST_NAME FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM WHERE  DECODE (PS_VALUE,2,CCLAS_CODE, CCLAS_TYPE)IN ('006','001')AND PS_CODE = 'CASH' AND PS_TYPE = 'LOV_CUST')AND CUST_FRZ_FLAG = 'N' AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM PM_CUST_DIVN WHERE CDIV_DIVN_CODE = NVL (NULL,CDIV_DIVN_CODE) AND CUST_APPL_ALL_BRAN_YN = 'N'))OR (CUST_APPL_ALL_BRAN_YN = 'Y')) AND CUST_CODE LIKE ?";

	String FETCH_CUSTOMER_LOV_QUERY1 = "SELECT CUST_CODE, CUST_NAME FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM WHERE  DECODE (PS_VALUE,2,CCLAS_CODE, CCLAS_TYPE)IN ('001','002','003','004','005','006','009') AND PS_CODE = 'CASH' AND PS_TYPE = 'LOV_CUST') AND CUST_FRZ_FLAG = 'N' AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM PM_CUST_DIVN WHERE CDIV_DIVN_CODE = NVL (NULL, CDIV_DIVN_CODE) AND CUST_APPL_ALL_BRAN_YN = 'N'))OR (CUST_APPL_ALL_BRAN_YN = 'Y'))";
	
	String FETCH_CUSTOMER_LOV_SUGGESTION_LIKE_QUERY1 = "SELECT CUST_CODE,CUST_NAME FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM WHERE  DECODE (PS_VALUE,2,CCLAS_CODE, CCLAS_TYPE)IN ('001','002','003','004','005','006','009') AND PS_CODE = 'CASH' AND PS_TYPE = 'LOV_CUST') AND CUST_FRZ_FLAG = 'N' AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM PM_CUST_DIVN WHERE CDIV_DIVN_CODE = NVL (NULL, CDIV_DIVN_CODE) AND CUST_APPL_ALL_BRAN_YN = 'N'))OR (CUST_APPL_ALL_BRAN_YN = 'Y')) AND CUST_CODE LIKE ? ";
	
	String OK_WHEN_BUTTON_PRESSED_sql_C1="SELECT 'X' FROM  PT_IL_LOAN WHERE LOAN_POL_SYS_ID = ? AND NVL(LOAN_STATUS, 'N')  = 'A' ";
}
