package com.iii.pel.forms.PILM041;

public interface PILM041_SQLQUERY_CONSTANTS {

	final String DELETE_PM_IL_FUND_ACCOUNT_SETUP="DELETE FROM PM_IL_DATA_UPLOAD_MAPPING WHERE ROWID= ?";
	final String UPDATE_PM_IL_FUND_ACCOUNT_SETUP="UPDATE * FROM PM_IL_DATA_UPLOAD_MAPPING WHERE ROWID=?";
	final String SELECT_ALL_PM_IL_DATA_UPLOAD_MAPPING=" select PM_IL_DATA_UPLOAD_MAPPING.ROWID,DUM_MAP_CODE,DUM_MAP_CODE_DESC,DUM_DEF_CODE,DUM_FIELD_01,DUM_FIELD_02,DUM_FIELD_03,DUM_FIELD_04,DUM_FIELD_05,DUM_FIELD_06,DUM_FIELD_07,DUM_FIELD_08,DUM_FIELD_09,DUM_FIELD_10,DUM_FIELD_11,DUM_FIELD_12,DUM_FIELD_13,DUM_FIELD_14,DUM_FIELD_15,DUM_FIELD_16,DUM_FIELD_17,DUM_FIELD_18,DUM_FIELD_19,DUM_FIELD_20 from PM_IL_DATA_UPLOAD_MAPPING";
//	final String LOV_FAS_SRC_BUS_FM_TO="SELECT PC_CODE,PC_DESC,PC_BL_DESC FROM PM_CODES" +
//			" WHERE PC_TYPE ='SRC_BUS_TY'AND NVL(PC_FRZ_FLAG,'N') = 'N'";
//	final String LOV_FAS_DEPT_FM_TO_CODE="SELECT DEPT_CODE,DEPT_NAME,DEPT_CODE " +
//			"FROM PM_DEPARTMENT WHERE DEPT_COMP_CODE = ':CTRL.M_COMP_CODE' AND " +
//			"DEPT_DIVN_CODE = ':PM_IL_FUND_ACCOUNT_SETUP.FAS_DIVN_FM_CODE' AND " +
//			"DEPT_FRZ_FLAG  = 'N' AND EXISTS (SELECT 1 FROM PM_APPR_DEPT_SETUP " +
//			"WHERE ADS_DIVN_CODE = DEPT_DIVN_CODE AND ADS_DEPT_CODE = DEPT_CODE" +
//			" AND ADS_USER_ID = NVL('&M_PARA_3',ADS_USER_ID) ANDADS_FRZ_FLAG = 'N')";
//	final String LOV_FAS_DOC_FM_TO_TYPE="SELECT DS_CODE,DS_DESC FROM " +
//			"PM_IL_DOC_SETUP WHERE ( DS_TYPE = '2' OR DS_TYPE = '2')  AND" +
//			"  NVL(DS_FRZ_FLAG ,'N') ='N'";
	
	/*Added by ganesh on 31-05-2017, ZBILQC-1724500 */
	/*
	 * Modified By Dhinesh on 09-10-2017
	 * 
	 * final String POL_EMPLOYER_CODE_LOV = "SELECT CONT_CODE, CONT_NAME  FROM PM_IL_CONTRACTOR WHERE CONT_EMPLOYER_YN ='Y' AND ROWNUM < ? UNION SELECT BANK_CODE,BANK_NAME FROM FM_BANK WHERE ROWNUM < ?";
	final String POL_EMPLOYER_CODE_LOV_LIKE = "SELECT CONT_CODE, CONT_NAME  FROM PM_IL_CONTRACTOR WHERE CONT_EMPLOYER_YN ='Y' AND (UPPER(CONT_CODE) LIKE ? OR UPPER(CONT_NAME) LIKE ?) AND ROWNUM < ? UNION SELECT BANK_CODE,BANK_NAME FROM FM_BANK WHERE (UPPER(BANK_CODE) LIKE ? OR UPPER(BANK_NAME) LIKE ?) AND ROWNUM < ?";
	*/
	
	/* Newly Added By Dhinesh on 09-10-2017 */
	final String POL_EMPLOYER_CODE_LOV = "SELECT CUST_CODE,CUST_NAME FROM PM_CUSTOMER,PM_CUST_CLASS  WHERE CUST_CLASS = CCLAS_CODE  AND CCLAS_TYPE = '001' AND CUST_FLEX_SEL_01 = 'Y'   AND ROWNUM < ? UNION SELECT BANK_CODE, BANK_NAME FROM FM_BANK WHERE ROWNUM < ? ";
	final String POL_EMPLOYER_CODE_LOV_LIKE = "SELECT CUST_CODE,CUST_NAME  FROM PM_CUSTOMER,PM_CUST_CLASS  WHERE CUST_CLASS = CCLAS_CODE  AND (UPPER(CUST_CODE) LIKE ? OR UPPER(CUST_NAME) LIKE ?)  AND CCLAS_TYPE = '001' AND CUST_FLEX_SEL_01 = 'Y'  AND ROWNUM < ? UNION SELECT BANK_CODE, BANK_NAME  FROM FM_BANK  WHERE (UPPER(BANK_CODE) LIKE ? OR UPPER(BANK_NAME) LIKE ?)  AND ROWNUM < ? ";
    /* End */
	
	
	/*end*/
}
