package com.iii.pel.forms.PP0100;

public class PP0100_COMPOSITE_ACTION {

	private PP0100_PT_IL_POLICY_ACTION PP0100_PT_IL_POLICY_ACTION_BEAN;
	
	private PT_IL_POLICY PT_IL_POLICY_BEAN;
	
	public PP0100_COMPOSITE_ACTION() {
		// TODO Auto-generated constructor stub
		PP0100_PT_IL_POLICY_ACTION_BEAN = new PP0100_PT_IL_POLICY_ACTION();
		PT_IL_POLICY_BEAN = new PT_IL_POLICY();
	}

	public PP0100_PT_IL_POLICY_ACTION getPP0100_PT_IL_POLICY_ACTION_BEAN() {
		return PP0100_PT_IL_POLICY_ACTION_BEAN;
	}

	public void setPP0100_PT_IL_POLICY_ACTION_BEAN(
			PP0100_PT_IL_POLICY_ACTION pP0100_PT_IL_POLICY_ACTION_BEAN) {
		PP0100_PT_IL_POLICY_ACTION_BEAN = pP0100_PT_IL_POLICY_ACTION_BEAN;
	}

	public PT_IL_POLICY getPT_IL_POLICY_BEAN() {
		return PT_IL_POLICY_BEAN;
	}

	public void setPT_IL_POLICY_BEAN(PT_IL_POLICY pT_IL_POLICY_BEAN) {
		PT_IL_POLICY_BEAN = pT_IL_POLICY_BEAN;
	}
	
	
}
