package com.iii.pel.forms.PILP203;

public class PILP203_COMPOSITE_ACTION {
	
	PT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION  PT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION_BEAN;

	public PT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION getPT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION_BEAN() {
		return PT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION_BEAN;
	}

	public void setPT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION_BEAN(
			PT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION pT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION_BEAN) {
		PT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION_BEAN = pT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION_BEAN;
	}
	
	public PILP203_COMPOSITE_ACTION(){
	PT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION_BEAN=new PT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION();
	PT_IL_POL_BROKER_HEAD_ORIGINAL_ACTION_BEAN.compositeAction=this;	
	}
}
