package com.iii.pel.forms.PILT021;

public interface PILT021_QUERYCONSTANTS {
	/*Modified by ganesh on 01-Feb-18 for invalid policy number issue for paid up policy*/
	/*String POL_NO_C1 = "SELECT POL_SYS_ID, POL_PROD_CODE,POL_START_DT ,POL_PREM_PAY_YRS,POL_CUST_EXCH_RATE,"
			+ "POL_PLAN_CODE,POL_CUST_CODE FROM PT_IL_POLICY WHERE POL_NO  = "
			+ "NVL(?,0) AND POL_STATUS IN ('A','E') AND POL_DS_TYPE = 2";*/
	
	String POL_NO_C1 = "SELECT POL_SYS_ID, POL_PROD_CODE,POL_START_DT ,POL_PREM_PAY_YRS,POL_CUST_EXCH_RATE,"
			+ "POL_PLAN_CODE,POL_CUST_CODE FROM PT_IL_POLICY WHERE POL_NO  = "
			+ "NVL(?,0) AND POL_STATUS IN ('A','E','P') AND POL_DS_TYPE = 2";
	/*end*/


	String POL_NO_C2 = "SELECT NVL(PROD_WITHDRAW_YN,'N') FROM PM_IL_PRODUCT WHERE PROD_CODE = ?";

	String POL_NO_C3 = "SELECT PLAN_TYPE FROM PM_IL_PLAN WHERE PLAN_CODE = ?";

	String POL_NO_C4 = "SELECT PWPH_MAX_NO_WITHDRAW,PWPH_WITHDRAW_INTERVAL FROM PM_IL_PROD_WD_PARAM_HDR "
			+ "WHERE PWPH_PROD_CODE = ?";

	String POL_NO_C5 = "SELECT COUNT(*) FROM PT_IL_WITHDRAWAL WHERE WD_POL_SYS_ID = ? AND "
			+ "NVL(WD_APPRV_STATUS,'N')='A'";

	String POL_NO_C6 = "SELECT 'X' FROM PT_IL_WITHDRAWAL WHERE  WD_SYS_ID =(SELECT MAX(WD_SYS_ID) FROM "
			+ "PT_IL_WITHDRAWAL WHERE WD_POL_SYS_ID = ? ) AND NVL(WD_APPRV_STATUS,'N') !='A' "
			+ "AND NVL(WD_STATUS_CODE,'N') NOT IN ('D','R')";
	
	String POL_NO_C6_1 = "SELECT 'X' FROM PT_IL_WITHDRAWAL WHERE  WD_SYS_ID =(SELECT MAX(WD_SYS_ID) FROM "
		+ "PT_IL_WITHDRAWAL WHERE WD_POL_SYS_ID = ? AND WD_SYS_ID <> ?) AND NVL(WD_APPRV_STATUS,'N') !='A' "
		+ "AND NVL(WD_STATUS_CODE,'N') NOT IN ('D','R')";

	String POL_NO_C7 = "SELECT WD_DATE FROM PT_IL_WITHDRAWAL WHERE WD_SYS_ID =(SELECT MAX(WD_SYS_ID)"
			+ "FROM PT_IL_WITHDRAWAL WHERE  WD_POL_SYS_ID = ?) AND NVL(WD_APPRV_STATUS,'N') ='A'";

	String POL_NO_C8 = "SELECT ROUND(TO_DATE(SYSDATE,'DD/MM/RRRR')-TO_DATE(?,'DD/MM/RRRR'),2) FROM DUAL";

	String POL_NO_C9 = "SELECT COUNT(*) FROM PT_IL_WITHDRAWAL WHERE WD_POL_SYS_ID = ?";

	String POL_NO_C10 = "SELECT PS_CODE FROM PP_SYSTEM WHERE PS_TYPE = 'SITE'";

	String POL_NO_C11 = "SELECT CLAIM_NO,CLAIM_TYPE,CLAIM_CLOSE_FLAG,CLAIM_SYS_ID FROM PT_IL_CLAIM "
			+ "WHERE CLAIM_POL_NO = ?";

	String POL_NO_C11A = "SELECT 'X' FROM PT_IL_CLAIM_PAID WHERE CP_CLAIM_SYS_ID = ? AND "
			+ "CP_APPR_FLAG IN ('A','R')";
	
	String POL_NO_C12 = "SELECT ASD_CHAR_VALUE FROM PM_IL_APPR_SETUP_DET "
		+ " WHERE ASD_CODE =?  AND   "
		+ " ASD_USER_ID = ?  AND  ?  "
		+ " BETWEEN NVL(ASD_FM_PROD_CODE,0) AND NVL(ASD_TO_PROD_CODE,'zzzzzzzzzzzz') ";

	String WD_DATE_C4 = "SELECT POL_DIVN_CODE, POL_CLASS_CODE, POL_PLAN_CODE, POL_PROD_CODE, POL_UW_YEAR "
			+ "FROM PT_IL_POLICY WHERE POL_SYS_ID = ?";

	String FTD_SELECT_YNC3 = "SELECT WD_DATE FROM PT_IL_WITHDRAWAL WHERE WD_SYS_ID = ( SELECT MAX("
			+ "FTD_TRAN_SYS_ID) FROM PT_IL_FUND_TRAN_DTL WHERE FTD_POL_SYS_ID  = ? AND FTD_TRAN_TYPE = 'W' "
			+ "AND FTD_FUND_CODE = ? AND FTD_SELECT_YN = 'Y')";

	String FTD_SELECT_YNC5 = "SELECT 'X' FROM PT_IL_FUND_TRAN_DTL,PT_IL_WITHDRAWAL WHERE "
			+ "WD_POL_SYS_ID = FTD_POL_SYS_ID AND FTD_POL_SYS_ID = ? AND FTD_TRAN_SYS_ID != ? AND "
			+ "FTD_TRAN_TYPE = 'W' AND FTD_FUND_CODE = ? AND FTD_SELECT_YN = 'Y' AND WD_APPRV_STATUS = 'A'";

	String lCalRedSumAssQuery1 = "SELECT SUM (UFRD_NO_OF_UNITS) FROM PT_IL_UNIT_FUND_REG_DTL "
			+ "WHERE UFRD_UFRH_SYS_ID IN ( SELECT UFRH_SYS_ID FROM PT_IL_UNIT_FUND_REG_HDR "
			+ "WHERE UFRH_POL_SYS_ID = ? " + "AND UFRH_TYPE = 'P')";

	String lCalRedSumAssQuery3 = "SELECT SUM (UFRD_NO_OF_UNITS) FROM PT_IL_UNIT_FUND_REG_DTL "
			+ "WHERE UFRD_UFRH_SYS_ID IN (SELECT UFRH_SYS_ID FROM PT_IL_UNIT_FUND_REG_HDR "
			+ "WHERE UFRH_POL_SYS_ID = ? AND UFRH_TYPE = 'W' "
			+ "AND UFRH_TRANS_SYS_ID<=?)";

	String lCalRedSumAssQuery2 = "SELECT NVL(POL_FC_SUM_ASSURED,0),NVL(POL_LC_SUM_ASSURED,0) "
			+ "FROM PT_IL_POLICY WHERE POL_SYS_ID = ?";
	
	  /*Added by Janani on 04.08.2017 for ZBILQC-1731624*/
	
	String POL_NO_C13 = "SELECT PLAN_TYPE,PROD_INTR_SAVINGS_YN FROM PT_IL_POLICY,PM_IL_PRODUCT,PM_IL_PLAN "
			+ "WHERE PLAN_CODE = POL_PLAN_CODE AND PROD_CODE = POL_PROD_CODE AND POL_NO = ?";
	
	/*eND*/
}
