package com.iii.pel.forms.PILP002_APAC;

public interface PILP002_APAC_SQLConstants {
	
	// Base_Curr changes PREMIAGDC-0030 : Added by Shankar Bodduluri : 25/03/09
	//String  selectParaValue = "SELECT PARA_VALUE FROM   FP_PARAMETER WHERE  PARA_ID = 'BASE.CURR'";
	String  selectParaValue = "SELECT PARA_VALUE FROM   FP_PARAMETER WHERE  PARA_ID = ?";
	String selectPlanType = "select PLAN_TYPE from   pm_il_plan where  plan_code  =  ? and    plan_frz_flag = 'N'";
	
	String selectPS_VALUE = "SELECT PS_VALUE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'IL_DEF_DT'";
	// string s1 = 	String selectPOL_STATUS = "SELECT POL_STATUS FROM  PT_IL_POLICY  WHERE  POL_SYS_ID  = :DUMMY.M_POL_SYS_ID ";
	String selectPOL_STATUS = "SELECT POL_STATUS FROM  PT_IL_POLICY  WHERE  POL_SYS_ID  = ? ";
	
	String sql_C1 = "SELECT POL_SYS_ID,NVL(POL_APPRV_STATUS,'N'),NVL(POL_END_DT, POL_ISSUE_DT)," +
			"POL_PLAN_CODE,NVL(POL_END_NO_IDX, 0),POL_PROP_NO,NVL(POL_FC_FIRST_PREM,0)," +
			"NVL(POL_LC_FIRST_PREM,0),NVL(POL_CUST_EXCH_RATE,1),POL_ISSUE_DT " +
			" FROM PT_IL_POLICY WHERE POL_NO = ? AND POL_DS_TYPE = '2'";

	String sql_C2 = "SELECT PLAN_TYPE FROM  PM_IL_PLAN  WHERE  PLAN_CODE  = ? ";
	
	String sql_C3 = "SELECT NVL(DEP_GROSS_NET_FLAG,'G')FROM PT_IL_DEPOSIT WHERE DEP_REF_NO = ? AND NVL(DEP_REC_REV_YN, 'N')= 'N' ";
	
	String fetchPolDetails = "SELECT POL_NO,POL_ISSUE_DT,POL_CUST_CODE FROM PT_IL_POLICY WHERE POL_NO = ? ";
	
	String pymtDetailsQuery = "SELECT PD_SR_NO,PD_PAY_MODE,PD_DPD_REF_ID,PD_FC_AMT,PD_LC_AMT,PD_PAID_FOR,PD_CHQ_NO,PD_CHQ_DT,PD_CR_ADVICE_NO,PD_PAYIN_DATE,PD_BANK_NAME,PD_BRANCH_NAME,PD_CUST_NAME,PD_ADDR_01,PD_ADDR_02,PD_ADDR_03,PD_REMARKS,PD_CURR_CODE,PD_LC_CHARGE,PD_FC_CHARGE FROM PT_IL_PYMT_DTLS WHERE PD_SYS_ID = ?";
	
	String policyApproveDateQuery1 = "SELECT POL_CUST_CODE,POL_CONT_CODE,POL_CUST_CURR_CODE,POL_CUST_EXCH_RATE,NVL(POL_FC_FIRST_PREM,0),NVL(POL_LC_FIRST_PREM,0),POL_CASH_YN,POL_DIVN_CODE,NVL(POL_END_TYPE,'000'),POL_MODE_OF_PYMT,POL_PLAN_CODE FROM PT_IL_POLICY WHERE POL_SYS_ID = ?";
	
	String policyApproveDateQuery2 = "SELECT NVL(CONT_LC_PROP_DEP_AMT,0),NVL(CONT_LC_PROP_UTIL_AMT,0),NVL(CONT_LC_POL_DEP_AMT,0),NVL(CONT_LC_POL_UTIL_AMT,0) FROM PM_IL_CONTRACTOR WHERE CONT_CODE  = ? ";
	
	String policyApproveDateQuery3 = "SELECT PS_VALUE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'IL_SHORT_COL'  AND PS_CODE  = ? ";
	
	String policyApproveDateQuery4 = "SELECT PS_VALUE FROM PP_SYSTEM WHERE PS_TYPE = 'IL_TOLL_TYPE' ";
	
	String policyApproveDateQuery16 = "SELECT PMOP_SHORT_RATE,PMOP_SHORT_RATE_PER,PMOP_TOLL_TYP FROM PM_IL_PLAN_MOP WHERE PMOP_PLAN_CODE  = ? AND PMOP_TYPE = ? ";
	
	String  L_VALIDATE_APPRV_DATEQuery = "SELECT NVL(POL_END_DT, POL_ISSUE_DT) FROM  PT_IL_POLICY  WHERE  POL_SYS_ID  = ?  AND POL_DS_TYPE  = '2'";
	
	String P_VAL_ROUND_AMT_sql_C1 = "SELECT CURR_DECIMAL FROM  FM_CURRENCY  WHERE  CURR_CODE  = ? ";
	
	String P_VAL_ROUND_AMT_sql_C2="SELECT PS_CODE,DECODE(PS_CODE,'1',PS_VALUE,'0',0,0)FROM PP_SYSTEM WHERE PS_TYPE ='IL_RND_APP'";
	
	String M_TRANSACTION_DATE_WHEN_VAL_QUERY = " SELECT POL_CUST_CODE,POL_CONT_CODE,POL_CUST_CURR_CODE,POL_CUST_EXCH_RATE,NVL(POL_FC_FIRST_PREM, 0),NVL(POL_LC_FIRST_PREM, 0),POL_CASH_YN,POL_DIVN_CODE,NVL(POL_END_TYPE, '000'),POL_MODE_OF_PYMT,POL_PLAN_CODE FROM PT_IL_POLICY WHERE POL_SYS_ID = ? ";
	
	String M_TRANSACTION_DATE_WHEN_VAL_QUERY2 = "SELECT NVL(CONT_LC_PROP_DEP_AMT, 0), NVL(CONT_LC_PROP_UTIL_AMT, 0),NVL(CONT_LC_POL_DEP_AMT, 0),NVL(CONT_LC_POL_UTIL_AMT, 0) FROM PM_IL_CONTRACTOR  WHERE CONT_CODE  = ? ";
	
	String M_TRANSACTION_DATE_WHEN_VAL_QUERY4 = "SELECT PS_VALUE FROM PP_SYSTEM WHERE PS_TYPE  = 'IL_TOLL_TYPE'";
	
	String M_TRANSACTION_DATE_WHEN_VAL_QUERY3 = "SELECT PS_VALUE FROM PP_SYSTEM WHERE PS_TYPE = 'IL_SHORT_COL' AND PS_CODE = ? ";
	
	String M_TRANSACTION_DATE_WHEN_VAL_QUERY16 = "SELECT PMOP_SHORT_RATE,PMOP_SHORT_RATE_PER,PMOP_TOLL_TYP FROM PM_IL_PLAN_MOP WHERE PMOP_PLAN_CODE = ? AND PMOP_TYPE = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY1 = "SELECT 'X' FROM  PT_IL_PYMT_DTLS  WHERE  PD_TXN_TYPE  = 'PT'  AND PD_TXN_SYS_ID  = ? GROUP BY  PD_TXN_SYS_ID  ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY2 = "SELECT NVL(SUM(PD_FC_AMT), 0) FROM  PT_IL_PYMT_DTLS  WHERE  PD_TXN_TYPE  = 'PT'  AND PD_TXN_SYS_ID  = ?  AND PD_PAY_MODE  != 'DP' GROUP BY  PD_TXN_SYS_ID  ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY16 = "SELECT NVL(SUM(PD_FC_AMT), 0) FROM  PT_IL_PYMT_DTLS  WHERE  PD_TXN_TYPE  = 'PT'  AND PD_TXN_SYS_ID  = ?  AND PD_PAY_MODE  = 'DP' GROUP BY  PD_TXN_SYS_ID  ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY3 = "SELECT POL_BASIC_RATE,POL_FC_AMAN_PREM,POL_FC_SENABEL_PREM,POL_LC_AMAN_PREM,POL_LC_SENABEL_PREM,POL_END_NO_IDX,NVL(POL_END_TYPE,'000'),POL_FIRST_INST_DT,POL_PERIOD,POL_MODE_OF_PYMT,POL_PREM_PAY_YRS,POL_END_CODE,POL_DS_CODE,POL_CLASS_CODE FROM PT_IL_POLICY WHERE POL_SYS_ID  = ? AND POL_DS_TYPE  = '2' ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY4 = "SELECT DECODE(?, '000', ?, ?) FROM  DUAL  ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY5 = "SELECT ASD_CHAR_VALUE FROM  PM_IL_APPR_SETUP_DET  WHERE  ASD_USER_ID  = ?  AND ASD_CODE  = DECODE(NVL(?, 'N'), 'Y', 'POL_STDAP_YN', 'PO_SSTDAP_YN')  AND ASD_FLAG  = 2  AND ? BETWEEN NVL(ASD_FM_PROD_CODE, '0')  AND  NVL(ASD_TO_PROD_CODE, 'ZZZZZZZZZZZZ') ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY6 = "SELECT ASD_NUM_VALUE FROM  PM_IL_APPR_SETUP_DET  WHERE  ASD_USER_ID  = ?  AND ASD_CODE  = DECODE(NVL(?, 'N'), 'Y', 'POL_STD_SA', 'POL_SSTD_SA')  AND ASD_FLAG  = 1  AND ?  BETWEEN NVL(ASD_FM_PROD_CODE, '0')  AND  NVL(ASD_TO_PROD_CODE, 'ZZZZZZZZZZZZ') ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY7 = "SELECT POL_LC_SUM_ASSURED,POL_STD_RISK_YN,POL_ORG_LC_SUM_ASSURED FROM  PT_IL_POLICY  WHERE  POL_SYS_ID  = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY8 = "SELECT PS_VALUE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'IL_CALC_MTHD' AND PS_CODE  = 'IL_CALC_MTHD' ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY9 = "SELECT POL_FC_BASIC_PREM,POL_LC_BASIC_PREM FROM PT_IL_POLICY WHERE POL_SYS_ID = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY10 = "SELECT NVL(PDL_FC_DISC_LOAD_VALUE, 0),NVL(PDL_LC_DISC_LOAD_VALUE, 0) FROM PT_IL_POL_DISC_LOAD WHERE PDL_POL_SYS_ID  = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY11 = "SELECT POL_CONT_CODE FROM  PT_IL_POLICY  WHERE  POL_SYS_ID  = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY12 = "SELECT CONT_PREFERRED_LANG FROM  PM_IL_CONTRACTOR  WHERE  CONT_CODE  = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY13 = "SELECT PC_DESC,PC_BL_DESC FRO	M PM_CODES WHERE PC_TYPE = 'IL_REMIN_RPT' AND PC_CODE = 'JE/END/006' ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY14 = "SELECT PC_DESC,PC_BL_DESC FROM PM_CODES WHERE PC_TYPE  = 'IL_REMIN_RPT' AND PC_CODE  = 'END/011' ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY15 = "SELECT PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_MR_RED_SA' AND PS_CODE = 'IL_MR_RED_SA' ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY18 = "SELECT POL_PROD_CODE,POL_NL_FM_DT,POL_END_DT,POL_TRAN_DT FROM PT_IL_POLICY WHERE POL_SYS_ID = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY17 = "SELECT CSVSD_PARA_CODE_DESC FROM PP_COMP_SITE_VALUE_SET_DTL,PP_COMP_SITE_VALUE_SET_HDR WHERE CSVSD_PARA_TYPE = 'ADDLFORM1' AND CSVSD_PARA_CODE = ? AND CSVSH_SYS_ID = CSVSD_CSVSH_SYS_ID AND CSVSH_SITE_CODE = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY19 = "SELECT POFD_FUND_CODE FROM PT_IL_POL_FUND_DTL WHERE  POFD_POL_SYS_ID = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY20 = "SELECT 1 FROM PM_IL_FUND_PRICE_DTL WHERE FPD_FS_CODE = ? AND ?  BETWEEN FPD_EFF_FM_DT  AND  FPD_EFF_TO_DT ";	
	
	String OK_BUTTON_PRESSED_SELECT_QUERY21 = "SELECT PROD_COOLOFF_DAYS,PROD_PREM_CALC_MTHD FROM PM_IL_PRODUCT WHERE PROD_CODE = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY22 = "SELECT POBH_BROKER_CODE,POBH_AGENT_RANK_CODE,POBH_AGENT_LEVEL,POBH_COMM_CODE FROM  PT_IL_POL_BROKER_HEAD A  WHERE  POBH_POL_SYS_ID  = ?  AND POBH_SRNO  IN  (   SELECT MIN(POBH_SRNO)  FROM  PT_IL_POL_BROKER_HEAD B   WHERE  B.POBH_POL_SYS_ID  = A.POBH_POL_SYS_ID  ) ";
		
	String OK_BUTTON_PRESSED_SELECT_QUERY23 = "SELECT BCD_COMM_RATE FROM  PM_BROKER_COMM_DTL,   PM_BROKER_COMM_HDR  WHERE  BCH_CODE  = BCD_BCH_CODE  AND BCH_CODE  = ? AND BCD_LEVEL  = ?  AND BCD_RANK_CODE  = ?  AND ? BETWEEN BCD_TERM_FM  AND  BCD_TERM_TO ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY24 = "SELECT PS_CODE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'IL_REP_STAT' ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY25 = "SELECT PS_CODE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'IL_REP_CANCL' ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY26 = "SELECT POAD_REF_ID1,POAD_REF_ID2 FROM PT_IL_POL_ASSURED_DTLS WHERE POAD_POL_SYS_ID = ?  AND POAD_TYPE  = 'R' ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY27 = "SELECT COUNT(POL_SYS_ID) FROM PT_IL_POLICY WHERE POL_SYS_ID IN " +
			"(SELECT DISTINCT POL_SYS_ID FROM PT_IL_POLICY,PT_IL_POL_ASSURED_DTLS WHERE POL_SYS_ID = POAD_POL_SYS_ID" +
			" AND (POAD_REF_ID1  = ? OR POAD_REF_ID2 = ?) AND POL_STATUS IN ('S','L') AND NOT EXISTS " +
			"(SELECT PLAN_TYPE FROM PM_IL_PLAN WHERE PLAN_CODE = POL_PLAN_CODE AND PLAN_TYPE = 'M') AND " +
			" POL_CLASS_CODE != '2' AND POL_DS_TYPE  = '2'AND MONTHS_BETWEEN(?, POL_PAIDUP_DT) <= ? UNION" +
			" SELECT DISTINCT POL_SYS_ID FROM PT_IL_POLICY,PT_IL_POL_ASSURED_DTLS WHERE POL_SYS_ID = POAD_POL_SYS_ID AND (POAD_REF_ID1  = ? OR POAD_REF_ID2 = ?) AND POL_STATUS IN ('C')AND POL_END_CODE = ? AND NOT EXISTS (SELECT PLAN_TYPE FROM PM_IL_PLAN WHERE PLAN_CODE = POL_PLAN_CODE AND PLAN_TYPE = 'M')AND POL_CLASS_CODE != '2' AND POL_DS_TYPE = '2' AND MONTHS_BETWEEN(?,POL_CANCEL_DT) <= ? UNION SELECT DISTINCT POL_SYS_ID FROM PT_IL_POLICY,PT_IL_POL_ASSURED_DTLS,PT_IL_POL_STATUS WHERE POL_SYS_ID = POAD_POL_SYS_ID AND POL_SYS_ID = PS_POL_SYS_ID AND(POAD_REF_ID1 = ? OR POAD_REF_ID2 = ?)AND PS_STATUS IN ('I05','I06')AND NOT EXISTS (SELECT PLAN_TYPE FROM PM_IL_PLAN WHERE PLAN_CODE = POL_PLAN_CODE AND PLAN_TYPE = 'M') AND POL_CLASS_CODE != '2' AND POL_DS_TYPE = '2' AND MONTHS_BETWEEN(?, PS_STATUS_DT) <= ? UNION SELECT DISTINCT POL_SYS_ID FROM PT_IL_POLICY,PT_IL_WITHDRAWAL,PT_IL_POL_ASSURED_DTLS WHERE POL_SYS_ID  = POAD_POL_SYS_ID AND POL_SYS_ID  = WD_POL_SYS_ID AND WD_APPRV_STATUS = 'A' AND NOT EXISTS (SELECT PLAN_TYPE FROM  PM_IL_PLAN WHERE PLAN_CODE = POL_PLAN_CODE AND PLAN_TYPE = 'M')AND POL_CLASS_CODE  != '2' AND POL_DS_TYPE = '2' AND (POAD_REF_ID1  = ? OR POAD_REF_ID2 = ?)AND MONTHS_BETWEEN(?,WD_DATE)<= ? UNION SELECT DISTINCT POLH_SYS_ID FROM PH_IL_POLICY,PT_IL_POL_ASSURED_DTLS WHERE POLH_SYS_ID = POAD_POL_SYS_ID AND POLH_N_END_CODE IN (SELECT PS_CODE FROM PP_SYSTEM WHERE PS_TYPE = 'IL_DEC_SA')AND (POAD_REF_ID1 = ? OR POAD_REF_ID2 = ?)AND POLH_DS_TYPE  = '2' AND NOT EXISTS (SELECT PLAN_TYPE FROM PM_IL_PLAN WHERE PLAN_CODE = POLH_PLAN_CODE AND PLAN_TYPE = 'M')AND POLH_CLASS_CODE != '2'AND MONTHS_BETWEEN(?, POLH_N_END_EFF_FROM_DT)<= ?) "; 
	
	String OK_BUTTON_PRESSED_SELECT_QUERY28 = "SELECT POL_PERIOD,NVL(POL_END_NO_IDX, 0),POL_PROD_CODE,POL_END_CODE,POL_MED_FEE_RECOVER_YN FROM PT_IL_POLICY WHERE POL_SYS_ID  = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY29 = "SELECT CUST_BLACK_LIST_COUNT FROM PM_CUSTOMER WHERE CUST_CODE = ?";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY30 = "SELECT PROD_MATU_DT FROM  PM_IL_PRODUCT  WHERE  PROD_CODE  = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY35 = "SELECT NVL(EAS_END_APPR_YN,'N')FROM PM_IL_END_APPR_SETUP WHERE EAS_AS_USER_ID = ? AND ? BETWEEN NVL(EAS_AS_FM_PROD_CODE,'0') AND NVL(EAS_AS_TO_PROD_CODE,'ZZZZZZZZZZZZ') AND ?  BETWEEN NVL(EAS_FM_END_CODE, '0') AND NVL(EAS_TO_END_CODE,'ZZZZZZZZZZZZ') AND EAS_END_PROC_YN = 'Y'";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY36 = "SELECT MFD_CLINIC_CODE,MFD_EXAM_CODE FROM PT_IL_MEDEX_FEE_DTL A,PT_IL_POL_MED_EXAM_DTL WHERE MFD_POL_SYS_ID = PMED_POL_SYS_ID  AND MFD_CLINIC_CODE  = PMED_CLINIC_CODE  AND MFD_EXAM_CODE  = PMED_EXAM_CODE  AND NVL(MFD_PAID_FLAG, 'N')  <> 'Y'  AND MFD_POL_SYS_ID  = ? MINUS SELECT MFD_CLINIC_CODE,MFD_EXAM_CODE FROM  PT_IL_MEDEX_FEE_DTL  WHERE  MFD_PROP_NO = ? AND NVL(MFD_PAID_FLAG, 'N')= 'Y'";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY38 = "SELECT POL_DS_TYPE,POL_DS_CODE FROM PT_IL_POLICY WHERE POL_SYS_ID  = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY37 = "SELECT DS_POST_BO FROM  PM_IL_DOC_SETUP  WHERE  DS_TYPE  = ?  AND DS_CODE  = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY39 = "SELECT PROD_DRIP_MTHD FROM  PM_IL_PRODUCT  WHERE  PROD_CODE  = ? ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY40 = "SELECT ESD_NUM_VALUE FROM PM_IL_END_APPR_SETUP," +
			" PM_IL_END_SETUP_DET WHERE EAS_AS_USER_ID = ?  AND ? BETWEEN " +
			"NVL(EAS_AS_FM_PROD_CODE, '0')  AND  NVL(EAS_AS_TO_PROD_CODE, 'ZZZZZZZZZZZ')  AND" +
			" ? BETWEEN NVL(EAS_FM_END_CODE, '0')  AND  NVL(EAS_TO_END_CODE, 'ZZZZZZZZZZZZ')  " +
			"AND EAS_SYS_ID  = ESD_EAS_SYS_ID  AND ? BETWEEN NVL(ESD_FM_PROD_CODE, '0')" +
			"  AND  NVL(ESD_TO_PROD_CODE, 'ZZZZZZZZZZZZ')  AND ESD_USER_ID  = ? " +
			" AND ESD_CODE  = DECODE(NVL(?, 'N'), 'Y', 'POL_STD_SA', 'POL_SSTD_SA') ";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY41 = " SELECT SUBSTR (PS_CODE_DESC,"+
	"                        1,"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 1),"+
	"                                0, 999,"+
	"                                INSTR (PS_CODE_DESC, ',', 1, 1) - 1"+
	"                               )"+
	"                       ),"+
	"                SUBSTR (PS_CODE_DESC,"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 1),"+
	"                                0, 999,"+
	"                                INSTR (PS_CODE_DESC, ',', 1, 1) + 1"+
	"                               ),"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 2),"+
	"                                0, 999,"+
	"                                  INSTR (PS_CODE_DESC, ',', 1, 2)"+
	"                                - 1"+
	"                                - INSTR (PS_CODE_DESC, ',', 1, 1)"+
	"                               )"+
	"                       ),"+
	"                SUBSTR (PS_CODE_DESC,"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 2),"+
	"                                0, 999,"+
	"                                INSTR (PS_CODE_DESC, ',', 1, 2) + 1"+
	"                               ),"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 3),"+
	"                                0, 999,"+
	"                                  INSTR (PS_CODE_DESC, ',', 1, 3)"+
	"                                - 1"+
	"                                - INSTR (PS_CODE_DESC, ',', 1, 2)"+
	"                               )"+
	"                       ),"+
	"                SUBSTR (PS_CODE_DESC,"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 3),"+
	"                                0, 999,"+
	"                                INSTR (PS_CODE_DESC, ',', 1, 3) + 1"+
	"                               ),"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 4),"+
	"                                0, 999,"+
	"                                  INSTR (PS_CODE_DESC, ',', 1, 4)"+
	"                                - 1"+
	"                                - INSTR (PS_CODE_DESC, ',', 1, 3)"+
	"                               )"+
	"                       ),"+
	"                SUBSTR (PS_CODE_DESC,"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 4),"+
	"                                0, 999,"+
	"                                INSTR (PS_CODE_DESC, ',', 1, 4) + 1"+
	"                               ),"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 5),"+
	"                                0, 999,"+
	"                                  INSTR (PS_CODE_DESC, ',', 1, 5)"+
	"                                - 1"+
	"                                - INSTR (PS_CODE_DESC, ',', 1, 4)"+
	"                               )"+
	"                       ),"+
	"                SUBSTR (PS_CODE_DESC,"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 5),"+
	"                                0, 999,"+
	"                                INSTR (PS_CODE_DESC, ',', 1, 5) + 1"+
	"                               ),"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 6),"+
	"                                0, 999,"+
	"                                  INSTR (PS_CODE_DESC, ',', 1, 6)"+
	"                                - 1"+
	"                                - INSTR (PS_CODE_DESC, ',', 1, 5)"+
	"                               )"+
	"                       ),"+
	"                SUBSTR (PS_CODE_DESC,"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 6),"+
	"                                0, 999,"+
	"                                INSTR (PS_CODE_DESC, ',', 1, 6) + 1"+
	"                               ),"+
	"                        DECODE (INSTR (PS_CODE_DESC, ',', 1, 7),"+
	"                                0, 999,"+
	"                                  INSTR (PS_CODE_DESC, ',', 1, 7)"+
	"                                - 1"+
	"                                - INSTR (PS_CODE_DESC, ',', 1, 6)"+
	"                               )"+
	"                       )"+
	"          FROM PP_SYSTEM"+
	"         WHERE PS_TYPE = 'IL_AUTO_WAK' "+
	"           AND PS_CODE = 'IL_AUTO_WAK'";
	
	String OK_BUTTON_PRESSED_SELECT_QUERY42 = "SELECT 'X'  FROM DUAL WHERE " +
			"  ? IN (?,  ?,?,?,?,?,?) ";	
                             
	String OK_BUTTON_PRESSED_SELECT_QUERY43=" SELECT PS_CODE     FROM PP_SYSTEM" +
			"      WHERE PS_TYPE ='IL_DEL_RIDER'";
	
	String OK_BUTTON_PRESSED_UPDATE_QUERY1 = "UPDATE PT_IL_POLICY SET POL_START_DT = ?,POL_EXPIRY_DT = ?,POL_FIRST_INST_DT = ?,POL_LAST_INST_DT = ?,POL_TRAN_DT = ?,POL_APPRV_UID = ? WHERE POL_SYS_ID = ?";
	
	String OK_BUTTON_PRESSED_UPDATE_QUERY2 = "UPDATE PT_IL_POLICY SET POL_ADDL_STATUS = ? WHERE  POL_SYS_ID  = ?  ";
	
	String OK_BUTTON_PRESSED_UPDATE_QUERY3 = "UPDATE PM_CUSTOMER SET CUST_BLACK_LIST_COUNT = NVL(?, 0) + 1  WHERE  CUST_CODE  = ? ";
	
	String OK_BUTTON_PRESSED_UPDATE_QUERY4 = "UPDATE PT_IL_POLICY SET POL_ADDL_STATUS = 'I00' WHERE POL_SYS_ID = ? ";
	
	String OK_BUTTON_PRESSED_UPDATE_QUERY5 = "UPDATE PT_IL_POLICY SET POL_ADDL_STATUS = 'I00' WHERE POL_SYS_ID = ? ";
	
    String OK_BUTTON_PRESSED_UPDATE_QUERY6 = "UPDATE PT_IL_POL_FUND_DTL SET POFD_EFF_FM_DT = ?,POFD_EFF_TO_DT = ? WHERE POFD_POL_SYS_ID = ? ";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY7 = "UPDATE PT_IL_POL_ADDL_COVER SET POAC_FM_DT = ?,POAC_TO_DT = ADD_MONTHS(?, POAC_PERIOD * 12) - 1  WHERE  POAC_POL_SYS_ID  = ?  ";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY8 = "UPDATE PT_IL_POLICY SET POL_START_DT = ?,POL_EXPIRY_DT = ? ,POL_FIRST_INST_DT = ? ,POL_LAST_INST_DT = ? ,POL_APPRV_UID = ? WHERE POL_SYS_ID = ?  ";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY9 = "UPDATE PT_IL_POL_FUND_DTL SET POFD_EFF_FM_DT = ?,POFD_EFF_TO_DT = ? WHERE POFD_POL_SYS_ID = ?  ";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY10 = "UPDATE PT_IL_POLICY SET POL_ADDL_STATUS = ? WHERE  POL_SYS_ID  = ?  ";
	
    String OK_BUTTON_PRESSED_UPDATE_QUERY11 = "UPDATE PT_IL_POLICY SET POL_ADDL_STATUS = 'I00' WHERE  POL_SYS_ID  = ? ";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY12 = "UPDATE   PT_IL_POLICY    SET POL_ADDL_STATUS = 'I00'  WHERE  POL_SYS_ID  = ?  ";
	
    String OK_BUTTON_PRESSED_UPDATE_QUERY13 = "UPDATE PT_IL_POL_ADDL_COVER SET POAC_FM_DT = ?,POAC_TO_DT = ADD_MONTHS(?, POAC_PERIOD * 12) - DECODE(?, '0', 1, 0)  WHERE  POAC_POL_SYS_ID  = ? ";
    
    String OK_BUTTON_PRESSED_INSERT_QUERY14 = "INSERT INTO PT_IL_POL_STATUS (PS_POL_SYS_ID,PS_END_NO_IDX ,PS_STATUS_DT ,PS_STATUS ,PS_STATUS_UID ,PS_STATUS_TYPE ,PS_CR_UID ,PS_CR_DT )VALUES ( ? ,? ,SYSDATE ,'I00',? ,'S',?,SYSDATE )   ";
	
    String OK_BUTTON_PRESSED_UPDATE_QUERY15 = "UPDATE PT_IL_POL_STATUS SET PS_STATUS = ?  WHERE  PS_POL_SYS_ID  = ?  ";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY16 = "UPDATE PT_IL_POL_STATUS SET PS_STATUS = 'I00' WHERE PS_POL_SYS_ID  = ?  ";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY17 = "UPDATE PT_IL_POL_STATUS SET PS_STATUS = 'I00' WHERE PS_POL_SYS_ID  = ? ";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY18 = "UPDATE PT_IL_POLICY SET POL_APPRV_STATUS = 'A',POL_STATUS = 'C',POL_APPRV_DT = ?,POL_APPRV_UID = ?,POL_CANCEL_DT = TRUNC(SYSDATE),POL_END_APPRV_DT = TRUNC(SYSDATE) WHERE POL_SYS_ID = ? ";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY19 = "UPDATE PT_IL_POLICY SET POL_ADDL_STATUS = 'I02' WHERE POL_SYS_ID = ? ";
    
    String OK_BUTTON_PRESSED_INSERT_QUERY20 = "INSERT INTO PT_IL_POL_STATUS (PS_POL_SYS_ID,PS_END_NO_IDX ,PS_STATUS_DT ,PS_STATUS,PS_STATUS_UID ,PS_STATUS_TYPE ,PS_CR_UID ,PS_CR_DT )VALUES (? ,? ,TRUNC(SYSDATE) ,'I02',? ,'S' ,? ,SYSDATE )";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY21 = "UPDATE PT_IL_POLICY SET POL_APPRV_STATUS = 'A',POL_STATUS = 'A',POL_ADDL_STATUS = 'I00',POL_APPRV_DT = ?,POL_END_APPRV_DT = TRUNC(SYSDATE),POL_APPRV_UID = ? WHERE  POL_SYS_ID = ? ";
    
    String OK_BUTTON_PRESSED_UPDATE_QUERY22 = "UPDATE PT_IL_POLICY SET POL_END_APPRV_DT = TRUNC(SYSDATE) WHERE POL_SYS_ID  = ?  ";
	
    String OK_BUTTON_PRESSED_INSERT_QUERY23 = " INSERT INTO PT_IL_PYMT_DTLS (PD_SYS_ID, PD_SR_NO, PD_TXN_TYPE, PD_TXN_SYS_ID, PD_PAY_MODE, PD_CURR_CODE, PD_FC_AMT, PD_LC_AMT, PD_CC_TYPE,  PD_CR_UID, PD_CR_DT, PD_DPD_REF_ID,   PD_PAID_FOR)VALUES ( PIL_PD_SYS_ID.NEXTVAL, PD_SR_NO, ?,    ?, 'P', ?,    ABS(?), ABS(?), 'O',    ?, SYSDATE, ?,    'D')";
    
	String POLICY_NO_LOV_QUERY = "SELECT POL_NO FROM PT_IL_POLICY WHERE NVL(POL_APPRV_STATUS,'N') = 'N' AND POL_NO IS NOT NULL AND POL_DS_TYPE = '2'";
	
	String POLICY_NO_LOV_QUERY_SUGGESTION = "SELECT POL_NO FROM PT_IL_POLICY WHERE NVL(POL_APPRV_STATUS,'N') = 'N' AND POL_NO IS NOT NULL AND POL_DS_TYPE = '2' AND POL_NO LIKE ? ";
	
	String CUSTOMER_CODE_LOV_QUERY = "SELECT CUST_CODE, CUST_NAME FROM   PM_CUSTOMER WHERE  CUST_CLASS IN (SELECT CCLAS_CODE FROM   PM_CUST_CLASS, PP_SYSTEM WHERE  DECODE (PS_VALUE,2,CCLAS_CODE, CCLAS_TYPE)IN ('001','002','003','004','005','006','009') AND    PS_CODE = 'CASH' AND    PS_TYPE = 'LOV_CUST')AND CUST_FRZ_FLAG = 'N' AND((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM  PM_CUST_DIVN WHERE CDIV_DIVN_CODE = NVL (NULL, CDIV_DIVN_CODE)AND CUST_APPL_ALL_BRAN_YN = 'N'))OR (CUST_APPL_ALL_BRAN_YN = 'Y'))AND ROWNUM<=20";
	
	String CUSTOMER_CODE_SUGGESTION_LOV_QUERY = "SELECT CUST_CODE, CUST_NAME FROM   PM_CUSTOMER WHERE  CUST_CLASS IN (SELECT CCLAS_CODE FROM   PM_CUST_CLASS, PP_SYSTEM WHERE  DECODE (PS_VALUE,2,CCLAS_CODE, CCLAS_TYPE)IN ('001','002','003','004','005','006','009') AND    PS_CODE = 'CASH' AND    PS_TYPE = 'LOV_CUST')AND CUST_FRZ_FLAG = 'N' AND((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM  PM_CUST_DIVN WHERE CDIV_DIVN_CODE = NVL (NULL, CDIV_DIVN_CODE)AND CUST_APPL_ALL_BRAN_YN = 'N'))OR (CUST_APPL_ALL_BRAN_YN = 'Y')) AND CUST_CODE LIKE ?";
	
	String UI_M_LC_AMOUNT_WHEN_VALIDATE_SQLC1 = "SELECT POL_END_NO_IDX,NVL(POL_END_TYPE, '000'),POL_PROD_CODE FROM PT_IL_POLICY WHERE POL_SYS_ID = ?  AND POL_DS_TYPE  = '2' ";
	
	String UI_M_LC_AMOUNT_WHEN_VALIDATE_SQLC2 = "SELECT NVL(PROD_PREM_CALC_MTHD,'T') FROM PM_IL_PRODUCT WHERE  PROD_CODE  = ? ";
	
	String NEW_FORM_INSTANCE_QUERY1 = "SELECT PS_VALUE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'IL_DEF_DT'";
	
	String NEW_FORM_INSTANCE_QUERY2  = "SELECT POL_STATUS FROM  PT_IL_POLICY  WHERE  POL_SYS_ID  = ? ";
	
	String query_DOC_BROK_YN="SELECT DS_BROKER_YN FROM PM_IL_DOC_SETUP WHERE DS_CODE IN (SELECT POL_DS_CODE FROM PT_IL_POLICY WHERE POL_NO=?)";
	
	String query_POL_DETAILS="SELECT POL_PROD_CODE,POL_CUST_CODE FROM PT_IL_POLICY WHERE POL_NO=?";
	
	String query_USER_APPROV="SELECT NVL(ASD_CHAR_VALUE,'N') FROM PM_IL_APPR_SETUP_DET " +
	"WHERE ASD_USER_ID = ? AND ? BETWEEN ASD_FM_PROD_CODE AND ASD_TO_PROD_CODE " +
	"AND  ASD_CODE = 'MOD_AC_FLAG'";
	
}
