package com.iii.pel.jasperreports;

public interface Reports_SQL_Query_Constants {
	
	
	String CHANGE_DATE_FORMAT=
		"SELECT TO_CHAR(TO_DATE(?, 'DD-MON-YYYY'),?) FROM DUAL";
	
	String  PP_REPORT_BP_HEAD="SELECT RBH_ID," +
	"DECODE(?,'ENG',RBH_TITLE1_ENG,RBH_TITLE1_FOR) C1_TITLE2," +
	"DECODE(?,'ENG',RBH_TITLE2_ENG,RBH_TITLE2_FOR) C1_TITLE3," +
	" LTRIM(RTRIM(DECODE(?,'ENG',RBH_DATE_ENG,RBH_DATE_FOR))) C1_DATE," +
	" LTRIM(RTRIM(DECODE(?,'ENG',RBH_USER_ENG,RBH_USER_FOR))) C1_USER," +
	" LTRIM(RTRIM(DECODE(?,'ENG',RBH_PAGE_ENG,RBH_PAGE_FOR))) C1_PAGE," +
	" LTRIM(RTRIM(DECODE(?,'ENG',RBH_REPID_ENG,RBH_REPID_FOR))) C1_REPID" +
	" FROM PP_REPORT_BP_HEAD WHERE RBH_REP_CODE = ?";


	String PP_REPORT_BP_COL= "SELECT DECODE(?,'ENG',RBC_HEAD_ENG_1,RBC_HEAD_FOR_1) C2_HEAD1," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_2,RBC_HEAD_FOR_2) C2_HEAD2," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_3,RBC_HEAD_FOR_3) C2_HEAD3," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_4,RBC_HEAD_FOR_4) C2_HEAD4,"+
		"DECODE(?,'ENG',RBC_HEAD_ENG_5,RBC_HEAD_FOR_5) C2_HEAD5," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_6,RBC_HEAD_FOR_6) C2_HEAD6," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_7,RBC_HEAD_FOR_7) C2_HEAD7," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_8,RBC_HEAD_FOR_8) C2_HEAD8," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_9,RBC_HEAD_FOR_9) C2_HEAD9," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_10,RBC_HEAD_FOR_10) C2_HEAD10," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_11,RBC_HEAD_FOR_11) C2_HEAD11," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_12,RBC_HEAD_FOR_12) C2_HEAD12," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_13,RBC_HEAD_FOR_13) C2_HEAD13," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_14,RBC_HEAD_FOR_14) C2_HEAD14," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_15,RBC_HEAD_FOR_15) C2_HEAD15," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_16,RBC_HEAD_FOR_16) C2_HEAD16," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_17,RBC_HEAD_FOR_17) C2_HEAD17," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_18,RBC_HEAD_FOR_18) C2_HEAD18," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_19,RBC_HEAD_FOR_19) C2_HEAD19," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_20,RBC_HEAD_FOR_20) C2_HEAD20," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_21,RBC_HEAD_FOR_21) C2_HEAD21," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_22,RBC_HEAD_FOR_22) C2_HEAD22," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_23,RBC_HEAD_FOR_23) C2_HEAD23," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_24,RBC_HEAD_FOR_24) C2_HEAD24," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_25,RBC_HEAD_FOR_25) C2_HEAD25," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_26,RBC_HEAD_FOR_26) C2_HEAD26," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_27,RBC_HEAD_FOR_27) C2_HEAD27," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_28,RBC_HEAD_FOR_28) C2_HEAD28," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_29,RBC_HEAD_FOR_29) C2_HEAD29," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_30,RBC_HEAD_FOR_30) C2_HEAD30," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_31,RBC_HEAD_FOR_31) C2_HEAD31," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_32,RBC_HEAD_FOR_32) C2_HEAD32," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_33,RBC_HEAD_FOR_33) C2_HEAD33," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_34,RBC_HEAD_FOR_34) C2_HEAD34," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_35,RBC_HEAD_FOR_35) C2_HEAD35," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_36,RBC_HEAD_FOR_36) C2_HEAD36," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_37,RBC_HEAD_FOR_37) C2_HEAD37," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_38,RBC_HEAD_FOR_38) C2_HEAD38," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_39,RBC_HEAD_FOR_39) C2_HEAD39," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_40,RBC_HEAD_FOR_40) C2_HEAD40," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_41,RBC_HEAD_FOR_41) C2_HEAD41," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_42,RBC_HEAD_FOR_42) C2_HEAD42," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_43,RBC_HEAD_FOR_43) C2_HEAD43," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_44,RBC_HEAD_FOR_44) C2_HEAD44," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_45,RBC_HEAD_FOR_45) C2_HEAD45," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_46,RBC_HEAD_FOR_46) C2_HEAD46," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_47,RBC_HEAD_FOR_47) C2_HEAD47," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_48,RBC_HEAD_FOR_48) C2_HEAD48," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_49,RBC_HEAD_FOR_49) C2_HEAD49," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_50,RBC_HEAD_FOR_50) C2_HEAD50," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_51,RBC_HEAD_FOR_51) C2_HEAD51," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_52,RBC_HEAD_FOR_52) C2_HEAD52," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_53,RBC_HEAD_FOR_53) C2_HEAD53," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_54,RBC_HEAD_FOR_54) C2_HEAD54," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_55,RBC_HEAD_FOR_55) C2_HEAD55," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_56,RBC_HEAD_FOR_56) C2_HEAD56," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_57,RBC_HEAD_FOR_57) C2_HEAD57," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_58,RBC_HEAD_FOR_58) C2_HEAD58," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_59,RBC_HEAD_FOR_59) C2_HEAD59," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_60,RBC_HEAD_FOR_60) C2_HEAD60," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_61,RBC_HEAD_FOR_61) C2_HEAD61," +
		"DECODE(?,'ENG',RBC_HEAD_ENG_62,RBC_HEAD_FOR_62) C2_HEAD62" +
		" FROM PP_REPORT_BP_COLUMNS " +
		" WHERE RBC_RBH_ID = ?";

	String IP_REP_INFO ="SELECT REP_KEY_NO,REP_VALUE_1, REP_VALUE_2, REP_VALUE_3, REP_VALUE_4," +
						"REP_VALUE_5,REP_VALUE_6, REP_VALUE_7, REP_VALUE_8, REP_VALUE_9," +
						"REP_VALUE_10,REP_VALUE_11, REP_VALUE_12, REP_VALUE_13," +
						"REP_VALUE_14, REP_VALUE_15, REP_VALUE_16,REP_VALUE_17,REP_VALUE_18," +
						"REP_VALUE_19, REP_VALUE_20,REP_VALUE_21, REP_VALUE_22,REP_VALUE_23," +
						"REP_VALUE_24, REP_VALUE_25,REP_VALUE_26, REP_VALUE_27,REP_VALUE_28," +
						"REP_VALUE_29, REP_VALUE_30,REP_VALUE_31, REP_VALUE_32, REP_VALUE_33," +
						"REP_VALUE_34, REP_VALUE_35,REP_VALUE_36, REP_VALUE_37, REP_VALUE_38," +
						"REP_VALUE_39, REP_VALUE_40,REP_VALUE_41, REP_VALUE_42, REP_VALUE_43," +
						"REP_VALUE_44, REP_VALUE_45, REP_VALUE_46, REP_VALUE_47, REP_VALUE_48," +
						"REP_VALUE_49, REP_VALUE_50,REP_VALUE_51, REP_VALUE_52, REP_VALUE_53," +
						"REP_VALUE_54, REP_VALUE_55,REP_VALUE_56, REP_VALUE_57, REP_VALUE_58," +
						" REP_VALUE_59, REP_VALUE_60,REP_ID" +
						" FROM IP_REP_INFO WHERE REP_KEY_NO = ?";   
	
	String COMP_NAME="SELECT DECODE(?,'ENG',COMP_NAME,COMP_BL_NAME) COMP_NAME FROM FM_COMPANY WHERE COMP_CODE = ?";
	
	
	String INSERT_INTO_OW_REPORT_BP_PARAMETERS=
		 "INSERT INTO OW_REPORT_BP_PARAMETERS (RBP_ID, RBP_RBH_ID, RBP_FROM_ENG,"+ 
	   		"	RBP_TO_ENG, RBP_FROM_FOR, RBP_TO_FOR,RBP_CR_DT, RBP_CR_UID,RBP_REP_ID )"+ 
	   		" SELECT RBP_ID, RBP_RBH_ID, RBP_FROM_ENG,RBP_TO_ENG, RBP_FROM_FOR, RBP_TO_FOR,"+ 
	   		" RBP_CR_DT, RBP_CR_UID,?  FROM PP_REPORT_BP_PARAMETERS  WHERE RBP_RBH_ID=?";
	
	String SELECT_DETAILS_FROM_IP_REP_INFO=
			"SELECT REP_ID, REP_CR_UID FROM IP_REP_INFO WHERE REP_KEY_NO = ?";
	
	String SELECT_DETIALS_FROM_PP_REPORT_BP_PARAMETER=
		"SELECT  DECODE(?,'ENG',RBP_FROM_ENG,RBP_FROM_FOR) HEAD1,"+
        " DECODE(?,'ENG',RBP_TO_ENG,RBP_TO_FOR)     HEAD2"+
        " FROM    PP_REPORT_BP_PARAMETERS WHERE   RBP_RBH_ID  = ? ORDER BY RBP_ID ";   

}
