package com.iii.pel.forms.PT001_A_TISB;

public interface PT_AGENT_APF_WITHDRAWL_CONSTANTS {
	
	String PT_AGENT_APF_WITHDRAWL_DELEGATE$AGENT_CODE$LOV$QUERY1="SELECT CUST_CODE,CUST_NAME FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS WHERE CCLAS_TYPE IN (?,?,?))AND CUST_FRZ_FLAG ='N'";
	
	String PT_AGENT_APF_WITHDRAWL_DELEGATE$AGENT_CODE$LOV$QUERY2="SELECT CUST_CODE,CUST_NAME FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS WHERE CCLAS_TYPE IN (?,?,?))AND CUST_FRZ_FLAG ='N' AND CUST_CODE LIKE ?";
	
	String PT_AGENT_APF_WITHDRAWL_DELEGATE$REASON_CODE$LOV$QUERY1="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE=?";
	
	String PT_AGENT_APF_WITHDRAWL_DELEGATE$REASON_CODE$LOV$QUERY2="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE=? AND PC_CODE LIKE ?";
	
	String PT_AGENT_APF_WITHDRAWL_DELEGATE$AGENT_CODE$VALIDATION="SELECT ROWID FROM PM_CUSTOMER " +
			"WHERE  CUST_CODE = ? AND CUST_CLASS IN " +
			"(SELECT CCLAS_CODE FROM PM_CUST_CLASS WHERE CCLAS_TYPE = '002')";
	
	String PT_AGENT_APF_WITHDRAWL_DELEGATE$REASON_CODE$VALIDATION="SELECT PC_DESC FROM PM_CODES" +
			"  WHERE  PC_TYPE = 'WITHDREASON'  AND    PC_FRZ_FLAG = 'N'";
	
	String PRE_INSERT$QUERY="SELECT PIL_APW_SYS_ID.NEXTVAL FROM DUAL";

}
