package com.iii.pel.forms.PILQ003;

public interface PT_IL_POLICY_QUERY_CONSTANTS {
    
    //For predelete
    
    String preDeletePT_IL_POL_CHARGE =" DELETE FROM PT_IL_POL_CHARGE P WHERE P.POC_POL_SYS_ID = ? ";
    
    String preDeletePT_IL_POL_CONDITION   = " DELETE FROM PT_IL_POL_CONDITION P WHERE P.PLCOND_POL_SYS_ID = ?; " ;
    
    String preDeletePT_IL_SURR_MAT_VALUES   = " DELETE FROM PT_IL_SURR_MAT_VALUES P WHERE P.SMV_POL_SYS_ID = ?; " ;
   
    String preDeletePT_IL_POL_BROKER_HEAD   = "DELETE FROM PT_IL_POL_BROKER_HEAD P WHERE P.POBH_POL_SYS_ID = ?";
    
    String preDeletePT_IL_UNPAID_PREM_DTLS   ="DELETE FROM PT_IL_UNPAID_PREM_DTLS P WHERE P.UPD_POL_SYS_ID = ? ";
   
    String preDeletePT_IL_DOC_TODO_LIST_STATUS   = "DELETE FROM PT_IL_DOC_TODO_LIST_STATUS P WHERE P.DTLS_POL_SYS_ID = ? and P.DTLS_END_NO_IDX = ? ";
   
    String preDeletePT_IL_POLICY   = "DELETE FROM PT_IL_POLICY P WHERE P.POL_SYS_ID = ? ";
 
    String preDeletePT_IL_POL_STATUS   =" DELETE FROM PT_IL_POL_STATUS P  WHERE P.PS_POL_SYS_ID = ?";
 
 //   String preDeletePT_IL_POL_STATUS   =" DELETE FROM PT_IL_POL_STATUS P WHERE P.PS_POL_SYS_ID = ?";
  
    String preDeletePT_IL_POL_BENEFICIARY   = "DELETE FROM PT_IL_POL_BENEFICIARY P WHERE P.PBEN_POL_SYS_ID = ?";
  
    String preDeletePT_IL_POL_DISC_LOAD   = "DELETE FROM PT_IL_POL_DISC_LOAD P  WHERE P.PDL_POL_SYS_ID = ? ";
   
    String preDeletePT_IL_POL_ASSURED_DTLS   = "DELETE FROM PT_IL_POL_ASSURED_DTLS P  WHERE P.POAD_POL_SYS_ID = ?";
  
    String preDeletePT_IL_POL_FUND_DTL   = "DELETE FROM PT_IL_POL_FUND_DTL P  WHERE P.POFD_POL_SYS_ID = ?";
  
 //   String preDeletePT_IL_POL_STATUS   ="DELETE FROM PT_IL_POL_STATUS P WHERE P.PS_POL_SYS_ID = ?";
  
    String preDeletePT_IL_POL_ASSR_MED_HIST   = "DELETE FROM PT_IL_POL_ASSR_MED_HIST P  WHERE P.PAMH_POL_SYS_ID = ?";
  
    String preDeletePT_IL_POL_SA_INST_PYMT_HEAD   ="DELETE FROM PT_IL_POL_SA_INST_PYMT_HEAD P WHERE P.SIPH_POL_SYS_ID = ?";
  
    // For LOV
    
    String POL_CONT_CODE_QUERY = " SELECT CONT_CODE,CONT_NAME FROM PM_IL_CONTRACTOR WHERE CONT_FRZ_FLAG='N' AND ROWNUM<=? ORDER BY 1 ";
 
    String POL_CONT_CODE_QUERY_LIKE = " SELECT CONT_CODE,CONT_NAME FROM PM_IL_CONTRACTOR WHERE CONT_FRZ_FLAG='N'" +
    				"  AND (CONT_CODE LIKE ? OR  CONT_NAME LIKE ?) AND ROWNUM<=? ORDER BY 1 ";
    
    String POL_CUSTOMER_LOV_QUERY = "SELECT CUST_CODE,CUST_NAME,CUST_BL_NAME "
	    + " FROM PM_CUSTOMER WHERE CUST_CLASS IN "
	    + " (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM "
	    + " WHERE DECODE(PS_VALUE,2,CCLAS_CODE, CCLAS_TYPE) IN "
	    + " (?)) AND CUST_FRZ_FLAG = 'N' AND (CUST_APPL_ALL_BRAN_YN = 'Y'"
	    + " OR CUST_CODE IN "
	    + " (SELECT CDIV_CUST_CODE FROM PM_CUST_DIVN "
	    + " WHERE CDIV_DIVN_CODE = NVL (?, CDIV_DIVN_CODE))) and ROWNUM < 25 order by 1";
   
}
