package com.iii.pel.forms.PM104_A_TISB;

public interface PM104_A_TSIB_SQLQUERY_CONSTANTS {
	
	

		final String DELETE_PM_IL_FUND_ACCOUNT_SETUP="DELETE FROM PM_IL_DATA_UPLOAD_MAPPING WHERE ROWID= ?";
		final String UPDATE_PM_IL_FUND_ACCOUNT_SETUP="UPDATE * FROM PM_IL_DATA_UPLOAD_MAPPING WHERE ROWID=?";
		final String SELECT_ALL_PM_IL_DATA_UPLOAD_MAPPING=" select PM_IL_DATA_UPLOAD_MAPPING.ROWID,DUM_MAP_CODE,DUM_MAP_CODE_DESC,DUM_DEF_CODE,DUM_FIELD_01,DUM_FIELD_02,DUM_FIELD_03,DUM_FIELD_04,DUM_FIELD_05,DUM_FIELD_06,DUM_FIELD_07,DUM_FIELD_08,DUM_FIELD_09,DUM_FIELD_10,DUM_FIELD_11,DUM_FIELD_12,DUM_FIELD_13,DUM_FIELD_14,DUM_FIELD_15,DUM_FIELD_16,DUM_FIELD_17,DUM_FIELD_18,DUM_FIELD_19,DUM_FIELD_20 from PM_IL_DATA_UPLOAD_MAPPING";
//		final String LOV_FAS_SRC_BUS_FM_TO="SELECT PC_CODE,PC_DESC,PC_BL_DESC FROM PM_CODES" +
//				" WHERE PC_TYPE ='SRC_BUS_TY'AND NVL(PC_FRZ_FLAG,'N') = 'N'";
//		final String LOV_FAS_DEPT_FM_TO_CODE="SELECT DEPT_CODE,DEPT_NAME,DEPT_CODE " +
//				"FROM PM_DEPARTMENT WHERE DEPT_COMP_CODE = ':CTRL.M_COMP_CODE' AND " +
//				"DEPT_DIVN_CODE = ':PM_IL_FUND_ACCOUNT_SETUP.FAS_DIVN_FM_CODE' AND " +
//				"DEPT_FRZ_FLAG  = 'N' AND EXISTS (SELECT 1 FROM PM_APPR_DEPT_SETUP " +
//				"WHERE ADS_DIVN_CODE = DEPT_DIVN_CODE AND ADS_DEPT_CODE = DEPT_CODE" +
//				" AND ADS_USER_ID = NVL('&M_PARA_3',ADS_USER_ID) ANDADS_FRZ_FLAG = 'N')";
//		final String LOV_FAS_DOC_FM_TO_TYPE="SELECT DS_CODE,DS_DESC FROM " +
//				"PM_IL_DOC_SETUP WHERE ( DS_TYPE = '2' OR DS_TYPE = '2')  AND" +
//				"  NVL(DS_FRZ_FLAG ,'N') ='N'";
		
	 final String WHEN_CREATE_RECORD_GET_PC_CODE_FOR_PC_TYPE="	SELECT PC_CODE FROM PM_CODES WHERE PC_TYPE='APFCLMTYP'";	
	
}
