package com.iii.pel.forms.PILM016_APAC_QE;

public interface PILM016_PM_IL_CONTRACTOR_CONSTANTS_QE {

	String PM_IL_CONTRACTOR_REF_ID2_TYPE = "LEN_REF_ID";
	String PM_IL_CONTRACTOR_REF_ID2_CODE = "REF_ID_2";
	String PM_IL_CONTRACTOR_ERRORFLAG = "N";

	String PM_IL_CONTRACTOR_REF_ID2_TYPE1 = "CST_INDREQ";
	String PM_IL_CONTRACTOR_REF_ID2_CODE1 = "CST_INDREQ";
	String PM_IL_CONTRACTOR_ERRORFLAG1 = "N";

	String PM_IL_CONTRACTOR_REF_ID2_TYPE2 = "CATG";
	String PM_IL_CONTRACTOR_ERRORFLAG2 = "N";

	String PM_IL_CONTRACTOR_REF_ID2_TYPE3 = "MARI_STAT";
	String PM_IL_CONTRACTOR_ERRORFLAG3 = "N";

	String PM_IL_CONTRACTOR_P_VAL_CODES_TYPE = "NATLITY";
	String PM_IL_CONTRACTOR_P_VAL_CODES_TYPE1 = "RELIGION";
	String PM_IL_CONTRACTOR_P_VAL_CODES_TYPE2 = "RACE";
	String PM_IL_CONTRACTOR_P_VAL_CODES_TYPE3 = "STATE";

	String PM_IL_CONTRACTOR_M_IND_REQ = "1";

	// Ref Id1
	String PM_IL_CONTRACTOR_REF_ID1_TYPE = "CATG";
	String PM_IL_CONTRACTOR_REF_ID1_ERRORFLAG = "N";
	String PM_IL_CONTRACTOR_REF_ID1_TYPE1 = "MARI_STAT";

	String PM_IL_CONTRACTOR_REF_ID1_TYPE2 = "LEN_REF_ID";
	String PM_IL_CONTRACTOR_REF_ID1_CODE = "REF_ID_1";

	String PM_IL_CONTRACTOR_REF_ID1_TYPE3 = "CUSTREFFMT";
	String PM_IL_CONTRACTOR_REF_ID1_CODE1 = "CUSTREFFMT";

	String PM_IL_CONTRACTOR_ERRORCODE91240 = "Field length exceeded!. Permitted is ERR1";
	String PM_IL_CONTRACTOR_ERRORCODE91152 = "Enter Atleast one IC Number";
	//[ Removed Hard coded user id: added by: Shankar bodduluri Dated: 19-Mar-2009 ]
	String PM_IL_CONTRACTOR_REF_ID1_ERRORFLAG1 = "E";
	
	String PM_IL_CONTRACTOR_COMP_CODE = "001";
	
	//String PM_IL_CONTRACTOR_DIVN_CODE = "HO";
	
	//String PM_IL_CONTRACTOR_DEPT_CODE = "ADM";
	// String
	// PM_IL_CONTRACTOR_M_DIVN_CODE=PM_IL_CONTRACTOR_COMP_CODE+PM_IL_CONTRACTOR_DIVN_CODE+PM_IL_CONTRACTOR_DEPT_CODE;
	//String PM_IL_CONTRACTOR_M_DIVN_CODE = "HO";
	
	String FORMNAME = "PILM016_APAC";
	
	String BLOCKNAME = "PM_IL_CONTRACTOR";
	
	String ITEM1 = "PM_IL_CONTRACTOR.CONT_EMPLOYER_YN";
	
	String ITEM2 = "PM_IL_CONTRACTOR.CONT_PREFERED_LANG";
	
	String PM_IL_CONTRACTOR_REFID1 ="Field length exceeded!. Permitted is 6!";
	
	String PM_IL_CONTRACTOR_P_VAL_CODES_TYPE4 = "CITY";

	//String GLOBAL_M_USER_ID = "LIFEALL";

	String N_FLAG = "N";

	String E_Flag = "E";

	String PM_IL_CONTRACTOR_P_VAL_CODES_TYPE5 = "COUNTRY";

	String EMPLOYEER_YN_N = "N";

	String PREFERRED_LANG_E = "E";

	String PM_IL_CONTRACTOR_CST_INDREQ = "CST_INDREQ";

	String Y_FLAG = "Y";

	String CATEGORY_CODE_1 = "1";

	String CATEGORY_CODE_2 = "2";

	String DATE_FORMAT_DDMMYY = "DD/MM/RR";

	String X_FLAG = "X";
		
	String PERCENTILE_FOR_SELECT_LIKE="%" ;
	
	String GLOBAL_M_PRIVILEGE="YYY";
	String GLOBAL_M_FAILURE ="FALSE";
	
	String GLOBAL_M_MODULE_NAME = "PILM016_APAC";
	
	//String M_CURR_CODE="INR";
	String M_PROG_NAME="PILM016_APAC";
}
