	

package com.iii.pel.forms.PILM035_APAC;

public interface PILM035_APAC_QUERYCONSTANTS {

    String BCH_CODE_LOV = "SELECT BCH_CODE,BCH_DESC FROM   PM_BROKER_COMM_HDR  WHERE ROWNUM <= ? ORDER BY 1";
   
    String BCH_CODE_LOV_LIKE = "SELECT BCH_CODE,BCH_DESC FROM   PM_BROKER_COMM_HDR WHERE (BCH_CODE LIKE ? OR BCH_DESC LIKE ?) " +
    		"AND ROWNUM<= ? ORDER BY 1 ";
   
	String PROD_DS_CODE_LOV_QUERY = "SELECT DS_CODE,DS_DESC  FROM   PM_IL_DOC_SETUP WHERE "
			+ "DS_TYPE = '1' AND DS_FRZ_FLAG ='N' AND ROWNUM<= ?";

	String PROD_DS_CODE_LOV_QUERY_LIKE = "SELECT DS_CODE,DS_DESC  FROM   PM_IL_DOC_SETUP WHERE "
			+ "DS_TYPE = '1' AND DS_FRZ_FLAG ='N' AND (DS_CODE LIKE ? OR DS_DESC LIKE ?)ROWNUM<= ? ORDER BY 1";

	String PROD_BCH_CODE_LOV_QUERY = "SELECT BCH_CODE,BCH_DESC FROM   PM_BROKER_COMM_HDR  AND ROWNUM<= ?";

	String PROD_BCH_CODE_LOV_QUERY_LIKE = "SELECT BCH_CODE,BCH_DESC FROM   PM_BROKER_COMM_HDR  "
			+ "where (BCH_CODE like ? OR BCH_DESC LIKE ?)ROWNUM<= ?";

	String PROD_PLAN_CODE_LOV_QUERY = "SELECT  PLAN_CODE "
			+ "FROM    PM_IL_PLAN WHERE PLAN_FRZ_FLAG='N' AND ROWNUM<= ?";

	String PROD_PLAN_CODE_LOV_QUERY_LIKE = "SELECT  PLAN_CODE "
			+ "FROM    PM_IL_PLAN WHERE PLAN_FRZ_FLAG='N' AND (PLAN_CODE LIKE ?) AND ROWNUM<= ?";

	String PROD_MORT_CODE_LOV_QUERY = " SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_MORT_CODE' AND ROWNUM<=?";

	String PROD_MORT_CODE_LOV_QUERY_LIKE = " SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_MORT_CODE' AND (PC_CODE LIKE ? OR PC_DESC LIKE ?) AND ROWNUM<=?";

	String PROD_SA_TARIFF_LOV_QUERY = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_VAL_TAR' AND ROWNUM<=?";

	String PROD_SA_TARIFF_LOV_QUERY_LIKE = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_VAL_TAR' AND (PC_CODE LIKE ? OR PC_DESC LIKE ?) AND ROWNUM<=?";

	String PROD_PREM_TARIFF_LOV_QUERY = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_VAL_TAR' AND ROWNUM<=?";

	String PROD_PREM_TARIFF_LOV_QUERY_LIKE = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_VAL_TAR' AND (PC_CODE LIKE ? OR PC_DESC LIKE ?) AND ROWNUM<=?";

	String PROD_TOPUP_COMM_CODE_LOV_QUERY = "SELECT  BCH_CODE,BCH_DESC FROM   PM_BROKER_COMM_HDR WHERE ROWNUM<=?";

	String PROD_TOPUP_COMM_CODE_LOV_QUERY_LIKE = "SELECT  BCH_CODE,BCH_DESC FROM   PM_BROKER_COMM_HDR WHERE (BCH_CODE LIKE ? OR BCH_DESC LIKE ?) AND ROWNUM<=?";

	String PROD_SURR_PLUS_FACTOR_LOV_QUERY = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_VAL_TAR' AND ROWNUM<=?";

	String PROD_SURR_PLUS_FACTOR_LOV_QUERY_LIKE = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_VAL_TAR' AND (PC_CODE LIKE ? OR PC_DESC LIKE ?) AND ROWNUM<=?";

	String PROD_SURRENDER_FACTOR_LOV_QUERY = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_VAL_TAR' AND ROWNUM<=?";

	String PROD_SURRENDER_FACTOR_LOV_QUERY_LIKE = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_VAL_TAR' AND (PC_CODE LIKE ? OR PC_DESC LIKE ?) AND ROWNUM<=?";
	
	

}
