package com.iii.pel.forms.PILM048_APAC;

public interface PM_BANK_CHARGE_SETUP_QUERY_CONSTANT {
	String FETCH_SERCH_LIST = "SELECT BCSH_BANK_CODE,BCSH_CHG_CODE,BCSH_MAIN_ACNT_CODE," +
			"BCSH_SUB_ACNT_CODE,BCSH_DIVN_CODE,BCSH_DEPT_CODE,ROWID FROM " +
			"PM_BANK_CHARGE_SETUP_HDR WHERE BCSH_BANK_CODE LIKE NVL(?,BCSH_BANK_CODE)" +
			"AND BCSH_CHG_CODE LIKE NVL(?,BCSH_CHG_CODE)";

}
