package com.iii.pel.forms.PILM074_APAC;


public interface PILM074_APAC_QUERY_CONSTANTS {

	String SELECT_SEARCH_DETAILS = "SELECT ROWID,TH_TAX_TYPE,TH_TAX_DESC from  PM_LIFE_TAX_HEADER WHERE TH_TAX_TYPE LIKE NVL(?, TH_TAX_TYPE) AND TH_TAX_LONG_DESC LIKE  NVL(?, TH_TAX_LONG_DESC)";
	String SELECT_COMBOBOXVALUE = "SELECT  LIV_CODE,LIV_CODE_DESC FROM PP_LIST_ITEM,PP_LIST_ITEM_VALUES WHERE LI_SYS_PARAM = LIV_SYS_PARAM AND LI_MODULE_NAME = ? AND LI_BLOCK_NAME = ? AND LI_ITEM_NAME = ?";
	//Commented by kavitha on 07.10.2019 for orient
	//String SELECT_TAX_TYPE_LOV = "SELECT PC_CODE,PC_DESC,PC_BL_DESC FROM PM_CODES WHERE PC_TYPE  = 'IL_CHARGE' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM < ? ORDER BY PC_CODE ASC";
	//String SELECT_TAX_TYPE_LOV_LIKE = "SELECT PC_CODE,PC_DESC,PC_BL_DESC FROM PM_CODES WHERE PC_CODE LIKE ? AND PC_TYPE  = 'IL_CHARGE' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM < ? ORDER BY PC_CODE ASC";
	String SELECT_LIFE_TAX_SETUP = "SELECT ROWID, PM_LIFE_TAX_HEADER.* FROM  PM_LIFE_TAX_HEADER WHERE ROWID = ? ";
	//Modified by senthilnathan for orient on 23-11-19 desc:LOV is listing correctly with desc, but on selecting, it changes to this description.
	//String SELECT_HEADER_POST_DESC = "SELECT PC_DESC FROM PM_CODES WHERE PC_CODE = ?";
	String SELECT_HEADER_POST_DESC = "SELECT PC_DESC FROM PM_CODES WHERE PC_TYPE  = 'IL_TRANS_TYP' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND PC_CODE = ? ";
	String SELECT_LIFE_TAX_PRODUCT = "SELECT ROWID,PM_LIFE_TAX_APPL_PROD.* FROM PM_LIFE_TAX_APPL_PROD WHERE TAP_TH_TAX_TYPE = ? ";
	String SELECT_LIFE_TAX_CLASS = "SELECT ROWID, PM_LIFE_TAX_APPL_CUST.* FROM PM_LIFE_TAX_APPL_CUST WHERE TAC_TH_TAX_TYPE = ? ";
	//Changing table name for below query as PM_IL_PRODUCT instead of PM_GL_PRODUCT for Individual Life
	String SELECT_PRODUCT_CODE_LOV = "SELECT PROD_CODE,PROD_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE IS NOT NULL AND ROWNUM < ? ORDER BY PROD_CODE";
	String SELECT_PRODUCT_CODE_LOV_LIKE = "SELECT PROD_CODE,PROD_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE LIKE ? AND PROD_CODE IS NOT NULL AND ROWNUM < ? ORDER BY PROD_CODE";
	//end
	String SELECT_PRODUCT_POST_DESC = "	SELECT PROD_DESC FROM   PM_IL_PRODUCT WHERE  PROD_CODE = ? ";
	String SELECT_X_FOR_PRE_INSERT_PROD = "SELECT ROWID  FROM   PM_LIFE_TAX_APPL_PROD WHERE( ? BETWEEN TAP_EFF_FM_DT AND TAP_EFF_TO_DT OR ?  BETWEEN TAP_EFF_FM_DT AND TAP_EFF_TO_DT OR TAP_EFF_FM_DT BETWEEN ? AND ? OR TAP_EFF_TO_DT BETWEEN ? AND ? ) AND TAP_TH_TAX_TYPE  = ? AND TAP_PROD_CODE	= ? ";

	/*Uncommented by Janani on 11.12.2019 for Orient
	issue : Not a valid cust class*/
	String SELECT_CUST_CODE_LOV = "SELECT CCLAS_CODE,CCLAS_CLASS_DESC FROM PM_CUST_CLASS WHERE PM_CUST_CLASS.CCLAS_FRZ_FLAG = 'N' AND ROWNUM < ? ORDER BY CCLAS_CODE";
	//String SELECT_CUST_CODE_LOV ="SELECT PC_CODE, PC_DESC FROM PM_CODES  WHERE PC_TYPE = 'SRC_BUS_TY' AND ROWNUM < ? ORDER BY PC_CODE";
	
	
	String SELECT_CUST_CODE_LOV_LIKE = "SELECT CCLAS_CODE,CCLAS_CLASS_DESC FROM PM_CUST_CLASS WHERE CCLAS_CODE LIKE ? AND PM_CUST_CLASS.CCLAS_FRZ_FLAG = 'N' AND ROWNUM < ? ORDER BY CCLAS_CODE";
	//String SELECT_CUST_CODE_LOV_LIKE = "SELECT PC_CODE, PC_DESC FROM PM_CODES  WHERE PC_CODE LIKE ? AND PC_TYPE = 'SRC_BUS_TY' AND ROWNUM < ? ORDER BY PC_CODE";
	
	/*End*/
	

	String SELECT_CUST_CLASS_POST_DESC = "SELECT CCLAS_CLASS_DESC FROM PM_CUST_CLASS WHERE CCLAS_CODE = ? ";
	
	
	String SELECT_X_FOR_PRE_INSERT_CUST = "SELECT ROWID FROM   PM_LIFE_TAX_APPL_CUST WHERE(? BETWEEN  TAC_EFF_FM_DT AND TAC_EFF_TO_DT OR ? BETWEEN TAC_EFF_FM_DT AND TAC_EFF_TO_DT OR TAC_EFF_FM_DT BETWEEN ? AND ? OR TAC_EFF_TO_DT BETWEEN ? AND ?) AND TAC_TH_TAX_TYPE = ? AND TAC_CUST_CLASS = ?";
	String CHECK_CUST_DELETE = "SELECT 1 FROM PM_LIFE_TAX_APPL_CUST P WHERE P.TAC_TH_TAX_TYPE = ? ";
	String CHECK_PRODUCT_DELETE = "SELECT 1 FROM PM_LIFE_TAX_APPL_PROD P WHERE P.TAP_TH_TAX_TYPE = ? ";
	//Added by kavitha on 07.10.2019 for orient
	String SELECT_TAX_TYPE_LOV = "SELECT PC_CODE,PC_DESC,PC_BL_DESC FROM PM_CODES WHERE PC_TYPE  = 'IL_TRANS_TYP' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM < ? ORDER BY PC_CODE ASC";
	String SELECT_TAX_TYPE_LOV_LIKE = "SELECT PC_CODE,PC_DESC,PC_BL_DESC FROM PM_CODES WHERE PC_CODE LIKE ? AND PC_TYPE  = 'IL_TRANS_TYP' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM < ? ORDER BY PC_CODE ASC";
	

}
