package com.iii.pel.forms.PILP042_APAC;

public interface PILP042_APAC_SQL_QUERY_CONSTANTS {
	
	String RETRIEVE_POLICY_NO_LOV = "SELECT POL_NO,TO_CHAR(POL_ISSUE_DT),TO_CHAR(POL_ISSUE_DT) FROM PT_IL_POLICY WHERE ROWNUM < ? AND NVL(POL_APPRV_STATUS,'N') ='A' AND POL_NO IS NOT NULL AND POL_DS_TYPE = '2' AND POL_PLAN_CODE IN (SELECT PLAN_CODE FROM PM_IL_PLAN WHERE PLAN_TYPE = 'U') ";
	
	String RETRIEVE_POLICY_NO_LOV_LIST_LIKE = "SELECT POL_NO,TO_CHAR(POL_ISSUE_DT),TO_CHAR(POL_ISSUE_DT) FROM PT_IL_POLICY WHERE POL_NO LIKE ? AND ROWNUM < ?  AND NVL(POL_APPRV_STATUS,'N') ='A' AND POL_NO IS NOT NULL AND POL_DS_TYPE = '2' AND POL_PLAN_CODE IN (SELECT PLAN_CODE FROM PM_IL_PLAN WHERE PLAN_TYPE = 'U')";
	
	String FTH_POL_NO_WHEN_VAL_SELECT_QUERY1 = "SELECT POL_SYS_ID ,POL_CUST_CODE ,POL_PROD_CODE ,POL_CUST_EXCH_RATE,POL_PREM_PAY_YRS FROM PT_IL_POLICY WHERE POL_NO = ? AND POL_PLAN_CODE IN (SELECT PLAN_CODE FROM PM_IL_PLAN WHERE PLAN_TYPE = 'U')"; 

	String FTH_POL_NO_WHEN_VAL_SELECT_QUERY6 = "SELECT COUNT(*) FROM PT_IL_FUND_TRAN_HDR  WHERE FTH_POL_NO = ? AND  FTH_APPRV_STATUS='A'";
	
	String FTH_POL_NO_WHEN_VAL_SELECT_QUERY7 = "SELECT WCS_NO_OF_TRANS,WCS_RATE,WCS_RATE_PER,WCS_MIN_VALUE,WCS_MAX_VALUE FROM PM_IL_WDS_CHARGES_SETUP WHERE WCS_PROD_CODE = ? AND WCS_SETUP_TYPE ='H' AND ? BETWEEN WCS_YRS_FM AND WCS_YRS_TO";
	
	String FTH_POL_NO_WHEN_VAL_SELECT_QUERY5 = "SELECT FTH_APPRV_STATUS,FTH_STATUS_CODE FROM PT_IL_FUND_TRAN_HDR WHERE FTH_SYS_ID=(SELECT MAX(FTH_SYS_ID) FROM PT_IL_FUND_TRAN_HDR WHERE FTH_POL_NO = ? )";
	
	String FTH_POL_NO_WHEN_VAL_SELECT_QUERY2 = "SELECT PROD_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE = ? ";
			
	String FTH_POL_NO_WHEN_VAL_SELECT_QUERY4 = " SELECT COUNT(*)+1 FROM PT_IL_FUND_TRAN_HDR WHERE FTH_POL_NO = ? AND FTH_APPRV_STATUS = 'A'";
	
	String FTH_FEE_LC_AMT_WHEN_VAL_SELECT_QUERY2 = "SELECT POL_PREM_PAY_YRS,POL_PROD_CODE FROM PT_IL_POLICY WHERE POL_NO = ? ";
	
	String FTH_FEE_LC_AMT_WHEN_VAL_SELECT_QUERY1 = "SELECT WCS_MIN_VALUE,WCS_MAX_VALUE,WCS_NO_OF_TRANS FROM PM_IL_WDS_CHARGES_SETUP WHERE WCS_PROD_CODE  = ? AND WCS_SETUP_TYPE  = 'H' AND ? BETWEEN WCS_YRS_FM AND WCS_YRS_TO ";
	
	String FTH_FEE_LC_AMT_WHEN_VAL_SELECT_QUERY3 = "SELECT COUNT(*) FROM PT_IL_FUND_TRAN_HDR WHERE FTH_POL_NO  = ? AND FTH_APPRV_STATUS  = 'A' ";
	
	String PT_IL_FUND_TRAN_HDR_PRE_INSERT = "SELECT P9IL_FTH_SYS_ID.NEXTVAL FROM DUAL  ";
	
	String PT_IL_FUND_TRAN_HDR_POST_QUERY_QUERY1 = "SELECT POL_CUST_CODE,POL_PROD_CODE FROM PT_IL_POLICY WHERE POL_NO = ? ";
	
	String PT_IL_FUND_TRAN_HDR_POST_QUERY_QUERY2 = "SELECT PROD_DESC FROM  PM_IL_PRODUCT  WHERE  PROD_CODE  = ? " ;
	
	String PT_IL_FUND_TRAN_HDR_WHEN_NEW_RECORD_INSTANCE_QUERY3 = "SELECT FTH_APPRV_STATUS,FTH_APPRV_DT,FTH_STATUS_CODE FROM PT_IL_FUND_TRAN_HDR WHERE FTH_SYS_ID  = ? "; 
	
	String PT_IL_FUND_TRAN_HDR_WHEN_NEW_RECORD_INSTANCE_QUERY4 = "SELECT COUNT(*) FROM  PT_IL_FUND_TRAN_DTL  WHERE  FTD_TRAN_SYS_ID  = ?  AND FTD_SELECT_YN IS NOT NULL ";
	
	String PT_IL_FUND_TRAN_HDR_WHEN_NEW_RECORD_INSTANCE_QUERY5 = "SELECT COUNT(*) FROM  PT_IL_FUND_TRAN_DTL  WHERE  FTD_TRAN_SYS_ID  = ?  AND FTD_SELECT_YN  IS NULL ";
	
	String PT_IL_FUND_TRAN_HDR_WHEN_NEW_RECORD_INSTANCE_QUERY6 = "SELECT FTH_STATUS_CODE FROM  PT_IL_FUND_TRAN_HDR  WHERE  FTH_SYS_ID  = ?  AND FTH_POL_SYS_ID  = ? ";
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}
