package com.iii.pel.forms.PILM015_APAC;

public interface PM_IL_PROP_TREATY_CONSTANTS {

	String PILM105_APAC_TREATY_MASTER_MODULE_NAME_PILM015_APAC ="PILM015_APAC";
	String PILM105_APAC_TREATY_MASTER_BLOCK_NAME_PM_IL_PROP_TREATY="PM_IL_PROP_TREATY";
	
	String PILM105_APAC_TREATY_MASTER_ITEM_NAME_CQS_YN="PM_IL_PROP_TREATY.PT_CQS_YN";
	String PILM105_APAC_TREATY_MASTER_SYS_PARAM_CQS_YN="YESNO";
	
	
	String PILM015_APAC_TREATY_MASTER_ITEM_NAME_ENDT_YN="PM_IL_PROP_TREATY.PT_REALLC_ENDT_YN";
	String PILM105_APAC_TREATY_MASTER_SYS_PARAM_ENDT_YN="YESNO";
	
	String PILM015_APAC_TREATY_MASTER_ITEM_NAME_RI_BASIS="PM_IL_PROP_TREATY.PT_RIDER_RI_BASIS";
	String PILM105_APAC_TREATY_MASTER_SYS_PARAM_RI_BASIS="IL_RIBASIS";
	
	String PILM015_APAC_TREATY_MASTER_ITEM_NAME_CLAIM_YN="PM_IL_PROP_TREATY.PT_SURR_CLAIM_YN";
	String PILM105_APAC_TREATY_MASTER_SYS_PARAM_CLAIM_YN="YESNO";
	
	String PILM015_APAC_TREATY_MASTER_SUGGESTION_BOX_GET_ALL ="*" ;
	
	String PERCENTILE_FOR_SELECT_LIKE = "%";
	String PILM_015_APAC_TREATY_MASTER_SUGGESTION_BOX_DISPLAY_RECORDS_LESS_THEN = "21";
	
	String PILM015_APAC_PM_IL_TREATY_PART_CUST_PTPC_LEADER_YN="PM_IL_PROP_TREATY_PART_CUST.PTPC_LEADER_YN";
	String PILM015_APAC_PM_IL_TREATY_PART_CUST="PM_IL_PROP_TREATY_PART_CUST";
	String PILM015_APAC_PM_IL_TREATY_PART_CUST_PTPC_LEADER_YN_SYS_PARAM="YESNO";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_P_NAME_FLAG="N";
	String PILM015_APAC_PM_IL_PROP_TREATY_P_ERR_FLAG="E";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PT_CQS_YN_N="N";
	String PILM015_APAC_PM_IL_PROP_TREATY_PT_CQS_YN_Y="Y";
	
	String COMP_CODE = "001";
	
	String DIVN_CODE = "HO";
	
	String DEPT_CODE = "ADM";
	// String
	// PM_IL_CONTRACTOR_M_DIVN_CODE=PM_IL_CONTRACTOR_COMP_CODE+PM_IL_CONTRACTOR_DIVN_CODE+PM_IL_CONTRACTOR_DEPT_CODE;
	String M_DIVN_CODE = "HO";
	String GLOBAL_M_PRIVILEGE="YYY";
	String GLOBAL_M_FAILURE ="FALSE";
	String GLOBAL_M_USER_ID ="PREMIA";
	String GLOBAL_M_NAME = "COMPANY NAME..................PROGRAM NAME";
	String GLOBAL_M_LANG_CODE = "ENG";
	String GLOBAL_M_DFLT_VALUES ="00101    01";
	String GLOBAL_M_PARA_1 = " ";
	String GLOBAL_M_FOR_LANG_CODE = "ARBR1";
	String GLOBAL_M_MODULE_NAME = "PILM015_APAC";
	
	String M_CURR_CODE="INR";
	String M_PROG_NAME="PILM015_APAC";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_POST_QUERY_P_TYPE_FOR_CODE_DESC=
																"IL_TTY_CH";
	String PILM015_APAC_PM_IL_PROP_TREATY_POST_QUERY_P_CODE_FOR_CODE_DESC=
																"IL_TTY_CH";
	String PILM015_APAC_PM_IL_PROP_TREATY_E_FLAG="E";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_N_FLAG="N";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PT_RIDER_RI_BASIS_S="S";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PT_SURR_CLAIM_YN_N="N";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PT_SURR_CLAIM_YN_Y="Y";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PT_REALLC_ENDT_YN_Y="Y";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PT_REALLC_ENDT_YN_N="N";
	
	String PILM015_APAC_PL_IL_PROP_TREATY_TYPE_TREATY_TYPE="IL_TTY_TYP";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_UW_YEAR_MIN_UPTO="1960";
	
	String  PILM015_APAC_PM_IL_PROP_TREATY_UW_YEAR_MAX_UPTO="2099";
	
}
