package com.iii.pel.forms.PILM015_APAC;

public interface PM_IL_PROP_TREATY_QUERY_CONSTANTS {

	String PILM015_APAC_TREATY_MASTER_SELECT_CLASS_CODE =
							"SELECT CLASS_CODE,CLASS_NAME FROM PM_IL_CLASS WHERE" +
											" CLASS_FRZ_FLAG='N'AND ROWNUM<?";
	String PILM015_APAC_TREATY_MASTER_SELECT_CLASS_CODE_LIKE = 
							"SELECT CLASS_CODE,CLASS_NAME FROM PM_IL_CLASS WHERE"+
											" CLASS_FRZ_FLAG='N'AND CLASS_CODE LIKE ? AND ROWNUM < ?"; 
	String PILM015_APAC_TREATY_MASTER_SELECT_TREATY_CODE =
							"SELECT PT_TREATY_CODE,PT_TREATY_DESC FROM PM_IL_PROP_TREATY WHERE " +
											" PM_IL_PROP_TREATY.PT_FRZ_FLAG = 'N' AND ROWNUM<?";
	
	String PILM015_APAC_TREATY_MASTER_SELECT_TREATY_CODE_LIKE = 
					"SELECT PT_TREATY_CODE,PT_TREATY_DESC FROM PM_IL_PROP_TREATY " +
							"WHERE PM_IL_PROP_TREATY.PT_FRZ_FLAG = 'N' AND PT_TREATY_CODE LIKE ? AND ROWNUM<?";

	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_CURRENCY to FM_CURRENCY. Added by : Mallika.S, 01-Apr-2009 */
	String PIL015_APAC_PM_IL_PROP_TREATY_PT_CURR_CODE=
					"SELECT CURR_CODE,CURR_NAME FROM FM_CURRENCY WHERE ROWNUM < ? ";
	
	String PIL015_APAC_PM_IL_PROP_TREATY_PT_CURR_CODE_LIKE=
					"SELECT CURR_CODE,CURR_NAME FROM FM_CURRENCY WHERE CURR_CODE LIKE ? AND ROWNUM < ? ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TTY_CVR_PTTC_COVER_CODE=
		"SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE"+
		" COVER_FRZ_FLAG = 'N'  AND COVER_TYPE = NVL('A',COVER_TYPE) AND ROWNUM<?";
	String PILM015_APAC_PM_IL_PROP_TREATY_TTY_CVR_PTTC_COVER_CODE_LIKE=
			"SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE"+
			" COVER_FRZ_FLAG = 'N'  AND COVER_TYPE = NVL('A',COVER_TYPE) AND COVER_CODE LIKE ? AND ROWNUM<?";
	
	/*String PILM015_APAC_PL_IL_PROP_TREATY_TYPE_CUST_PTPC_CUST_CODE=
		 "SELECT CUST_CODE,CUST_NAME FROM PM_CUSTOMER"+
		    "WHERE "+
		   " CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM "+
		                  " WHERE  DECODE (PS_VALUE,2,CCLAS_CODE, CCLAS_TYPE)IN ('REINS')"+
		                  " AND PS_CODE = 'REINS' AND PS_TYPE ='LOV_CUST') "+
		   " AND CUST_FRZ_FLAG = 'N' "+
		   " AND((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM  PM_CUST_DIVN"+
		                      " WHERE CDIV_DIVN_CODE = NVL (?, CDIV_DIVN_CODE)"+
		                      " AND CUST_APPL_ALL_BRAN_YN = 'N'))"+
		                      " OR (CUST_APPL_ALL_BRAN_YN = 'Y'))";
			//? IS dIVSION CODE SHOLUD COME FROM cONTROL bEAN
	
	String PILM015_APAC_PL_IL_PROP_TREATY_TYPE_CUST_PTPC_CUST_CODE_LIKE=
		
		"SELECT CUST_CODE,CUST_NAME FROM PM_CUSTOMER"+
	    "WHERE "+
	   " CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM "+
	                  " WHERE  DECODE (PS_VALUE,2,CCLAS_CODE, CCLAS_TYPE)IN ('REINS')"+
	                  " AND PS_CODE = 'REINS' AND PS_TYPE ='LOV_CUST') "+
	   " AND CUST_FRZ_FLAG = 'N' "+
	   " AND((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM  PM_CUST_DIVN"+
	                      " WHERE CDIV_DIVN_CODE = NVL (?, CDIV_DIVN_CODE)"+
	                      " AND CUST_APPL_ALL_BRAN_YN = 'N'))"+
	                      " OR (CUST_APPL_ALL_BRAN_YN = 'Y')) AND CUST_CODE LIKE ? ";*/
	
	String PILM015_APAC_PL_IL_PROP_TREATY_TYPE_CUST_PTPC_CUST_CODE=
		 "SELECT CUST_CODE, CUST_NAME FROM PM_CUSTOMER	WHERE CUST_CLASS IN"
       + " (SELECT CCLAS_CODE" 
       + " FROM PM_CUST_CLASS, PP_SYSTEM" 
       + " WHERE INSTR(PS_CODE_DESC," 
                   + " '''' || DECODE(PS_VALUE, 2, CCLAS_CODE, CCLAS_TYPE) || '''') <> 0" 
         + " AND PS_CODE = 'REINS'" 
         + " AND PS_TYPE = 'LOV_CUST')" 
  + " AND CUST_FRZ_FLAG = 'N'" 
  + " AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE" 
                       + " FROM PM_CUST_DIVN" 
                       + " WHERE CDIV_DIVN_CODE = NVL (?, CDIV_DIVN_CODE)" 
                       + " AND NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'N')) OR" 
     + " (NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'Y')) AND ROWNUM<21";
	
	String PILM015_APAC_PL_IL_PROP_TREATY_TYPE_CUST_PTPC_CUST_CODE_LIKE=
		 "SELECT CUST_CODE, CUST_NAME FROM PM_CUSTOMER	WHERE CUST_CLASS IN"
       + " (SELECT CCLAS_CODE" 
       + " FROM PM_CUST_CLASS, PP_SYSTEM" 
       + " WHERE INSTR(PS_CODE_DESC," 
                   + " '''' || DECODE(PS_VALUE, 2, CCLAS_CODE, CCLAS_TYPE) || '''') <> 0" 
         + " AND PS_CODE = 'REINS'" 
         + " AND PS_TYPE = 'LOV_CUST')" 
  + " AND CUST_FRZ_FLAG = 'N'" 
  + " AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE" 
                       + " FROM PM_CUST_DIVN" 
                       + " WHERE CDIV_DIVN_CODE = NVL (?, CDIV_DIVN_CODE)" 
                       + " AND NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'N')) OR" 
     + " (NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'Y')) AND CUST_CODE LIKE ? AND ROWNUM<21";
		                
	
	String PILM015_APAC_PM_IL_PROP_TREATY_SELECT_X_FOR_TREATY_CLASS_CODE=
						"SELECT 'X' " +
	            		"FROM   PM_IL_PROP_TREATY " +
	            		"WHERE  PT_CLASS_CODE = ? " +
	            		"AND    PT_UW_YEAR = ? " +
	            		"AND    (PT_START_DT BETWEEN ? AND ? " +
	            		"OR  PT_END_DT BETWEEN ? AND ? " +
	            		"OR ? BETWEEN PT_START_DT AND PT_END_DT " +
	            		"OR ? BETWEEN PT_START_DT AND PT_END_DT) " +
	            		"AND NVL(PT_CQS_YN, 'N')  = NVL(?, 'N') ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_SELECT_X_FOR_TREATY_CLASS_CODE_ROW_ID=
						"SELECT 'X' " +
	            		"FROM   PM_IL_PROP_TREATY " +
	            		"WHERE  PT_CLASS_CODE = ? " +
	            		"AND    PT_UW_YEAR = ? " +
	            		"AND    (PT_START_DT BETWEEN ? AND ? " +
	            		"OR  PT_END_DT BETWEEN ? AND ? " +
	            		"OR ? BETWEEN PT_START_DT AND PT_END_DT " +
	            		"OR ? BETWEEN PT_START_DT AND PT_END_DT) " +
	            		"AND NVL(PT_CQS_YN, 'N')  = NVL(?, 'N')  AND ROWID  <> ? ";
	
	String PILM015_APAC_PM_PM_IL_PROP_TREATY_SELECT_1_FOR_TREATY_CODE=
		"SELECT 1 FROM  PM_IL_PROP_TREATY  WHERE  PT_TREATY_CODE  =?" +
		" AND PT_CLASS_CODE  = ? AND PT_CQS_YN  = ?";
	
	String PILM015_APAC_PM_PM_IL_PROP_TREATY_PIL_PT_SYS_ID=
			"SELECT PIL_PT_SYS_ID.NEXTVAL FROM  DUAL  ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_POST_QUERY=
			"SELECT 'X' FROM  PT_IL_POLICY  WHERE  POL_UW_YEAR  = ?"+  
				"AND POL_CLASS_CODE  = ?  AND POL_DS_TYPE  = '2' ";
	
	String PILM015_APAC_PM_IL_PROP_TTYCOV_GRP_SELECT_X_FOR_PTG_COVER_CODE=
		"SELECT 'X' FROM  PM_IL_COVER  WHERE  COVER_TYPE  IN ( 'A'  ) " +
			" AND COVER_CODE  = ? ";
	
	String PILM015_APAC_PM_IL_PROP_TTYCOV_GRP_SELECT_DEATILS_FOR_COVER_CODE=
		"SELECT    DECODE(?, 'N', COVER_DESC, COVER_LONG_DESC)," +
		"    DECODE(?, 'N', COVER_BL_DESC, COVER_BL_LONG_DESC), " +
		"   COVER_FRZ_FLAG FROM  PM_IL_COVER  WHERE  COVER_CODE  = ?" +
		"  AND COVER_TYPE  IN ( 'A'  , 'S'  ) ";
	
	String PILM015_APAC_PM_IL_PROP_TTYCOV_GRP_SELECT_X_FOR_PTT_AND_PTG_SYS_ID=
		"SELECT 'X' FROM  PM_IL_PROP_TTYCOV_GRP,  PM_IL_PROP_TREATY_TYPE "+ 
		" WHERE  PTG_PTT_SYS_ID  = PTT_SYS_ID  AND PTG_PTC_SYS_ID  = "+
		" ? AND PTG_PTT_SYS_ID  = ?"+
		" AND PTT_PT_SYS_ID  = ?  AND PTG_COVER_CODE"+ 
		" = ? ";
	
	String PILM015_APAC_PM_IL_PROP_TTYCOV_GRP_SELECT_X_FOR_PTT_AND_PTG_SYS_ID_AND_ROWID=
	"SELECT 'X' FROM  PM_IL_PROP_TTYCOV_GRP,   PM_IL_PROP_TREATY_TYPE"+ 
	" WHERE  PTG_PTT_SYS_ID  = PTT_SYS_ID  AND PTG_PTC_SYS_ID  ="+ 
	" ?  AND PTG_PTT_SYS_ID  = "+
	" ?  AND PTT_PT_SYS_ID  = "+
	" ?  AND PTG_COVER_CODE  = "+
	" ? AND PM_IL_PROP_TTYCOV_GRP.ROWID"+ 
	" != ? ";
	
	
	String  PILM015_APAC_PM_IL_PROP_TTYCOV_GRP_UPDATE_PM_IL_PROP_TTYCOV_GRP=
		"UPDATE   PM_IL_PROP_TTYCOV_GRP    SET PTG_SR_NO = TO_NUMBER(:SYSTEM.TRIGGER_RECORD) " +
			" WHERE  PTG_SYS_ID  = :PM_IL_PROP_TTYCOV_GRP.PTG_SYS_ID  ";
	
	String 	PILM015_APAC_PM_IL_PROP_TTYCOV_GRP_SELECT_COVER_DESC_FOR_COVER_CODE=
		"SELECT COVER_DESC FROM  PM_IL_COVER  WHERE  COVER_CODE  = ? ";
	
	String PILM015_APAC_PM_IL_PROP_TTYCOV_GRP_P9IL_PTG_SYS_ID=
		"SELECT P9IL_PTG_SYS_ID.NEXTVAL FROM  DUAL "; 
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_CVR_SELECT_X_FOR_SYSID_COVER_CODE=
		"SELECT 'X' FROM  PM_IL_PROP_TREATY_TYPE_COVER  WHERE  PTTC_PTT_SYS_ID  =" +
			" ?  AND PTTC_COVER_CODE  =" +
				" ? ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_CVR_SELECT_X_FOR_COVER_TYPE_AND_COVER_CODE=
				"SELECT ROWID FROM  PM_IL_COVER  WHERE  COVER_TYPE  = 'B'  " +
						"AND COVER_CODE  = ? ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_CVR_PIL_PTTC_SYS_ID=
					"SELECT PIL_PTTC_SYS_ID.NEXTVAL FROM  DUAL  ";

	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_CVR_SELECT_X_FOR_SYSID_AND_COVER_CODE=
				"SELECT 'X' FROM  PM_IL_PROP_TREATY_TYPE_COVER  WHERE  PTTC_PTT_SYS_ID  = " +
					"?  AND PTTC_COVER_CODE  = ? ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_PIL_PTT_SYS_ID=
		"SELECT PIL_PTT_SYS_ID.NEXTVAL FROM  DUAL  ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_SELECT_PS_VALUE=
	"SELECT PS_VALUE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'NUMFMTMASK'  AND PS_CODE  = 'NUMFMTMASK' ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_SELECT_DESTAILS_FOR_ITEM_BLOCK_AND_MODULE=
	"SELECT    LI_SYS_PARAM,    LI_EXTERNAL_TABLE_YN,    LI_WHERE_CLAUSE FROM  PP_LIST_ITEM  " +
	"WHERE  LI_ITEM_NAME  = ?  AND LI_BLOCK_NAME  = ?  AND LI_MODULE_NAME  = ? ";
	
	String  PILM015_APAC_PM_IL_PROP_TREATY_TYPE_SELECT_FONT=
	"SELECT    NVL(PS_CODE_DESC, 'MICROSOFT SANS SERIF')," +
	"    NVL(PS_VALUE, 1000) FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'BL_FONT'  AND PS_CODE  = 'BL_FONT' ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_SELECT_PTT_SR_NO_FOR_SYS_ID=
	 "SELECT NVL(MAX(PTT_SRNO) + 1, 1) FROM  PM_IL_PROP_TREATY_TYPE  " +
     "WHERE  PTT_PT_SYS_ID  = ? ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_SELECT_DETAILS_FOR_PT_SYS_ID=
	"SELECT    PTT_MGT_EXP_RATIO,    PTT_PROFIT_COMM," +
    "    PTT_REINS_TAX_PERC,    PTT_PREM_PF_ENT_PERC,    PTT_PREM_PF_WD_PERC," +
    "    PTT_LOSS_PF_ENT_PERC,    PTT_LOSS_PF_WD_PERC,    PTT_LOSS_CF_YEARS," +
    "    PTT_DEPOSIT_PREM,    PTT_PREM_RES_RATIO,    PTT_INT_ON_RES_REL, " +
    "   PTT_OS_CLM_RES_RATIO,    PTT_NOTICE_CANCEL_DAYS FROM " +
    " PM_IL_PROP_TREATY_TYPE  WHERE  PTT_PT_SYS_ID  = ?  " +
    "AND PTT_SRNO  = 1 ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PERIOD_SELECT_X_FOR_PPTP_PT_TREATY_PERIOD=
	"SELECT 'X' FROM  PM_IL_PROP_TREATY_PERIOD  WHERE  " +
	"PPTP_PT_TREATY_CODE  = ? ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PERIOD_SELECT_PTT_ACCOUNTS_SUBMIT_PERIOD=
	"SELECT PTT_ACCOUNTS_SUBMIT_PERIOD FROM  PM_IL_PROP_TREATY_TYPE  WHERE  PTT_PT_SYS_ID  = " +
	"?  AND PTT_SRNO  = ? ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PERIOD_DELETE_FOR_PT_TREATY_CODE=
	"DELETE FROM   PM_IL_PROP_TREATY_PERIOD    WHERE  PPTP_PT_TREATY_CODE  " +
	"= ?";
	
	String  PILM015_APAC_PM_IL_PROP_TREATY_PART_CUST_SELECT_LEADER_YN=
	"SELECT PTPC_LEADER_YN FROM  PM_IL_PROP_TREATY_PART_CUST  WHERE  PTPC_LEADER_YN  = 'Y'" +
	"  AND PTPC_PTT_SYS_ID  = ? ";
	
	String  PILM015_APAC_PM_IL_PROP_TREATY_PART_CUST_SELECT_LEADER_YN_FOR_SYSID_AND_ROWID=
	"SELECT PTPC_LEADER_YN FROM  PM_IL_PROP_TREATY_PART_CUST  WHERE  PTPC_LEADER_YN  = 'Y'  AND PTPC_PTT_SYS_ID  = " +
	"?  AND ROWID  != ? ";
	
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PART_CUST_PIL_PTPC_SYS_ID=
	"SELECT PIL_PTPC_SYS_ID.NEXTVAL FROM  DUAL  ";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_PART_CUST_SELECT_1_FOR_CUST_CODE_SYS_ID=
	"SELECT ROWID FROM  PM_IL_PROP_TREATY_PART_CUST  WHERE  PTPC_CUST_CODE  = " +
	"? " +
	" AND PTPC_PTT_SYS_ID  = ?";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_CVR_PTTC_COVER_CODE_RIDER_BASIS_B_LOV=
	"SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE COVER_FRZ_FLAG = 'N'  AND"+
	" COVER_TYPE = NVL('A',COVER_TYPE)AND ROWNUM<?"
	+"ORDER BY 1ASC";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_CVR_PTTC_COVER_CODE_RIDER_BASIS_B_LOV_LIKE=
		"SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE COVER_FRZ_FLAG = 'N'  AND"+
		" COVER_TYPE = NVL('A',COVER_TYPE)AND COVER_CODE LIKE ? AND ROWNUM<?"
		+"ORDER BY 1ASC";
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_CVR_PTTC_COVER_CODE_LOV=
		"SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE COVER_FRZ_FLAG = 'N'  AND"+
		" COVER_TYPE = COVER_TYPE AND ROWNUM<?"
		+"ORDER BY 1ASC";
	
	String PILM015_APAC_PM_IL_PROP_TREATY_TYPE_CVR_PTTC_COVER_CODE_LOV_LIKE=
		"SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE COVER_FRZ_FLAG = 'N'  AND"+
		" COVER_TYPE = COVER_TYPE AND COVER_CODE LIKE ? AND ROWNUM<?"
		+"ORDER BY 1ASC";
	
	String PILM015_APAC_CTRL1_UI_M_CP_TREATY_CODE_SELECT_TREATY_DESC=
		"SELECT PT_TREATY_DESC FROM  PM_IL_PROP_TREATY  WHERE  PT_TREATY_CODE  = ?";
	
	String PILM015_APAC_CTRL1_UI_M_CP_TREATY_CODE_SELECT_UW_YEAR=
	"SELECT PT_UW_YEAR FROM  PM_IL_PROP_TREATY  WHERE  PT_TREATY_CODE  =?";
	
	String PILM015_APAC_CTRL1_M_CP_UW_YEAR_SELECT_FOR_TREATY_CODE_AND_YEAR=
	"SELECT 1 FROM  PM_IL_PROP_TREATY  WHERE  PT_TREATY_CODE  = ?  AND PT_UW_YEAR  = ?";
	
	String PILM015_APAC_CTRL1_M_CP_DEST_UW_YEAR_SELECT_1_FOR_TREATY_CODE_YEAR_CQSYN_CLASS_CODE=
	"SELECT 1 FROM  PM_IL_PROP_TREATY  WHERE  PT_TREATY_CODE = ?  AND PT_UW_YEAR  = ? " +
	" AND PT_CQS_YN  = ?  AND PT_CLASS_CODE  = ? ";
	
	String PILM015_APAC_CTRL1_OK_BUTTON_SELECT_SYSID_FOR_DETAILS=
	"SELECT PT_SYS_ID FROM  PM_IL_PROP_TREATY  WHERE  PT_TREATY_CODE  = ?  AND PT_UW_YEAR  " +
	"= ?  AND PT_CQS_YN  = ?  AND PT_CLASS_CODE  = ? ";
	
	String PILM015_APAC_CTRL1_OK_BUTTON_SELECT_DETAILS_FOR_SYSID=
	"SELECT    PTT_SYS_ID,PTT_PT_SYS_ID,PTT_SRNO,PTT_TREATY_TYPE,PTT_PROFIT_COMM," +
	" PTT_REINS_TAX_PERC,PTT_PREM_PF_ENT_PERC,PTT_PREM_PF_WD_PERC,PTT_LOSS_PF_ENT_PERC," +
	" PTT_LOSS_PF_WD_PERC,PTT_LOSS_CF_YEARS,PTT_DEPOSIT_PREM,PTT_PREM_RES_RATIO,PTT_INT_ON_RES_REL," +
	" PTT_OS_CLM_RES_RATIO PTT_DFLT_RETN_RATIO,PTT_EXCLUSION,PTT_NOTICE_CANCEL_DAYS,PTT_ACCOUNTS_SUBMIT_PERIOD," +
	" PTT_FRZ_FLAG,PTT_CR_DT,PTT_CR_UID,PTT_UPD_DT,PTT_UPD_UID FROM  PM_IL_PROP_TREATY_TYPE" +
	"  WHERE  PTT_PT_SYS_ID  = ? ";
	
	String PILM015_APAC_CTRL1_OK_BUTTON_SELECT_DETAILS_FOR_TREATY_COVER_FOR_SYSID=
	"SELECT    PTC_SYS_ID,PTC_COVER_CODE,PTC_STD_TREATY_LIMIT,PTC_SUB_STD_TREATY_LIMIT," +
	"    PTC_STD_MAX_RETN,PTC_SSTD_MAX_RETN,PTC_COMM_PERC_1ST_YR,PTC_COMM_PERC_SUB_YRS,PTC_SSTD_COMM_PERC_1ST_YR," +
	"    PTC_SSTD_COMM_PERC_SUB_YRS,PTC_SUB_STD_TARIFF,PTC_GROUP_COVER_YN,PTC_CVR_GRP_CODE FROM " +
	"	 PM_IL_PROP_TREATY_COVER  WHERE  PTC_PTT_SYS_ID  = ? ";
	
	String PILM015_APAC_CTRL1_OK_BUTTON_SELECT_DETAILS_FOR_TTY_COV_GRP_FOR_SYSID=
	"SELECT    PTG_PTC_CVR_GRP_CODE,PTG_COVER_CODE,PTG_SR_NO FROM" +
	"  PM_IL_PROP_TTYCOV_GRP  WHERE  " +
	"  PTG_PTC_SYS_ID  = ?  AND PTG_PTT_SYS_ID  = ? ";
	
	String  PILM015_APAC_CTRL1_OK_BUTTON_SELECT_DETAILS_FOR_TREAY_TYPE_COVER_FOR_SYSID=
	"SELECT    PTTC_COVER_CODE,PTTC_PERC FROM" +
	"  PM_IL_PROP_TREATY_TYPE_COVER  WHERE  PTTC_PTT_SYS_ID  = ? ";
	
	String PILM015_APAC_CTRL1_OK_BUTTON_SELECT_DETAILS_FOR_TREATY_PART_CUST_FOR_SYSID=
	"SELECT    PTPC_SYS_ID,PTPC_PTT_SYS_ID,PTPC_CUST_CODE,PTPC_SHARE_PERC,PTPC_LEADER_YN," +
	"    PTPC_CR_DT,PTPC_CR_UID,PTPC_UPD_DT,PTPC_UPD_UID FROM  " +
	" PM_IL_PROP_TREATY_PART_CUST  WHERE  PTPC_PTT_SYS_ID  = ? ";
	
	 String PILM015_APAC_CTRL1_OK_BUTTON_PIL_PT_SYS_ID="SELECT PIL_PT_SYS_ID.NEXTVAL FROM  DUAL  ";
     
     
     String PILM015_APAC_CTRL1_OK_BUTTON_PIL_PTT_SYS_ID=" SELECT PIL_PTT_SYS_ID.NEXTVAL FROM  DUAL  ";
    
     
     String PILM015_APAC_CTRL1_OK_BUTTON_PIL_PTTC_SYS_ID="SELECT PIL_PTTC_SYS_ID.NEXTVAL FROM  DUAL  ";
     
     
     String PILM015_APAC_CTRL1_OK_BUTTON_PIL_PTC_SYS_ID="SELECT PIL_PTC_SYS_ID.NEXTVAL FROM  DUAL  ";
     
     
     String PILM015_APAC_CTRL1_OK_BUTTON_P9IL_PTG_SYS_ID="SELECT P9IL_PTG_SYS_ID.NEXTVAL FROM  DUAL  ";
     
     
     String PILM015_APAC_CTRL1_OK_BUTTON_PIL_PTPC_SYS_ID="SELECT PIL_PTPC_SYS_ID.NEXTVAL FROM  DUAL  ";
     
     String  PILM015_APAC_CTRL1_OK_BUTTON_INSERT_INTO_PM_IL_PROP_TREATY=
     "INSERT INTO  PM_IL_PROP_TREATY      ( PT_SYS_ID ,PT_TREATY_CODE ,PT_TREATY_DESC ,PT_CLASS_CODE ,PT_UW_YEAR ,PT_UW_YEAR_DESC ," +
		"	PT_START_DT ,PT_END_DT ,PT_CURR_CODE ,PT_CURR_RATE ,PT_FRZ_FLAG ,PT_CR_DT ,PT_CR_UID ,PT_CQS_YN ,PT_CQS_PERC ," +
		"   PT_RIDER_RI_BASIS ,PT_UW_BASIS ,PT_CORIDOR_LC_LIMIT ,PT_SURR_CLAIM_YN ) " +
		"  	SELECT    ?,?,PT_TREATY_DESC,PT_CLASS_CODE," +
		"   ?,PT_UW_YEAR_DESC,PT_START_DT,PT_END_DT,PT_CURR_CODE,PT_CURR_RATE," +
		"   'N',SYSDATE,?,NVL(PT_CQS_YN, 'N'),PT_CQS_PERC, NVL(PT_RIDER_RI_BASIS, 'N')," +
		"   PT_UW_BASIS,PT_CORIDOR_LC_LIMIT,NVL(PT_SURR_CLAIM_YN, 'N') FROM  PM_IL_PROP_TREATY  WHERE " +
		" 	PT_SYS_ID  = ? ";
     
     String PILM015_APAC_CTRL1_OK_BUTTON_SELECT_DETAILS_FOR_TREATY_TYPE_SYSID=
    	 "SELECT ROWID,PM_IL_PROP_TREATY_TYPE.* FROM PM_IL_PROP_TREATY_TYPE WHERE PTT_PT_SYS_ID  = ?  ";
     
     /*String PILM015_APAC_CTRL1_OK_BUTTON_SELECT_DETAILS_FOR_TREATY_TYPE_SYSID=
     "SELECT    PTT_SYS_ID,PTT_PT_SYS_ID,PTT_SRNO,PTT_TREATY_TYPE,PTT_PROFIT_COMM,PTT_REINS_TAX_PERC," +
		" 	 PTT_PREM_PF_ENT_PERC,PTT_PREM_PF_WD_PERC,PTT_LOSS_PF_ENT_PERC,PTT_LOSS_PF_WD_PERC,PTT_LOSS_CF_YEARS," +
		"    PTT_DEPOSIT_PREM,PTT_PREM_RES_RATIO,PTT_INT_ON_RES_REL,PTT_OS_CLM_RES_RATIO PTT_DFLT_RETN_RATIO," +
		"    PTT_EXCLUSION,PTT_NOTICE_CANCEL_DAYS,PTT_ACCOUNTS_SUBMIT_PERIOD,PTT_FRZ_FLAG,PTT_CR_DT,PTT_CR_UID," +
		"    PTT_UPD_DT, PTT_UPD_UID FROM  PM_IL_PROP_TREATY_TYPE  WHERE  PTT_PT_SYS_ID  = ? ";*/
	 
     String PILM015_APAC_CTRL1_OK_BUTTON_INSERT_INTO_TREATY_TYPE=
     "INSERT INTO  PM_IL_PROP_TREATY_TYPE( PTT_SYS_ID ,PTT_PT_SYS_ID ," +
		" PTT_SRNO ,PTT_TREATY_TYPE ,PTT_LINK_TREATY_CODE ,PTT_MGT_EXP_RATIO ,PTT_PROFIT_COMM ," +
		" PTT_REINS_TAX_PERC ,PTT_PREM_PF_ENT_PERC ,PTT_PREM_PF_WD_PERC ,PTT_LOSS_PF_ENT_PERC ,PTT_LOSS_PF_WD_PERC ," +
		" PTT_LOSS_CF_YEARS ,PTT_DEPOSIT_PREM ,PTT_PREM_RES_RATIO ,PTT_INT_ON_RES_REL ,PTT_OS_CLM_RES_RATIO ,PTT_EXCLUSION ," +
		" PTT_NOTICE_CANCEL_DAYS ,PTT_ACCOUNTS_SUBMIT_PERIOD ,PTT_FRZ_FLAG ,PTT_CR_DT ,PTT_CR_UID ) " +
		"   VALUES   ( ? ,? ,? , ? ,? ," +
		"    ? ,? ,? ,? ,? ," +
		"    ? ,? , ? , ? ,? ," +
		"    ? , ? , ? , ? ,? ," +
		"    'N' ,    SYSDATE ,    ? )   ";
     
     String PILM015_APAC_CTRL1_OK_BUTTON_INSERT_INTO_TREATY_TYPE_COVER=
     "INSERT INTO  PM_IL_PROP_TREATY_TYPE_COVER( PTTC_SYS_ID ,PTTC_PTT_SYS_ID ," +
		"    PTTC_COVER_CODE ,PTTC_PERC ,PTTC_CR_DT ,PTTC_CR_UID ) VALUES  " +
		"( ? ,? ,? ,? , SYSDATE ," +
		"  ? )   ";
    String PILM015_APAC_CTRL1_OK_BUTTON_SELECT_DETAILS_FROM_TREATY_COVER=
     "SELECT    PTC_SYS_ID,PTC_COVER_CODE,PTC_STD_TREATY_LIMIT,PTC_SUB_STD_TREATY_LIMIT,PTC_STD_MAX_RETN,PTC_SSTD_MAX_RETN," +
		"    PTC_COMM_PERC_1ST_YR,PTC_COMM_PERC_SUB_YRS,PTC_SSTD_COMM_PERC_1ST_YR,PTC_SSTD_COMM_PERC_SUB_YRS,PTC_SUB_STD_TARIFF,PTC_GROUP_COVER_YN," +
		"    PTC_CVR_GRP_CODE FROM  PM_IL_PROP_TREATY_COVER  WHERE  PTC_PTT_SYS_ID  = ? ";
    
    String PILM015_APAC_CTRL1_OK_BUTTON_INSERT_INTO_TREATY_COVER=
    "INSERT INTO  PM_IL_PROP_TREATY_COVER( PTC_SYS_ID ,PTC_PTT_SYS_ID ,PTC_COVER_CODE ," +
	"    PTC_STD_TREATY_LIMIT ,PTC_SUB_STD_TREATY_LIMIT ,PTC_STD_MAX_RETN ,PTC_SSTD_MAX_RETN ,PTC_COMM_PERC_1ST_YR ," +
	"    PTC_COMM_PERC_SUB_YRS ,PTC_SSTD_COMM_PERC_1ST_YR ,PTC_SSTD_COMM_PERC_SUB_YRS ,PTC_SUB_STD_TARIFF ," +
	"    PTC_GROUP_COVER_YN ,PTC_CVR_GRP_CODE ) VALUES ( ? ,? ," +
	"    ? ,?,?,? ," +
	"    ? ,? ,? ,? ," +
	"    ? ,? ,? ,? )   ";
    
    String PILM015_APAC_CTRL1_OK_BUTTON_SELECT_FROM_TTYCOV_GRP=
    "SELECT    PTG_PTC_CVR_GRP_CODE,PTG_COVER_CODE,PTG_SR_NO " +
	" FROM  PM_IL_PROP_TTYCOV_GRP  WHERE  PTG_PTC_SYS_ID  = ? " +
	" AND PTG_PTT_SYS_ID  = ? ";
    
    String PILM015_APAC_CTRL1_OK_BUTTON_INSERT_INTO_TTYCOV_GRP=
    "INSERT INTO  PM_IL_PROP_TTYCOV_GRP( PTG_SYS_ID ,PTG_PTC_SYS_ID ," +
    "    PTG_PTT_SYS_ID ,PTG_PTC_CVR_GRP_CODE ,PTG_COVER_CODE ,PTG_SR_NO ,PTG_CR_UID ,PTG_CR_DT )" +
	"    VALUES   ( ?, ? , ? , ?," +
	"    ? , ? ,? , SYSDATE )";
    
    String PILM015_APAC_CTRL1_OK_BUTTON_SELECT_TREATY_PART_CUST_DETAILS=
    "SELECT    PTPC_SYS_ID,PTPC_PTT_SYS_ID, PTPC_CUST_CODE,PTPC_SHARE_PERC,PTPC_LEADER_YN,PTPC_CR_DT,PTPC_CR_UID,PTPC_UPD_DT," +
	" PTPC_UPD_UID FROM  PM_IL_PROP_TREATY_PART_CUST  WHERE  PTPC_PTT_SYS_ID  = ? ";
    
    String PILM015_APAC_CTRL1_OK_BUTTON_INSERT_INTO_TREATY_PART_CUST=
    "INSERT INTO  PM_IL_PROP_TREATY_PART_CUST  ( PTPC_SYS_ID ,PTPC_PTT_SYS_ID ,PTPC_CUST_CODE ,PTPC_SHARE_PERC ," +
	"    PTPC_LEADER_YN ,PTPC_CR_DT ,PTPC_CR_UID ) VALUES ( ? , ? ," +
	"    ? ,? ,? , ? ,?)";
    
    String PILM015_APAC_TREATY_MASTER_TREATY_CODE_WHEN_VALIDATE_ITEM =
		"SELECT PT_TREATY_DESC FROM PM_IL_PROP_TREATY WHERE " +
						" PM_IL_PROP_TREATY.PT_FRZ_FLAG = 'N' AND PT_TREATY_CODE=?";
    /*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_CURRENCY to FM_CURRENCY. Added by : Mallika.S, 01-Apr-2009 */
    String PIL015_APAC_PM_IL_PROP_TREATY_CURR_CODE_WHEN_VALIDATE_ITEM=
		"SELECT CURR_NAME FROM FM_CURRENCY WHERE CURR_CODE = ? ";
 // [BugId:PREMIAGDC-266172 MMuthu 09-Jan-09 When treaty is copied, treaty account period submission also copied		  
    String PIL015_APAC_PM_IL_PROP_TREATY_PERIOD ="INSERT INTO PM_IL_PROP_TREATY_PERIOD" +
    		"   (PPTP_PT_TREATY_CODE, PPTP_MON_FM, PPTP_MON_TO, PPTP_SUB_NO)" +
    		" VALUES   (?,?,?, ?)";
    
    String PIL015_APAC_PM_IL_PROP_TREATY_PERIOD_SELECT = "SELECT * FROM  PM_IL_PROP_TREATY_PERIOD WHERE PPTP_PT_TREATY_CODE=?";
 // BugId:PREMIAGDC-266172 MMuthu 09-Jan-09 When treaty is copied, treaty account period submission also copied	]
   
}

