package com.iii.pel.forms.PILT002_APAC;

import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;

import com.iii.apps.persistence.CRUDHandler;
import com.iii.premia.common.utils.CommonUtils;

public class PT_IL_POL_ASSURED_POLICY_DTLS_DELEGATE {
	
	
	 public void executeSelectStatement(
			 PILT002_APAC_COMPOSITE_ACTION compositeAction)
			    throws Exception {
		 	/*commented by gopi for for ZBILQC_12-JAN-2017_Issue_Flow on 17/01/17*/
		 
			/*String selectStatement = "SELECT POL_NO,POL_PERIOD, POL_FC_SUM_ASSURED,POL_LC_SUM_ASSURED,POL_FC_BASIC_PREM,POL_LC_BASIC_PREM,"+
			" POL_STATUS,POL_MODE_OF_PYMT,POL_START_DT,POL_EXPIRY_DT "+
			" FROM PT_IL_POLICY WHERE POL_CONT_CODE LIKE  ? ";*/
		
		/*
		 * modified by Ameen on 31-07-2017 for ZBILQC-1718998 as per siva sugg.
		 *  String selectStatement = "SELECT POL_NO,POL_PERIOD, POL_FC_SUM_ASSURED,POL_LC_SUM_ASSURED,POL_FC_BASIC_PREM,POL_LC_BASIC_PREM,"+
					" POL_STATUS,POL_MODE_OF_PYMT,POL_START_DT,POL_EXPIRY_DT,POL_EXPIRY_DT,"
					+ "DECODE(POL_MODE_OF_PYMT,'Y','YEARLY','H','HALF-YEARLY','Q','QUARTERLY','M','MONTHLY','SINGLE') MOP_DESC,"
					+ "(SELECT PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_REC_STA' AND   PS_CODE = POL_STATUS) STATUS FROM PT_IL_POLICY "
					+ "WHERE POL_CONT_CODE LIKE ? ";*/
		 
		 /*
		  * modified by Ameen on 12-04-2018 for KIC
		  * String selectStatement = "SELECT POL_NO, POL_PERIOD, POL_FC_SUM_ASSURED, POL_LC_SUM_ASSURED, POL_FC_BASIC_PREM, POL_LC_BASIC_PREM, "
		 		+ "POL_STATUS, POL_MODE_OF_PYMT, POL_START_DT, POL_EXPIRY_DT, POL_EXPIRY_DT, DECODE(POL_MODE_OF_PYMT, 'Y', 'YEARLY', 'H', 'HALF-YEARLY', "
		 		+ "'Q', 'QUARTERLY', 'M', 'MONTHLY', 'SINGLE') MOP_DESC, (SELECT PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_REC_STA' AND PS_CODE = "
		 		+ "POL_STATUS) STATUS FROM PT_IL_POLICY A WHERE POL_SYS_ID IN (SELECT POAD_POL_SYS_ID FROM PT_IL_POL_ASSURED_DTLS WHERE POAD_REF_ID1 = "
		 		+ "? OR POAD_REF_ID2 = ?) AND POL_DS_TYPE = '1' AND POL_NO NOT IN (SELECT POL_PROP_NO FROM PT_IL_POLICY B WHERE "
		 		+ "POL_DS_TYPE = '2' AND B.POL_PROP_SYS_ID = A.POL_SYS_ID) AND NVL(A.POL_ADDL_STATUS, '001') NOT IN ('N01', 'W02') UNION SELECT POL_NO, "
		 		+ "POL_PERIOD, POL_FC_SUM_ASSURED, POL_LC_SUM_ASSURED, POL_FC_BASIC_PREM, POL_LC_BASIC_PREM, POL_STATUS, POL_MODE_OF_PYMT, POL_START_DT, "
		 		+ "POL_EXPIRY_DT, POL_EXPIRY_DT, DECODE(POL_MODE_OF_PYMT, 'Y', 'YEARLY', 'H', 'HALF-YEARLY', 'Q', 'QUARTERLY', 'M', 'MONTHLY', 'SINGLE') "
		 		+ "MOP_DESC, (SELECT PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_REC_STA' AND PS_CODE = POL_STATUS) STATUS FROM PT_IL_POLICY WHERE "
		 		+ "POL_SYS_ID IN (SELECT POAD_POL_SYS_ID FROM PT_IL_POL_ASSURED_DTLS WHERE POAD_REF_ID1 = ? OR POAD_REF_ID2 = ?) "
		 		+ "AND POL_DS_TYPE = '2' AND POL_STATUS NOT IN ('C','M','S')";*/
		 
		 String selectStatement = "SELECT POL_NO, POL_PERIOD, POL_FC_SUM_ASSURED, POL_LC_SUM_ASSURED, POL_FC_BASIC_PREM, POL_LC_BASIC_PREM, "
			 		+ "POL_STATUS, POL_MODE_OF_PYMT, POL_START_DT, POL_EXPIRY_DT, POL_EXPIRY_DT, F_STATUS_DESC('IL_ADDL_STAT', POL_ADDL_STATUS) POL_ADDL_STATUS,DECODE(POL_MODE_OF_PYMT, 'Y', 'YEARLY', 'H', 'HALF-YEARLY', "
			 		+ "'Q', 'QUARTERLY', 'M', 'MONTHLY', 'SINGLE') MOP_DESC, (SELECT PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_REC_STA' AND PS_CODE = "
			 		+ "POL_STATUS) STATUS FROM PT_IL_POLICY A WHERE POL_SYS_ID IN (SELECT POAD_POL_SYS_ID FROM PT_IL_POL_ASSURED_DTLS WHERE POAD_REF_ID1 = "
			 		+ "? OR POAD_REF_ID2 = ?) AND POL_DS_TYPE = '1' AND POL_NO NOT IN (SELECT POL_PROP_NO FROM PT_IL_POLICY B WHERE "
			 		+ "POL_DS_TYPE = '2' AND B.POL_PROP_SYS_ID = A.POL_SYS_ID) AND NVL(A.POL_ADDL_STATUS, '001') NOT IN ('N01', 'W02') UNION SELECT POL_NO, "
			 		+ "POL_PERIOD, POL_FC_SUM_ASSURED, POL_LC_SUM_ASSURED, POL_FC_BASIC_PREM, POL_LC_BASIC_PREM, POL_STATUS, POL_MODE_OF_PYMT, POL_START_DT, "
			 		+ "POL_EXPIRY_DT, POL_EXPIRY_DT, F_STATUS_DESC('IL_ADDL_STAT', POL_ADDL_STATUS) POL_ADDL_STATUS,DECODE(POL_MODE_OF_PYMT, 'Y', 'YEARLY', 'H', 'HALF-YEARLY', 'Q', 'QUARTERLY', 'M', 'MONTHLY', 'SINGLE') "
			 		+ "MOP_DESC, (SELECT PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_REC_STA' AND PS_CODE = POL_STATUS) STATUS FROM PT_IL_POLICY WHERE "
			 		+ "POL_SYS_ID IN (SELECT POAD_POL_SYS_ID FROM PT_IL_POL_ASSURED_DTLS WHERE POAD_REF_ID1 = ? OR POAD_REF_ID2 = ?) "
			 		+ "AND POL_DS_TYPE = '2' AND POL_STATUS NOT IN ('C','M','S')";
		 
					/* end*/
		 
			Connection connection = null;
			ResultSet resultSet = null;
			compositeAction.getPT_IL_POL_ASSURED_POLICY_DTLS_ACTION_BEAN().getDataList_PT_IL_POL_ASSURED_POLICY_DTLS().clear();
			try {
			    connection = CommonUtils.getConnection();
			    resultSet = new CRUDHandler().executeSelectStatement(selectStatement, connection,
			    		/*
			    		 * modified by Ameen on 31-07-2017 for ZBILQC-1718998 as per siva sugg.
			    		 * new Object[] {compositeAction.getPT_IL_POLICY_ACTION_BEAN().getPT_IL_POLICY_BEAN().getPOL_CONT_CODE() });*/
			    		new Object[] {compositeAction.getPT_IL_POL_ASSURED_DTLS_ACTION_BEAN().getPT_IL_POL_ASSURED_DTLS_BEAN().getPOAD_REF_ID1(),
			    		compositeAction.getPT_IL_POL_ASSURED_DTLS_ACTION_BEAN().getPT_IL_POL_ASSURED_DTLS_BEAN().getPOAD_REF_ID2(),
			    		compositeAction.getPT_IL_POL_ASSURED_DTLS_ACTION_BEAN().getPT_IL_POL_ASSURED_DTLS_BEAN().getPOAD_REF_ID1(),
			    		compositeAction.getPT_IL_POL_ASSURED_DTLS_ACTION_BEAN().getPT_IL_POL_ASSURED_DTLS_BEAN().getPOAD_REF_ID2()});
			    while (resultSet.next()) {
			    	PT_IL_POL_ASSURED_POLICY_DTLS PT_IL_POL_ASSURED_POLICY_DTLS_BEAN = new PT_IL_POL_ASSURED_POLICY_DTLS();
			    	//PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setROWID(resultSet.getString("ROWID"));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_NO(resultSet.getString(1));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_PEROID(resultSet.getDouble(2));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_FC_SA(resultSet.getDouble(3));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_LC_SA(resultSet.getDouble(4));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_FC_PREM(resultSet.getDouble(5));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_LC_PREM(resultSet.getDouble(6));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_STATUS(resultSet.getString(7));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_MOP(resultSet.getString(8));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_ST_DATE(resultSet.getDate(9));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_EX_DATE(resultSet.getDate(10));
			    	/*added by gopi for for ZBILQC_12-JAN-2017_Issue_Flow on 17/01/17*/
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setUI_M_ASSR_DTLS_POL_MOP_DESC(resultSet.getString("MOP_DESC"));
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setUI_M_ASSR_DTLS_POL_STATUS_DESC(resultSet.getString("STATUS"));
			    	/*end*/
			    	
			    	/*added by raja on 22-06-2017 for ZBILQC-1718998*/
			    	
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setASSR_DTLS_POL_ST_DATE_DATATABLE(
			    			new SimpleDateFormat("dd/MM/yyyy").format(resultSet.getDate(9)));
			    	
			    	/*end*/
			    	
			    	/*Added by Ameen on 12-04-2018 for KIC*/
			    	PT_IL_POL_ASSURED_POLICY_DTLS_BEAN.setUI_M_ASSR_DTLS_POL_ADDL_STATUS(resultSet.getString("POL_ADDL_STATUS"));
			    	/*end*/
				compositeAction.getPT_IL_POL_ASSURED_POLICY_DTLS_ACTION_BEAN().getDataList_PT_IL_POL_ASSURED_POLICY_DTLS()
				.add(PT_IL_POL_ASSURED_POLICY_DTLS_BEAN);
			    }
			} finally {
			    CommonUtils.closeCursor(resultSet);
			}
		    }


}
