package com.iii.pel.forms.PM094_A;

public interface PM094_A_PM_AGENT_BONUS_QUERY_CONSTANTS {
	
	
	public String PM094_A$PM_AGENT_BONUS$VALIDATE$ABS_CODE=" SELECT 1 FROM  PM_AGENT_BONUS_SETUP"
															+" WHERE LTRIM(RTRIM(UPPER(ABS_CODE)))=LTRIM(RTRIM(UPPER(?)))";
	
	public String PM094_A$PM_AGENT_BONUS_SETUP$PRE_DELETE$BONUS_APPL_RANKS_DELETE_BEAN=
								"DELETE FROM PM_AGENT_BONUS_APPL_RANKS P  WHERE P.ABAR_ABS_CODE = ?";

	public String PM094_A$PM_AGENT_BONUS_SETUP$PRE_DELETE$BONUS_APPL_PROD_DELETE_BEAN=
								"DELETE FROM PM_AGENT_BONUS_APPL_PROD P WHERE P.ABAP_ABS_CODE = ?";
	
	public String LOV$PM094_A$PM_AGENT_BONUS_SETUP$ABS_BONUS_TYPE=
		"SELECT PS_CODE,PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE='AGT_BONUS' AND ROWNUM<=? ORDER BY PS_CODE";
	
	public String LOV$PM094_A$PM_AGENT_BONUS_SETUP$ABS_BONUS_TYPE$LIKE=
		"SELECT PS_CODE,PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE='AGT_BONUS' AND PS_CODE LIKE ? AND ROWNUM<=? ORDER BY PS_CODE";

	public String PM_AGENT_BONUS_SETUP_DUPLICATE_RECORD_CHECK="SELECT ROWID FROM PM_AGENT_BONUS_SETUP WHERE ABS_CODE=? ";

	public String PM_AGENT_BONUS_SETUP_SEARCH_QUERY="SELECT ROWID,PM_AGENT_BONUS_SETUP.* FROM PM_AGENT_BONUS_SETUP";
	
	public String PM_AGENT_BONUS_SETUP_SEARCH_FETCH_QUERY="SELECT ROWID,PM_AGENT_BONUS_SETUP.* FROM PM_AGENT_BONUS_SETUP WHERE ROWID=?";
	
	public String PM_AGENT_BONUS_APPL_PROD_FETCH_RECORDS_FOR_ABS_CODE="SELECT ROWID,PM_AGENT_BONUS_APPL_PROD.* FROM PM_AGENT_BONUS_APPL_PROD WHERE ABAP_ABS_CODE=?";

	public String PM_AGENT_BONUS_APPL_RANKS_FETCH_RECORDS_FOR_ABS_CODE = "SELECT ROWID,PM_AGENT_BONUS_APPL_RANKS.* FROM PM_AGENT_BONUS_APPL_RANKS WHERE ABAR_ABS_CODE=?";
	
	/*
	 * modified by Ameen on 10-08-2018 for KICLIFEQC-1760174 as per Ajay
	 * public String PM_AGENT_BONUS_RATES_FETCH_RECORDS_FOR_ABR_CODE_AND_ABR_RANK_CODE=
		"SELECT ROWID,PM_AGENT_BONUS_RATES.* FROM PM_AGENT_BONUS_RATES WHERE ABR_ABS_CODE=? AND ABR_RANK_CODE=?";*/
	
	
	public String PM_AGENT_BONUS_RATES_FETCH_RECORDS_FOR_ABR_CODE_AND_ABR_RANK_CODE=
			"SELECT ROWID,PM_AGENT_BONUS_RATES.* FROM PM_AGENT_BONUS_RATES WHERE ABR_ABS_CODE=? AND ABR_RANK_CODE=? AND ABR_AGENT_NEW=?";
	
	public String PM_AGENT_BONUS_APPL_PROD_MODULE_ID_QUERY=
		" SELECT  PROD_CODE,PROD_DESC FROM 	PV_LIFE_PRODUCTS WHERE 	MODULE_ID = LTRIM(RTRIM(?))"
		+"	AND PROD_CODE = LTRIM(RTRIM(?))";

	public String LOV$PM094_A$PM_AGNET_BONUS_APPL_PROD$ABAP_PROD_CODE=
		"SELECT PROD_CODE,PROD_DESC FROM PV_LIFE_PRODUCTS WHERE MODULE_ID=? AND ROWNUM<=? ORDER BY PROD_CODE";
	
	public String LOV$PM094_A$PM_AGNET_BONUS_APPL_PROD$ABAP_PROD_CODE$LIKE=
		"SELECT PROD_CODE,PROD_DESC FROM PV_LIFE_PRODUCTS WHERE PROD_CODE LIKE ? AND MODULE_ID=? AND ROWNUM<=? ORDER BY PROD_CODE";

	public String PM_AGENT_BONUS_APPL_PROD_PRE_INSERT_QUERY1="SELECT 1 FROM  PM_AGENT_BONUS_APPL_PROD	WHERE ABAP_ABS_CODE = ?"
																	+" AND   ABAP_MODULE_ID = ?	AND   ABAP_PROD_CODE = ?";
	
	public String PM_AGENT_BONUS_APPL_PROD_PRE_INSERT_QUERY2="SELECT 1 FROM  PM_AGENT_BONUS_APPL_PROD	WHERE ABAP_ABS_CODE = ?"
																+" AND   ABAP_MODULE_ID = ?	AND   ABAP_PROD_CODE = ? AND ROWID!=?";

	public String PM_AGENT_BONUS_APPL_RANKS_PRE_INSERT_QUERY1=" SELECT 1 FROM  PM_AGENT_BONUS_APPL_RANKS WHERE ABAR_ABS_CODE = ?"
																+"	AND   ABAR_RANK_CODE = ?";
	
	public String PM_AGENT_BONUS_APPL_RANKS_PRE_INSERT_QUERY2=" SELECT 1 FROM  PM_AGENT_BONUS_APPL_RANKS WHERE ABAR_ABS_CODE = ?"
																	+"	AND   ABAR_RANK_CODE = ? AND ROWID!=?";
	public String PM_AGENT_BONUS_APPL_RANKS_PRE_DELETE_QUERY=" DELETE FROM PM_AGENT_BONUS_RATES P  WHERE P.ABR_RANK_CODE = ? and P.ABR_ABS_CODE = ?";

	public String PM_AGENT_BONUS_RATES_PRE_INSERT_QUERY=
		"SELECT 1 FROM  PM_AGENT_BONUS_RATES WHERE ABR_ABS_CODE = ?"
		+"  AND   ABR_RANK_CODE = ?	AND   ABR_PERIOD  =   ?"
		+" AND   ( (NVL(?,0) BETWEEN NVL(ABR_YTD_FYC_FM,0) AND NVL(ABR_YTD_FYC_TO,0))"
		+" OR (NVL(?,0) BETWEEN NVL(ABR_YTD_FYC_FM,0) AND NVL(ABR_YTD_FYC_TO,0))"
		+" OR (NVL(ABR_YTD_FYC_FM,0) BETWEEN NVL(?,0) AND NVL(?,0)) "
		+" OR (NVL(ABR_YTD_FYC_TO,0) BETWEEN NVL(?,0) AND NVL(?,0)) "
		+"	) AND ((NVL(?,0) BETWEEN NVL(ABR_NO_OF_POL_FM,0) AND NVL(ABR_NO_OF_POL_TO,0))"
		+" OR (NVL(?,0) BETWEEN NVL(ABR_NO_OF_POL_FM,0) AND NVL(ABR_NO_OF_POL_TO,0))"
		+" OR (NVL(ABR_NO_OF_POL_FM,0) BETWEEN NVL(?,0) AND NVL(?,0))"
		+" OR (NVL(ABR_NO_OF_POL_TO,0) BETWEEN NVL(?,0) AND NVL(?,0))"
		+"	) AND ((NVL(?,TO_DATE('01/01/1900','DD/MM/RRRR')) BETWEEN NVL(ABR_EFF_FM_DT,TO_DATE('01/01/1900','DD/MM/RRRR')) AND NVL(ABR_EFF_TO_DT,TO_DATE('31/12/2999','DD/MM/RRRR')))"
		+" OR (NVL(?,TO_DATE('31/12/2999','DD/MM/RRRR')) BETWEEN NVL(ABR_EFF_FM_DT,TO_DATE('01/01/1900','DD/MM/RRRR')) AND NVL(ABR_EFF_TO_DT,TO_DATE('31/12/2999','DD/MM/RRRR')))"
		+" OR (NVL(ABR_EFF_FM_DT,TO_DATE('01/01/1900','DD/MM/RRRR')) BETWEEN NVL(?,TO_DATE('01/01/1900','DD/MM/RRRR')) AND NVL(?,TO_DATE('31/12/2999','DD/MM/RRRR')))"
		+" OR (NVL(ABR_EFF_TO_DT,TO_DATE('31/12/2999','DD/MM/RRRR')) BETWEEN NVL(?,TO_DATE('01/01/1900','DD/MM/RRRR')) AND NVL(?,TO_DATE('31/12/2999','DD/MM/RRRR')))"
		+" ) ";
	
	/* [ BugId:PREMIAGDC-AGENCY-0040 Deepika 05-Feb-09 Same combination of records should not be allowed */
	public String PM_AGENT_BONUS_RATES_PRE_UPDTAE_QUERY=
		"SELECT 1 FROM  PM_AGENT_BONUS_RATES WHERE ABR_ABS_CODE = ?"
		+"  AND   ABR_RANK_CODE = ?	AND   ABR_PERIOD  =   ?"
		+" AND   ( (NVL(?,0) BETWEEN NVL(ABR_YTD_FYC_FM,0) AND NVL(ABR_YTD_FYC_TO,0))"
		+" OR (NVL(?,0) BETWEEN NVL(ABR_YTD_FYC_FM,0) AND NVL(ABR_YTD_FYC_TO,0))"
		+" OR (NVL(ABR_YTD_FYC_FM,0) BETWEEN NVL(?,0) AND NVL(?,0)) "
		+" OR (NVL(ABR_YTD_FYC_TO,0) BETWEEN NVL(?,0) AND NVL(?,0)) "
		+"	) AND ((NVL(?,0) BETWEEN NVL(ABR_NO_OF_POL_FM,0) AND NVL(ABR_NO_OF_POL_TO,0))"
		+" OR (NVL(?,0) BETWEEN NVL(ABR_NO_OF_POL_FM,0) AND NVL(ABR_NO_OF_POL_TO,0))"
		+" OR (NVL(ABR_NO_OF_POL_FM,0) BETWEEN NVL(?,0) AND NVL(?,0))"
		+" OR (NVL(ABR_NO_OF_POL_TO,0) BETWEEN NVL(?,0) AND NVL(?,0))"
		+"	) AND ((NVL(?,TO_DATE('01/01/1900','DD/MM/RRRR')) BETWEEN NVL(ABR_EFF_FM_DT,TO_DATE('01/01/1900','DD/MM/RRRR')) AND NVL(ABR_EFF_TO_DT,TO_DATE('31/12/2999','DD/MM/RRRR')))"
		+" OR (NVL(?,TO_DATE('31/12/2999','DD/MM/RRRR')) BETWEEN NVL(ABR_EFF_FM_DT,TO_DATE('01/01/1900','DD/MM/RRRR')) AND NVL(ABR_EFF_TO_DT,TO_DATE('31/12/2999','DD/MM/RRRR')))"
		+" OR (NVL(ABR_EFF_FM_DT,TO_DATE('01/01/1900','DD/MM/RRRR')) BETWEEN NVL(?,TO_DATE('01/01/1900','DD/MM/RRRR')) AND NVL(?,TO_DATE('31/12/2999','DD/MM/RRRR')))"
		+" OR (NVL(ABR_EFF_TO_DT,TO_DATE('31/12/2999','DD/MM/RRRR')) BETWEEN NVL(?,TO_DATE('01/01/1900','DD/MM/RRRR')) AND NVL(?,TO_DATE('31/12/2999','DD/MM/RRRR')))"
		+" ) AND ROWID != ?";
	/* BugId:PREMIAGDC-AGENCY-0040 Deepika 05-Feb-09 Same combination of records should not be allowed ]*/
}
