package com.iii.pel.forms.PM094_A;

public interface PM094_A_PM_AGENT_BONUS_CONSTANTS {

	String PERCENTILE_FOR_SELECT_LIKE="%";

	String FORM_NAME="PM094_A";
	
	String BLOCK_NAME="PM_AGENT_BONUS_SETUP";
	
	String ITEM_NAME_BONUS_FREQ="PM_AGENT_BONUS_SETUP.ABS_BONUS_FREQ";
	
	String ITEM_NAME_PRORATA_YN="PM_AGENT_BONUS_SETUP.ABS_PRORATA_YN";
	
	String ITEM_NAME_TAXABLE_YN="PM_AGENT_BONUS_SETUP.ABS_TAXABLE_YN";
	
	String SYS_PARAM_BONUS_FREQ="PYMT_MODE";
	
	String SYS_PARAM_PRORATA_YN="YESNO";
	
	String SYS_PARAM_TAXABLE_YN="YESNO";  
	
	String BLOCK_NAME_APPL_PROD="PM_AGENT_BONUS_APPL_PROD";
	
	String ITEM_NAME_MODULE_ID="PM_AGENT_BONUS_APPL_PROD.ABAP_MODULE_ID";


}
