package com.iii.pel.forms.PILM044;

public class PILM044_COMPOSITE_ACTION {

	public PILM044_PM_IL_INTEREST_RATES_ACTION PILM044_PM_IL_INTEREST_RATES_ACTION_BEAN;
	
	public PM_IL_INTEREST_RATES PM_IL_INTEREST_RATES_BEAN;
	
	public PILM044_PM_IL_INTEREST_RATES_ACTION getPILM044_PM_IL_INTEREST_RATES_ACTION_BEAN() {
		return PILM044_PM_IL_INTEREST_RATES_ACTION_BEAN;
	}

	public void setPILM044_PM_IL_INTEREST_RATES_ACTION_BEAN(
			PILM044_PM_IL_INTEREST_RATES_ACTION pILM044_PM_IL_INTEREST_RATES_ACTION_BEAN) {
		PILM044_PM_IL_INTEREST_RATES_ACTION_BEAN = pILM044_PM_IL_INTEREST_RATES_ACTION_BEAN;
	}

	public PM_IL_INTEREST_RATES getPM_IL_INTEREST_RATES_BEAN() {
		return PM_IL_INTEREST_RATES_BEAN;
	}

	public void setPM_IL_INTEREST_RATES_BEAN(
			PM_IL_INTEREST_RATES pM_IL_INTEREST_RATES_BEAN) {
		PM_IL_INTEREST_RATES_BEAN = pM_IL_INTEREST_RATES_BEAN;
	}

	public PILM044_COMPOSITE_ACTION() {
		// TODO Auto-generated constructor stub
		PILM044_PM_IL_INTEREST_RATES_ACTION_BEAN = new PILM044_PM_IL_INTEREST_RATES_ACTION();
		PM_IL_INTEREST_RATES_BEAN = new PM_IL_INTEREST_RATES();
		PILM044_PM_IL_INTEREST_RATES_ACTION_BEAN.compositeAction = this;
	}
	
}
