package com.iii.pel.forms.PILT039_APAC;



public class PILT039_APAC_COMPOSITE_ACTION {

	
	PILT039_APAC_ACTION PILT039_APAC_ACTION_BEAN;
	public PILT039_APAC_COMPOSITE_ACTION()
	{
	
		PILT039_APAC_ACTION_BEAN = new PILT039_APAC_ACTION();
		PILT039_APAC_ACTION_BEAN.compositeAction=this;
	}
	public PILT039_APAC_ACTION getPILT039_APAC_ACTION_BEAN() {
		return PILT039_APAC_ACTION_BEAN;
	}
	public void setPILT039_APAC_ACTION_BEAN(
			PILT039_APAC_ACTION pILT039_APAC_ACTION_BEAN) {
		PILT039_APAC_ACTION_BEAN = pILT039_APAC_ACTION_BEAN;
	}
	
	
}
