package com.iii.pel.forms.PILP206;

public class PILP206_COMPOSITE_ACTION {
	
	private PW_IL_BALANCE_SUM_ACTION PW_IL_BALANCE_SUM_ACTION_BEAN;
	
	public PW_IL_BALANCE_SUM_ACTION getPW_IL_BALANCE_SUM_ACTION_BEAN() {
		return PW_IL_BALANCE_SUM_ACTION_BEAN;
	}

	public void setPW_IL_BALANCE_SUM_ACTION_BEAN(
			PW_IL_BALANCE_SUM_ACTION pW_IL_BALANCE_SUM_ACTION_BEAN) {
		PW_IL_BALANCE_SUM_ACTION_BEAN = pW_IL_BALANCE_SUM_ACTION_BEAN;
	}

	public PILP206_COMPOSITE_ACTION(){
			PW_IL_BALANCE_SUM_ACTION_BEAN=new PW_IL_BALANCE_SUM_ACTION();
			PW_IL_BALANCE_SUM_ACTION_BEAN.compositeAction = this;
	}


	
}
