package com.iii.pel.forms.PILP207;

public class PILP207_COMPOSITE_ACTION {
	
	private PW_IL_BENIFIT_PAYMT_ACTION PW_IL_BENIFIT_PAYMT_ACTION_BEAN;

	public PW_IL_BENIFIT_PAYMT_ACTION getPW_IL_BENIFIT_PAYMT_ACTION_BEAN() {
		return PW_IL_BENIFIT_PAYMT_ACTION_BEAN;
	}

	public void setPW_IL_BENIFIT_PAYMT_ACTION_BEAN(
			PW_IL_BENIFIT_PAYMT_ACTION pW_IL_BENIFIT_PAYMT_ACTION_BEAN) {
		PW_IL_BENIFIT_PAYMT_ACTION_BEAN = pW_IL_BENIFIT_PAYMT_ACTION_BEAN;
	}




	public PILP207_COMPOSITE_ACTION(){
		PW_IL_BENIFIT_PAYMT_ACTION_BEAN=new PW_IL_BENIFIT_PAYMT_ACTION();
		PW_IL_BENIFIT_PAYMT_ACTION_BEAN.compositeAction = this;
	}


	
}
