package com.iii.pel.forms.PILP060_APAC;

public interface PILP060_APAC_SQLQUERY_CONSTANTS {
	final String LOV_FM_TO_PROD_CODE="SELECT PROD_CODE,PROD_DESC,PROD_BL_DESC FROM " +
	"PM_IL_PRODUCT WHERE PROD_CODE IS NOT NULL AND ROWNUM <= ? ";
	
	final String FETCH_ROW_COUNT="25";
	
	final String LOV_FM_TO_POL_NO="SELECT POL_NO,POL_ASSURED_NAME FROM PT_IL_POLICY " +
			"WHERE NVL(POL_STATUS,'N') IN ('A','E','P','R') AND POL_NO IS NOT NULL " +
			"AND POL_DS_TYPE = '2' AND ROWNUM <=? ";
	
	final String LOV_FM_TO_BON_CODE="SELECT BONUS_CODE,BONUS_DESC,BONUS_BL_DESC " +
			"FROM PM_IL_BONUS WHERE ROWNUM <= ? ";
	
	final String SELECT_PM_IL_PRODUCT = "SELECT PROD_DESC FROM PM_IL_PRODUCT " +
			"WHERE  PROD_CODE = ?"; 
	
	final String SELECT_PT_IL_POLICY="SELECT * FROM PT_IL_POLICY WHERE " +
			"POL_NO = ?";
	
	final String SELECT_PM_IL_BONUS="SELECT BONUS_DESC,BONUS_BL_DESC " +
		"FROM PM_IL_BONUS WHERE BONUS_CODE = ?";
	
	final String PROCESS_BUTTON_ACTION_CURSOR_C1="SELECT  POL_SYS_ID,POL_SA_EXCH_RATE," +
			"PAPP_PROD_CODE FROM PT_IL_POLICY,PT_IL_POL_APPL_PROD WHERE  " +
			"POL_SYS_ID = PAPP_POL_SYS_ID " +
			"AND POL_NO BETWEEN ? AND ? " +
			"AND PAPP_PROD_CODE BETWEEN ? AND ? " +
			"AND NVL(POL_STATUS,'N') IN ('A','E','P','R')" +
			"AND POL_DS_TYPE = '2'";
	
	final String SELECT_PT_IL_BONUS="SELECT PT_IL_BONUS.* , ROWID FROM PT_IL_BONUS ";
	
	final String PT_IL_BONUS_POST_QUERY_CURSOR_C1=" SELECT POL_SYS_ID,POL_NO FROM PT_IL_POLICY ";
	
	final String GEN_PV_ACTION_CURSOR_C2="SELECT * FROM PT_IL_PROCESS " +
			" WHERE PR_PROCESS_TYPE='O'";
	
	final String SELECT_PT_IL_PROCESS="SELECT * FROM PT_IL_PROCESS " +
	" WHERE PR_PROCESS_TYPE='O'";
	
	final String PT_IL_PROCESS_POST_QUERY_CURSOR_C1="SELECT POL_NO,POL_SYS_ID " +
			" FROM PT_IL_POLICY";
	
	final String DELETE_PT_IL_PROCESS="DELETE FROM PT_IL_PROCESS WHERE PR_PROCESS_TYPE='O'";
}
