package com.iii.pel.forms.PILP001_APAC;

public interface SQLQueryInterfacePILP001 {
	
	public String sql_C1="SELECT POL_CUST_CURR_CODE,NVL(POL_CUST_EXCH_RATE, 0),POL_CONT_CODE,NVL(POL_END_NO_IDX, 0),NVL(POL_FC_DEPOSIT_AMOUNT,0),NVL(POL_LC_DEPOSIT_AMOUNT, 0),NVL(POL_FC_FIRST_PREM, 0), NVL(POL_LC_FIRST_PREM, 0),    NVL(POL_FC_NET_PREM, 0),    NVL(POL_LC_NET_PREM, 0),    NVL(POL_NO_OF_INST, 1),    NVL(POL_INCORPORATED_YN, 'N'),    NVL(POL_FC_BASIC_PREM, 0),    NVL(POL_LC_BASIC_PREM, 0),    NVL(POL_FC_ADDL_PREM, 0),    NVL(POL_LC_ADDL_PREM, 0),    NVL(POL_FC_SUM_ASSURED, 0),    NVL(POL_LC_SUM_ASSURED, 0),    POL_PLAN_CODE,    POL_PROP_NO,    POL_DS_CODE,    POL_DS_TYPE,    POL_PREM_PAY_YRS,    POL_PROD_CODE,    POL_FAC_YN FROM  PT_IL_POLICY  WHERE  POL_SYS_ID  = ? ";
	
	public String sql_C2="SELECT NVL(SUM(PD_FC_AMT), 0) FROM PT_IL_PYMT_DTLS WHERE PD_TXN_TYPE = 'QT' AND PD_TXN_SYS_ID = ? GROUP BY PD_TXN_SYS_ID";
	
	public String sql_C3="SELECT NVL(CONT_LC_PROP_DEP_AMT, 0), NVL(CONT_LC_PROP_UTIL_AMT,0),NVL(CONT_LC_POL_DEP_AMT, 0),NVL(CONT_LC_POL_UTIL_AMT,0)FROM PM_IL_CONTRACTOR WHERE CONT_CODE  = ? ";
	
	public String sql_C4="SELECT 'X' FROM PT_IL_PYMT_DTLS WHERE PD_TXN_TYPE = 'QT' AND PD_TXN_SYS_ID = ? GROUP BY PD_TXN_SYS_ID";
	
	public String sql_C5="SELECT 'X' FROM PT_IL_POLICY WHERE POL_PROP_NO = ? AND POL_DS_TYPE = '2'";
	
	public String sql_C6="SELECT 'X' FROM PT_IL_POLICY WHERE POL_SYS_ID = ? AND POL_APPRV_STATUS = 'A'";
	
	public String sql_C7="SELECT ASD_CHAR_VALUE FROM PM_IL_APPR_SETUP_DET WHERE ASD_USER_ID = ? AND ASD_CODE = DECODE(NVL(?,'N'),'Y','PRO_STDAP_YN','PR_SSTDAP_YN') AND ASD_FLAG = 2 AND ? BETWEEN NVL(ASD_FM_PROD_CODE,'0') AND NVL(ASD_TO_PROD_CODE,'ZZZZZZZZZZZZ')";
	
	public String sql_C8="SELECT ASD_NUM_VALUE FROM PM_IL_APPR_SETUP_DET WHERE ASD_USER_ID = ? AND ASD_CODE = DECODE(NVL(?,'N'),'Y','PROP_STD_SA','PROP_SSTD_SA') AND ASD_FLAG = 1 AND ? BETWEEN NVL(ASD_FM_PROD_CODE,'0') AND NVL(ASD_TO_PROD_CODE,'ZZZZZZZZZZZZ')";
	
	public String sql_C9="SELECT POL_LC_SUM_ASSURED,POL_STD_RISK_YN FROM PT_IL_POLICY WHERE POL_SYS_ID = ? ";
	
	public String sql_C10="SELECT PS_VALUE FROM PP_SYSTEM WHERE PS_TYPE = 'IL_CALC_MTHD'";
	
	public String sql_C11="SELECT NVL(PROD_AUTO_APPROV, 'N'),NVL(PROD_CBC_YN, 'N'), NVL(PROD_PREM_CALC_MTHD, 'T'), PROD_AGENT_HIRE_YN FROM PM_IL_PRODUCT WHERE PROD_CODE = (SELECT POL_PROD_CODE FROM PT_IL_POLICY WHERE POL_SYS_ID = ? )";
	
	public String sql_C12="SELECT NVL(CONT_LC_PROP_DEP_AMT, 0) - NVL(CONT_LC_PROP_UTIL_AMT, 0) FROM PM_IL_CONTRACTOR WHERE CONT_CODE =(SELECT POL_CONT_CODE FROM PT_IL_POLICY WHERE POL_SYS_ID= ?)";
	
	public String sql_C13="SELECT NVL(PDL_FC_DISC_LOAD_VALUE, 0),NVL(PDL_LC_DISC_LOAD_VALUE, 0),PDL_DISC_LOAD_CODE FROM PT_IL_POL_DISC_LOAD,PP_SYSTEM WHERE PS_TYPE = 'IL_MTLD_CODE' AND PS_CODE = '?' AND PS_CODE_DESC = PDL_DISC_LOAD_CODE AND PDL_POL_SYS_ID = ? ";
	
	public String sql_C14="SELECT NVL(PDL_FC_DISC_LOAD_VALUE, 0),NVL(PDL_LC_DISC_LOAD_VALUE, 0),PDL_DISC_LOAD_CODE FROM PT_IL_POL_DISC_LOAD,PP_SYSTEM WHERE PS_TYPE = 'IL_UWOC_LOAD' AND PS_CODE_DESC = PDL_DISC_LOAD_CODE AND PDL_POL_SYS_ID = ? ";
	
	public String sql_C15="SELECT POL_MODE_OF_PYMT FROM PT_IL_POLICY WHERE POL_SYS_ID = ? ";
	
	public String sql_C16="SELECT PLAN_TYPE FROM PM_IL_PLAN WHERE PLAN_CODE = ? AND NVL(PLAN_FRZ_FLAG,'N')!= 'Y'";
	
	public String sql_C17="SELECT DEP_GROSS_NET_FLAG FROM  PT_IL_DEPOSIT  WHERE  DEP_REF_NO  = ?  AND NVL(DEP_REC_REV_YN, 'N')  = 'N' ";
	
	public String sql_C18="SELECT ASD_CHAR_VALUE FROM  PM_IL_APPR_SETUP_DET  WHERE  ASD_USER_ID  = ?  AND ASD_CODE  = 'PR_PSTPND_YN'  AND ? BETWEEN NVL(ASD_FM_PROD_CODE, '0')  AND  NVL(ASD_TO_PROD_CODE, 'ZZZZZZZZZZZZ')";
	
	public String sql_C19="SELECT DR_REPORT_CODE FROM  PM_IL_DOC_REMINDERS  WHERE  DR_DS_TYPE  = '1'  AND DR_DS_CODE  = ?  AND DR_STATUS_CODE  = :DUMMY.M_PS_REASON_CODE ";
	
	public String sql_C20="SELECT    PC_DESC,    PC_BL_DESC FROM  PM_CODES  WHERE  PC_TYPE  = 'IL_REMIN_RPT'  AND PC_CODE  = ?";
	
	public String sql_C21="SELECT CONT_PREFERRED_LANG FROM  PM_IL_CONTRACTOR  WHERE  CONT_CODE  =?";
	
	public String sql_C22="SELECT POAD_LC_THRESHOLD_LMT FROM  PT_IL_POL_ASSURED_DTLS  WHERE  POAD_POL_SYS_ID  = ? ";
	
	public String sql_C23="SELECT NVL(ASD_NUM_VALUE, 0) FROM  PM_IL_APPR_SETUP_DET  WHERE  ASD_USER_ID  = ?  AND ASD_CODE  = DECODE(NVL(?, 'N'), 'Y', 'MAX_STD_TL', 'MAX_SSTD_TL')  AND ASD_FLAG  = 1  AND ?  BETWEEN NVL(ASD_FM_PROD_CODE, '0')  AND  NVL(ASD_TO_PROD_CODE, 'ZZZZZZZZZZZZ') ";
	
	public String sql_C24="SELECT SUM(MFD_FC_VALUE) FROM  PT_IL_MEDEX_FEE_DTL  WHERE  MFD_POL_SYS_ID  = ?  AND MFD_PAID_FLAG  = 'Y'  AND MFD_FRZ_FLAG  = 'Y' ";
	
	public String sql_C25="SELECT 'X' FROM  PT_IL_MEDEX_FEE_DTL,   PT_IL_POL_MED_EXAM_DTL  WHERE  MFD_POL_SYS_ID  = PMED_POL_SYS_ID  AND MFD_CLINIC_CODE  = PMED_CLINIC_CODE  AND NVL(MFD_PAID_FLAG, 'N')  <> 'Y'  AND MFD_POL_SYS_ID  = ? ";
	
	public String sql_C26="SELECT    PMOP_SHORT_RATE,    PMOP_SHORT_RATE_PER,    PMOP_TOLL_TYP FROM  PM_IL_PLAN_MOP  WHERE  PMOP_PLAN_CODE  = ? AND PMOP_TYPE  = ?";
	
	public String sql_C27="SELECT DS_POST_BO FROM  PM_IL_DOC_SETUP  WHERE  DS_TYPE  = ? AND DS_CODE  =?";
	
	public String sql_Update1="UPDATE PT_IL_POLICY SET POL_STATUS = ? , POL_APPRV_STATUS = 'A', POL_ADDL_STATUS = DECODE(?, 1, 'C05', NULL)  WHERE  POL_SYS_ID  = ?  ";
	
	public String sql_Update2="UPDATE   PT_IL_POLICY    SET POL_STATUS = ?,      POL_APPRV_STATUS = 'A',      POL_ADDL_STATUS = DECODE(?, 1, 'B06', NULL)  WHERE  POL_SYS_ID  = ? ";
	
	public String sql_Update9="UPDATE   PT_IL_POLICY    SET POL_STATUS = 'N',      POL_ADDL_STATUS = DECODE(?, 1, ?, NULL)  WHERE  POL_SYS_ID  = ?  ";
	
	public String sql_insert1="INSERT INTO PT_IL_POL_STATUS ( PS_POL_SYS_ID ,PS_END_NO_IDX , PS_STATUS_DT , PS_STATUS , PS_REASON_CODE , PS_REMARKS , PS_STATUS_UID , PS_STATUS_TYPE , PS_CR_UID , PS_CR_DT ) VALUES( ? ,    ? ,    ? ,    'C05' ,    ? ,    ? ,    ? ,    'S' ,    ? ,    SYSDATE )   ";
	
	public String sql_insert2="INSERT INTO PT_IL_POL_STATUS ( PS_POL_SYS_ID ,PS_END_NO_IDX ,PS_STATUS_DT ,PS_STATUS ,PS_REASON_CODE ,PS_REMARKS ,PS_STATUS_UID ,PS_STATUS_TYPE ,PS_CR_UID ,PS_CR_DT )    VALUES   ( ? ,    ? ,    ? ,    'B06' , ? ,? ,    ? ,    'S' , ? ,    SYSDATE )   ";
	
	public String sql_update3="UPDATE PT_IL_POLICY SET POL_STATUS = ?, POL_APPRV_STATUS = 'A', POL_ADDL_STATUS = DECODE(?, 1, 'C05', NULL)  WHERE  POL_SYS_ID  = ? ";
	
	public String sql_insert3="INSERT INTO  PT_IL_POL_STATUS ( PS_POL_SYS_ID ,PS_END_NO_IDX ,    PS_STATUS_DT ,    PS_STATUS ,    PS_REASON_CODE ,    PS_REMARKS ,    PS_STATUS_UID ,    PS_STATUS_TYPE ,    PS_CR_UID ,    PS_CR_DT )    VALUES   ( ? , ? ,    ? ,    'C05' ,    ? ,    ? , ? ,    'S' , ? ,    SYSDATE )   ";
	
	public String sql_update4="UPDATE   PT_IL_POLICY    SET POL_STATUS = ?,      POL_APPRV_STATUS = 'A',      POL_ADDL_STATUS = DECODE(?, 1, 'B06', NULL)  WHERE  POL_SYS_ID  = ? ";
	
	public String sql_insert4="INSERT INTO  PT_IL_POL_STATUS ( PS_POL_SYS_ID ,    PS_END_NO_IDX ,    PS_STATUS_DT ,    PS_STATUS ,    PS_REASON_CODE ,    PS_REMARKS ,    PS_STATUS_UID ,    PS_STATUS_TYPE ,    PS_CR_UID ,    PS_CR_DT )    VALUES   ( ? ,    ? ,    ? ,    'B06' ,    ? ,    ? ,    ? ,    'S' ,    ? ,    SYSDATE )   ";
	
	public String sql_insert5="INSERT INTO  PT_IL_POL_STATUS      ( PS_POL_SYS_ID ,    PS_END_NO_IDX ,    PS_STATUS_DT ,    PS_STATUS ,    PS_REASON_CODE ,    PS_REMARKS ,    PS_STATUS_UID ,    PS_STATUS_TYPE ,    PS_CR_UID ,    PS_CR_DT )    VALUES   ( ? ,    ? ,  ? ,   ? ,    ? , ? , ? ,    'S' ,    ? ,    SYSDATE )   ";
	
	public String sql_insert11="INSERT INTO  PW_IL_REMINDER_SUMMARY      ( RS_PROCESS_DT ,    RS_DS_TYPE ,    RS_POL_SYS_ID ,    RS_END_NO_IDX ,    RS_STATUS_CODE ,    RS_REPORT_NAME ,    RS_CR_DT ,    RS_CR_UID )    VALUES   ( SYSDATE ,    ? ,    ? ,    ? ,    ? ,    ? ,    SYSDATE ,    ? )   ";
	
	public String sql_vembu12="UPDATE   PT_IL_POLICY    SET POL_STATUS = 'A',      POL_APPRV_STATUS = 'A',      POL_APPRV_DT = ?,      POL_ADDL_STATUS = DECODE(?, 1, 'C01', NULL),      POL_TRAN_DT = TO_DATE(SYSDATE),      POL_APPRV_UID = ?  WHERE  POL_SYS_ID  = ?  ";
	
	public String sql_vembu13="INSERT INTO  PT_IL_POL_STATUS      ( PS_POL_SYS_ID ,    PS_END_NO_IDX ,    PS_STATUS_DT ,    PS_STATUS ,    PS_REASON_CODE ,    PS_REMARKS ,    PS_STATUS_UID ,    PS_STATUS_TYPE ,    PS_CR_UID ,    PS_CR_DT )    VALUES   ( ?,    ? ,    ? ,    'C01' ,    ? ,    ? ,    ? ,    'S' ,    ? ,    SYSDATE )   ";
	
	public String sql_vembu14="UPDATE   PT_IL_POLICY    SET POL_STATUS = 'A',      POL_APPRV_STATUS = 'A',      POL_APPRV_DT = ?,      POL_ADDL_STATUS = DECODE(?, 1, 'C01', NULL),      POL_TRAN_DT = TO_DATE(SYSDATE),      POL_APPRV_UID = ?  WHERE  POL_SYS_ID  = ?  ";
	
	public String sql_vembu15="INSERT INTO  PT_IL_POL_STATUS      ( PS_POL_SYS_ID ,    PS_END_NO_IDX ,    PS_STATUS_DT ,    PS_STATUS ,    PS_REASON_CODE ,    PS_REMARKS ,    PS_STATUS_UID ,    PS_STATUS_TYPE ,    PS_CR_UID ,    PS_CR_DT )    VALUES   ( ? ,    ? ,    ? ,    'C01' ,    ? ,    ? ,? ,    'S' ,  ? ,    SYSDATE )   ";
	
	public String sql_vembu16="UPDATE   PT_IL_POLICY    SET POL_STATUS = 'A',      POL_APPRV_STATUS = 'A',      POL_APPRV_DT = ?,      POL_ADDL_STATUS = DECODE(?, 1, 'C01', NULL),      POL_TRAN_DT = TO_DATE(SYSDATE),      POL_APPRV_UID = ?  WHERE  POL_SYS_ID  = ?  ";
	
	public String sql_vembu17="INSERT INTO  PT_IL_POL_STATUS      ( PS_POL_SYS_ID ,    PS_END_NO_IDX ,    PS_STATUS_DT ,    PS_STATUS ,    PS_REASON_CODE ,    PS_REMARKS ,    PS_STATUS_UID ,    PS_STATUS_TYPE ,    PS_CR_UID ,    PS_CR_DT )    VALUES   ( ? ,    ? ,    ? ,    'C01' ,    ? ,    ? ,    ? ,    'S' ,    ? ,    SYSDATE )   ";
	
	public String sql_vembu18="UPDATE   PT_IL_POLICY    SET POL_STATUS = 'A',      POL_APPRV_STATUS = 'A',      POL_APPRV_DT = ?,      POL_ADDL_STATUS = DECODE(?, 1, 'C02', NULL),      POL_TRAN_DT = TO_DATE(SYSDATE),      POL_APPRV_UID = ? WHERE  POL_SYS_ID  = ?  ";
	
	public String sql_vembu19="INSERT INTO  PT_IL_POL_STATUS      ( PS_POL_SYS_ID ,    PS_END_NO_IDX ,    PS_STATUS_DT ,    PS_STATUS ,    PS_REASON_CODE ,    PS_REMARKS ,    PS_STATUS_UID ,    PS_STATUS_TYPE ,    PS_CR_UID ,    PS_CR_DT )    VALUES   ( ? ,    ? ,    ? ,    'C02' ,    ?,    ? ,    ? ,    'S' ,    ?,    SYSDATE )   ";
	
	public String sql_vembu20="UPDATE   PT_IL_POLICY    SET POL_STATUS = 'A',      POL_APPRV_STATUS = 'A',      POL_APPRV_DT = ?,      POL_ADDL_STATUS = DECODE(?, 1, 'C01', NULL),      POL_TRAN_DT = TO_DATE(SYSDATE),      POL_APPRV_UID = ?  WHERE  POL_SYS_ID  = ?  ";
	
	public String sql_vembu21="INSERT INTO  PT_IL_POL_STATUS      ( PS_POL_SYS_ID ,    PS_END_NO_IDX ,    PS_STATUS_DT ,    PS_STATUS ,    PS_REASON_CODE ,    PS_REMARKS ,    PS_STATUS_UID ,    PS_STATUS_TYPE ,    PS_CR_UID ,    PS_CR_DT )    VALUES   ( ? ,    ? ,    ? ,    'C01' ,    ? ,    ? ,    ? ,    'S' ,    ? ,    SYSDATE )   ";
	
	public String sql_vembu22="UPDATE   PT_IL_POLICY    SET POL_STATUS = 'A',      POL_APPRV_STATUS = 'A',      POL_APPRV_DT = ? ,      POL_ADDL_STATUS = NULL,      POL_TRAN_DT = TO_DATE(SYSDATE),      POL_APPRV_UID = ?  WHERE  POL_SYS_ID  = ?  ";
	
	public String sql_vembu23="UPDATE   PT_IL_POLICY    SET POL_STATUS = 'A',      POL_APPRV_STATUS = 'A',      POL_APPRV_DT = ?,      POL_ADDL_STATUS = DECODE(?, 1, 'C01', NULL),      POL_TRAN_DT = TO_DATE(SYSDATE),      POL_APPRV_UID = ? WHERE  POL_SYS_ID  = ? ";
	
	public String sql_vembu24="INSERT INTO  PT_IL_POL_STATUS      ( PS_POL_SYS_ID ,    PS_END_NO_IDX ,    PS_STATUS_DT ,    PS_STATUS ,    PS_REASON_CODE ,    PS_REMARKS ,    PS_STATUS_UID ,    PS_STATUS_TYPE ,    PS_CR_UID ,    PS_CR_DT )    VALUES   ( ? ,    ? ,    ? ,    'C01' ,    ? ,    ? ,    ? ,    'S' ,   ? ,    SYSDATE )   ";
	
	public String sql_vembu25="UPDATE   PT_IL_POLICY    SET POL_NO = ?  WHERE  POL_SYS_ID  = ? ";
	
	public String L_GENERATE_POLICY_NUMBER_SQL_C1 = "SELECT    POL_DIVN_CODE,    POL_CLASS_CODE,    POL_PLAN_CODE,    POL_UW_YEAR,    POL_DS_CODE,    POL_PROD_CODE FROM  PT_IL_POLICY  WHERE  POL_SYS_ID  = ?  AND POL_DS_TYPE  = '1' ";
	
	public String L_GENERATE_POLICY_NUMBER_SQL_C2 = "SELECT DS_POL_CODE FROM  PM_IL_DOC_SETUP  WHERE  DS_TYPE  = '1'  AND DS_CODE  = ? ";
	
	public String L_GENERATE_POLICY_NUMBER_SQL_C3 = "SELECT 'X' FROM  PT_IL_POLICY  WHERE  POL_NO  = ? AND POL_DS_TYPE  = '2' ";
	
	public String L_PRINT_LETTER_SQL_C1 = "SELECT    POL_DS_TYPE,    POL_CONT_CODE,    POL_END_NO_IDX,    POL_DS_CODE FROM  PT_IL_POLICY  WHERE  POL_SYS_ID  = ? ";
	
	public String L_PRINT_LETTER_SQL_C2 = "SELECT CONT_PREFERRED_LANG FROM  PM_IL_CONTRACTOR  WHERE  CONT_CODE  = ? ";
		
	public String L_PRINT_LETTER_SQL_C3 = "SELECT DR_REPORT_CODE FROM  PM_IL_DOC_REMINDERS  WHERE  DR_DS_TYPE  = ?  AND DR_DS_CODE  = ? AND DR_STATUS_CODE  = DECODE(?, 'A', 'C01', 'C', 'B05')  AND DR_REMINDER_TYPE  = 'N' ";
		
	public String L_PRINT_LETTER_SQL_C4 = "SELECT PLAN_TYPE FROM  PM_IL_PLAN  WHERE  PLAN_CODE  IN  (   SELECT POL_PLAN_CODE  FROM  PT_IL_POLICY   WHERE  POL_SYS_ID  = ?  )  AND NVL(PLAN_FRZ_FLAG, 'N')  = 'N' ";
	
	public String PreForm_Query = "select * from PT_IL_POLICY WHERE POL_PROP_NO = ?";
	
}
