package com.iii.pel.forms.PILT009;

public interface PILT009_SQL_CONSTANTS {

	String SELECT_PT_IL_PREM_COLL = "SELECT PC_PREM_TYPE,PC_SCHD_PYMT_DT,PC_SYS_ID FROM PT_IL_PREM_COLL,PT_IL_POLICY WHERE PC_POL_SYS_ID = POL_SYS_ID"+
      " AND POL_NO = ? AND  PC_SYS_ID = NVL(?, PC_SYS_ID) ORDER BY PC_SCHD_PYMT_DT ";
	
	String SELECT_WHEN_NEW_FORM_INSTANCE = "SELECT DS_CURR_RATE_BS,NVL(POL_APPRV_STATUS,'N'),POL_NO, POL_CQS_YN, POL_CQS_PERC FROM PM_IL_DOC_SETUP,PT_IL_POLICY WHERE DS_CODE = POL_DS_CODE AND POL_NO = NVL(?, POL_NO) AND POL_DS_TYPE = '2'";
	
	String SELECT_PLAN_TYPE = "SELECT PLAN_TYPE FROM PM_IL_PLAN WHERE PLAN_CODE IN( SELECT POL_PLAN_CODE FROM PT_IL_POLICY WHERE POL_NO = NVL(?, POL_NO))";
	
	String SELECT_PT_IL_POLICY1 = "SELECT POL_SYS_ID,NVL(POL_FAC_YN,'N'), NVL(POL_COINS_YN,'N'), NVL(POL_FACIN_YN,'N'), POL_CUST_CURR_CODE,POL_ISSUE_DT, NVL(POL_END_NO_IDX,0), POL_APPRV_STATUS,POL_CUST_EXCH_RATE,POL_SA_EXCH_RATE, NVL(POL_FAC_CLOSE_FLAG,'N') FROM PT_IL_POLICY WHERE POL_NO = ? AND POL_DS_TYPE = '2'";
	
	String SELECT_PC_FAC_CLOSE_FLAG = "SELECT NVL(PC_FAC_CLOSE_FLAG,'N') FROM PT_IL_PREM_COLL WHERE PC_POL_SYS_ID = ? AND PC_SYS_ID = ?";
	
	String SELECT_PT_IL_FAC_OUT = "SELECT PT_IL_FAC_OUT.ROWID, PT_IL_FAC_OUT.* FROM PT_IL_FAC_OUT, PT_IL_POLICY WHERE POL_SYS_ID = FO_POL_SYS_ID AND POL_NO = ?";
	
	String CHECK_PT_IL_FAC_PART_CUST = "SELECT 'X' FROM PT_IL_FAC_PART_CUST WHERE FPCU_FO_SYS_ID = ?";
	
	String SELECT_PT_IL_POLICY2 = "SELECT NVL(POL_FAC_YN,'N'), NVL(POL_COINS_YN,'N'),POL_SA_EXCH_RATE, POL_CUST_CURR_CODE,POL_CUST_EXCH_RATE FROM PT_IL_POLICY WHERE POL_SYS_ID = ?";
	
	String SELECT_POAD_ASSURED_NAME = "SELECT POAD_ASSURED_NAME FROM PT_IL_POL_ASSURED_DTLS WHERE POAD_ASSR_CODE = ?";
	
	String SELECT_PC_DOC_NO = "SELECT PC_DOC_NO FROM PT_IL_PREM_COLL WHERE PC_SYS_ID = ?";
	
	String SELECT_PT_IL_POLICY3 = "SELECT NVL(POL_FAC_YN,'N'), POL_FACIN_YN FROM PT_IL_POLICY WHERE POL_SYS_ID = ?";
	
	String SELECT_PT_IL_FAC_DETL1 = "SELECT FD_YEAR,FD_ASSURED_AGE,NVL(FD_FC_SA,0),NVL(FD_LC_SA,0), NVL(FD_FC_PREM,0),NVL(FD_LC_PREM,0),FD_SYS_ID,FD_TAR_RATE,FD_TAR_RATE_PER FROM PT_IL_FAC_DETL WHERE FD_FO_SYS_ID = ? AND FD_YEAR = (SELECT MAX(FD_YEAR) FROM PT_IL_FAC_DETL WHERE FD_FO_SYS_ID = ?)";
	
	String UPDATE_PT_IL_FAC_DETL = "UPDATE PT_IL_FAC_DETL SET FD_FC_FAC_SA = ?, FD_LC_FAC_SA = ?, FD_FC_FAC_PREM = ?, FD_LC_FAC_PREM = ?, FD_FC_FAC_GRS_PREM = ?, FD_LC_FAC_GRS_PREM = ? WHERE FD_FO_SYS_ID = ? AND FD_YEAR = ? AND FD_DEL_FLAG NOT IN ('Y', 'E')";
	
	String SELECT_PIL_FO_SYS_ID = "SELECT PIL_FO_SYS_ID.NEXTVAL FROM DUAL";
	
	String SELECT_POL_PROD_CODE = "SELECT POL_PROD_CODE FROM PT_IL_POLICY WHERE POL_NO = ?";
	
	String SELECT_ASD_CHAR_VALUE = "SELECT ASD_CHAR_VALUE FROM PM_IL_APPR_SETUP_DET WHERE ASD_USER_ID = ?	AND ASD_CODE = 'FAC_AMT_YN'	AND ? BETWEEN NVL(ASD_FM_PROD_CODE,'0') AND NVL(ASD_TO_PROD_CODE,'zzzzzzzzzzzz')";
	
	String SELECT_PT_IL_FAC_DETL2 = "SELECT PT_IL_FAC_DETL.ROWID, PT_IL_FAC_DETL.* FROM PT_IL_FAC_DETL WHERE FD_FO_SYS_ID = ?";

	String SELECT_SUM_FPCU_SHARE_PERC = "SELECT SUM(NVL(FPCU_SHARE_PERC,0)) FROM PT_IL_FAC_PART_CUST WHERE FPCU_FO_SYS_ID = ?";
	
	String SELECT_PT_IL_FAC_PART_CUST = "SELECT PT_IL_FAC_PART_CUST.ROWID, PT_IL_FAC_PART_CUST.* FROM PT_IL_FAC_PART_CUST WHERE FPCU_FO_SYS_ID = ?";
	
	String SELECT_PT_IL_FAC_CUST_RETRO = "SELECT PT_IL_FAC_CUST_RETRO.ROWID, PT_IL_FAC_CUST_RETRO.* FROM PT_IL_FAC_CUST_RETRO WHERE FCR_FO_SYS_ID = ?";
	
	String SELECT_PT_IL_FAC_DISC_LOAD = "SELECT PT_IL_FAC_DISC_LOAD.ROWID, PT_IL_FAC_DISC_LOAD.* FROM PT_IL_FAC_DISC_LOAD WHERE FDL_FD_SYS_ID = ?";
	
	String SELECT_PT_IL_FAC_PART_CUST_DETL = "SELECT PT_IL_FAC_PART_CUST_DETL.ROWID, PT_IL_FAC_PART_CUST_DETL.* FROM PT_IL_FAC_PART_CUST_DETL WHERE FPCUD_FPCU_SYS_ID = ?";
	
	String SELECT_PT_IL_FAC_PART_CHRG = "SELECT PT_IL_FAC_PART_CHRG.ROWID, PT_IL_FAC_PART_CHRG.* FROM PT_IL_FAC_PART_CHRG WHERE FPC_FPCUD_SYS_ID = ?";
	
	String SELECT_PC_DESC = "SELECT PC_DESC FROM PM_CODES WHERE PC_CODE = ?";
	
	String SELECT_PT_IL_FAC_CUST_RETRO_DETL = "SELECT PT_IL_FAC_CUST_RETRO_DETL.ROWID, PT_IL_FAC_CUST_RETRO_DETL.* FROM PT_IL_FAC_CUST_RETRO_DETL WHERE FCRD_FCR_SYS_ID = ?";
	
	
}
