package com.iii.pel.forms.PILT020;

public class PILT020_PT_IL_SEARCH_PAGE_ACTION {

	//SELECT PM_IL_DATA_UPLOAD_DEFN_HDR.ROWID,DUDH_DEF_CODE,DUDH_DESC,DUDH_SHORT_DESC,DUDH_LONG_DESC,DUDH_BL_DESC,DUDH_BL_SHORT_DESC,DUDH_BL_LONG_DESC,DUDH_EFF_FM_DT,DUDH_EFF_TO_DT,DUDH_CR_DT,DUDH_CR_UID,DUDH_UPD_DT,DUDH_UPD_UID FROM PM_IL_DATA_UPLOAD_DEFN_HDR {0} ORDER BY DUDH_DEF_CODE
}
