package com.iii.pel.forms.PM102;

public class PM102_COMPOSITE_ACTION {
	AG_INCENTIVES_TRGT_STP_ACTION AG_INCENTIVES_TRGT_STP_ACTION_BEAN = null;
	BSC_RATES_SETUP_ACTION BSC_RATES_SETUP_ACTION_BEAN = null;

	public PM102_COMPOSITE_ACTION() {
		AG_INCENTIVES_TRGT_STP_ACTION_BEAN = new AG_INCENTIVES_TRGT_STP_ACTION();
		BSC_RATES_SETUP_ACTION_BEAN = new BSC_RATES_SETUP_ACTION();
		
		AG_INCENTIVES_TRGT_STP_ACTION_BEAN.compositeAction = this;
		BSC_RATES_SETUP_ACTION_BEAN.compositeAction = this;
		
	}

	public AG_INCENTIVES_TRGT_STP_ACTION getAG_INCENTIVES_TRGT_STP_ACTION_BEAN() {
		return AG_INCENTIVES_TRGT_STP_ACTION_BEAN;
	}

	public void setAG_INCENTIVES_TRGT_STP_ACTION_BEAN(
			AG_INCENTIVES_TRGT_STP_ACTION aG_INCENTIVES_TRGT_STP_ACTION_BEAN) {
		AG_INCENTIVES_TRGT_STP_ACTION_BEAN = aG_INCENTIVES_TRGT_STP_ACTION_BEAN;
	}

	public BSC_RATES_SETUP_ACTION getBSC_RATES_SETUP_ACTION_BEAN() {
		return BSC_RATES_SETUP_ACTION_BEAN;
	}

	public void setBSC_RATES_SETUP_ACTION_BEAN(
			BSC_RATES_SETUP_ACTION bsc_rates_setup_action_bean) {
		BSC_RATES_SETUP_ACTION_BEAN = bsc_rates_setup_action_bean;
	}
	
}
