package com.iii.pel.forms.PILM062_APAC;

public interface PILM062_APAC_SQL_QUERY_CONSTANTS {

	String CHECK_PM_IL_PROD_GROUP1 = "SELECT 'X' FROM PM_IL_PROD_GROUP WHERE PG_PROD_CODE = ?";
	
	String CHECK_PM_IL_PROD_GROUP2 = "SELECT 'X' FROM PM_IL_PROD_GROUP WHERE PG_CODE = ? AND ROWID <> ?";
	
	String SELECT_PROD_DESC = "SELECT PROD_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE = ?";
	
	String SELECT_PC_CODE_LOV = "SELECT PC_CODE, PC_DESC FROM PM_CODES WHERE PC_TYPE = ? AND NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM <= ? ORDER BY PC_CODE";
	
	String SELECT_PC_CODE_LOV_LIKE = "SELECT PC_CODE, PC_DESC FROM PM_CODES WHERE PC_TYPE = ? AND NVL(PC_FRZ_FLAG,'N') = 'N' AND PC_CODE LIKE ? AND ROWNUM <= ? ORDER BY PC_CODE";
	
	String SELECT_PROD_CODE_LOV = "SELECT PROD_CODE, PROD_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE IS NOT NULL AND ROWNUM <= ? ORDER BY PROD_CODE";
	
	String SELECT_PROD_CODE_LOV_LIKE = "SELECT PROD_CODE, PROD_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE IS NOT NULL AND PROD_CODE LIKE ? AND ROWNUM <= ? ORDER BY PROD_CODE";
	
	String PILM062_APAC_SEARCH_LIST_QUERY = "SELECT PG_CODE,PG_PROD_CODE FROM PM_IL_PROD_GROUP WHERE ( PG_CODE  LIKE  ?  OR  PG_PROD_CODE  LIKE  ?  )ORDER BY PG_CODE";
	
	String FETCH_RECORDS = "SELECT ROWID, PG_CODE, PG_PROD_CODE, PG_CR_UID, PG_CR_DT FROM PM_IL_PROD_GROUP WHERE ROWID = ?"; 
}
