package com.iii.pel.forms.PILM106;

public interface PILM106_A_QUERYCONSTANTS {
	
	String Select_Menu_Values = "SELECT LIV_CODE,LIV_CODE_DESC FROM PP_LIST_ITEM_VALUES WHERE LIV_SYS_PARAM = 'MAIL_TMP_TYP'";
	String Data_Table_List_Key ="SELECT PEF_COL_NAME, PEF_COL_DESC FROM PW_LIFE_EMAIL_FLDS";
	
	/*MOdified by Ganesh on 28.06.2017 for ZBILQC-1725181 */
	//String LoadData="SELECT PMT_PROD_CODE,PMT_MAIL_FM,PMT_MAIL_TYPE,PMT_MAIL_SUB,PMT_MAIL_TEXT,PMT_FRZ_FLAG,PMT_EFF_FM_DT,PMT_EFF_TO_DT,PMT_ATTACH_YN FROM PM_LIFE_MAIL_TEMPLATE WHERE PM_LIFE_MAIL_TEMPLATE.ROWID = ? ";
	String LoadData="SELECT PMT_PROD_CODE,PMT_MAIL_FM,PMT_MAIL_TYPE,PMT_MAIL_SUB,PMT_MAIL_TEXT,PMT_FRZ_FLAG,PMT_EFF_FM_DT,PMT_EFF_TO_DT,PMT_ATTACH_YN,PMT_KEY_MAIL_TO,PMT_KEY_MAIL_CC,PMT_TYPE FROM PM_LIFE_MAIL_TEMPLATE WHERE PM_LIFE_MAIL_TEMPLATE.ROWID = ? ";
	/*End*/
	
	String DeleteQuery="";
	String InsertCond="SELECT 'X' FROM PM_LIFE_MAIL_TEMPLATE WHERE PMT_MAIL_TYPE= ?";
	String UpdateCond="SELECT 'X' FROM PM_LIFE_MAIL_TEMPLATE WHERE PMT_MAIL_TYPE= ? AND ROWID = ?";	
	String CheckTypeDuplicationIns = "SELECT 'X' FROM PM_LIFE_MAIL_TEMPLATE WHERE PMT_MAIL_TYPE= ? AND PMT_PROD_CODE = ?";
	String CheckTypeDuplicationUpd = "SELECT 'X' FROM PM_LIFE_MAIL_TEMPLATE WHERE PMT_MAIL_TYPE= ? AND PMT_PROD_CODE = ? AND ROWID != ?";	
	
	
	/*Added by janani on 23.02.2018 for SMS as discussed with Girirsh*/
	String Select_notf_type_Values = "SELECT LIV_CODE,LIV_CODE_DESC FROM PP_LIST_ITEM_VALUES WHERE LIV_SYS_PARAM = 'NOTF_TYPE'";
	/*End*/
	
}
