package com.iii.pel.forms.PILM075_APAC;

public interface PILM075_APAC_SQL_CONSTANTS {
	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00178: ROWID fetched from DB. Added By : Mallika.S 01-Apr-2009 */

	String PM_IL_END_APPR_SETUP$MAIN_PAGE_QUERY = "SELECT ROWID,EAS_AS_USER_ID, EAS_AS_FM_PROD_CODE, EAS_AS_TO_PROD_CODE, EAS_END_PROC_YN, " +
													"EAS_END_APPR_YN, EAS_CR_DT, EAS_CR_UID, EAS_UPD_DT, EAS_UPD_UID, EAS_FM_END_CODE, " +
													"EAS_TO_END_CODE,EAS_SYS_ID, ROWID FROM PM_IL_END_APPR_SETUP WHERE ROWID =?";
	String PM_IL_END_APPR_SETUP$SEARCH_QUERY = "SELECT EAS_AS_USER_ID, EAS_FM_END_CODE, EAS_TO_END_CODE,ROWID FROM PM_IL_END_APPR_SETUP WHERE EAS_AS_USER_ID LIKE NVL(?, EAS_AS_USER_ID) AND EAS_FM_END_CODE LIKE NVL(?, EAS_FM_END_CODE) AND EAS_TO_END_CODE LIKE NVL(?, EAS_TO_END_CODE)"; 
	String LOV_CLASS_MODULE_ID_QUERY_STAR = "SELECT PS_CODE,PS_CODE_DESC,PS_BL_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'LIMODCODES'  AND ROWNUM < 25 ORDER BY 1 ASC";
	String LOV_CLASS_MODULE_ID_QUERY_SEARCH = "SELECT PS_CODE, PS_CODE_DESC,PS_BL_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'LIMODCODES' AND PS_CODE LIKE ?  AND ROWNUM < 25 ORDER BY 1 ASC";
	String PM_GL_CLASS$CLASS_CODE = "SELECT 'X' FROM PM_GL_CLASS WHERE CLASS_CODE = ?";
	//  [BugId:TRACK_PREMIAGDC_GL.10.5-00164: USER_BL_DESC Removed from Query : Added by : Mallika.S 31-Mar-2009
	String LOV_EAS_AS_USER_ID_QUERY_STAR = "SELECT USER_ID, USER_DESC FROM MENU_USER WHERE ROWNUM < 25 ORDER BY 1 ASC";
	//  [BugId:TRACK_PREMIAGDC_GL.10.5-00164: USER_BL_DESC Removed from Query : Added by : Mallika.S 31-Mar-2009
	String LOV_EAS_AS_USER_ID_QUERY_SEARCH = "SELECT USER_ID, USER_DESC FROM MENU_USER WHERE USER_ID LIKE ?  AND ROWNUM < 25 ORDER BY 1 ASC";
	String LOV_EAS_AS_FM_PROD_CODE_QUERY_STAR = "SELECT PROD_CODE, PROD_DESC, PROD_BL_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE IS NOT NULL AND ROWNUM < 25 ORDER BY 1 ASC";
	String LOV_EAS_AS_FM_PROD_CODE_QUERY_SEARCH = "SELECT PROD_CODE, PROD_DESC, PROD_BL_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE LIKE ? AND ROWNUM < 25 ORDER BY 1 ASC";
	String LOV_EAS_FM_END_CODE_QUERY_STAR = "SELECT DS_CODE, DS_DESC, DS_BL_DESC FROM PM_IL_DOC_SETUP WHERE DS_TYPE = '3' OR DS_TYPE = '3'  AND  NVL(DS_FRZ_FLAG ,'N') ='N' AND ROWNUM < 25 ORDER BY 1 ASC";
	String LOV_EAS_FM_END_CODE_QUERY_SEARCH = "SELECT DS_CODE, DS_DESC, DS_BL_DESC FROM PM_IL_DOC_SETUP WHERE DS_CODE LIKE ? AND DS_TYPE = '3' OR DS_TYPE = '3'  AND  NVL(DS_FRZ_FLAG ,'N') ='N' AND ROWNUM < 25 ORDER BY 1 ASC";
	String PM_IL_END_APPR_SETUP$POST_QUERY_C1= "SELECT USER_GROUP_ID FROM MENU_USER WHERE  USER_ID = ?";
	String PM_IL_END_APPR_SETUP$POST_QUERY_C2= "SELECT DS_DESC FROM PM_IL_DOC_SETUP WHERE DS_CODE =? AND DS_TYPE ='3'";
	String PM_IL_END_APPR_SETUP$POST_QUERY_C3= "SELECT DS_DESC FROM PM_IL_DOC_SETUP WHERE DS_CODE =? AND DS_TYPE ='3'";
	String PM_IL_END_APPR_SETUP$PRE_INSERT_C1= "SELECT PS_CODE,PS_VALUE FROM PP_SYSTEM WHERE PS_TYPE = 'IL_ENDT_PARA'";
	String PM_IL_END_APPR_SETUP$PRE_INSERT_C2= "SELECT P9IL_EAS_SYS_ID.NEXTVAL FROM DUAL";
	String PM_IL_END_APPR_SETUP$PRE_INSERT_C3= "SELECT P9IL_ESD_SYS_ID.NEXTVAL FROM DUAL";
	String PM_IL_END_APPR_SETUP$PRE_INSERT_ins1 = "INSERT INTO PM_IL_END_SETUP_DET(ESD_SYS_ID, " +
								"ESD_EAS_SYS_ID, ESD_USER_ID, ESD_CODE, ESD_NUM_VALUE, ESD_CHAR_VALUE, ESD_FLAG, ESD_CR_DT," +
								"ESD_CR_UID, ESD_UPD_DT, ESD_UPD_UID, ESD_FM_PROD_CODE, ESD_TO_PROD_CODE)" +
								"VALUES(?,?,?,?,0,'N',TO_CHAR(?), SYSDATE,?,NULL,NULL,?,?)";
      
	
	
	String PM_IL_END_APPR_SETUP$PRE_UPDATE_C1= "SELECT  'X' FROM PM_IL_END_APPR_SETUP WHERE " +
							"(?  BETWEEN  EAS_FM_END_CODE AND EAS_TO_END_CODE" +
							"  OR  ? BETWEEN  EAS_FM_END_CODE AND EAS_TO_END_CODE" +
							"  OR  EAS_FM_END_CODE BETWEEN ?   AND ? OR  EAS_TO_END_CODE BETWEEN ? AND ?)" +
							" AND (? BETWEEN EAS_AS_FM_PROD_CODE  AND EAS_AS_TO_PROD_CODE   " +
							" OR ? BETWEEN EAS_AS_FM_PROD_CODE  AND EAS_AS_TO_PROD_CODE  " +
							" OR EAS_AS_FM_PROD_CODE BETWEEN ? AND ?  OR EAS_AS_TO_PROD_CODE BETWEEN ? AND ?) " +
							" AND  EAS_AS_USER_ID  =:PM_IL_END_APPR_SETUP.EAS_AS_USER_ID " +
							" AND  ROWID != ? AND  EAS_END_PROC_YN =? AND  EAS_END_APPR_YN  =?"; 
	String PM_IL_END_SETUP_DET1$getData="SELECT PM_IL_END_SETUP_DET.*, ROWID from PM_IL_END_SETUP_DET WHERE " +
			"ESD_FLAG='2' AND ESD_USER_ID = ? AND  ESD_FM_PROD_CODE =? AND  ESD_TO_PROD_CODE =? ";
	String PM_IL_END_SETUP_DET$getData="select PM_IL_END_SETUP_DET.*, ROWID from PM_IL_END_SETUP_DET WHERE " +
			"ESD_FLAG='1' AND ESD_USER_ID = ? AND  ESD_FM_PROD_CODE =? AND  ESD_TO_PROD_CODE =? ";
	 
	String P_CHK_DULI_SETUP$C1= "SELECT  'X' FROM PM_IL_END_APPR_SETUP WHERE " +
							"(?  BETWEEN  EAS_FM_END_CODE AND EAS_TO_END_CODE" +
							"  OR  ? BETWEEN  EAS_FM_END_CODE AND EAS_TO_END_CODE" +
							"  OR  EAS_FM_END_CODE BETWEEN ?   AND ? OR  EAS_TO_END_CODE BETWEEN ? AND ?)" +
							" AND (? BETWEEN EAS_AS_FM_PROD_CODE  AND EAS_AS_TO_PROD_CODE   " +
							" OR ? BETWEEN EAS_AS_FM_PROD_CODE  AND EAS_AS_TO_PROD_CODE  " +
							" OR EAS_AS_FM_PROD_CODE BETWEEN ? AND ?  OR EAS_AS_TO_PROD_CODE BETWEEN ? AND ?) " +
							" AND  EAS_AS_USER_ID  =? " ;
							
	String P_CHK_DUPL_END_SETUP$C1= "SELECT  'X' FROM PM_IL_END_APPR_SETUP WHERE " +
						"(?  BETWEEN  EAS_FM_END_CODE AND EAS_TO_END_CODE" +
						"  OR  ? BETWEEN  EAS_FM_END_CODE AND EAS_TO_END_CODE" +
						"  OR  EAS_FM_END_CODE BETWEEN ?   AND ? OR  EAS_TO_END_CODE BETWEEN ? AND ?)" +
						" AND (? BETWEEN EAS_AS_FM_PROD_CODE  AND EAS_AS_TO_PROD_CODE   " +
						" OR ? BETWEEN EAS_AS_FM_PROD_CODE  AND EAS_AS_TO_PROD_CODE  " +
						" OR EAS_AS_FM_PROD_CODE BETWEEN ? AND ?  OR EAS_AS_TO_PROD_CODE BETWEEN ? AND ?) " +
						" AND  EAS_AS_USER_ID  =?" ;
	
	
	/* [BugId:PREMIAGDC-000069 Deepika 25-Feb-09 Newly added constant for requerying the Master details in copy window */
	String PM_IL_END_APPR_SETUP$MAIN_PAGE_QUERY1 = "SELECT EAS_AS_USER_ID, EAS_AS_FM_PROD_CODE, EAS_AS_TO_PROD_CODE, EAS_END_PROC_YN, " +
	"EAS_END_APPR_YN, EAS_CR_DT, EAS_CR_UID, EAS_UPD_DT, EAS_UPD_UID, EAS_FM_END_CODE, " +
	"EAS_TO_END_CODE,EAS_SYS_ID, ROWID FROM PM_IL_END_APPR_SETUP WHERE EAS_AS_USER_ID =?";
	/* BugId:PREMIAGDC-000069 Deepika 25-Feb-09 Newly added constant for requerying the Master details in copy window ]*/
	
}

