package com.iii.pel.forms.PILC_PROP;

public class PILC_PROP_COMPOSITE_ACTION {

	private PILC_PROP_ACTION PILC_PROP_ACTION_BEAN;
	
	public PILC_PROP_COMPOSITE_ACTION()
	{
		PILC_PROP_ACTION_BEAN = new PILC_PROP_ACTION();
		PILC_PROP_ACTION_BEAN.compositeAction = this;
	}

	public PILC_PROP_ACTION getPILC_PROP_ACTION_BEAN() {
		return PILC_PROP_ACTION_BEAN;
	}

	public void setPILC_PROP_ACTION_BEAN(PILC_PROP_ACTION pILC_PROP_ACTION_BEAN) {
		PILC_PROP_ACTION_BEAN = pILC_PROP_ACTION_BEAN;
	}
}
