package com.iii.pel.forms.PILT023;

public class PILT023_COMPOSITE_ACTION {

	//private PILT023_MEDICAL_CLINIC_PAYMENTS_ACTION PILT023_ACTION_BEAN;
	private PILT023_MEDICAL_CLINIC_PAYMENTS_ACTION PILT023_MEDICAL_CLINIC_PAYMENTS_ACTION_BEAN;
	
	private PILT023_PAYMENT_QUERY_ACTION PILT023_PAYMENT_QUERY_ACTION_BEAN;
	
	private PT_IL_MEDEX_FEE_DTL PT_IL_MEDEX_FEE_DTL_BEAN;
	
	private PV_IL_MEDEX_DOC_DTL PV_IL_MEDEX_DOC_DTL_BEAN;
	
	private DUMMY DUMMY_BEAN;
	
	
	


	public PT_IL_MEDEX_FEE_DTL getPT_IL_MEDEX_FEE_DTL_BEAN() {
		return PT_IL_MEDEX_FEE_DTL_BEAN;
	}


	public void setPT_IL_MEDEX_FEE_DTL_BEAN(
			PT_IL_MEDEX_FEE_DTL pT_IL_MEDEX_FEE_DTL_BEAN) {
		PT_IL_MEDEX_FEE_DTL_BEAN = pT_IL_MEDEX_FEE_DTL_BEAN;
	}


	public PV_IL_MEDEX_DOC_DTL getPV_IL_MEDEX_DOC_DTL_BEAN() {
		return PV_IL_MEDEX_DOC_DTL_BEAN;
	}


	public void setPV_IL_MEDEX_DOC_DTL_BEAN(
			PV_IL_MEDEX_DOC_DTL pV_IL_MEDEX_DOC_DTL_BEAN) {
		PV_IL_MEDEX_DOC_DTL_BEAN = pV_IL_MEDEX_DOC_DTL_BEAN;
	}

	public DUMMY getDUMMY_BEAN() {
		return DUMMY_BEAN;
	}


	public void setDUMMY_BEAN(DUMMY dUMMY_BEAN) {
		DUMMY_BEAN = dUMMY_BEAN;
	}

	

	public PILT023_MEDICAL_CLINIC_PAYMENTS_ACTION getPILT023_MEDICAL_CLINIC_PAYMENTS_ACTION_BEAN() {
		return PILT023_MEDICAL_CLINIC_PAYMENTS_ACTION_BEAN;
	}


	public void setPILT023_MEDICAL_CLINIC_PAYMENTS_ACTION_BEAN(
			PILT023_MEDICAL_CLINIC_PAYMENTS_ACTION pILT023_MEDICAL_CLINIC_PAYMENTS_ACTION_BEAN) {
		PILT023_MEDICAL_CLINIC_PAYMENTS_ACTION_BEAN = pILT023_MEDICAL_CLINIC_PAYMENTS_ACTION_BEAN;
	}
	
	


	public PILT023_PAYMENT_QUERY_ACTION getPILT023_PAYMENT_QUERY_ACTION_BEAN() {
		return PILT023_PAYMENT_QUERY_ACTION_BEAN;
	}


	public void setPILT023_PAYMENT_QUERY_ACTION_BEAN(
			PILT023_PAYMENT_QUERY_ACTION pILT023_PAYMENT_QUERY_ACTION_BEAN) {
		PILT023_PAYMENT_QUERY_ACTION_BEAN = pILT023_PAYMENT_QUERY_ACTION_BEAN;
	}


	public PILT023_COMPOSITE_ACTION() {
		// TODO Auto-generated constructor stub
		PILT023_MEDICAL_CLINIC_PAYMENTS_ACTION_BEAN = new PILT023_MEDICAL_CLINIC_PAYMENTS_ACTION();
		PILT023_MEDICAL_CLINIC_PAYMENTS_ACTION_BEAN.compositeAction=this;
		PILT023_PAYMENT_QUERY_ACTION_BEAN = new PILT023_PAYMENT_QUERY_ACTION();
		PILT023_PAYMENT_QUERY_ACTION_BEAN.compositeAction=this;
		PT_IL_MEDEX_FEE_DTL_BEAN = new PT_IL_MEDEX_FEE_DTL();
	}
	
}
