package com.iii.pel.forms.PILM043;

public interface PM_IL_RI_POOL_SETUP_CONSTANTS {
	
	String PILM043$PM_IL_RI_POOL_SETUP$SEARCH_PAGE = "SELECT RPS_CODE, RPS_DESC, ROWID FROM PM_IL_RI_POOL_SETUP";
	String PILM043$PM_IL_RI_POOL_SETUP$SEARCH_PAGE_TO_MAIN_PAGE = "SELECT RPS_CODE,RPS_DESC,RPS_SHORT_DESC,RPS_LONG_DESC,RPS_BL_DESC,RPS_BL_SHORT_DESC,RPS_BL_LONG_DESC,RPS_EFF_FM_DT,RPS_EFF_TO_DT,RPS_CR_DT,RPS_CR_UID,RPS_UPD_DT,RPS_UPD_UID, ROWID FROM PM_IL_RI_POOL_SETUP WHERE ROWID = ?";
	String PILM043$PM_IL_RI_POOL_SETUP$RPS_CODE = "SELECT 'X' FROM PM_IL_RI_POOL_SETUP WHERE RPS_CODE = ?";
	String PILM043$PM_IL_RI_POOL_SETUP$RPCVR_CODE$LOV1 = "SELECT COVER_CODE, COVER_DESC FROM PM_IL_COVER WHERE COVER_FRZ_FLAG = 'N'";
	String PILM043$PM_IL_RI_POOL_SETUP$RPCVR_CODE$LOV2 = "SELECT COVER_CODE, COVER_DESC FROM PM_IL_COVER WHERE COVER_FRZ_FLAG = 'N' AND COVER_CODE LIKE ?";
	String PILM043$PM_IL_RI_POOL_SETUP$RPCVR_CODE = "SELECT 'X' FROM PM_IL_RI_POOL_COVER WHERE  RPCVR_CODE = ? AND RPCVR_RPS_CODE = ?"; 
	String PILM043$PM_IL_RI_POOL_SETUP$RPCVR_CODE_UPDATE = "SELECT count(RPCVR_CODE) CNT FROM PM_IL_RI_POOL_COVER WHERE  RPCVR_CODE = ? AND RPCVR_RPS_CODE = ?"; 
	String PILM043$PM_IL_RI_POOL_SETUP$RPCUST_CODE$LOV1 = "SELECT CUST_CODE, CUST_NAME FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM WHERE INSTR(PS_CODE_DESC, '''' || DECODE(PS_VALUE, 2, CCLAS_CODE, CCLAS_TYPE) || '''') <> 0 AND PS_CODE = 'REINS' AND PS_TYPE = 'LOV_CUST') AND CUST_FRZ_FLAG = 'N' AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM PM_CUST_DIVN WHERE CDIV_DIVN_CODE = NVL (?, CDIV_DIVN_CODE) AND NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'N')) OR (NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'Y'))AND ROWNUM <= 21";
	String PILM043$PM_IL_RI_POOL_SETUP$RPCUST_CODE$LOV2 = "SELECT CUST_CODE, CUST_NAME FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM WHERE INSTR(PS_CODE_DESC, '''' || DECODE(PS_VALUE, 2, CCLAS_CODE, CCLAS_TYPE) || '''') <> 0 AND PS_CODE = 'REINS' AND PS_TYPE = 'LOV_CUST') AND CUST_FRZ_FLAG = 'N' AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM PM_CUST_DIVN WHERE CDIV_DIVN_CODE = NVL (?, CDIV_DIVN_CODE) AND NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'N')) OR (NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'Y'))AND ROWNUM <= 21 AND CUST_CODE LIKE ?";
	String PILM043$PM_IL_RI_POOL_SETUP$COMP_RCC_CHRG_CODE$LOV1 = "SELECT PC_CODE, PC_DESC FROM PM_CODES WHERE PC_TYPE ='IL_CHARGE' AND PC_RI_APPL_YN='Y'";
	String PILM043$PM_IL_RI_POOL_SETUP$COMP_RCC_CHRG_CODE$LOV2 = "SELECT PC_CODE, PC_DESC FROM PM_CODES WHERE PC_TYPE ='IL_CHARGE' AND PC_RI_APPL_YN='Y' AND PC_CODE LIKE ?";
	String PILM043$PM_IL_RI_POOL_SETUP$FETCH_COVER_DETAILS = "SELECT RPCVR_CR_DT,RPCVR_CR_UID,RPCVR_UPD_DT,RPCVR_UPD_UID,RPCVR_CODE,RPCVR_SHARE_PERC,ROWID FROM PM_IL_RI_POOL_COVER WHERE RPCVR_RPS_CODE = ?";
	String PILM043$PM_IL_RI_POOL_SETUP$FETCH_CUSTOMER_DETAILS = "SELECT RPCUST_RPS_CODE,RPCUST_RPCVR_CODE,RPCUST_CODE,RPCUST_SHARE_PERC,RPCUST_NEW_COMM,RPCUST_REN_COMM,RPCUST_NEW_TAX,RPCUST_REN_TAX,RPCUST_RETRO_SHARE_PERC,RPCUST_RETRO_NEW_COMM,RPCUST_RETRO_REN_COMM,RPCUST_RETRO_NEW_TAX,RPCUST_RETRO_REN_TAX,RPCUST_CR_DT,RPCUST_CR_UID,RPCUST_UPD_DT,RPCUST_UPD_UID,ROWID FROM PM_IL_RI_POOL_CUST WHERE RPCUST_RPS_CODE = ? AND RPCUST_RPCVR_CODE = ?";
	String PILM043$PM_IL_RI_POOL_SETUP$FETCH_CHARGE_DETAILS = "SELECT RCC_RPS_CODE,RCC_RPCVR_CODE,RCC_RPCUST_CODE,RCC_SRNO,RCC_CHRG_TYPE,RCC_CHRG_CODE,RCC_RATE,RCC_RATE_PER,RCC_APPLY_PERIOD,RCC_CUST_SHARE_PERC,RCC_CR_DT,RCC_CR_UID,RCC_UPD_DT,RCC_UPD_UID,ROWID FROM PM_IL_RI_CUST_CHRG WHERE RCC_RPS_CODE = ? AND RCC_RPCVR_CODE = ? AND RCC_RPCUST_CODE = ?";
	String PILM043$PM_IL_RI_POOL_SETUP$RPCUST_CODE = "SELECT RPCUST_CODE FROM PM_IL_RI_POOL_CUST WHERE RPCUST_RPS_CODE = ? AND RPCUST_RPCVR_CODE = ?"; 
	String PILM043$PM_IL_RI_POOL_SETUP$RPCUST_CODE_UPDATE = "SELECT count(RPCUST_CODE) CNT FROM PM_IL_RI_POOL_CUST WHERE RPCUST_RPS_CODE = ? AND RPCUST_RPCVR_CODE = ? AND RPCUST_CODE= ?";
	String PILM043$PM_IL_RI_POOL_SETUP$DELETE_PM_IL_RI_CUST_CHRG = "DELETE FROM PM_IL_RI_CUST_CHRG WHERE RCC_RPS_CODE = ?";
	String PILM043$PM_IL_RI_POOL_SETUP$DELETE_PM_IL_RI_POOL_COVER = "DELETE FROM PM_IL_RI_POOL_COVER WHERE RPCVR_RPS_CODE = ?";
	String PILM043$PM_IL_RI_POOL_SETUP$DELETE_PM_IL_RI_POOL_CUST = "DELETE FROM PM_IL_RI_POOL_CUST WHERE RPCUST_RPS_CODE = ?";
	String PILM043$PM_IL_RI_POOL_SETUP$DELETE_PM_IL_RI_POOL_SETUP = "DELETE FROM PM_IL_RI_POOL_SETUP WHERE RPS_CODE = ?";
}
