package com.iii.pel.forms.PILM036;

public interface Constants {
//:GLOBAL.M_MODULE_NAME=GET_FORM_PROPERTY.GET_FORM_PROPERTY(GET_APPLICATION_PROPERTY.GET_APPLICATION_PROPERTY(CURRENT_FORM_NAME),FORM_NAME);
	String M_PRIVILEGE="YYY";
	String M_FAILURE="FALSE";
	String M_USER_ID="LIFEALL";
	String M_NAME="COMPANY NAME..................PROGRAM NAME";
	String M_LANG_CODE="ENG";
	String M_PARA_1=" ";
	String M_FOR_LANG_CODE="ARBR1";
	String M_MODULE_NAME = "";
}
