package com.iii.pel.forms.PILP014_A;

public interface SQLQueryInterface {
	
	DUMMY_ACTION DUMMY_BEAN = new DUMMY_ACTION();
	
	public String sql_C1A="SELECT DISTINCT RS_REPORT_NAME FROM  PW_IL_REMINDER_SUMMARY WHERE RS_REPORT_NAME IS NOT NULL AND RS_POL_SYS_ID IN(SELECT POL_SYS_ID FROM PT_IL_POLICY WHERE POL_PLAN_CODE IN(SELECT PLAN_CODE FROM PM_IL_PLAN WHERE PLAN_TYPE <>'M') AND POL_NO BETWEEN ? AND ?)GROUP BY RS_REPORT_NAME";
	
	public String sql_C1="SELECT DISTINCT RS_REPORT_NAME,RS_POL_SYS_ID FROM  PW_IL_REMINDER_SUMMARY  WHERE  RS_POL_SYS_ID  IN  (   SELECT POL_SYS_ID  FROM  PT_IL_POLICY   WHERE  POL_PLAN_CODE  IN   (    SELECT PLAN_CODE   FROM  PM_IL_PLAN    WHERE  PLAN_TYPE  <> 'M'   )   AND POL_NO  BETWEEN ? AND ? AND RS_REPORT_NAME  = ?";
	
	public String sql_C9="SELECT DSRC_SYS_ID.NEXTVAL FROM DUAL";
	
	public String sql_dummy1="INSERT INTO PS_IL_REMINDER_SUMMARY SELECT * FROM PW_IL_REMINDER_SUMMARY WHERE RS_REPORT_NAME = ? AND RS_POL_SYS_ID =?";
	
	public String sql_dummy2="DELETE PW_IL_REMINDER_SUMMARY WHERE RS_REPORT_NAME = ? AND RS_POL_SYS_ID = ?";

	public String sql_dummy3="DELETE PW_IL_DATA_SOURCE WHERE DSRC_SYS_ID = ?";
	
	public String sql_dummy4="DELETE FROM PW_IL_DATA_SOURCE";
	
	public String sql_dummy5="DELETE FROM PW_IL_REMINDER_SUMMARY";
}

