package com.iii.pel.forms.PILQ_AGI;

public class PILQ_AGI_COMPOSITE_ACTION {
	private AGENT_INCENTIVES_ACTION AGENT_INCENTIVES_ACTION_BEAN;

	public PILQ_AGI_COMPOSITE_ACTION() {
		AGENT_INCENTIVES_ACTION_BEAN = new AGENT_INCENTIVES_ACTION();

		AGENT_INCENTIVES_ACTION_BEAN.compositeAction = this;
	}

	public AGENT_INCENTIVES_ACTION getAGENT_INCENTIVES_ACTION_BEAN() {
		return AGENT_INCENTIVES_ACTION_BEAN;
	}

	public void setAGENT_INCENTIVES_ACTION_BEAN(
			AGENT_INCENTIVES_ACTION agent_incentives_action_bean) {
		AGENT_INCENTIVES_ACTION_BEAN = agent_incentives_action_bean;
	}

}
