package com.iii.pel.forms.PILP078;

public class PILP078_COMPOSITE_ACTION {
	
	private INTERNAL_TRANSFER_ACTION INTERNAL_TRANSFER_ACTION_BEAN;
	
	public INTERNAL_TRANSFER_ACTION getINTERNAL_TRANSFER_ACTION_BEAN() {
		return INTERNAL_TRANSFER_ACTION_BEAN;
	}
	public void setINTERNAL_TRANSFER_ACTION_BEAN(
			INTERNAL_TRANSFER_ACTION iNTERNAL_TRANSFER_ACTION_BEAN) {
		INTERNAL_TRANSFER_ACTION_BEAN = iNTERNAL_TRANSFER_ACTION_BEAN;
	}
	
	public PILP078_COMPOSITE_ACTION(){
		
		INTERNAL_TRANSFER_ACTION_BEAN = new INTERNAL_TRANSFER_ACTION();
		INTERNAL_TRANSFER_ACTION_BEAN.compositeAction = this;
	}
	
}
