package com.iii.pel.forms.PILM037;

public interface PILM037_SQLQUERY_CONSTANTS {
	
	String PM_IL_PLAN_LOV = "SELECT PLAN_CODE,COVER_DESC FROM PM_IL_PLAN,PM_IL_COVER" 
    +" WHERE PLAN_CODE= COVER_CODE AND PLAN_FRZ_FLAG = 'N'";
	
	String PM_IL_PLAN_LOV_1 = "SELECT PLAN_CODE,COVER_DESC FROM PM_IL_PLAN,PM_IL_COVER" 
	    +" WHERE PLAN_CODE= COVER_CODE AND PLAN_FRZ_FLAG = 'N' AND PLAN_CODE LIKE UPPER('{0}%')";
	
	String PM_IL_BONUS_SETUP_DRP_DWN = "SELECT  LIV_CODE,LIV_CODE_DESC" 
		  +" FROM PP_LIST_ITEM,PP_LIST_ITEM_VALUES WHERE LI_SYS_PARAM = LIV_SYS_PARAM"
		  +" AND LI_MODULE_NAME = '{0}' AND LI_BLOCK_NAME = '{1}'"
		  +" AND LI_ITEM_NAME = '{2}'";
	
	String PM_IL_BONUS_BSET_BONUS_LOV="SELECT BONUS_CODE,BONUS_DESC FROM PM_IL_BONUS";
	
	String PM_IL_BONUS_BSET_BONUS_LOV1="SELECT BONUS_CODE,BONUS_DESC FROM PM_IL_BONUS"
		+" WHERE BONUS_CODE LIKE '{0}%' ";
	
	String PM_IL_BONUS_Table_Values="SELECT PLAN_CODE,BSET_BONUS_CODE,BONUS_DESC,BSET_YEAR,"+
	"BSET_RATE,BSET_RATE_PER,PM_IL_BONUS_SETUP.ROWID, BSET_CR_DT, BSET_CR_UID"+
	" FROM PM_IL_PLAN,PM_IL_BONUS_SETUP,PM_IL_BONUS,PM_IL_COVER	WHERE PLAN_CODE=BSET_PLAN_CODE"+
	" AND BSET_BONUS_CODE = BONUS_CODE AND COVER_CODE=PLAN_CODE AND PLAN_CODE='{0}'AND PLAN_FRZ_FLAG = 'N'";
	
	
	String L_DUP_CHK_q1 = "SELECT 'X' FROM PM_IL_BONUS_SETUP WHERE  BSET_PLAN_CODE = ?" +
			" AND BSET_BONUS_CODE = ? AND BSET_YEAR = ? ";
	
	String L_DUP_CHK_q2 = "SELECT 'X' FROM PM_IL_BONUS_SETUP WHERE BSET_PLAN_CODE = ?" +
			" AND BSET_BONUS_CODE = ? AND BSET_YEAR = ? AND ROWID != ?";
	
	
	
	
	String BONUSCODE_WHEN_VALIDATE_C1="SELECT MAX(BSET_YEAR) FROM  PM_IL_BONUS_SETUP"+
	" WHERE  BSET_BONUS_CODE ='{0}' AND BSET_PLAN_CODE = '{1}'";
	
	String BONUSCODE_WHEN_VALIDATE_C2="SELECT BSET_RATE_PER FROM  PM_IL_BONUS_SETUP WHERE BSET_YEAR = '{0}'"
	+" AND BSET_BONUS_CODE  = '{1}' AND BSET_PLAN_CODE ='{2}'";
	
	String BONUSCODE_WHEN_VALIDATE_C3="SELECT BONUS_TYPE FROM  PM_IL_BONUS  WHERE"
		+" BONUS_CODE = '{0}'";
	
	String BONUSCODE_WHEN_VALIDATE_C4="SELECT PLAN_TYPE FROM  PM_IL_PLAN WHERE"
		+" PLAN_CODE  = {0} ";
	
	String Procedure_L_VAL_BONUS="SELECT BONUS_DESC FROM PM_IL_BONUS WHERE " +
			"BONUS_CODE ={0} ";
	
	
	
	
		
			
		
}
