package com.iii.pel.forms.PILM037;

public interface PILM034_SQLQUERY_CONSTANTS {
	

	String PM_IL_TAR_PARAM_SelectDrpDwnValues = "SELECT  LIV_CODE,LIV_CODE_DESC"
		   +" FROM PP_LIST_ITEM,PP_LIST_ITEM_VALUES WHERE LI_SYS_PARAM = LIV_SYS_PARAM"
		   +" AND LI_MODULE_NAME = '{0}' AND LI_BLOCK_NAME = '{1}' AND LI_ITEM_NAME = '{2}'";
	
	String PM_IL_TAR_HDR_SelectCaptionValues = "SELECT TP_SRNO,TP_CAPTION, ROWID FROM PM_IL_TAR_PARAM";
	

	String PM_IL_TAR_PARAM_SelectTableValues ="SELECT TP_SRNO, TP_CAPTION, TP_BL_CAPTION,"
		   +" TP_DATA_TYPE, TP_TABLE_NAME, TP_COL_NAME, TP_WHERE_CLAUSE, ROWID FROM PM_IL_TAR_PARAM";
		   			
	String PM_IL_TAR_HDR_SelectThParameterListValues="SELECT TP_CAPTION,ROWID FROM PM_IL_TAR_PARAM";
	
	String PM_IL_TAR_HDR_SelectParameterTypeValues="SELECT LIV_CODE,LIV_CODE_DESC FROM PP_LIST_ITEM_VALUES WHERE LIV_SYS_PARAM='IL_TAR_TYP'";
	
	String PM_IL_TAR_HDR_SelectParameterType1=" SELECT LIV_CODE,LIV_CODE_DESC"
								+" FROM PP_LIST_ITEM_VALUES WHERE LIV_SYS_PARAM='IL_TAR_TYP' AND"
								+" LIV_CODE LIKE'{0}%'";
	
	String PM_IL_TAR_HDR_SelectThCodeList="SELECT TH_CODE FROM PM_IL_TAR_HDR,"
		+"PP_LIST_ITEM_VALUES WHERE PP_LIST_ITEM_VALUES.LIV_CODE=PM_IL_TAR_HDR.TH_PARAM_TYPE"
		+" AND PP_LIST_ITEM_VALUES.LIV_CODE='{0}'";
	
	String PM_IL_TAR_HDR_SelectThCodeList1="SELECT  TH_CODE FROM PM_IL_TAR_HDR,"
		+"PP_LIST_ITEM_VALUES WHERE PP_LIST_ITEM_VALUES.LIV_CODE=PM_IL_TAR_HDR.TH_PARAM_TYPE"
		+" AND PP_LIST_ITEM_VALUES.LIV_CODE='{0}' AND TH_CODE LIKE '{1}%'";
	
	String PM_IL_TAR_HDR_SelectValues="SELECT TH_DESC,TH_BL_DESC,TH_RATE_PER,TH_PARA_01,"
		+"TH_PARA_02,TH_PARA_03,TH_PARA_04,TH_PARA_05,TH_PARA_06,TH_PARA_07,TH_PARA_08,"
		+"TH_PARA_09,TH_PARA_10,TH_EFF_FM_DT,TH_EFF_TO_DT FROM PM_IL_TAR_HDR,PP_LIST_ITEM_VALUES"
		+" WHERE PP_LIST_ITEM_VALUES.LIV_CODE=PM_IL_TAR_HDR.TH_PARAM_TYPE AND"
		+" PP_LIST_ITEM_VALUES.LIV_CODE='{0}' AND TH_CODE='{1}'";
	
	String PM_IL_TAR_HDR_SelectValuesForParamter="SELECT LIV_CODE_DESC,TH_CODE,TH_DESC,TH_BL_DESC,TH_RATE_PER,TH_PARA_01,"
		+"TH_PARA_02,TH_PARA_03,TH_PARA_04,TH_PARA_05,TH_PARA_06,TH_PARA_07,TH_PARA_08,"
		+"TH_PARA_09,TH_PARA_10,TH_EFF_FM_DT,TH_EFF_TO_DT FROM PM_IL_TAR_HDR,PP_LIST_ITEM_VALUES"
		+" WHERE PP_LIST_ITEM_VALUES.LIV_CODE=PM_IL_TAR_HDR.TH_PARAM_TYPE AND"
		+" PP_LIST_ITEM_VALUES.LIV_CODE='{0}'"; 
				// AND TH_CODE='{1}'";

			


}
