package com.iii.pel.forms.PM091_A;

public interface PM_AGENT_BENEFIT_QUERY_CONSTANTS {

	String PM_AGENT_BENEFIT_DTL_DUP_CHECK_QUERY1=" SELECT ROWID  FROM  PM_AGENT_BENEFIT_DTL" +
			" WHERE ABD_ABH_BNF_CODE	= ? AND " +
			" ABD_BNF_FREQ	 = ?" +
			" AND   ABD_PROD_TYPE  = ?  AND" +
			"  (((? BETWEEN ABD_LC_FYC_FM AND ABD_LC_FYC_TO) OR (? BETWEEN ABD_LC_FYC_FM  AND ABD_LC_FYC_TO)) OR" +
			"  ((ABD_LC_FYC_FM  BETWEEN ?  AND ?) OR (ABD_LC_FYC_TO BETWEEN ? AND ?)))" +
			"  AND (((? BETWEEN ABD_NO_OF_POL_FM AND ABD_NO_OF_POL_TO) OR (? BETWEEN ABD_NO_OF_POL_FM AND ABD_NO_OF_POL_TO)) OR" +
			" ((ABD_NO_OF_POL_FM BETWEEN ? AND ?) OR (ABD_NO_OF_POL_TO BETWEEN ? AND ?)))";
	
	String PM_AGENT_BENEFIT_DTL_DUP_CHECK_QUERY2=" SELECT 'X'  FROM  PM_AGENT_BENEFIT_DTL" +
	" WHERE ABD_ABH_BNF_CODE	= ? AND " +
	" ABD_BNF_FREQ	 = ?" +
	" AND   ABD_PROD_TYPE  = ?  AND" +
	"  (((? BETWEEN ABD_LC_FYC_FM AND ABD_LC_FYC_TO) OR (? BETWEEN ABD_LC_FYC_FM  AND ABD_LC_FYC_TO)) OR" +
	"  ((ABD_LC_FYC_FM  BETWEEN ?  AND ?) OR (ABD_LC_FYC_TO BETWEEN ? AND ?)))" +
	"  AND (((? BETWEEN ABD_NO_OF_POL_FM AND ABD_NO_OF_POL_TO) OR (? BETWEEN ABD_NO_OF_POL_FM AND ABD_NO_OF_POL_TO)) OR" +
	" ((ABD_NO_OF_POL_FM BETWEEN ? AND ?) OR (ABD_NO_OF_POL_TO BETWEEN ? AND ?))) AND    ROWID  != ?";
	
}
