package com.iii.pel.forms.PILM013_APAC;

public interface PM_IL_DOC_MED_HIST_CONSTANTS {

	String FORM_NAME_DOCUMENT_SETUP = "PILM013_APAC";

	String BLOCK_NAME_PM_IL_DOC_MED_HIST = "PM_IL_DOC_MED_HIST";

	/* LI Item name */
	String ITEM_NAME_DMH_DATA_TYPE = "PM_IL_DOC_MED_HIST.DMH_DATA_TYPE";

	String ITEM_NAME_DMH_MANDAORY_YN = "PM_IL_DOC_MED_HIST.DMH_MANDATORY_YN";

	/* LI System parameter */
	String LI_SYS_PARAM_DMH_DATA_TYPE = "IL_DAT_TYP";

	String LI_SYS_PARAM_DMH_MANDATORY_YN = "YESNO";

	String DEFAULT_DMH_DATATYPE = "C";

	String DEFAULT_DMH_MANDATORY_YN = "N";
}
