package com.iii.pel.forms.PILM013_APAC;

public interface PM_IL_DOC_NO_RANGE_CONSTANTS {
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$POST_QUERY="SELECT LAST_NUMBER FROM  USER_SEQUENCES  WHERE  SEQUENCE_NAME  = ?";
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$LEVEL1_001="Branch";
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$LEVEL1_002="Class";
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$LEVEL1_003="Plan";
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$LEVEL1_004="UW Year";
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$LEVEL1_005="Document Code";
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$LEVEL1_008="Claim Month";
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$LEVEL1_009="Claim Year";
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$LEVEL1_006="Calendar Year";
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$LEVEL1_007="Claim Type";
	String PILM013_APAC$PM_IL_DOC_NO_RANGE$LEVEL1_010="Product";
	
	String MSG$PILM013_APAC = "PILM013_APAC";
	String PILM013_APAC$PM_IL_DOC_SETUP$DOC_NO_RANGE="PM_IL_DOC_NO_RANGE";
	String PILM013_APAC$PM_IL_DOC_SETUP$DNR_DISABLE_YN="PM_IL_DOC_NO_RANGE.DNR_DISABLE_YN";

}
