package com.iii.pel.forms.PILM013_APAC;

public interface PM_IL_DOC_REMINDERS_CONSTANTS {

	String PILM013_APAC$PM_IL_DOC_REMINDERS$L_DUP_REMINDER_NO$QUERY1="SELECT 'X' FROM   PM_IL_DOC_REMINDERS" +
			" WHERE  DR_STATUS_CODE    = ?  AND    DR_REMINDER_NO    = ? AND    DR_REMINDER_TYPE  = ?  " +
			"AND  DR_DS_CODE = ?  AND  DR_DS_TYPE = ?";
	String PILM013_APAC$PM_IL_DOC_REMINDERS$L_DUP_REMINDER_NO$QUERY2="SELECT 'X' FROM   PM_IL_DOC_REMINDERS" +
			" WHERE  DR_STATUS_CODE    = ?  AND    DR_REMINDER_NO    = ? AND    DR_REMINDER_TYPE  = ?  AND  DR_DS_CODE  = ?" +
			"  AND DR_DS_TYPE  = ?   AND    ROWID   <> ?";
	
	
	String PILM013_APAC$PM_IL_DOC_SETUP$BLOCK_NAME$PM_IL_DOC_REMINDERS="PM_IL_DOC_REMINDERS";
	String PILM013_APAC$PM_IL_DOC_SETUP$FIELD_NAME$DR_REMINDER_TYPE="PM_IL_DOC_REMINDERS.DR_REMINDER_TYPE";
	String PILM013_APAC$PM_IL_DOC_SETUP$COMBO_BOX$QUERY="SELECT LIV_CODE,LIV_CODE_DESC FROM PP_LIST_ITEM,PP_LIST_ITEM_VALUES WHERE LI_SYS_PARAM = LIV_SYS_PARAM AND LI_MODULE_NAME = ? AND LI_BLOCK_NAME = ? AND LI_ITEM_NAME = ?";
	String PILM013_APAC$PM_IL_DOC_SETUP$DOCUMENT_REMINDER$REPORT_CODE$LOV1="SELECT PC_CODE, PC_DESC FROM PM_CODES WHERE PC_TYPE = 'IL_REMIN_RPT' AND NVL(PC_FRZ_FLAG,'N') = 'N'";
	String PILM013_APAC$PM_IL_DOC_SETUP$DOCUMENT_REMINDER$REPORT_CODE$LOV2="SELECT PC_CODE, PC_DESC FROM PM_CODES WHERE PC_TYPE = 'IL_REMIN_RPT' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND PC_CODE LIKE ?";
	String PILM013_APAC$PM_IL_DOC_SETUP$DOCUMENT_REMINDER$STATUS_CODE$LOV1="SELECT PS_CODE, PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_ADDL_STAT' AND PS_VALUE LIKE '1'";
	String PILM013_APAC$PM_IL_DOC_SETUP$DOCUMENT_REMINDER$STATUS_CODE$LOV2="SELECT PS_CODE, PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_ADDL_STAT' AND PS_VALUE LIKE '1' AND PS_CODE LIKE ?";
}
