package com.iii.pel.forms.PILM013_APAC;

public interface PM_IL_DOC_TODO_GROUP_CONSTANTS {

	String PILM013_APAC$PM_IL_DOC_SETUP$FIELD_NAME$DTG_RESULT="PM_IL_DOC_TODO_GROUP.DTG_RESULT";
	String PILM013_APAC$PM_IL_DOC_SETUP$DOCUMENT_TODO_GROUP_ACTION$GROUP_TYPE$LOV1="SELECT PS_CODE, PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_TODO_GRP'";
	String PILM013_APAC$PM_IL_DOC_SETUP$DOCUMENT_TODO_GROUP_ACTION$GROUP_TYPE$LOV2="SELECT PS_CODE, PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_TODO_GRP'AND PS_CODE LIKE ?";
	/** [ BugId:PREMIAGDC-0065 Mallika 25-Feb-09 Details fetch query where condition changed*/
	
	/*Modified by saritha on 11-07-2017 for ssp call id ZBILQC-1719714*/
	String PILM013_APAC$PM_IL_DOC_SETUP$DOCUMENT_TODO_LIST_ACTION="SELECT ROWID,DTL_DS_TYPE,DTL_DS_CODE,DTL_SR_NO," +
			"DTL_CLAIM_TYPE,DTL_TODO_LIST_ITEM, DTL_MANDATORY_YN,DTL_EFF_FM_DT,DTL_EFF_TO_DT," +
			"DTL_CR_DT,DTL_CR_UID,DTL_UPD_DT,DTL_UPD_UID,DTL_DTG_GROUP_CODE,DTL_DEFAULT_YN,DTL_SA_FROM,DTL_SA_TO,DTL_PROD_CODE " +
			"FROM PM_IL_DOC_TODO_LIST WHERE DTL_DTG_GROUP_CODE = ? AND DTL_DS_TYPE = ? " +
			"AND DTL_DS_CODE = ? ";
	/*End*/
	
	/**  BugId:PREMIAGDC-0065 Mallika 25-Feb-09 Details fetch query where condition changed ]*/
	
	String PILM013_APAC$PM_IL_DOC_SETUP$BLOCK_NAME$PM_IL_DOC_TODO_GROUP="PM_IL_DOC_TODO_GROUP";
	String PILM013_APAC$PM_IL_DOC_SETUP$BLOCK_NAME$PM_IL_DOC_TODO_LIST="PM_IL_DOC_TODO_LIST";
	String PILM013_APAC$PM_IL_DOC_SETUP$COMBO_BOX$QUERY="SELECT LIV_CODE,LIV_CODE_DESC FROM PP_LIST_ITEM,PP_LIST_ITEM_VALUES WHERE LI_SYS_PARAM = LIV_SYS_PARAM AND LI_MODULE_NAME= ? AND LI_BLOCK_NAME = ? AND LI_ITEM_NAME = ?";
}
