package com.iii.pel.forms.PILM013_APAC;

public interface PM_IL_DOC_TODO_LIST_CONSTANTS {

	String PILM013_APAC$PM_IL_DOC_TODO_LIST$POST_DELETE="UPDATE   PM_IL_DOC_TODO_LIST    SET DTL_SR_NO = DTL_SR_NO  WHERE  DTL_SR_NO  > ?  AND DTL_DS_TYPE  = ?  AND DTL_DS_CODE  = ?";
	String PILM013_APAC$PM_IL_DOC_SETUP$BLOCK_NAME$PM_IL_DOC_TODO_LIST="PM_IL_DOC_TODO_LIST";
	String PILM013_APAC$PM_IL_DOC_SETUP$FIELD_NAME$DTL_CLAIM_TYPE="PM_IL_DOC_TODO_LIST.DTL_CLAIM_TYPE";
	String PILM013_APAC$PM_IL_DOC_SETUP$FIELD_NAME$DTL_MANDATORY_YN="PM_IL_DOC_TODO_LIST.DTL_MANDATORY_YN";
	String PILM013_APAC$PM_IL_DOC_SETUP$FIELD_NAME$DTL_DEFAULT_YN="PM_IL_DOC_TODO_LIST.DTL_DEFAULT_YN";
}
