package com.iii.pel.utils;

public interface REPORT_UTIL_CONSTANTS {
	
	String IP_REP_INFO_REP_KEY_NO_SEQUENCE="SELECT SEQ_REP_KEY_NO.NEXTVAL FROM DUAL";
	
	int IP_REP_INFO_ROW_NUM_TO_DIPLAY_LESS_THEN=21;
	
	String IP_REP_INFO_PERCENTILE_FOR_SELECT_LIKE="%";
	
	String SET_SECOND_FIELD_DEFAULT_ZZZZ="zzzzzz";
	
	String SET_FIRST_FIELD_DEFAULT_0="0";
	
	String IP_REP_INFO_BRANCH_CODE_LOV = "SELECT DIVN_CODE, DIVN_NAME FROM FM_DIVISION WHERE ROWNUM<? ORDER BY 1 ASC ";
	String IP_REP_INFO_BRANCH_CODE_LOV_LIKE = "SELECT DIVN_CODE,DIVN_NAME FROM FM_DIVISION WHERE DIVN_CODE LIKE ? AND ROWNUM<?  ORDER BY 1 ASC ";
	String IP_REP_INFO_DEPT_CODE_LOV="SELECT DEPT_CODE, DEPT_NAME FROM FM_DEPARTMENT WHERE ROWNUM<?  ORDER BY 1 ASC  ";
	String IP_REP_INFO_DEPT_CODE_LOV_LIKE="SELECT DEPT_CODE, DEPT_NAME FROM FM_DEPARTMENT WHERE DEPT_CODE LIKE ? AND  ROWNUM<?  ORDER BY 1 ASC ";
	String IP_REP_INFO_PLAN_CODE_LOV="SELECT PLAN_CODE,NULL FROM PM_IL_PLAN WHERE ROWNUM<?  ORDER BY 1 ASC ";
	String IP_REP_INFO_PLAN_CODE_LOV_LIKE="SELECT PLAN_CODE,NULL FROM PM_IL_PLAN WHERE PLAN_CODE LIKE ? AND ROWNUM<?  ORDER BY 1 ASC ";
	String IP_REP_INFO_CLASS_CODE_LOV="SELECT CLASS_CODE,CLASS_NAME FROM PM_IL_CLASS WHERE ROWNUM<?  ORDER BY 1 ASC ";
	String IP_REP_INFO_CLASS_CODE_LOV_LIKE="SELECT CLASS_CODE,CLASS_NAME FROM PM_IL_CLASS WHERE CLASS_CODE LIKE ? AND ROWNUM<?  ORDER BY 1 ASC ";
	String IP_REP_INFO_CURR_CODE_LOV="SELECT CURR_CODE, CURR_SHORT_NAME FROM FM_CURRENCY  ORDER BY 1 ASC ";
	String IP_REP_INFO_CURR_CODE_LOV_LIKE="SELECT CURR_CODE, CURR_SHORT_NAME FROM FM_CURRENCY WHERE CURR_CODE LIKE ?  ORDER BY 1 ASC ";
	String IP_REP_INFO_CVR_CODE_LOV = "SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE COVER_TYPE = 'A' AND ROWNUM < ? ORDER BY COVER_CODE";
	String IP_REP_INFO_CVR_CODE_LOV_LIKE = "SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE COVER_TYPE = 'A' AND COVER_CODE LIKE ? AND ROWNUM < ? ORDER BY COVER_CODE";
	
	String VALIDATE_BRANCH_CODE = "SELECT 1 FROM FM_DIVISION WHERE DIVN_CODE = ?"; 
	String VALIDATE_DEPT_CODE   = "SELECT 1 FROM FM_DEPARTMENT WHERE DEPT_CODE = ?";
	String VALIDATE_PLAN_CODE	= "SELECT 1 FROM PM_IL_PLAN WHERE PLAN_CODE = ?";
	String VALIDATE_CLASS_CODE	= "SELECT 1 FROM PM_IL_CLASS WHERE CLASS_CODE = ?";
	String VALIDATE_CURR_CODE	= "SELECT 1 FROM FM_CURRENCY WHERE CURR_CODE = ?";
	String VALIDATE_CVR_CODE	= "SELECT 1 FROM PM_IL_COVER WHERE COVER_CODE = ?";
	
	String IP_REP_INFO_POLICY_NUM_LOV="SELECT POL_NO,POL_ASSURED_NAME FROM PT_GL_POLICY WHERE ROWNUM < ? ";
	String IP_REP_INFO_POLICY_NUM_LOV_LIKE="SELECT POL_NO,POL_ASSURED_NAME FROM PT_GL_POLICY WHERE POL_NO LIKE ? AND  ROWNUM <? ";
	String IP_REP_INFO_POLICY_NUM_RECORD_CHECK="SELECT 1 FROM PT_GL_POLICY WHERE POL_NO = ? ";
	
	String IP_REP_INFO_CUST_CODE_LOV="SELECT CUST_CODE,DECODE(?,'ENG',CUST_NAME,CUST_BL_NAME)"+ 
			" FROM FM_CUSTOMER WHERE CUST_FRZ_FLAG = 'N' AND ROWNUM < ? ";
	String IP_REP_INFO_CUST_CODE_LOV_LIKE="SELECT CUST_CODE,DECODE(?,'ENG',CUST_NAME,CUST_BL_NAME)"+ 
			" FROM FM_CUSTOMER WHERE CUST_FRZ_FLAG = 'N' AND CUST_CODE LIKE ? AND  ROWNUM <? ";
	String IP_REP_INFO_CUST_CODE_RECORD_CHECK="	SELECT 1 FROM FM_CUSTOMER WHERE CUST_FRZ_FLAG = 'N' AND CUST_CODE = ? ";
	
	String IP_REP_INFO_EMP_CODE_LOV =  "SELECT  PEMP_ID,PEMP_NAME  FROM PT_GL_POL_EMPLOYEE  WHERE ROWNUM<?  ";
	String IP_REP_INFO_EMP_CODE_LOV_LIKE = "SELECT  PEMP_ID,PEMP_NAME  FROM PT_GL_POL_EMPLOYEE WHERE PEMP_ID LIKE ?  AND ROWNUM<?  "; 
	String IP_REP_INFO_EMP_NUM_RECORD_CHECK="SELECT 1 FROM   PT_GL_POL_EMPLOYEE WHERE PEMP_ID=?";
	
	String IP_REP_INFO_CLASS_CODE_RECORD_CHECK= "SELECT 1 FROM PM_IL_CLASS WHERE CLASS_CODE = ?";
	
	String IP_REP_INFO_PLAN_TYPE_LOV="SELECT PLAN_TYPE,NULL FROM PM_IL_PLAN WHERE ROWNUM<?";
	String IP_REP_INFO_PLAN_TYPE_LOV_LIKE="SELECT PLAN_TYPE,NULL FROM PM_IL_PLAN WHERE PLAN_TYPE LIKE ? AND ROWNUM<?";
	String IP_REP_INFO_PLAN_TYPE_RECORD_CHECK="SELECT 1 FROM PM_IL_PLAN WHERE PLAN_TYPE=?  ";

	String IP_REP_INFO_BROKER_CODE_LOV =  "SELECT CUST_CODE, CUST_NAME FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM WHERE INSTR(PS_CODE_DESC,'''' || DECODE(PS_VALUE, 2, CCLAS_CODE, CCLAS_TYPE) || '''') <> 0 AND PS_CODE = 'IL_BROKER' AND PS_TYPE = 'LOV_CUST') AND CUST_FRZ_FLAG = 'N' AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM PM_CUST_DIVN WHERE CDIV_DIVN_CODE = ? AND NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'N')) OR (NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'Y')) AND ROWNUM < ? ORDER BY 1 ASC ";
	String IP_REP_INFO_BROKER_CODE_LOV_LIKE = "SELECT CUST_CODE, CUST_NAME FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM WHERE INSTR(PS_CODE_DESC,'''' || DECODE(PS_VALUE, 2, CCLAS_CODE, CCLAS_TYPE) || '''') <> 0 AND PS_CODE = 'IL_BROKER' AND PS_TYPE = 'LOV_CUST') AND CUST_FRZ_FLAG = 'N' AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM PM_CUST_DIVN WHERE CDIV_DIVN_CODE = ? AND NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'N')) OR (NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'Y')) AND CUST_CODE LIKE ? AND ROWNUM < ? ORDER BY 1 ASC "; 
	String IP_REP_INFO_BROKER_RECORD_CHECK="SELECT 1 FROM PM_CUSTOMER WHERE CUST_CLASS IN (SELECT CCLAS_CODE FROM PM_CUST_CLASS, PP_SYSTEM WHERE INSTR(PS_CODE_DESC,'''' || DECODE(PS_VALUE, 2, CCLAS_CODE, CCLAS_TYPE) || '''') <> 0 AND PS_CODE = 'IL_BROKER' AND PS_TYPE = 'LOV_CUST') AND CUST_FRZ_FLAG = 'N' AND ((CUST_CODE IN (SELECT CDIV_CUST_CODE FROM PM_CUST_DIVN WHERE CDIV_DIVN_CODE = ?? AND NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'N')) OR (NVL(CUST_APPL_ALL_BRAN_YN,'N') = 'Y')) AND CUST_CODE = ? ";
	
	String PROPOSAL_STATUS_STAR = "SELECT PS_CODE, PS_CODE_DESC FROM PP_SYSTEM WHERE  PS_TYPE = 'IL_ADDL_STAT' AND ROWNUM < ? ORDER BY 1 ASC  ";
	String PROPOSAL_STATUS_SEARCH = "SELECT PS_CODE, PS_CODE_DESC FROM PP_SYSTEM WHERE  PS_TYPE = 'IL_ADDL_STAT' AND PS_CODE LIKE ? AND ROWNUM < ? ORDER BY 1 ASC ";
	String IP_REP_INFO_PROPOSAL_STATUS_RECORD_CHECK = "SELECT 1 FROM PP_SYSTEM WHERE  PS_TYPE = 'IL_ADDL_STAT' AND PS_CODE = ?";
	
	String IP_REP_INFO_PLAN_CODE_LOV_NEW="SELECT COVER_CODE,DECODE(?,'ENG',COVER_DESC,COVER_BL_DESC)FROM PM_IL_COVER WHERE COVER_CODE IN (SELECT PLAN_CODE FROM PM_IL_PLAN ) AND ROWNUM < ? ORDER BY COVER_CODE ";
	String IP_REP_INFO_PLAN_CODE_LOV_LIKE_NEW="SELECT COVER_CODE,DECODE(?,'ENG',COVER_DESC,COVER_BL_DESC)FROM PM_IL_COVER WHERE COVER_CODE IN (SELECT PLAN_CODE FROM PM_IL_PLAN )AND COVER_CODE LIKE ? AND ROWNUM <? ORDER BY COVER_CODE  ";
	String IP_REP_INFO_PLAN_CODE_CHECK="SELECT 1 FROM PM_IL_COVER WHERE COVER_CODE IN (SELECT PLAN_CODE FROM PM_IL_PLAN ) AND COVER_CODE=? ";
	
}
