package com.iii.pel.forms.PT099_A;

public interface PT_AGENT_TRAN_HDR_QUERY_CONSTANTS {
	
	public String PT_AGENT_PYMT_REVERSAL_FETCH_SYS_ID_RELATED_DATA=
					"SELECT ROWID,PT_AGENT_PYMT_REVERSAL_DTLS.* FROM PT_AGENT_PYMT_REVERSAL_DTLS WHERE APRD_ATH_SYS_ID=?";

	public String PT_AGENT_PYMT_REVERSAL_POST_QUERY_1=
		" SELECT SUM(NVL(ACV_FC_VALUE,0)),SUM(NVL(ACV_LC_VALUE ,0)) "
		+ " FROM PT_AGENT_COMM_VALUES WHERE ACV_POL_SYS_ID=? "
		+" AND ACV_AGENT_CODE  =? AND ACV_PC_SYS_ID  = ?";
	
	public String PT_AGENT_PYMT_REVERSAL_POST_QUERY_2=
		" SELECT PC_SCHD_PYMT_DT,PC_PAID_DT,PC_FC_GROSS_PREM,PC_LC_GROSS_PREM" 
		+" FROM PT_IL_PREM_COLL WHERE PC_POL_SYS_ID=? "
		+" AND PC_SYS_ID=? ";

	public String PT_AGENT_TRAN_HDR_PROCESS_BUTTON_QUERY = "SELECT POL_SYS_ID FROM PT_IL_POLICY WHERE POL_NO=?";
	
	public String PT_AGENT_TRAN_HDR_ATH_AGENT_NAME="SELECT CUST_NAME FROM PM_CUSTOMER WHERE CUST_CODE= ?";
	
	public String PT_AGENT_TRAN_HDR_ATH_N_AGENT="SELECT PC_VALUE FROM PM_CODES WHERE  PC_TYPE = 'AGNRANK' "
												+" AND PC_CODE = (SELECT CUST_AGENT_RANK_CODE FROM PM_CUSTOMER WHERE CUST_CODE =? ";
	
	public String PT_AGENT_TRAN_HDR_ATH_AGENT_CODE="SELECT PC_VALUE FROM  PM_CODES WHERE  PC_TYPE = 'AGNRANK' "
													+"AND  PC_CODE =(SELECT CUST_AGENT_RANK_CODE FROM PM_CUSTOMER WHERE CUST_CODE = ?";

	public String PT_AGENT_TRAN_HDR_APPROVAL_BUTTON_QUERY_1="SELECT PC_DESC,PC_BL_DESC FROM PM_CODES WHERE PC_TYPE = 'IL_REMIN_RPT'" 
															+" AND PC_CODE IN (SELECT PS_CODE_DESC FROM PP_SYSTEM WHERE  PS_TYPE = 'AGT_LETTER'" 
															+" AND    PS_CODE = ?) ";
	public String PT_AGENT_TRAN_HDR_APPROVAL_BUTTON_QUERY_2=" SELECT CUST_PREFERRED_LANG FROM   PM_CUSTOMER "
		                                                   +" WHERE  CUST_CODE = ?";
	
	public String PT_AGENT_TRAN_HDR_APPROVAL_BUTTON_QUERY_3="SELECT 'X' FROM PT_AGENT_PYMT_REVERSAL_DTLS "
															+" WHERE APRD_POL_SYS_ID=? "
															+" AND ROWID =?";

	public String PT_AGENT_TRAN_HDR_SEARCH_QUERY_UNCONDITIONAL = "SELECT POL_NO, PT_AGENT_TRAN_HDR.ROWID, ATH_AGENT_CODE, ATH_NEW_AGENT_CODE "
				+ "FROM PT_AGENT_TRAN_HDR, PT_IL_POLICY " 
				+ "WHERE PT_AGENT_TRAN_HDR.ATH_POL_SYS_ID=PT_IL_POLICY.POL_SYS_ID";
	public String PT_AGENT_TRAN_HDR_SEARCH_QUERY_CONDITIONAL = "SELECT POL_NO, PT_AGENT_TRAN_HDR.ROWID, ATH_AGENT_CODE, ATH_NEW_AGENT_CODE "
				+ "FROM PT_AGENT_TRAN_HDR, PT_IL_POLICY " 
				+ "WHERE PT_AGENT_TRAN_HDR.ATH_POL_SYS_ID=PT_IL_POLICY.POL_SYS_ID AND POL_NO LIKE ?";
}
