package com.iii.pel.forms.PILT006_APAC;

public interface PILT006_APAC_QUERY_CONSTANT {
	String ClassCodeUnique="SELECT CLAIM_NO FROM  PT_IL_CLAIM  WHERE  CLAIM_NO  = ? ";
	String ClaimPciNo_sq1_C1 = "SELECT PCI_CLAIM_TYPE,PCI_LOSS_DT,PCI_REPORT_DT,PCI_POL_NO FROM PT_IL_PRE_CLAIMS_INFO WHERE PCI_REF_NO = ? ";
	String ClaimPciNo_sq1_C2 = "SELECT PCI_ADDL_STATUS FROM  PT_IL_PRE_CLAIMS_INFO  WHERE  PCI_REF_NO  = ? ";
	String ClaimPciNo_sq1_C3 = "SELECT 'X' FROM  PT_IL_PRE_CLAIMS_INFO  WHERE  PCI_REF_NO  = ? ";
	String ClaimType = "SELECT PLAN_TYPE FROM  PM_IL_PLAN  WHERE  PLAN_CODE  =  (   SELECT POL_PLAN_CODE  FROM  PT_IL_POLICY   WHERE  POL_NO  = ?  ) ";
	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_CURRENCY to FM_CURRENCY. Added by : Mallika.S, 01-Apr-2009 */
	String ClaimPolNo_sq1 = "SELECT CURR_NAME FROM  FM_CURRENCY  WHERE  CURR_CODE  = ? ";
	String ClaimPolNo_sq2 = "SELECT PLAN_TYPE FROM  PM_IL_PLAN  WHERE  PLAN_CODE  =  (   SELECT POL_PLAN_CODE  FROM  PT_IL_POLICY   WHERE  POL_NO  = ?  ) ";
	String ClaimPolNo_sq3 = "SELECT POL_STATUS FROM  PT_IL_POLICY  WHERE  POL_NO  = ? ";
	String NewBlockInstance = "SELECT 'X' FROM  PT_IL_CLAIM_PAID  WHERE  CP_CLAIM_SYS_ID  = ?  AND NVL(CP_APPR_FLAG, 'N')  IN ( 'A'  , 'R'  )  AND NVL(CP_CLM_PAID_STATUS, 'N')  = 'A' ";
	String ClaimLossDate = "SELECT PLAN_POL_VALID_AFTER_MAT_YN FROM  PM_IL_PLAN  WHERE  PLAN_CODE  =  (   SELECT POL_PLAN_CODE  FROM  PT_IL_POLICY   WHERE  POL_SYS_ID  = ?  ) ";
	String ClaimRefNo = "SELECT 'X' FROM  PT_IL_CLAIM  WHERE  CLAIM_REF_NO  = ?  AND CLAIM_POL_SYS_ID  <> ? ";
}
