package com.iii.pel.forms.PILM072_APAC;

public interface PILM072_APAC_SQLQUERY_CONSTANTS {

	
	final String FETCH_ROW_COUNT="25";
	
	final String DELETE_PM_IL_FUND_ACCOUNT_SETUP="DELETE FROM PM_IL_FUND_ACCOUNT_SETUP WHERE ROWID ?";
	
	final String UPDATE_PM_IL_FUND_ACCOUNT_SETUP="UPDATE * FROM PM_IL_FUND_ACCOUNT_SETUP WHERE ROWID=?";
	
	final String SELECT_ALL_PM_IL_IF_ACCNT_SETUP_HDR="select PM_IL_IF_ACCNT_SETUP_HDR.ROWID,PIFH_MAIN_ACNT_CODE,PIFH_SUB_ACNT_CODE,PIFH_DIVN_CODE,PIFH_DEPT_CODE,PIFH_ANLY_CODE_1,PIFH_ANLY_CODE_2,PIFH_ACTY_CODE_1,PIFH_ACTY_CODE_2,PIFH_DRCR_FLAG from PM_IL_IF_ACCNT_SETUP_HDR";
	
}
