package com.iii.pel.forms.PILM205;

import java.io.Serializable;

/**
 * @author 1001061
 *
 */
public class PILM205_COMPOSITE_ACTION implements Serializable {

	private static final long serialVersionUID = -7097618810792580503L;
	
	private PILM205_CUSTOMIZED_REPORT_ACTION PILM205_CUSTOMIZED_REPORT_ACTION_BEAN;
	
	public PILM205_COMPOSITE_ACTION(){
		PILM205_CUSTOMIZED_REPORT_ACTION_BEAN = new PILM205_CUSTOMIZED_REPORT_ACTION();
		PILM205_CUSTOMIZED_REPORT_ACTION_BEAN.compositeAction = this;
	}

	public PILM205_CUSTOMIZED_REPORT_ACTION getPILM205_CUSTOMIZED_REPORT_ACTION_BEAN() {
		return PILM205_CUSTOMIZED_REPORT_ACTION_BEAN;
	}

	public void setPILM205_CUSTOMIZED_REPORT_ACTION_BEAN(
			PILM205_CUSTOMIZED_REPORT_ACTION pILM205_CUSTOMIZED_REPORT_ACTION_BEAN) {
		PILM205_CUSTOMIZED_REPORT_ACTION_BEAN = pILM205_CUSTOMIZED_REPORT_ACTION_BEAN;
	}

	

	
	
	
}
