package com.iii.pel.forms.PILT018;

public interface QueryRepository {

	String PT_IL_BROK_ADV_HDR_CUST_CODE_QUERY = "SELECT CUST_CODE,CUST_NAME FROM PM_CUSTOMER WHERE ROWNUM<50  ";
	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_CURRENCY to FM_CURRENCY. Added by : Mallika.S, 01-Apr-2009 */
	String PT_IL_BROK_ADV_HDR_CURR_CODE_QUERY = "SELECT CURR_CODE,CURR_NAME FROM FM_CURRENCY WHERE ROWNUM<50  ";
	String PT_IL_BROK_ADV_HDR_CUST_CODE_DESC_QUERY = "SELECT CUST_NAME FROM PM_CUSTOMER WHERE CUST_CODE=";
	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_CURRENCY to FM_CURRENCY. Added by : Mallika.S, 01-Apr-2009 */
	String PT_IL_BROK_ADV_HDR_CURR_CODE_DESC_QUERY = "SELECT CURR_NAME FROM FM_CURRENCY WHERE CURR_CODE=";
	String SELECT_BV_FC_VALUE = "SELECT BV_FC_VALUE FROM  PT_IL_BROKER_VALUES  WHERE  BV_BROKER_CODE  = ? ";
	String SELECT_ACV_FC_VALUE = "SELECT ACV_FC_VALUE FROM  PT_AGENT_COMM_VALUES  WHERE  ACV_AGENT_CODE  = ?";
	String SELECT_PRIORITY = "SELECT BAH_PAY_PRIORITY FROM   PT_IL_BROK_ADV_HDR WHERE BAH_CUST_CODE = ?";
	String SELECT_BAH_PAY_PRIORITY = "	SELECT MAX(BAH_PAY_PRIORITY) FROM PT_IL_BROK_ADV_HDR WHERE BAH_STATUS ='O'";
	String SELECT_PC_LONG_DESC = "SELECT PC_LONG_DESC,PC_BL_LONG_DESC FROM PM_CODES  WHERE PC_TYPE = 'IL_BAH_PYMT' AND PC_CODE= ?";
	String UPDATE_PT_IL_BROK_ADV_HDR = "UPDATE PT_IL_BROK_ADV_HDR SET BAH_PAID_FLAG  = 'Y' WHERE  BAH_SYS_ID = ? AND NVL(BAH_PAID_FLAG,'N') != 'Y'";
	
	
}
