package com.iii.pel.forms.PM023_A;

import java.io.Serializable;

/**
 * @author Pidugu Raj , dt: 04-12-2018
 *
 */
public class PM023_A_COMPOSITE_ACTION /*implements Serializable*/ {

	//private static final long serialVersionUID = -6365038972791399750L;
	
	private PM_IL_CUSTOM_MASTER_REPORT_ACTION PM_IL_CUSTOM_MASTER_REPORT_ACTION_BEAN;

	public PM_IL_CUSTOM_MASTER_REPORT_ACTION getPM_IL_CUSTOM_MASTER_REPORT_ACTION_BEAN() {
		return PM_IL_CUSTOM_MASTER_REPORT_ACTION_BEAN;
	}

	public void setPM_IL_CUSTOM_MASTER_REPORT_ACTION_BEAN(
			PM_IL_CUSTOM_MASTER_REPORT_ACTION pM_IL_CUSTOM_MASTER_REPORT_ACTION_BEAN) {
		PM_IL_CUSTOM_MASTER_REPORT_ACTION_BEAN = pM_IL_CUSTOM_MASTER_REPORT_ACTION_BEAN;
	}
	
	public PM023_A_COMPOSITE_ACTION() throws Exception
	{
		PM_IL_CUSTOM_MASTER_REPORT_ACTION_BEAN = new PM_IL_CUSTOM_MASTER_REPORT_ACTION();
		PM_IL_CUSTOM_MASTER_REPORT_ACTION_BEAN.compositeAction = this;
	}

}
