package com.iii.pel.forms.PLM005;

public interface PLM005_QUERYCONSTANTS {

	String EXC_RATE_FLAG_Values="SELECT LIV_CODE,LIV_CODE_DESC FROM PP_LIST_ITEM_VALUES WHERE LIV_SYS_PARAM = 'UNIT_SEL_BUY'";
	
	
	//String EXC_RATE_FLAG_Values="SELECT * FROM PP_LIST_ITEM_VALUES WHERE LIV_SYS_PARAM = 'UNIT_SEL_BUY'";
	
}
