package com.iii.premia.common.commonimpl.sso.ssomanager;


public class SSO_MANAGER_COMPOSITE_ACTION {
	private PM_LOGIN_SWITCH_ACTION PM_LOGIN_SWITCH_ACTION_BEAN;
	private PM_APPLICATION_SETUP_ACTION PM_APPLICATION_SETUP_ACTION_BEAN;

	public SSO_MANAGER_COMPOSITE_ACTION(){
		PM_LOGIN_SWITCH_ACTION_BEAN = new PM_LOGIN_SWITCH_ACTION();
		PM_APPLICATION_SETUP_ACTION_BEAN = new PM_APPLICATION_SETUP_ACTION();
	}
	
	public PM_LOGIN_SWITCH_ACTION getPM_LOGIN_SWITCH_ACTION_BEAN() {
		return PM_LOGIN_SWITCH_ACTION_BEAN;
	}

	public void setPM_LOGIN_SWITCH_ACTION_BEAN(
			PM_LOGIN_SWITCH_ACTION pm_login_switch_action_bean) {
		PM_LOGIN_SWITCH_ACTION_BEAN = pm_login_switch_action_bean;
	}

	public PM_APPLICATION_SETUP_ACTION getPM_APPLICATION_SETUP_ACTION_BEAN() {
		return PM_APPLICATION_SETUP_ACTION_BEAN;
	}

	public void setPM_APPLICATION_SETUP_ACTION_BEAN(
			PM_APPLICATION_SETUP_ACTION pm_application_setup_action_bean) {
		PM_APPLICATION_SETUP_ACTION_BEAN = pm_application_setup_action_bean;
	}
}
