package com.iii.premia.common.commonimpl.sso.ssomanager;

public interface SSO_MANAGER_CONSTANTS {
	// Search page constants
	String SSO_MANAGER_SEARCH_APP_MAPPING_FETCH_QUERY = "SELECT " +
			"DISTINCT PLS_FM_APPLICATION, PLS_FM_USER_ID, DECRYPT(PLS_FM_USER_PWD,'3iInfotech') PLS_FM_USER_PWD, PLS_FM_COMPANY, PLS_FM_DIVISION, PLS_FM_DEPARTMENT " +
			"FROM PM_LOGIN_SWITCH " +
			"WHERE PLS_FM_APPLICATION LIKE ? AND " +
			"PLS_FM_USER_ID LIKE ? AND "+
			"PLS_FM_COMPANY LIKE ? AND "+
			"PLS_FM_DIVISION LIKE ? AND "+
			"PLS_FM_DEPARTMENT LIKE ? "+
			"GROUP BY (PLS_FM_APPLICATION, PLS_FM_USER_ID, PLS_FM_COMPANY, PLS_FM_DIVISION, PLS_FM_DEPARTMENT, PLS_FM_USER_PWD) ORDER BY 1";
	
	// Login Switch- User-App mappping
	String SSO_MANAGER_PM_LOGIN_SWITCH_QUERY = "SELECT ROWID, " +
			"PLS_FM_APPLICATION, PLS_FM_USER_ID, DECRYPT(PLS_FM_USER_PWD,'3iInfotech') PLS_FM_USER_PWD, PLS_FM_COMPANY, PLS_FM_DIVISION, PLS_FM_DEPARTMENT, " +
			"PLS_TO_APPLICATION, PLS_TO_USER_ID, DECRYPT(PLS_TO_USER_PWD,'3iInfotech') PLS_TO_USER_PWD, PLS_TO_COMPANY, PLS_TO_DIVISION, PLS_TO_DEPARTMENT " +
			"FROM PM_LOGIN_SWITCH " +
			"WHERE PLS_FM_APPLICATION=? AND " +
			"PLS_FM_USER_ID=? AND "+
			"PLS_FM_COMPANY=? AND "+
			"PLS_FM_DIVISION=? AND "+
			"PLS_FM_DEPARTMENT=? "+
			//"GROUP BY (PLS_TO_APPLICATION, PLS_TO_USER_ID, PLS_TO_COMPANY, PLS_TO_DIVISION, PLS_TO_DEPARTMENT) " +
			"ORDER BY PLS_TO_APPLICATION, PLS_TO_USER_ID, PLS_TO_COMPANY, PLS_TO_DIVISION, PLS_TO_DEPARTMENT";
	String SSO_MANAGER_PM_LOGIN_SWITCH_DUPLICATE_CHECK = "SELECT ROWID " +
			"FROM PM_LOGIN_SWITCH " +
			"WHERE " +
			"PLS_FM_APPLICATION=? AND " +
			"PLS_FM_USER_ID=? AND "+
			"PLS_FM_COMPANY=? AND "+
			"PLS_FM_DIVISION=? AND "+
			"PLS_FM_DEPARTMENT=? AND "+
			"PLS_TO_APPLICATION=? AND " +
			"PLS_TO_USER_ID=? AND "+
			"PLS_TO_COMPANY=? AND "+
			"PLS_TO_DIVISION=? AND "+
			"PLS_TO_DEPARTMENT=? ";
	String SSO_MANAGER_PM_LOGIN_SWITCH_DELETE = "DELETE PM_LOGIN_SWITCH WHERE ROWID=?";
	String SSO_MANAGER_PM_LOGIN_SWITCH_DELETE_MAPPING = "DELETE PM_LOGIN_SWITCH WHERE PLS_FM_APPLICATION=? AND PLS_FM_USER_ID=? AND PLS_FM_COMPANY=? AND PLS_FM_DIVISION=? AND PLS_FM_DEPARTMENT=?";
	String SSO_MANAGER_PM_LOGIN_SWITCH_UPDATE_PASSWORDS = "UPDATE PM_LOGIN_SWITCH SET PLS_FM_USER_PWD=ENCRYPT(PLS_FM_USER_PWD,'3iInfotech'), PLS_TO_USER_PWD=ENCRYPT(PLS_TO_USER_PWD,'3iInfotech') WHERE ROWID=?";
	// Switch Suggestion Queries
	String SSO_MANAGER_PM_LOGIN_SWITCH_FROM_APPLICATION = "SELECT PAD.PAD_APPL_CODE, PAD.PAD_APPL_DESC, ISS.PARA_VALUE FROM IM_SYSTEM_SETUP ISS, PM_APPLICATION_DTLS PAD " + 
			"WHERE PAD.PAD_APPL_CODE=ISS.PARA_CODE " + 
			"AND ISS.PARA_MODULE=? AND (PAD.PAD_APPL_CODE LIKE ? OR PAD.PAD_APPL_DESC LIKE ?) " +
			"AND ROWNUM < ? " +
			"ORDER BY PAD.PAD_APPL_CODE";
	String SSO_MANAGER_PM_LOGIN_SWITCH_FROM_USER_ID = "SELECT USER_ID, USER_DESC, DECRYPT(USER_PASSWD, '3iInfotech') USER_PASSWD " +
			"FROM {0}.MENU_USER " +
			"WHERE USER_ID LIKE ? OR USER_DESC LIKE ? " +
			"AND ROWNUM < ? " +
			"ORDER BY USER_ID ";
	String SSO_MANAGER_PM_LOGIN_SWITCH_FROM_COMAPNY = "SELECT COMP_CODE, COMP_NAME " +
			"FROM {0}.FM_COMPANY " + 
			"WHERE COMP_FRZ_FLAG = 'N' AND (COMP_CODE LIKE ? OR COMP_NAME LIKE ?) " +
			"AND ROWNUM < ? " +
			"ORDER BY COMP_CODE";
	String SSO_MANAGER_PM_LOGIN_SWITCH_FROM_DIVISION = "SELECT DIVN_CODE, DIVN_NAME " + 
			"FROM {0}.FM_DIVISION " + 
			"WHERE DIVN_FRZ_FLAG = 'N' " +
			"AND DIVN_COMP_CODE = ? " + 
			/*"AND EXISTS ( " +
			"SELECT 1 FROM PM_APPR_DEPT_SETUP " + 
			"WHERE ADS_DIVN_CODE = DIVN_CODE " + 
			"AND ADS_FRZ_FLAG = 'N' " + 
			"AND ADS_USER_ID = ?) " +*/ 
			"AND (DIVN_CODE LIKE ?  OR DIVN_NAME LIKE ?) " +
			"AND ROWNUM < ? " +
			"ORDER BY DIVN_CODE";
	String SSO_MANAGER_PM_LOGIN_SWITCH_FROM_DEPARTMENT = "SELECT DEPT_CODE, DEPT_NAME FROM {0}.FM_DEPARTMENT " +
			"WHERE DEPT_COMP_CODE = ? " +
			"AND DEPT_DIVN_CODE = ? " +
			"AND DEPT_FRZ_FLAG = 'N' " +
			"AND (DEPT_CODE LIKE ? OR DEPT_NAME LIKE ?) " +
			"AND ROWNUM < ? " +
			"ORDER BY DEPT_CODE";
	
	// Application Setup 
	String SSO_MANAGER_PM_APPLICATION_SETUP_QUERY = "SELECT ROWID, PM_APPLICATION_DTLS.* FROM PM_APPLICATION_DTLS";
	String SSO_MANAGER_PM_APPLICATION_SETUP_POST_QUERY = "SELECT ROWID, IM_SYSTEM_SETUP.* FROM IM_SYSTEM_SETUP WHERE PARA_CODE=? AND PARA_MODULE=?";
	String SSO_MANAGER_PM_APPLICATION_DTLS_DELETE = "DELETE PM_APPLICATION_DTLS WHERE PAD_APPL_CODE=?";
	String SSO_MANAGER_IM_SYSTEM_SETUP_DELETE = "DELETE IM_SYSTEM_SETUP WHERE PARA_CODE=? AND PARA_MODULE=?";
	String SSO_MANAGER_IM_SYSTEM_SETUP_APP_CODE_DUPLICATE_CHECK = "SELECT ROWID FROM IM_SYSTEM_SETUP WHERE PARA_CODE=?";
	String SSO_MANAGER_IM_SYSTEM_SETUP_APP_NAME_DUPLICATE_CHECK = "SELECT ROWID FROM PM_APPLICATION_DTLS WHERE PAD_APPL_DESC=?";
}
