package com.iii.pel.forms.PILP080;

import java.util.List;

import com.iii.premia.common.utils.CommonUtils;

public class PT_IL_POL_MED_EXAM_DTL_HELPER {

	public void executeQuery(PILP080_COMPOSITE_ACTION compositeAction)
			throws Exception {
		new PT_IL_POL_MED_EXAM_DTL_DELEGATE()
				.executeSelectStatement(compositeAction);

		List<PT_IL_POL_MED_EXAM_DTL> dataList = compositeAction
				.getPT_IL_POL_MED_EXAM_DTL_ACTION_BEAN()
				.getDataList_PT_IL_POL_MED_EXAM_DTL();
		if (dataList != null && dataList.size() > 0) {
			PT_IL_POL_MED_EXAM_DTL PT_IL_POL_MED_EXAM_DTL_BEAN = dataList
					.get(0);
			PT_IL_POL_MED_EXAM_DTL_BEAN.setRowSelected(true);
			compositeAction
					.getPT_IL_POL_MED_EXAM_DTL_ACTION_BEAN()
					.setPT_IL_POL_MED_EXAM_DTL_BEAN(PT_IL_POL_MED_EXAM_DTL_BEAN);
		}
	}

	public void WHEN_NEW_BLOCK_INSTANCE(PILP080_COMPOSITE_ACTION compositeAction)
			throws Exception {
		PT_IL_PV_MED_HDR_ACTION PT_IL_PV_MED_HDR_ACTION_BEAN = compositeAction
				.getPT_IL_PV_MED_HDR_ACTION_BEAN();
		PT_IL_PV_MED_HDR PT_IL_PV_MED_HDR_BEAN = compositeAction
				.getPT_IL_PV_MED_HDR_ACTION_BEAN().getPT_IL_PV_MED_HDR_BEAN();
		DUMMY_ACTION DUMMY_ACTION_BEAN = compositeAction.getDUMMY_ACTION_BEAN();
		
		if ("A".equalsIgnoreCase(CommonUtils.nvl(PT_IL_PV_MED_HDR_BEAN
				.getPMH_APPRV_STATUS(), "N"))) {
			PT_IL_PV_MED_HDR_ACTION_BEAN.getCOMP_UI_M_BUT_DTLS().setDisabled(
					true);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_APPROVE().setDisabled(true);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_GENERATE().setDisabled(true);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_REP().setDisabled(false);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_ERR_DTLS().setDisabled(true);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_APPRV_STATUS().setRendered(true);

			PT_IL_PV_MED_HDR_ACTION_BEAN.setINSERT_ALLOWED(false);
			PT_IL_PV_MED_HDR_ACTION_BEAN.setDELETE_ALLOWED(false);
			PT_IL_PV_MED_HDR_ACTION_BEAN.setUPDATE_ALLOWED(false);
			/*
			 * SET_ITEM_PROPERTY('PT_IL_PV_MED_HDR.M_BUT_DTLS',ENABLED,PROPERTY_FALSE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_APPROVE',ENABLED,PROPERTY_FALSE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_GENERATE',ENABLED,PROPERTY_FALSE);
			 * SET_ITEM_PROPERTY('DUMMY.M_APPRV_STATUS',VISIBLE,PROPERTY_TRUE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_REP',ENABLED,PROPERTY_TRUE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_ERR_DTLS',ENABLED,PROPERTY_FALSE);
			 * SET_BLOCK_PROPERTY('PT_IL_PV_MED_HDR',UPDATE_ALLOWED,PROPERTY_FALSE);
			 * SET_BLOCK_PROPERTY('PT_IL_PV_MED_HDR',INSERT_ALLOWED,PROPERTY_FALSE);
			 * SET_BLOCK_PROPERTY('PT_IL_PV_MED_HDR',DELETE_ALLOWED,PROPERTY_FALSE);
			 */

		}
	}

	public void WHEN_NEW_RECORD_INSTANCE(
			PILP080_COMPOSITE_ACTION compositeAction) {
		PT_IL_PV_MED_HDR_ACTION PT_IL_PV_MED_HDR_ACTION_BEAN = compositeAction
				.getPT_IL_PV_MED_HDR_ACTION_BEAN();
		PT_IL_PV_MED_HDR PT_IL_PV_MED_HDR_BEAN = compositeAction
				.getPT_IL_PV_MED_HDR_ACTION_BEAN().getPT_IL_PV_MED_HDR_BEAN();
		DUMMY_ACTION DUMMY_ACTION_BEAN = compositeAction.getDUMMY_ACTION_BEAN();
		if ("A".equalsIgnoreCase(CommonUtils.nvl(PT_IL_PV_MED_HDR_BEAN
				.getPMH_APPRV_STATUS(), "N"))) {
			PT_IL_PV_MED_HDR_ACTION_BEAN.getCOMP_UI_M_BUT_DTLS().setDisabled(
					true);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_APPRV_STATUS().setRendered(true);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_APPROVE().setDisabled(true);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_REP().setDisabled(false);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_ERR_DTLS().setDisabled(true);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_GENERATE().setDisabled(true);
			/*
			 * SET_ITEM_PROPERTY('PT_IL_PV_MED_HDR.M_BUT_DTLS',ENABLED,PROPERTY_FALSE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_APPROVE',ENABLED,PROPERTY_FALSE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_GENERATE',ENABLED,PROPERTY_FALSE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_REP',ENABLED,PROPERTY_TRUE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_ERR_DTLS',ENABLED,PROPERTY_FALSE);
			 * SET_ITEM_PROPERTY('DUMMY.M_APPRV_STATUS',VISIBLE,PROPERTY_TRUE);
			 */
		} else {
			/*
			 * SET_ITEM_PROPERTY('PT_IL_PV_MED_HDR.M_BUT_DTLS',ENABLED,PROPERTY_TRUE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_APPROVE',ENABLED,PROPERTY_TRUE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_GENERATE',ENABLED,PROPERTY_TRUE);
			 * SET_ITEM_PROPERTY('DUMMY.M_BUT_REP',ENABLED,PROPERTY_FALSE);
			 * SET_ITEM_PROPERTY('DUMMY.M_APPRV_STATUS',VISIBLE,PROPERTY_FALSE);
			 * SET_BLOCK_PROPERTY('PT_IL_PV_MED_HDR',UPDATE_ALLOWED,PROPERTY_TRUE);
			 * SET_BLOCK_PROPERTY('PT_IL_PV_MED_HDR',INSERT_ALLOWED,PROPERTY_TRUE);
			 */
			PT_IL_PV_MED_HDR_ACTION_BEAN.getCOMP_UI_M_BUT_APPROVE().setDisabled(false);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_APPRV_STATUS().setRendered(false);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_APPROVE().setDisabled(true);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_REP().setDisabled(true);
			DUMMY_ACTION_BEAN.getCOMP_UI_M_BUT_GENERATE().setDisabled(false);
			PT_IL_PV_MED_HDR_ACTION_BEAN.setINSERT_ALLOWED(true);
			PT_IL_PV_MED_HDR_ACTION_BEAN.setUPDATE_ALLOWED(true);
		}
	}

}
