package com.iii.pel.forms.PILP090_APAC;

public class PILP090_APAC_COMPOSITE_ACTION {
	
	private PERSISTENCY_ACTION PERSISTENCY_ACTION_BEAN;

	public PERSISTENCY_ACTION getPERSISTENCY_ACTION_BEAN() {
		return PERSISTENCY_ACTION_BEAN;
	}

	public void setPERSISTENCY_ACTION_BEAN(
			PERSISTENCY_ACTION pERSISTENCY_ACTION_BEAN) {
		PERSISTENCY_ACTION_BEAN = pERSISTENCY_ACTION_BEAN;
	}
	public PILP090_APAC_COMPOSITE_ACTION(){
		
		PERSISTENCY_ACTION_BEAN = new PERSISTENCY_ACTION();
		PERSISTENCY_ACTION_BEAN.compositeAction = this;
	}
	
}
