package com.iii.pel.forms.PILM042;

public interface PILM042_QUERY_CONSTANTS {
	String DUDH_DEF_CODE_WHEN_VALIDATE_ITEM = "SELECT 1 FROM PM_IL_DATA_UPLOAD_DEFN_HDR WHERE DUDH_DEF_CODE = ?";
	
	String SELECT_ALL_PM_IL_DATA_UPLOAD_DEFN_HDR_SETUP = "SELECT PM_IL_DATA_UPLOAD_DEFN_HDR.ROWID,DUDH_DEF_CODE,DUDH_DESC,DUDH_SHORT_DESC,DUDH_LONG_DESC,DUDH_BL_DESC,DUDH_BL_SHORT_DESC,DUDH_BL_LONG_DESC,DUDH_EFF_FM_DT,DUDH_EFF_TO_DT,DUDH_CR_DT,DUDH_CR_UID,DUDH_UPD_DT,DUDH_UPD_UID FROM PM_IL_DATA_UPLOAD_DEFN_HDR {0} ORDER BY DUDH_DEF_CODE";
	String SELECT_ALL_PM_IL_DATA_UPLOAD_DEFN_HDR_SETUP1 = "SELECT PM_IL_DATA_UPLOAD_DEFN_HDR.ROWID,DUDH_DEF_CODE,DUDH_DESC,DUDH_SHORT_DESC,DUDH_LONG_DESC,DUDH_BL_DESC,DUDH_BL_SHORT_DESC,DUDH_BL_LONG_DESC,DUDH_EFF_FM_DT,DUDH_EFF_TO_DT,DUDH_CR_DT,DUDH_CR_UID,DUDH_UPD_DT,DUDH_UPD_UID FROM PM_IL_DATA_UPLOAD_DEFN_HDR  WHERE rowid = ? ORDER BY DUDH_DEF_CODE";
	
	String PILM042_DETAIL_QUERY = "SELECT tab1.rowid,tab1.*  FROM PM_IL_DATA_UPLOAD_DEFN_DTL tab1 WHERE EXISTS (SELECT 1 FROM PM_IL_DATA_UPLOAD_DEFN_HDR tab2 WHERE tab2.rowid = ? AND tab2. DUDH_DEF_CODE = tab1.DUDD_DUDH_DEF_CODE)";
}
