package com.iii.pel.forms.PILM042;

public interface PILM042_SQL_QUERY {
	final String DELETE_PM_IL_DATA_UPLOAD_DEFN_HDR_SETUP="DELETE FROM SELECT PM_IL_DATA_UPLOAD_DEFN_HDR WHERE ROWID= ?";
	final String UPDATE_PM_IL_DATA_UPLOAD_DEFN_HDR_SETUP="UPDATE * FROM SELECT PM_IL_DATA_UPLOAD_DEFN_HDR WHERE ROWID=?";
	final String SELECT_ALL_PM_IL_DATA_UPLOAD_DEFN_HDR_SETUP="SELECT PM_IL_DATA_UPLOAD_DEFN_HDR.ROWID,DUDH_DEF_CODE,DUDH_DESC,DUDH_SHORT_DESC,DUDH_LONG_DESC,DUDH_BL_DESC,DUDH_BL_SHORT_DESC,DUDH_BL_LONG_DESC,DUDH_EFF_FM_DT,DUDH_EFF_TO_DT,DUDH_CR_DT,DUDH_CR_UID,DUDH_UPD_DT,DUDH_UPD_UID FROM PM_IL_DATA_UPLOAD_DEFN_HDR";
//	final String LOV_FAS_SRC_BUS_FM_TO="SELECT PC_CODE,PC_DESC,PC_BL_DESC FROM PM_CODES" +
//			" WHERE PC_TYPE ='SRC_BUS_TY'AND NVL(PC_FRZ_FLAG,'N') = 'N'";
//	final String LOV_FAS_DEPT_FM_TO_CODE="SELECT DEPT_CODE,DEPT_NAME,DEPT_CODE " +
//			"FROM PM_DEPARTMENT WHERE DEPT_COMP_CODE = ':CTRL.M_COMP_CODE' AND " +
//			"DEPT_DIVN_CODE = ':PM_IL_FUND_ACCOUNT_SETUP.FAS_DIVN_FM_CODE' AND " +
//			"DEPT_FRZ_FLAG  = 'N' AND EXISTS (SELECT 1 FROM PM_APPR_DEPT_SETUP " +
//			"WHERE ADS_DIVN_CODE = DEPT_DIVN_CODE AND ADS_DEPT_CODE = DEPT_CODE" +
//			" AND ADS_USER_ID = NVL('&M_PARA_3',ADS_USER_ID) ANDADS_FRZ_FLAG = 'N')";
//	final String LOV_FAS_DOC_FM_TO_TYPE="SELECT DS_CODE,DS_DESC FROM " +
//			"PM_IL_DOC_SETUP WHERE ( DS_TYPE = '2' OR DS_TYPE = '2')  AND" +
//			"  NVL(DS_FRZ_FLAG ,'N') ='N'";
}
