package com.iii.pel.forms.PILM016_APAC;

public interface PILM016_PM_IL_CONTRACTOR_QUERY_CONSTANTS {
	String PM_IL_CONTRACTOR_QUERY_REFID2_DETAIL = "SELECT    'X',    CONT_NAME,    CONT_ADDR1,    CONT_ADDR2,    CONT_ADDR3, "
			+ "   CONT_CONTACT,    CONT_PHONE,    CONT_FAX,    CONT_REMARKS,    CONT_DFLT_YN,  "
			+ "  CONT_CUST_CODE,    CONT_FRZ_FLAG,    CONT_BL_NAME,    CONT_BL_ADDR1,   "
			+ " CONT_BL_ADDR2,    CONT_BL_ADDR3,    CONT_BL_CONTACT,    CONT_EMPLOYER_YN,   "
			+ " CONT_EFF_FM_DT,    CONT_EFF_TO_DT,    CONT_REF_NO,    CONT_REF_ID1,   "
			+ " CONT_REF_ID2,    CONT_TEL_AREA_CODE,    CONT_MOBILE_NO,    CONT_FAX_AREA_CODE,   "
			+ " CONT_PREFERRED_LANG,    CONT_EMAIL_ID,    CONT_POSTAL_CODE,    CONT_CITY,   "
			+ " CONT_STATE_CODE,    CONT_DOB,    CONT_BIRTH_CERT_NO,    CONT_CATG_CODE,    "
			+ "CONT_MAR_STATUS,    CONT_NATIONALITY_CODE,    CONT_RACE,    CONT_RELIGION,   "
			+ " CONT_AREA,    CONT_REGION,    CONT_AD_BANK_CODE,    CONT_AD_ACC_NO,    "
			+ "CONT_CITY_CODE,    CONT_COUNT_CODE,    CONT_COUNTRY FROM  PM_IL_CONTRACTOR  "
			+ "WHERE  CONT_REF_ID2  = ?";

	String PM_IL_CONTRACTOR_QUERY_REFID1_DETAIL = "SELECT    'X',    CONT_NAME,    CONT_ADDR1,    CONT_ADDR2,    CONT_ADDR3, "
			+ "   CONT_CONTACT,    CONT_PHONE,    CONT_FAX,    CONT_REMARKS,    CONT_DFLT_YN,   "
			+ " CONT_CUST_CODE,    CONT_FRZ_FLAG,    CONT_BL_NAME,    CONT_BL_ADDR1,    CONT_BL_ADDR2,  "
			+ "  CONT_BL_ADDR3,    CONT_BL_CONTACT,    CONT_EMPLOYER_YN,    CONT_EFF_FM_DT,    "
			+ "CONT_EFF_TO_DT,    CONT_REF_NO,    CONT_REF_ID1,    CONT_REF_ID2,    CONT_TEL_AREA_CODE, "
			+ "   CONT_MOBILE_NO,    CONT_FAX_AREA_CODE,    CONT_PREFERRED_LANG,    CONT_EMAIL_ID,   "
			+ " CONT_POSTAL_CODE,    CONT_CITY,    CONT_STATE_CODE,    CONT_DOB,    CONT_BIRTH_CERT_NO, "
			+ "   CONT_CATG_CODE,    CONT_MAR_STATUS,    CONT_NATIONALITY_CODE,    CONT_RACE,   "
			+ " CONT_RELIGION,    CONT_AREA,    CONT_REGION,    CONT_AD_BANK_CODE,    CONT_AD_ACC_NO,  "
			+ "  CONT_CITY_CODE,    CONT_COUNT_CODE,    CONT_COUNTRY FROM  PM_IL_CONTRACTOR "
			+ " WHERE  CONT_REF_ID1  = ?";

	String PM_IL_CONTRACTOR_QUERY_PCCODE_SELECT = "SELECT PC_CODE FROM  PM_CODES  WHERE  PC_TYPE  = 'NATLITY'  AND PC_VALUE  = 1 ";

	String PM_IL_CONTRACTOR_QUERY_UPDATEQUERY = "UPDATE PM_IL_CONTRACTOR SET CONT_NAME=?,CONT_ADDR1=?,CONT_ADDR2=?,CONT_ADDR3=?,"
			+ "CONT_CONTACT=?,CONT_PHONE=?,CONT_FAX=?,CONT_REMARKS=?,CONT_EMPLOYER_YN=?,"
			+ "CONT_LC_PROP_DEP_AMT=?,CONT_LC_PROP_UTIL_AMT=?,CONT_LC_POL_DEP_AMT=?,CONT_LC_POL_UTIL_AMT=?,"
			+ "CONT_EFF_FM_DT=?,CONT_EFF_TO_DT=?,CONT_REF_NO=?,CONT_REF_ID1=?,CONT_REF_ID2=?,CONT_TEL_AREA_CODE=?,"
			+ "CONT_MOBILE_NO=?,CONT_FAX_AREA_CODE=?,CONT_PREFERRED_LANG=?,CONT_EMAIL_ID=?,CONT_POSTAL_CODE=?,"
			+ "CONT_CITY=?,CONT_STATE=?,CONT_DOB=?,CONT_BIRTH_CERT_NO=?,CONT_CATG_CODE=?,CONT_MAR_STATUS=?,"
			+ "CONT_NATIONALITY_CODE=?,CONT_RACE=?,CONT_RELIGION=?,CONT_AREA=?,CONT_REGION=?,CONT_AD_BANK_CODE=?,"
			+ "CONT_AD_ACC_NO=?,CONT_CITY_CODE=?,CONT_STATE_CODE=?,CONT_COUNT_CODE=?,CONT_COUNTRY=?"
			+ " WHERE CONT_CODE=?";
	String PM_IL_CONTRACTOR_QUERY_DELETE_CONT_CODE = "DELETE FROM  PM_IL_CONTRACTOR WHERE CONT_CODE=?";

	String PM_IL_CONTRACTOR_P_CREATE_NUMBER_SELECT_PS_VALUE = "SELECT PS_VALUE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'NUM_GEN_YN'  AND PS_CODE  = 'CONTRACTOR' ";

	String PM_IL_CONTRACTOR_P_CREATE_NUMBER_SELECT_PS_CODE = "SELECT PS_CODE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'IL_CONT_NUM'  AND PS_BL_CODE_DESC  = ?";

	String PM_IL_CONTRACTOR_P_CREATE_NUMBER_SELECT_NGS_YN = "SELECT    'X',    NGS_DISABLE_YN FROM  PM_NUMBER_GEN_SETUP  WHERE  NGS_CODE  = ? ";

	String PM_IL_CONTRACTOR_P_GEN_AUTO_NO_SELECT_NGS_VALUES = "SELECT    NGS_CODE,    NGS_PREFIX_YN,    NGS_PREFIX,    NGS_SUFFIX_YN,    NGS_SUFFIX,"
			+ "NGS_PAD_YN,    NGS_PAD_LENGTH,    NGS_CHK_DIGIT_YN,    NGS_FIRST_NO,    NGS_CURR_NO,"
			+ "NGS_LAST_NO,    NGS_DISABLE_YN FROM  PM_NUMBER_GEN_SETUP  WHERE  NGS_CODE  = ? ";

	String PM_IL_CONTRACTOR_P_GEN_AUTO_NO_SELECT_NGS_CURRNO = "SELECT DECODE(SIGN(NGS_LAST_NO - NGS_CURR_NO), - 1, NGS_FIRST_NO, NGS_CURR_NO) FROM  PM_NUMBER_GEN_SETUP  WHERE  NGS_CODE  = ? ";

	String PM_IL_CONTRACTOR_P_GEN_AUTO_NO_UPDATE_PM_NOGENSETUP = "UPDATE   PM_NUMBER_GEN_SETUP    SET NGS_CURR_NO =?+ 1  WHERE  NGS_CODE  =? ";
	
	String PM_IL_CONTRACTOR_EMPLOYER_YN="SELECT  LIV_CODE,LIV_CODE_DESC FROM PP_LIST_ITEM,PP_LIST_ITEM_VALUES WHERE LI_SYS_PARAM = LIV_SYS_PARAM AND LI_MODULE_NAME = ? AND LI_BLOCK_NAME = ? AND LI_ITEM_NAME = ?";

   String PM_IL_CONTRACTOR_WHEN_CREATE_RECORD_SELECT_PC_CODE_FOR_RELIGION ="SELECT PC_CODE FROM  PM_CODES  WHERE  PC_TYPE  = 'RELIGION'  AND PC_VALUE  = 1 ";

	String PM_IL_CONTRACTOR_WHEN_CREATE_RECORD_SELECT_PC_CODE_FOR_RACE="SELECT PC_CODE FROM  PM_CODES  WHERE  PC_TYPE  = 'RACE'  AND PC_VALUE  = 1";
	
	String PM_IL_CONTRACTOR_WHEN_CREATE_RECORD_SELECT_PC_CODE_FOR_NATIONALITY="SELECT PC_CODE FROM  PM_CODES  WHERE  PC_TYPE  = 'NATLITY'  AND PC_VALUE  = 1 ";
	
	String PM_IL_CONTRACTOR_PREPARE_MART_STAT_CODE_LIST="SELECT PS_CODE,PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'MARI_STAT' AND ROWNUM<25 ORDER BY 1 ASC";

	/*
	 * commented by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016
	 * 
	 * String PM_IL_CONTRACTOR_PREPARE_MART_STAT_CODE_LIST_LIKE="SELECT PS_CODE,PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'MARI_STAT' AND (PS_CODE LIKE ? OR PS_CODE_DESC LIKE ? ) AND ROWNUM<25 ORDER BY 1 ASC";*/
	/*Added by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016*/
	String PM_IL_CONTRACTOR_PREPARE_MART_STAT_CODE_LIST_LIKE="SELECT PS_CODE,PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'MARI_STAT' AND (UPPER(PS_CODE) LIKE UPPER(?) OR UPPER(PS_CODE_DESC) LIKE UPPER(?) ) AND ROWNUM<25 ORDER BY 1 ASC";
	/*end*/
	String PM_IL_CONTRACTOR_PREPARE_CATG_CODE_LIST="SELECT PS_CODE,PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'CATG' AND ROWNUM<25 ORDER BY 1 ASC ";
	
	String PM_IL_CONTRACTOR_PREPARE_STATE_CODE_LIST="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'STATE' AND NVL(PC_FRZ_FLAG,'N')= 'N' AND ROWNUM<25 ORDER BY 1 ASC ";
	
	/*
	 * 
	 * commented by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016
	 * 
	 * String PM_IL_CONTRACTOR_PREPARE_CATG_CODE_LIST_LIKE="SELECT PS_CODE,PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'CATG'AND (PS_CODE LIKE ? OR PS_CODE_DESC LIKE ? ) AND ROWNUM<25 ORDER BY 1 ASC ";
	 * String PM_IL_CONTRACTOR_PREPARE_STATE_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'STATE' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND (PC_CODE LIKE ? OR PC_DESC LIKE ? ) AND ROWNUM<25 ORDER BY 1 ASC ";*/
	
	/*Added by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016*/
	String PM_IL_CONTRACTOR_PREPARE_STATE_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'STATE' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND (UPPER(PC_CODE) LIKE UPPER(?) OR UPPER(PC_DESC) LIKE UPPER(?) ) AND ROWNUM<25 ORDER BY 1 ASC ";
	String PM_IL_CONTRACTOR_PREPARE_CATG_CODE_LIST_LIKE="SELECT PS_CODE,PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'CATG'AND (UPPER(PS_CODE) LIKE UPPER(?) OR UPPER(PS_CODE_DESC) LIKE UPPER(?) ) AND ROWNUM<25 ORDER BY 1 ASC ";
	/*End*/
	String PM_IL_CONTRACTOR_PREPARE_CITY_CODE_LIST="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'CITY' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM<25 ORDER BY 1 ASC ";
	
	/*
	 * commented by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016
	 * 
	 * String PM_IL_CONTRACTOR_PREPARE_CITY_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'CITY' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND  (PC_CODE LIKE ? OR PC_DESC LIKE ? ) AND ROWNUM<25 ORDER BY 1 ASC ";*/

	/*Added by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016*/
	String PM_IL_CONTRACTOR_PREPARE_CITY_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'CITY' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND  (UPPER(PC_CODE) LIKE UPPER(?) OR UPPER(PC_DESC) LIKE UPPER(?) ) AND ROWNUM<25 ORDER BY 1 ASC ";
	/*end*/
	String PM_IL_CONTRACTOR_PREPARE_RELEGION_CODE_LIST="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'RELIGION' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM<25 ORDER BY 1 ASC ";

	/*
	 * commented by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016
	 * 
	 * String PM_IL_CONTRACTOR_PREPARE_RACE_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'RACE' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND  (PC_CODE LIKE ? OR PC_DESC LIKE ? ) AND ROWNUM<25 ORDER BY 1 ASC ";
	 * String PM_IL_CONTRACTOR_PREPARE_RELEGION_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'RELIGION' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND  (PC_CODE LIKE ? OR PC_DESC LIKE ? ) AND ROWNUM<25 ORDER BY 1 ASC " ;*/
	
	/*Added by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016*/
	String PM_IL_CONTRACTOR_PREPARE_RELEGION_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'RELIGION' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND  (UPPER(PC_CODE) LIKE UPPER(?) OR UPPER(PC_DESC) LIKE UPPER(?) ) AND ROWNUM<25 ORDER BY 1 ASC " ;
	String PM_IL_CONTRACTOR_PREPARE_RACE_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'RACE' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND  (UPPER(PC_CODE) LIKE UPPER(?) OR UPPER(PC_DESC) LIKE UPPER(?) ) AND ROWNUM<25 ORDER BY 1 ASC ";
	/*end*/
	String PM_IL_CONTRACTOR_PREPARE_RACE_CODE_LIST="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'RACE' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM<25 ORDER BY 1 ASC ";

	
	
	String PM_IL_CONTRACTOR_PREPARE_COUNTRY_CODE_LIST="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'COUNTRY' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM<25 ORDER BY 1 ASC ";
	
	/*
	 * 
	 * commented by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016
	 * String PM_IL_CONTRACTOR_PREPARE_BANK_CODE_LIST_LIKE="SELECT BANK_CODE, BANK_NAME FROM FM_BANK WHERE (BANK_CODE LIKE ? OR BANK_NAME LIKE ?) AND ROWNUM<25 ORDER BY 1 ASC "; 
	 * String PM_IL_CONTRACTOR_PREPARE_COUNTRY_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'COUNTRY' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND  (PC_CODE LIKE ? OR PC_DESC LIKE ? ) AND ROWNUM<25 ORDER BY 1 ASC ";*/
	
	/*Added by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016*/
	String PM_IL_CONTRACTOR_PREPARE_COUNTRY_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'COUNTRY' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND  (UPPER(PC_CODE) LIKE UPPER(?) OR UPPER(PC_DESC) LIKE UPPER(?) ) AND ROWNUM<25 ORDER BY 1 ASC ";
	
	String PM_IL_CONTRACTOR_PREPARE_BANK_CODE_LIST_LIKE="SELECT BANK_CODE, BANK_NAME FROM FM_BANK WHERE (UPPER(BANK_CODE) LIKE UPPER(?) OR UPPER(BANK_NAME) LIKE UPPER(?)) AND ROWNUM<25 ORDER BY 1 ASC ";
	/*end*/
	String PM_IL_CONTRACTOR_PREPARE_BANK_CODE_LIST="SELECT BANK_CODE, BANK_NAME FROM FM_BANK";
	
	String PM_IL_CONTRACTOR_PREPARE_NATIONALITY_CODE_LIST="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'NATLITY' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM<25 ORDER BY 1 ASC ";
	
	/*commented by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016
	 * 
	 * String PM_IL_CONTRACTOR_PREPARE_NATIONALITY_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'NATLITY' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND  (PC_CODE LIKE ? OR PC_DESC LIKE ? ) AND ROWNUM<25 ORDER BY 1 ASC ";*/
	/*Added by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016*/
	String PM_IL_CONTRACTOR_PREPARE_NATIONALITY_CODE_LIST_LIKE="SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'NATLITY' AND	NVL(PC_FRZ_FLAG,'N') = 'N' AND  (UPPER(PC_CODE) LIKE UPPER(?) OR UPPER(PC_DESC) LIKE UPPER(?) ) AND ROWNUM<25 ORDER BY 1 ASC ";
	/*end*/
	String PM_IL_CONTRACTOR_SELECT_PS_VALUE="SELECT PS_VALUE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'NUM_GEN_YN'  AND PS_CODE  = 'CONTRACTOR' ";
	
	String PM_IL_CONTRACTOR_SELECT_X_FOR_CONTCODE="SELECT 'X' FROM  PM_IL_CONTRACTOR  WHERE  CONT_CODE  =?";

	String PM_IL_CONTRACTOR_SELECT_X_AND_DISABLE_YN="SELECT    'X',    NGS_DISABLE_YN FROM  PM_NUMBER_GEN_SETUP  WHERE  NGS_CODE  =  (SELECT PS_CODE  FROM  PP_SYSTEM   WHERE  PS_TYPE  = 'IL_CONT_NUM'   AND PS_BL_CODE_DESC  = ?  )";
	
	String PM_IL_CONTRACTOR_SELECT_X_FROM_PP_SYSTEM="SELECT 'X' FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'IL_CONT_NUM'  AND PS_BL_CODE_DESC  = ? ";
	
	String PM_IL_CONTRACTOR_ERROR_MESSAGE_REF_ID="SELECT EM_FOR_MSG FROM PP_ERROR_MESSAGE WHERE EM_ERR_NO='91240'";
	
	String PM_IL_CONTRACTOR_SELECT_REF_ID_1="SELECT SUBSTR( ?, 1, 6) FROM  DUAL";
	
	String PM_IL_CONTRACTOR_SELECT_X_FOR_REF_ID_1_AND_ROW_ID="SELECT 'X' FROM  PM_IL_CONTRACTOR  WHERE  CONT_REF_ID1  = ?  AND ROWID  <> ? ";

	String PM_IL_CONTRACTOR_WHEN_NEW_FORM_INSTANCE_SELECT_X_FOR_PS_TYPE="SELECT 'X'  FROM PP_SYSTEM  WHERE PS_TYPE = 'IL_CONT_NUM'";
	String PM_IL_CONTRACTOR_WHEN_NEW_FORM_INSTANCE_SELECT_DETAILS_FROM_NUM_SETUP="SELECT 'X',NGS_DISABLE_YN  FROM   PM_NUMBER_GEN_SETUP WHERE " +
																					" NGS_CODE = (SELECT PS_CODE FROM   PP_SYSTEM WHERE  PS_TYPE " +
																					" = 'IL_CONT_NUM')";
}
