package com.iii.pel.forms.PILM007;
public interface PILM007_QUERYCONSTANTS {
	String CR_COVER_CODE$WHEN_VALIDATE_ITEM_CURSOR_QRY_1=" SELECT 1 FROM   PM_IL_PLAN WHERE  PLAN_CODE =  ?  AND    PLAN_TYPE='U' AND    NVL( ? ,'XX') IN ('PA','SP','SPP','PP','PPS','PS','PPP','SMIN','SMAX') ";
	String CR_COVER_CODE$WHEN_VALIDATE_ITEM_CURSOR_QRY_2=" SELECT 1 FROM   PM_IL_PLAN WHERE  PLAN_CODE IN (SELECT PROD_PLAN_CODE FROM   PM_IL_PRODUCT,PM_IL_PROD_APPL_COVER WHERE  PROD_CODE =PAC_PROD_CODE AND    PAC_COVER_CODE =  ? ) AND    PLAN_TYPE='U' AND    NVL( ? ,'XX') IN ('PA','SP','SPP','PP','PPS','PS','PPP','SMIN','SMAX') ";
	String CR_COVER_CODE$WHEN_VALIDATE_ITEM_CURSOR_QRY_3=" SELECT COVER_CLASS FROM   PM_IL_COVER WHERE  COVER_CODE =  ? ";
	String CR_LOSS_TYPE$WHEN_VALIDATE_ITEM_CURSOR_QRY_1=" SELECT PS_CODE FROM PP_SYSTEM WHERE PS_TYPE LIKE 'IL_DEATH' AND PS_CODE = ?";
	String COVER_CODE_LOV = "SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE COVER_FRZ_FLAG ='N' AND ROWNUM<= ? ORDER BY 1";
	String COVER_CODE_LOV_LIKE = "SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE (COVER_CODE LIKE ? OR COVER_DESC LIKE ?) AND COVER_FRZ_FLAG ='N' AND ROWNUM<= ? ORDER BY 1";
	String LOSS_TYPE_LOV = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_LOS_TYP' AND PC_FRZ_FLAG = 'N' ORDER BY 1";
	String LOSS_TYPE_LOV_LIKE = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_LOS_TYP' AND (PC_CODE LIKE ? OR PC_DESC LIKE ?) AND PC_FRZ_FLAG = 'N' ORDER BY 1";
	String DISABLE_TYPE_LOV = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_DIS_TYP' AND PC_FRZ_FLAG = 'N' AND ROWNUM<=? ORDER BY 1";
	String DISABLE_TYPE_LOV_LIKE = "SELECT PC_CODE,PC_DESC FROM   PM_CODES WHERE  PC_TYPE = 'IL_DIS_TYP' AND (PC_CODE LIKE ? OR PC_DESC LIKE ?) AND PC_FRZ_FLAG = 'N' AND ROWNUM<=? ORDER BY 1";

	String FORMULA_LOV = "SELECT FRM_CODE,FRM_DESC FROM PM_IL_FORMULA WHERE ROWNUM <= ? ORDER BY 1";
}
