package com.iii.pel.forms.PILQ142;

public class PILQ142_COMPOSITE_ACTION {

	private PILQ142_PT_IL_SUB_STD_REG_ACTION PILQ142_PT_IL_SUB_STD_REG_ACTION_BEAN;
	
	private PT_IL_SUB_STD_REG PT_IL_SUB_STD_REG_BEAN;
	
	public PILQ142_COMPOSITE_ACTION() {
		// TODO Auto-generated constructor stub
		PILQ142_PT_IL_SUB_STD_REG_ACTION_BEAN = new PILQ142_PT_IL_SUB_STD_REG_ACTION();
		PT_IL_SUB_STD_REG_BEAN = new PT_IL_SUB_STD_REG();
		PILQ142_PT_IL_SUB_STD_REG_ACTION_BEAN.compositeAction = this;
	}

	public PILQ142_PT_IL_SUB_STD_REG_ACTION getPILQ142_PT_IL_SUB_STD_REG_ACTION_BEAN() {
		return PILQ142_PT_IL_SUB_STD_REG_ACTION_BEAN;
	}

	public void setPILQ142_PT_IL_SUB_STD_REG_ACTION_BEAN(
			PILQ142_PT_IL_SUB_STD_REG_ACTION pILQ142_PT_IL_SUB_STD_REG_ACTION_BEAN) {
		PILQ142_PT_IL_SUB_STD_REG_ACTION_BEAN = pILQ142_PT_IL_SUB_STD_REG_ACTION_BEAN;
	}

	public PT_IL_SUB_STD_REG getPT_IL_SUB_STD_REG_BEAN() {
		return PT_IL_SUB_STD_REG_BEAN;
	}

	public void setPT_IL_SUB_STD_REG_BEAN(PT_IL_SUB_STD_REG pT_IL_SUB_STD_REG_BEAN) {
		PT_IL_SUB_STD_REG_BEAN = pT_IL_SUB_STD_REG_BEAN;
	}
	
}
