package com.iii.pel.forms.PILQ138;

public class PILQ138_COMPOSITE_ACTION {

	private PREMIUM_ENQU_ACTION PREMIUM_ENQU_ACTION_BEAN;

	public PREMIUM_ENQU_ACTION getPREMIUM_ENQU_ACTION_BEAN() {
		return PREMIUM_ENQU_ACTION_BEAN;
	}

	public void setPREMIUM_ENQU_ACTION_BEAN(
			PREMIUM_ENQU_ACTION pREMIUM_ENQU_ACTION_BEAN) {
		PREMIUM_ENQU_ACTION_BEAN = pREMIUM_ENQU_ACTION_BEAN;
	}
	
	public PILQ138_COMPOSITE_ACTION()
	{
		PREMIUM_ENQU_ACTION_BEAN=new PREMIUM_ENQU_ACTION();
		PREMIUM_ENQU_ACTION_BEAN.compositeAction=this;
	}
}
