package com.iii.pel.forms.PP_LIST_ITEM;

public interface PP_LIST_ITEM_QUERY_CONSTANTS {

	String SELECT_LIST_ITEMS = "SELECT TBL1.ROWID,TBL1.* FROM PP_LIST_ITEM TBL1 WHERE ROWID = ?";
	
	String FETCH_LIST_ITEM_SERCH_DETAILS = "SELECT ROWID,LI_MODULE_NAME,LI_BLOCK_NAME,LI_ITEM_NAME," +
			"LI_SYS_PARAM,LI_REMARKS FROM PP_LIST_ITEM WHERE LI_MODULE_NAME LIKE NVL(?, LI_MODULE_NAME)" +
			" AND LI_BLOCK_NAME LIKE NVL(?, LI_BLOCK_NAME) AND LI_ITEM_NAME LIKE NVL(?, LI_ITEM_NAME)";

	String SELECT_LIST_ITEMS_VALUES = "SELECT TBL1.ROWID,TBL1.* FROM PP_LIST_ITEM_VALUES TBL1 WHERE LIV_SYS_PARAM = ?";
	
}
