package com.iii.pel.forms.PILP017;
public interface PILP017_QUERYCONSTANTS { 
	/*changed by raja on 27-06-2017 for ZBILQC-1729595*/
	/*Added by ganesh on 31-05-2017, ZBILQC-1724500 */
	/*final String POL_EMPLOYER_CODE_LOV = "SELECT CONT_CODE, CONT_NAME  FROM PM_IL_CONTRACTOR WHERE CONT_EMPLOYER_YN ='Y' AND ROWNUM < ? UNION SELECT BANK_CODE,BANK_NAME FROM FM_BANK WHERE ROWNUM < ?";
	final String POL_EMPLOYER_CODE_LOV_LIKE = "SELECT CONT_CODE, CONT_NAME  FROM PM_IL_CONTRACTOR WHERE CONT_EMPLOYER_YN ='Y' AND (UPPER(CONT_CODE) LIKE ? OR UPPER(CONT_NAME) LIKE ?) AND ROWNUM < ? UNION SELECT BANK_CODE,BANK_NAME FROM FM_BANK WHERE (UPPER(BANK_CODE) LIKE ? OR UPPER(BANK_NAME) LIKE ?) AND ROWNUM < ?";*/
	/*end*/
	
	final String POL_EMPLOYER_CODE_LOV = "SELECT DUM_EMPLOYER_CODE, CONT_NAME FROM PM_IL_DATA_UPLOAD_MAPPING, PM_IL_CONTRACTOR WHERE DUM_EMPLOYER_TYPE = 'U' AND DUM_EMPLOYER_CODE = CONT_CODE AND ROWNUM < ? UNION SELECT DUM_EMPLOYER_CODE, BANK_NAME FROM PM_IL_DATA_UPLOAD_MAPPING, PM_BANK WHERE DUM_EMPLOYER_TYPE = 'U' AND DUM_EMPLOYER_CODE = BANK_CODE  AND ROWNUM < ? ";
	final String POL_EMPLOYER_CODE_LOV_LIKE = "SELECT DUM_EMPLOYER_CODE, CONT_NAME FROM PM_IL_DATA_UPLOAD_MAPPING, PM_IL_CONTRACTOR WHERE DUM_EMPLOYER_TYPE = 'U' AND DUM_EMPLOYER_CODE = CONT_CODE AND (UPPER(DUM_EMPLOYER_CODE) LIKE ? OR UPPER(CONT_NAME) LIKE ?) AND ROWNUM < ?  UNION SELECT DUM_EMPLOYER_CODE, BANK_NAME FROM PM_IL_DATA_UPLOAD_MAPPING, PM_BANK WHERE DUM_EMPLOYER_TYPE = 'U' AND DUM_EMPLOYER_CODE = BANK_CODE  AND (UPPER(DUM_EMPLOYER_CODE) LIKE ? OR UPPER(BANK_NAME) LIKE ? ) AND ROWNUM < ? ";
	/*end*/
}