package com.iii.pel.forms.PGIM_LOV_DEFN;

public interface PGIM_LOV_DEFN_QUERY_CONSTANTS {

	String FETCH_LOV_DETAILS = "SELECT TBL1.ROWID, TBL1.* FROM PGIM_LOV_DEFN TBL1 WHERE PLD_PROG_CODE = ?";
	
	String FETCH_LOV_SERCH_DETAILS = "SELECT ROWID,PLD_PROG_CODE,PLD_BLOCK_NAME,PLD_FIELD_NAME," +
			"PLD_LOV_TITLE FROM PGIM_LOV_DEFN WHERE PLD_PROG_CODE LIKE NVL(?, PLD_PROG_CODE) " +
			"AND PLD_BLOCK_NAME LIKE NVL(?, PLD_BLOCK_NAME) " +
			"AND PLD_LOV_TITLE = NVL(?, PLD_LOV_TITLE)";

}
