package com.iii.pel.forms.PILP039_APAC;

public interface PILP039_APAC_RI_CLOSING_CONSTANTS {
	String PILP039_APAC_RI_CLOSING_M_PROD_FM_LOV = "SELECT DISTINCT POL_PROD_CODE ,PROD_DESC FROM PT_IL_POLICY ,PM_IL_PRODUCT"+ 
" WHERE POL_PROD_CODE = PROD_CODE";

}
