package com.iii.pel.forms.PILT003_APAC;
public interface PILT003_APAC_QUERYCONSTANTS { 
	
	String ACV_FLEX_04_Values="SELECT LIV_CODE, LIV_CODE_DESC FROM PP_LIST_ITEM_VALUES WHERE LIV_SYS_PARAM = 'IL_PAY_MODE'AND ROWNUM <= ? AND LIV_CODE IS NOT NULL ORDER BY 1";
	/*commented by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016
	 * 
	 * String ACV_FLEX_04_Values_LIKE="SELECT LIV_CODE, LIV_CODE_DESC FROM PP_LIST_ITEM_VALUES WHERE (LIV_CODE LIKE ? OR LIV_CODE_DESC LIKE ?) AND LIV_SYS_PARAM = 'IL_PAY_MODE' AND LIV_CODE IS NOT NULL AND ROWNUM <= ? ORDER BY 1";*/
	/*Added by Ameen for lov lower case issue ssp call id FALCONLIFE-1344105 on 14-10-2016*/
	String ACV_FLEX_04_Values_LIKE="SELECT LIV_CODE, LIV_CODE_DESC FROM PP_LIST_ITEM_VALUES WHERE (UPPER(LIV_CODE) LIKE UPPER(?) OR UPPER(LIV_CODE_DESC) LIKE UPPER(?)) AND LIV_SYS_PARAM = 'IL_PAY_MODE' AND LIV_CODE IS NOT NULL AND ROWNUM <= ? ORDER BY 1";
	/*end*/
	
}