package com.iii.pel.forms.PILT003_APAC;

public class PILT_003_COMPOSITE_BEAN {
	
	private PT_IL_POLICY_ACTION PT_IL_POLICY_ACTION;
	
	private PT_IL_PREM_COLL_ACTION PT_IL_PREM_COLL_ACTION;
	
	private PT_IL_LOAN_INT_COLL_ACTION PT_IL_LOAN_INT_COLL_ACTION;
	
	private PT_AGENT_COMM_VALUES_ACTION PT_AGENT_COMM_VALUES_ACTION;
	
	private PT_IL_BROKER_VALUES_ACTION PT_IL_BROKER_VALUES_ACTION;
	
	private PT_IL_PREM_COLL_CHARGE_ACTION PT_IL_PREM_COLL_CHARGE_ACTION;
	
	private PT_IL_PREM_COLL_CVR_DTL_ACTION PT_IL_PREM_COLL_CVR_DTL_ACTION;
	
	private PT_IL_PYMT_DTLS_ACTION PT_IL_PYMT_DTLS_ACTION;
	
	private DUMMY_ACTION DUMMY_ACTION;

	
	public PILT_003_COMPOSITE_BEAN(){
		PT_IL_POLICY_ACTION = new PT_IL_POLICY_ACTION();
		PT_IL_PREM_COLL_ACTION = new PT_IL_PREM_COLL_ACTION();
		PT_IL_LOAN_INT_COLL_ACTION = new PT_IL_LOAN_INT_COLL_ACTION();
		PT_AGENT_COMM_VALUES_ACTION = new PT_AGENT_COMM_VALUES_ACTION();
		PT_IL_BROKER_VALUES_ACTION = new PT_IL_BROKER_VALUES_ACTION();
		PT_IL_PREM_COLL_CHARGE_ACTION = new PT_IL_PREM_COLL_CHARGE_ACTION();
		PT_IL_PREM_COLL_CVR_DTL_ACTION = new PT_IL_PREM_COLL_CVR_DTL_ACTION();
		PT_IL_PYMT_DTLS_ACTION = new PT_IL_PYMT_DTLS_ACTION();
		DUMMY_ACTION = new DUMMY_ACTION();
		
	}
	
	
	
	
	public PT_IL_POLICY_ACTION getPT_IL_POLICY_ACTION() {
		return PT_IL_POLICY_ACTION;
	}

	public void setPT_IL_POLICY_ACTION(PT_IL_POLICY_ACTION pt_il_policy_action) {
		PT_IL_POLICY_ACTION = pt_il_policy_action;
	}

	public PT_IL_PREM_COLL_ACTION getPT_IL_PREM_COLL_ACTION() {
		return PT_IL_PREM_COLL_ACTION;
	}

	public void setPT_IL_PREM_COLL_ACTION(
			PT_IL_PREM_COLL_ACTION pt_il_prem_coll_action) {
		PT_IL_PREM_COLL_ACTION = pt_il_prem_coll_action;
	}

	public PT_IL_LOAN_INT_COLL_ACTION getPT_IL_LOAN_INT_COLL_ACTION() {
		return PT_IL_LOAN_INT_COLL_ACTION;
	}

	public void setPT_IL_LOAN_INT_COLL_ACTION(
			PT_IL_LOAN_INT_COLL_ACTION pt_il_loan_int_coll_action) {
		PT_IL_LOAN_INT_COLL_ACTION = pt_il_loan_int_coll_action;
	}

	public PT_AGENT_COMM_VALUES_ACTION getPT_AGENT_COMM_VALUES_ACTION() {
		return PT_AGENT_COMM_VALUES_ACTION;
	}

	public void setPT_AGENT_COMM_VALUES_ACTION(
			PT_AGENT_COMM_VALUES_ACTION pt_agent_comm_values_action) {
		PT_AGENT_COMM_VALUES_ACTION = pt_agent_comm_values_action;
	}

	public PT_IL_BROKER_VALUES_ACTION getPT_IL_BROKER_VALUES_ACTION() {
		return PT_IL_BROKER_VALUES_ACTION;
	}

	public void setPT_IL_BROKER_VALUES_ACTION(
			PT_IL_BROKER_VALUES_ACTION pt_il_broker_values_action) {
		PT_IL_BROKER_VALUES_ACTION = pt_il_broker_values_action;
	}

	public PT_IL_PREM_COLL_CHARGE_ACTION getPT_IL_PREM_COLL_CHARGE_ACTION() {
		return PT_IL_PREM_COLL_CHARGE_ACTION;
	}

	public void setPT_IL_PREM_COLL_CHARGE_ACTION(
			PT_IL_PREM_COLL_CHARGE_ACTION pt_il_prem_coll_charge_action) {
		PT_IL_PREM_COLL_CHARGE_ACTION = pt_il_prem_coll_charge_action;
	}

	public PT_IL_PREM_COLL_CVR_DTL_ACTION getPT_IL_PREM_COLL_CVR_DTL_ACTION() {
		return PT_IL_PREM_COLL_CVR_DTL_ACTION;
	}

	public void setPT_IL_PREM_COLL_CVR_DTL_ACTION(
			PT_IL_PREM_COLL_CVR_DTL_ACTION pt_il_prem_coll_cvr_dtl_action) {
		PT_IL_PREM_COLL_CVR_DTL_ACTION = pt_il_prem_coll_cvr_dtl_action;
	}

	public PT_IL_PYMT_DTLS_ACTION getPT_IL_PYMT_DTLS_ACTION() {
		return PT_IL_PYMT_DTLS_ACTION;
	}

	public void setPT_IL_PYMT_DTLS_ACTION(
			PT_IL_PYMT_DTLS_ACTION pt_il_pymt_dtls_action) {
		PT_IL_PYMT_DTLS_ACTION = pt_il_pymt_dtls_action;
	}

	public DUMMY_ACTION getDUMMY_ACTION() {
		return DUMMY_ACTION;
	}

	public void setDUMMY_ACTION(DUMMY_ACTION dummy_action) {
		DUMMY_ACTION = dummy_action;
	}

}
