package com.iii.pel.forms.PILM054_APAC;

public interface PILM054_APAC_SQL_CONSTANTS {
	
	/*String SEARCH_ACCT_CODE_LIST = "SELECT RAS_MAIN_ACNT_CODE, RAS_SUB_ACNT_CODE,RAS_DIVN_CODE FROM" +
			" PM_IL_RI_ACCOUNT_SETUP WHERE RAS_MAIN_ACNT_CODE LIKE NVL(?,RAS_MAIN_ACNT_CODE) AND " +
			"RAS_SUB_ACNT_CODE LIKE NVL(?, RAS_SUB_ACNT_CODE) AND RAS_DIVN_CODE LIKE NVL(?,RAS_DIVN_CODE)";	
	*/
	// [BugId:TRACK_PREMIAGDC_GL.10.5-00163:Modified query for fetching record from search screen : Added by : Shankar Bodduluri : 31-Mar-2009
	String SEARCH_ACCT_CODE_LIST = "SELECT RAS_MAIN_ACNT_CODE, RAS_SUB_ACNT_CODE,RAS_DIVN_CODE,ROWID FROM" +
				" PM_IL_RI_ACCOUNT_SETUP " +
				"WHERE NVL(RAS_MAIN_ACNT_CODE,'***') LIKE NVL(?,NVL(RAS_MAIN_ACNT_CODE,'***')) " +
				"AND  NVL(RAS_SUB_ACNT_CODE,'***') LIKE NVL(?, NVL(RAS_SUB_ACNT_CODE,'***')) " +
				"AND NVL(RAS_DIVN_CODE,'***') LIKE NVL(?,NVL(RAS_DIVN_CODE,'***'))";	

	String PM_IL_RI_ACNT_FETCH_FORM_VALUES="SELECT PM_IL_RI_ACCOUNT_SETUP.ROWID," +
			"RAS_FRZ_FLAG,RAS_DIVN_FM_CODE,RAS_DIVN_TO_CODE,RAS_DEPT_FM_CODE," +
			"RAS_DEPT_TO_CODE,RAS_CLASS_FM_CODE,RAS_CLASS_TO_CODE," +
			"RAS_SRC_BUS_FM,RAS_SRC_BUS_TO,RAS_PROD_FM_CODE,RAS_PROD_TO_CODE," +
			"RAS_COVER_FM_CODE,RAS_COVER_TO_CODE,RAS_CUST_CLS_FM_CODE,RAS_CUST_CLS_TO_CODE," +
			"RAS_NB_REN_TYPE,RAS_FORCE_DIVN_YN,RAS_SETUP_TYPE,RAS_FORCE_DEPT_YN," +
			"RAS_TREATY_TYPE,RAS_MAIN_ACNT_CODE,RAS_SUB_ACNT_CODE,RAS_DIVN_CODE," +
			"RAS_DEPT_CODE,RAS_ANLY_CODE_1,RAS_ANLY_CODE_2,RAS_ACTY_CODE_1,RAS_ACTY_CODE_2" +
			" FROM PM_IL_RI_ACCOUNT_SETUP WHERE RAS_MAIN_ACNT_CODE=? AND" +
			" RAS_SUB_ACNT_CODE=? AND RAS_DIVN_CODE=?";
	
	String PM_IL_RI_ACCOUNT_SETUP_SelectDrpDwnValues="SELECT LIV_CODE,LIV_CODE_DESC"
		   +" FROM PP_LIST_ITEM,PP_LIST_ITEM_VALUES WHERE LI_SYS_PARAM = LIV_SYS_PARAM"
		   +" AND LI_MODULE_NAME = '{0}' AND LI_BLOCK_NAME = '{1}' AND LI_ITEM_NAME = '{2}'";
	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DIVISION to FM_DIVISION. Added by : Mallika.S, 31-Mar-2009 */
	String divLov = "SELECT DIVN_CODE,DIVN_NAME FROM FM_DIVISION WHERE DIVN_COMP_CODE = ?" +
			" AND NVL(DIVN_FRZ_FLAG, 'N') = 'N' AND EXISTS (SELECT 1 FROM PM_APPR_DEPT_SETUP" +
			" WHERE ADS_DIVN_CODE = DIVN_CODE AND ADS_USER_ID = NVL(?,ADS_USER_ID)" +
			" AND ADS_FRZ_FLAG = 'N') ORDER BY 1 ASC"; 
	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DIVISION to FM_DIVISION. Added by : Mallika.S, 31-Mar-2009 */
	String divLov1 = "SELECT DIVN_CODE,DIVN_NAME FROM FM_DIVISION WHERE DIVN_COMP_CODE = ?" +
	" AND NVL(DIVN_FRZ_FLAG, 'N') = 'N' AND EXISTS (SELECT 1 FROM PM_APPR_DEPT_SETUP" +
	" WHERE ADS_DIVN_CODE = DIVN_CODE AND ADS_USER_ID = NVL(?,ADS_USER_ID)" +
	" AND ADS_FRZ_FLAG = 'N') AND DIVN_CODE LIKE ? ORDER BY 1 ASC" ; 

	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DEPARTMENT to FM_DEPARTMENT. Added by : Mallika.S, 31-Mar-2009 */
	String deptLov="SELECT DEPT_CODE,DEPT_NAME FROM FM_DEPARTMENT WHERE DEPT_COMP_CODE = ?" +
			" AND DEPT_DIVN_CODE = ? AND DEPT_FRZ_FLAG  = 'N' AND EXISTS" +
			" (SELECT 1 FROM PM_APPR_DEPT_SETUP WHERE ADS_DIVN_CODE = DEPT_DIVN_CODE" +
			" AND ADS_DEPT_CODE = DEPT_CODE AND ADS_USER_ID = NVL(?,ADS_USER_ID)" +
			" AND ADS_FRZ_FLAG = 'N') ORDER BY 1 ASC";
	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DEPARTMENT to FM_DEPARTMENT. Added by : Mallika.S, 31-Mar-2009 */
	String deptLov1="SELECT DEPT_CODE,DEPT_NAME FROM FM_DEPARTMENT WHERE DEPT_COMP_CODE = ?" +
	" AND DEPT_DIVN_CODE = ? AND DEPT_FRZ_FLAG  = 'N' AND EXISTS" +
	" (SELECT 1 FROM PM_APPR_DEPT_SETUP WHERE ADS_DIVN_CODE = DEPT_DIVN_CODE" +
	" AND ADS_DEPT_CODE = DEPT_CODE AND ADS_USER_ID = NVL(?,ADS_USER_ID)" +
	" AND ADS_FRZ_FLAG = 'N') AND DEPT_CODE LIKE ? ORDER BY 1 ASC";
	
	String mainAcntCodeLov = "SELECT MAIN_ACNT_CODE,MAIN_ACNT_NAME FROM FM_MAIN_ACCOUNT" +
			" WHERE NVL(MAIN_FRZ_FLAG,'N') = 'N' ORDER BY 1 ASC";
	
	String mainAcntCodeLov1 = "SELECT MAIN_ACNT_CODE,MAIN_ACNT_NAME FROM FM_MAIN_ACCOUNT" +
	" WHERE NVL(MAIN_FRZ_FLAG,'N') = 'N' AND MAIN_ACNT_CODE LIKE ? ORDER BY 1 ASC" ;
	
	String analysis1Lov = "SELECT ANLY_CODE,ANLY_NAME FROM FM_ANALYSIS " +
			"WHERE ANLY_HEAD_NO ='1' AND NVL(ANLY_FRZ_FLAG,'N') = 'N'";
	
	String analysis1Lov1 = "SELECT ANLY_CODE,ANLY_NAME FROM FM_ANALYSIS " +
	"WHERE ANLY_HEAD_NO ='1' AND NVL(ANLY_FRZ_FLAG,'N') = 'N' AND ANLY_CODE LIKE '{1}%'";
	
	String analysis2Lov = "SELECT ANLY_CODE,ANLY_NAME FROM FM_ANALYSIS " +
	"WHERE ANLY_HEAD_NO ='2' AND NVL(ANLY_FRZ_FLAG,'N') = 'N'";

	String analysis2Lov1 = "SELECT ANLY_CODE,ANLY_NAME FROM FM_ANALYSIS " +
	"WHERE ANLY_HEAD_NO ='2' AND NVL(ANLY_FRZ_FLAG,'N') = 'N' AND ANLY_CODE LIKE '{1}%'";
	
	String subAcntCodelov = "SELECT SUB_ACNT_CODE,SUB_ACNT_NAME FROM FM_SUB_ACCOUNT" +
			" WHERE SUB_ACNT_CODE IN (SELECT MS_SUB_ACNT_CODE FROM  FM_MAIN_SUB" +
			" WHERE MS_MAIN_ACNT_CODE = ?) AND NVL(SUB_FRZ_FLAG,'N') = 'N' ORDER BY 1 ASC";
	
	String subAcntCodelov1 = "SELECT SUB_ACNT_CODE,SUB_ACNT_NAME FROM FM_SUB_ACCOUNT" +
	" WHERE SUB_ACNT_CODE IN (SELECT MS_SUB_ACNT_CODE FROM  FM_MAIN_SUB" +
	" WHERE MS_MAIN_ACNT_CODE = ?) AND NVL(SUB_FRZ_FLAG,'N') = 'N' AND" +
	" SUB_ACNT_CODE LIKE ? ORDER BY 1 ASC";
	
	String coverCodeLov = "SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE" +
			" COVER_FRZ_FLAG = 'N' AND COVER_TYPE = NVL(NULL,COVER_TYPE) ORDER BY 1 ASC";
	
	String coverCodeLov1 = "SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE" +
	" COVER_FRZ_FLAG = 'N' AND COVER_TYPE = NVL(NULL,COVER_TYPE) AND COVER_CODE LIKE ? ORDER BY 1 ASC";
	
	String classCodeLov = "SELECT CLASS_CODE,CLASS_NAME FROM PM_IL_CLASS WHERE CLASS_FRZ_FLAG = 'N' ORDER BY 1 ASC";
	
	String classCodeLov1 = "SELECT CLASS_CODE,CLASS_NAME FROM PM_IL_CLASS WHERE" +
			" CLASS_FRZ_FLAG = 'N' AND CLASS_CODE LIKE ? ORDER BY 1 ASC";
	
	String srcBussRangeLov="SELECT PC_CODE,PC_TYPE,PC_DESC FROM PM_CODES WHERE" +
			" PC_TYPE = ? AND NVL(PC_FRZ_FLAG,'N') = 'N'";

	String srcBussRangeLov1="SELECT PC_CODE,PC_TYPE,PC_DESC FROM PM_CODES WHERE" +
	" PC_TYPE = ? AND NVL(PC_FRZ_FLAG,'N') = 'N' AND PC_TYPE LIKE ?";
	
	String acty1codeLov = "SELECT AVAL_ACTY_CODE,AVAL_CODE,AVAL_VALUE_NAME FROM FM_ACTY_VALUE" +
			" WHERE AVAL_ACTY_CODE=?";
	
	String acty1codeLov1 = "SELECT AVAL_ACTY_CODE,AVAL_CODE,AVAL_VALUE_NAME FROM FM_ACTY_VALUE" +
	" WHERE AVAL_ACTY_CODE=? AND AVAL_ACTY_CODE LIKE '?'";
	
	String acty2codeLov = "SELECT AVAL_ACTY_CODE,AVAL_CODE,AVAL_VALUE_NAME FROM FM_ACTY_VALUE" +
	" WHERE AVAL_ACTY_CODE=?";

	String acty2codeLov1 = "SELECT AVAL_ACTY_CODE,AVAL_CODE,AVAL_VALUE_NAME FROM FM_ACTY_VALUE" +
	" WHERE AVAL_ACTY_CODE=? AND AVAL_ACTY_CODE LIKE '?'";
	
	String productCodeLov="SELECT PROD_CODE,PROD_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE IS NOT NULL ORDER BY 1 ASC";
	
	String productCodeLov1="SELECT PROD_CODE,PROD_DESC FROM PM_IL_PRODUCT"+
			" WHERE PROD_CODE IS NOT NULL AND PROD_CODE LIKE ? ORDER BY 1 ASC";
	
	String custClassLov = "SELECT CCLAS_CODE, DECODE(NVL(G_LANG_CODE,'ENG'),'ENG',CCLAS_CLASS_DESC," +
			" CCLAS_BL_CLASS_DESC) FROM PM_CUST_CLASS WHERE NVL(CCLAS_FRZ_FLAG,'N') = 'N' ORDER BY 1 ASC";
	
	String custClassLov1 = "SELECT CCLAS_CODE, DECODE(NVL(G_LANG_CODE,'ENG'),'ENG',CCLAS_CLASS_DESC," +
	" CCLASS_BL_CLASS_DESC) FROM PM_CUST_CLASS WHERE NVL(CCLAS_FRZ_FLAG,'N') = 'N'" +
	" AND CCLAS_CODE LIKE ? ORDER BY 1 ASC";
	
	
	
	
	//LI_MODULE_NAME='PILM054_APAC'
	
	
	
	
	
	

}
