package com.iii.pel.forms.PILM054_APAC;

public interface PM_IL_RI_ACCOUNT_SETUP_SQL_CONSTANTS {
	
	String MAIN_ACNT_CODE_SQL_QUERY1 = "SELECT MAIN_ACTY_CODE_1,MAIN_ACTY_CODE_2 FROM FM_MAIN_ACCOUNT WHERE MAIN_ACNT_CODE = ? ";

	String MAIN_ACNT_CODE_SQL_QUERY2 = "SELECT ACTY_NAME FROM  FM_ACTIVITY  WHERE  ACTY_CODE  = ? ";
		
	String MAIN_ACNT_CODE_SQL_QUERY3 = "SELECT ACTY_NAME FROM  FM_ACTIVITY  WHERE  ACTY_CODE  = ? ";
	
	String L_VAL_MAIN_ACNT_SQL_QUERY = "SELECT DECODE(?,'N',MAIN_ACNT_NAME, MAIN_ACNT_SHORT_NAME),DECODE(?, 'N', MAIN_ACNT_NAME, MAIN_ACNT_SHORT_NAME),MAIN_FRZ_FLAG FROM FM_MAIN_ACCOUNT WHERE  MAIN_ACNT_CODE  = ? ";
	
	String L_VAL_MAIN_ACTIVITY_SQL_QUERY = "SELECT MAIN_CTL_ACNT_FLAG,MAIN_ACTY_CODE_1,MAIN_ACTY_CODE_2, 'X' FROM FM_MAIN_ACCOUNT WHERE MAIN_ACNT_CODE = ? ";
	
}
