package com.iii.pel.forms.PLM010;

public interface PLM010_QUERY_CONSTANT {
	
	String CASSUREDMASTERDETAILS="SELECT PC.CUST_CODE,PC.CUST_NAME,PA.ASSR_CODE,PA.ASSR_NAME,PA.ASSR_OCC_CODE,PA.ASSR_FLOOR," +
			"PA.ASSR_BUILDING,PA.ASSR_STREET,PA.ASSR_ADDR1,PA.ASSR_ADDR2,PA.ASSR_ADDR3,PA.ASSR_CONTACT,PA.ASSR_PHONE," +
			"PA.ASSR_FAX,PA.ASSR_OFFICE_PHONE,PA.ASSR_PIN_NO,PA.ASSR_DOB,PA.ASSR_ID_NO,PA.ASSR_VAT_NO,PA.ASSR_REMARKS," +
			"PA.ASSR_DFLT_YN,PA.ASSR_FRZ_FLAG,PA.ROWID FROM PM_CUSTOMER PC,PM_ASSURED PA " +
			"WHERE PC.CUST_CODE = ? AND PC.CUST_NAME=? AND PA.ASSR_CODE=? " +
			"AND PA.ASSR_NAME=?";

}
