package com.iii.pel.forms.PILM039;

public interface PILM039_QUERY_CONSTANT {
	
	String P_VAL_USER_ID = "SELECT USER_DESC FROM  MENU_USER  WHERE  USER_ID  = ?";

	String ERRORCODE = "SELECT EM_FOR_MSG FROM PP_ERROR_MESSAGE WHERE EM_ERR_NO = '11302'";

	String FECTH_USER_GROUP = "SELECT DISTINCT(user_group_id) FROM menu_user,pm_il_appr_setup WHERE user_id = as_user_id AND as_user_id = ?";

	String FECTH_USER_GROUP1 = "SELECT DISTINCT(user_group_id), user_desc FROM menu_user,pm_il_appr_setup WHERE user_id = ?";

	//String FETCH_DIVISIONCODE = "SELECT DIVN_CODE FROM  PM_DIVISION  WHERE  DIVN_FRZ_FLAG  = 'N'";
	//String FETCH_DIVISION_DESC = "SELECT DIVN_NAME FROM PM_DIVISION WHERE DIVN_CODE=?";
	//[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DIVISION to FM_DIVISION. Added by : Shankar.B 31-Mar-2009
	String FETCH_DIVISIONCODE = "SELECT DIVN_CODE FROM  FM_DIVISION  WHERE  DIVN_FRZ_FLAG  = 'N'";
	String FETCH_DIVISION_DESC = "SELECT DIVN_NAME FROM FM_DIVISION WHERE DIVN_CODE=?";

	//[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DEPARTMENT to FM_DEPARTMENT. Added by : Shankar.B 31-Mar-2009
	//String FETCH_DEPTCODE = "SELECT DEPT_CODE FROM  PM_DEPARTMENT  WHERE  DEPT_DIVN_CODE  = ?";
	//String FETCH_DEPT_NAME = " select DEPT_NAME from PM_DEPARTMENT , PM_DIVISION where DEPT_DIVN_CODE = ? AND DEPT_CODE = ?";
	String FETCH_DEPTCODE = "SELECT DEPT_CODE FROM  FM_DEPARTMENT  WHERE  DEPT_DIVN_CODE  = ?";
	String FETCH_DEPT_NAME = " select DEPT_NAME from FM_DEPARTMENT , FM_DIVISION where DEPT_DIVN_CODE = ? AND DEPT_CODE = ?";

	String CHECK_DEPT_VALUE_IS_THERE = "SELECT 'X' FROM pm_il_appr_dept_setup WHERE ads_user_id = ? AND ads_divn_code = ? AND ads_dept_code = ? AND ads_fm_prod_code = ? AND ads_to_prod_code = ?";

	String FETCH_P_ENDT_DESC = "SELECT DS_DESC FROM  PM_IL_DOC_SETUP  WHERE  DS_CODE  = ?  AND DS_TYPE  = '3' ";

	String UPDATE_DETAILS_DET_CONDITION_CHECK = "SELECT 'X' FROM  PM_IL_APPR_SETUP_DET  WHERE  ASD_USER_ID  = ?  AND ASD_FM_PROD_CODE  = NVL(?, '0')  AND ASD_TO_PROD_CODE  = NVL(?, 'ZZZZZZZZZZZZ') ";

	String UPDATE_DETAILS_END_CONDITION_CHECK = "SELECT 'X' FROM  PM_IL_END_APPR_SETUP  WHERE  EAS_AS_USER_ID  = ?  AND EAS_AS_FM_PROD_CODE  = NVL(?, '0')  AND EAS_AS_TO_PROD_CODE  = NVL(?, 'ZZZZZZZZZZZZ')";

	String CHECK_DUPLICATE_RECORD = "SELECT ROWID FROM   PM_IL_APPR_SETUP WHERE (? BETWEEN AS_FM_PROD_CODE AND AS_TO_PROD_CODE OR ? BETWEEN AS_FM_PROD_CODE  AND AS_TO_PROD_CODE OR AS_FM_PROD_CODE BETWEEN ?  AND ? OR AS_TO_PROD_CODE BETWEEN ? AND ? )AND AS_USER_ID =?";

	String SELECT_COMBOBOXVALUE = "SELECT  LIV_CODE,LIV_CODE_DESC FROM PP_LIST_ITEM,PP_LIST_ITEM_VALUES WHERE LI_SYS_PARAM = LIV_SYS_PARAM AND LI_MODULE_NAME = ? AND LI_BLOCK_NAME = ? AND LI_ITEM_NAME = ?";

	String FETCH_COMBO_VALUE = "SELECT LIV_CODE,LIV_CODE_DESC FROM PP_LIST_ITEM_VALUES WHERE LIV_SYS_PARAM = (select LI_SYS_PARAM from pp_list_item where LI_MODULE_NAME = ? AND LI_ITEM_NAME LIKE '%ASD_CHAR_VALUE%') order by LIV_CODE_DESC";

	String CHECK_USER_ID = "SELECT distinct(user_id) FROM menu_user,  pm_il_appr_setup WHERE user_id = as_user_id and as_user_id =?";

	String FETCH_FROM_PRODUCT_CODE_DESC = " SELECT DISTINCT(prod_desc) FROM pm_il_product,pm_il_appr_setup WHERE prod_code = as_fm_prod_code AND as_fm_prod_code = ?";

	String FETCH_TO_PRODUCT_CODE_DESC = "SELECT DISTINCT(PROD_DESC) FROM PM_IL_PRODUCT,  PM_IL_APPR_SETUP WHERE PROD_CODE = AS_TO_PROD_CODE AND AS_TO_PROD_CODE = ?";
	//[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DEPARTMENT to FM_DEPARTMENT. Added by : Shankar.B 31-Mar-2009
	//String FETCH_DEPTNAME_FROM_DIVCODE = "select DEPT_NAME from PM_DEPARTMENT where DEPT_DIVN_CODE=? and DEPT_CODE=? and DEPT_COMP_CODE=? ";
	//String FETCTH_DIVIDION_DESC = " select DIVN_NAME from PM_DIVISION where DIVN_CODE=? ";
	String FETCH_DEPTNAME_FROM_DIVCODE = "select DEPT_NAME from FM_DEPARTMENT where DEPT_DIVN_CODE=? and DEPT_CODE=? and DEPT_COMP_CODE=? ";
	String FETCTH_DIVIDION_DESC = " select DIVN_NAME from FM_DIVISION where DIVN_CODE=? ";

	String LOAD_DIVISION_VALUES = " select ADS_DIVN_CODE from PM_IL_APPR_DEPT_SETUP where NVL(ADS_USER_ID,'X') LIKE NVL(? ,NVL(ADS_USER_ID,'X')) and NVL(ADS_FM_PROD_CODE,'X') LIKE NVL(?,NVL(ADS_FM_PROD_CODE,'X')) and NVL(ADS_TO_PROD_CODE,'X') LIKE NVL(?,NVL(ADS_TO_PROD_CODE,'X'))";
	//[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DEPARTMENT to FM_DEPARTMENT. Added by : Shankar.B 31-Mar-2009
	//String LOAD_DIVISION_VALUE_LINK_CLICK_QUERY = "select TAB1.ROWID,TAB1.*,DIVN_NAME,DEPT_NAME from PM_IL_APPR_DEPT_SETUP TAB1,PM_DIVISION,PM_DEPARTMENT where ADS_DIVN_CODE=DIVN_CODE and ADS_DEPT_CODE=DEPT_CODE AND ADS_USER_ID= ? AND ADS_FM_PROD_CODE= ? AND ADS_TO_PROD_CODE= ? ORDER BY ADS_DIVN_CODE";
	
	/*Modified by Jyoti
	String LOAD_DIVISION_VALUE_LINK_CLICK_QUERY = "select TAB1.ROWID,TAB1.*,DIVN_NAME,DEPT_NAME from PM_IL_APPR_DEPT_SETUP TAB1,FM_DIVISION,FM_DEPARTMENT where ADS_DIVN_CODE=DIVN_CODE and ADS_DEPT_CODE=DEPT_CODE AND ADS_USER_ID= ? AND ADS_FM_PROD_CODE= ? AND ADS_TO_PROD_CODE= ? ORDER BY ADS_DIVN_CODE";*/
	String LOAD_DIVISION_VALUE_LINK_CLICK_QUERY = "SELECT  ROWID, PM_IL_APPR_DEPT_SETUP.* FROM PM_IL_APPR_DEPT_SETUP WHERE ADS_USER_ID = ? AND ADS_FM_PROD_CODE = ? AND ADS_TO_PROD_CODE = ?";

	String LOAD_SEARCH_VALUE_QUERY = " select AS_USER_ID,AS_FM_PROD_CODE,AS_TO_PROD_CODE,user_group_id,user_desc, pm_il_appr_setup.rowid from menu_user, pm_il_appr_setup where user_id = as_user_id AND NVL(AS_USER_ID,'X') LIKE NVL(? ,NVL(AS_USER_ID,'X')) and NVL(AS_FM_PROD_CODE,'X') LIKE NVL(?,NVL(AS_FM_PROD_CODE,'X')) and NVL(AS_TO_PROD_CODE,'X') LIKE NVL(? ,NVL(AS_TO_PROD_CODE,'X')) and ROWNUM<25";

	String LOAD_RIGHTS_VALUE_ONCLICK_QUERY = " select TAB1.ROWID,TAB1.* ,PS_CODE_DESC FROM PM_IL_APPR_SETUP_DET TAB1,PP_SYSTEM WHERE ASD_FLAG='2' AND PS_TYPE  = 'IL_USER_PARA' AND PS_CODE  =  ASD_CODE  AND ASD_USER_ID=? AND ASD_FM_PROD_CODE=? AND ASD_TO_PROD_CODE=? order by asd_code ";

	String LOAD_LIMITS_VALUE_ONCLICK_QUERY = " select TAB1.ROWID,TAB1.* ,PS_CODE_DESC FROM PM_IL_APPR_SETUP_DET TAB1,PP_SYSTEM WHERE ASD_FLAG='1' AND PS_TYPE  = 'IL_USER_PARA' AND PS_CODE  =  ASD_CODE  AND ASD_USER_ID=? AND ASD_FM_PROD_CODE=? AND ASD_TO_PROD_CODE=? order by asd_code ";

	String ENDOSMENT_FETCH_QUERY = "select TAB1.ROWID, TAB1.* from PM_IL_END_APPR_SETUP TAB1 where EAS_AS_USER_ID=? AND EAS_AS_FM_PROD_CODE=? AND EAS_AS_TO_PROD_CODE=? ";

	String PILM039_ENDOWMENT_SUGGESTIONBOX_ALL_VALUES = "SELECT DS_CODE , DS_DESC FROM  PM_IL_DOC_SETUP  WHERE  DS_TYPE  = '3' AND ROWNUM < 25";

	String PILM039_ENDOWMENT_SUGGESTIONBOX_LIKE_VALUE = "SELECT DS_CODE , DS_DESC FROM  PM_IL_DOC_SETUP  WHERE DS_CODE LIKE ? AND  DS_TYPE  = '3' AND ROWNUM < 25";

	String PILM039_ENDOWMENT_INSERTNEW_VALUE = "INSERT INTO PM_IL_END_APPR_SETUP (EAS_AS_USER_ID,EAS_AS_FM_PROD_CODE,EAS_AS_TO_PROD_CODE,EAS_END_PROC_YN,EAS_END_APPR_YN,EAS_CR_DT,EAS_CR_UID,EAS_UPD_DT,EAS_TO_END_CODE,EAS_SYS_ID ) VALUES (?,?,?,?,?,?,?,?,?,?)";
	
	String PILM039_LOV_USERID_SUGGESTION ="SELECT USER_ID,USER_DESC FROM MENU_USER WHERE ROWNUM < 25 ORDER BY 1 ASC";
	
	String PILM039_LOV_USERID_SUGGESTION_LIKE ="SELECT USER_ID,USER_DESC FROM MENU_USER WHERE USER_ID LIKE ? OR USER_DESC LIKE ? AND ROWNUM < 25 ORDER BY 1 ASC";
	
	String PILM039_LOV_PRODUCTCODE ="SELECT PROD_CODE , PROD_DESC FROM PM_IL_PRODUCT WHERE ROWNUM < 25 ORDER BY 1 ASC";
	
	String PILM039_LOV_PRODUCTCODE_LIKE ="SELECT PROD_CODE , PROD_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE LIKE ? OR PROD_DESC LIKE ? AND ROWNUM < 25 ORDER BY 1 ASC";
	//[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DIVISION to FM_DIVISION. Added by : Shankar.B 31-Mar-2009
	//String PILM039_LOV_DIVISION_CODE = " SELECT DIVN_CODE ,DIVN_NAME FROM PM_DIVISION ORDER BY 1 ASC";
	//String PILM039_LOV_DIVISION_CODE_LIKE = " SELECT DIVN_CODE ,DIVN_NAME FROM PM_DIVISION WHERE DIVN_CODE LIKE ? ORDER BY 1 ASC";
	//String PILM039_LOV_DEPT_CODE = " SELECT DEPT_CODE , DEPT_NAME  FROM  PM_DEPARTMENT ORDER BY 1 ASC";
	//String PILM039_LOV_DEPT_CODE_LIKE = " SELECT DEPT_CODE , DEPT_NAME  FROM  PM_DEPARTMENT  WHERE  DEPT_DIVN_CODE LIKE ? ORDER BY 1 ASC ";
	String PILM039_LOV_DIVISION_CODE = " SELECT DIVN_CODE ,DIVN_NAME FROM FM_DIVISION WHERE ROWNUM < 25 ORDER BY 1 ASC";
	String PILM039_LOV_DIVISION_CODE_LIKE = " SELECT DIVN_CODE ,DIVN_NAME FROM FM_DIVISION WHERE DIVN_CODE LIKE ? OR DIVN_NAME LIKE ? AND ROWNUM < 25 ORDER BY 1 ASC";
	String PILM039_LOV_DEPT_CODE = " SELECT DEPT_CODE , DEPT_NAME  FROM  FM_DEPARTMENT WHERE ROWNUM < 25 ORDER BY 1 ASC";
	String PILM039_LOV_DEPT_CODE_LIKE = " SELECT DEPT_CODE , DEPT_NAME  FROM  FM_DEPARTMENT  WHERE  DEPT_DIVN_CODE LIKE ? AND ROWNUM < 25 ORDER BY 1 ASC ";
	
	String INSERT_COPY_PM_IL_APPR_SETUP = "INSERT INTO PM_IL_APPR_SETUP (AS_USER_ID, AS_APPR_YN, AS_FAC_ENTER_YN, AS_APPR_MAX_DISC_PERC, AS_APPR_MAX_LC_DISC_AMT, AS_APPR_ONE_DISC_PERC, AS_APPR_ONE_LC_DISC_AMT, AS_APPR_MAX_LC_SI, AS_APPR_MAX_LC_CLAIM, AS_APPR_BRK_PERC, AS_FRZ_FLAG, AS_CR_DT, AS_CR_UID, AS_UPD_DT, AS_UPD_UID, AS_CLM_REOPEN_YN, AS_RENEWAL_YN, AS_NO_OF_CLAIMS, AS_REINST_POL_YN, AS_MOD_ACC_FLAG_YN, AS_ISS_DT_BACK_DATED_YN, AS_BACK_DATED_UPTO_NO_OF_DAYS, AS_POL_DEL_YN, AS_PROP_APPR_YN, AS_REPRINT_YN, AS_FM_PROD_CODE, AS_TO_PROD_CODE) SELECT ?, AS_APPR_YN, AS_FAC_ENTER_YN, AS_APPR_MAX_DISC_PERC, AS_APPR_MAX_LC_DISC_AMT, AS_APPR_ONE_DISC_PERC, AS_APPR_ONE_LC_DISC_AMT, AS_APPR_MAX_LC_SI, AS_APPR_MAX_LC_CLAIM, AS_APPR_BRK_PERC, AS_FRZ_FLAG, AS_CR_DT, AS_CR_UID, AS_UPD_DT, AS_UPD_UID, AS_CLM_REOPEN_YN, AS_RENEWAL_YN, AS_NO_OF_CLAIMS, AS_REINST_POL_YN, AS_MOD_ACC_FLAG_YN, AS_ISS_DT_BACK_DATED_YN, AS_BACK_DATED_UPTO_NO_OF_DAYS, AS_POL_DEL_YN, AS_PROP_APPR_YN, AS_REPRINT_YN, ?, ? FROM PM_IL_APPR_SETUP WHERE AS_USER_ID = ? AND AS_FM_PROD_CODE = ? AND AS_TO_PROD_CODE = ?";
	
	String INSERT_COPY_PM_IL_APPR_DEPT_SETUP = "INSERT INTO PM_IL_APPR_DEPT_SETUP (ADS_USER_ID, ADS_DIVN_CODE, ADS_DEPT_CODE, ADS_FRZ_FLAG, ADS_CR_DT, ADS_CR_UID, ADS_UPD_DT, ADS_UPD_UID, ADS_FM_PROD_CODE, ADS_TO_PROD_CODE) SELECT ?, ADS_DIVN_CODE, ADS_DEPT_CODE, ADS_FRZ_FLAG, ADS_CR_DT, ADS_CR_UID, ADS_UPD_DT, ADS_UPD_UID, ?, ? FROM PM_IL_APPR_DEPT_SETUP WHERE ADS_USER_ID = ? AND ADS_FM_PROD_CODE = ? AND ADS_TO_PROD_CODE = ?";
	//[BugId:TRACK_PREMIAGDC_GL.10.5-00183: modified for approval group column for copying . Added by : Mallika.S, 01-Apr-2009 	
	String INSERT_COPY_PM_IL_APPR_SETUP_DET = "INSERT INTO PM_IL_APPR_SETUP_DET (ASD_USER_ID, ASD_CODE, ASD_NUM_VALUE, ASD_CHAR_VALUE, ASD_FLAG, ASD_CR_DT, ASD_CR_UID, ASD_UPD_DT, ASD_UPD_UID, ASD_FM_PROD_CODE, ASD_TO_PROD_CODE,ASD_APPR_GRP) SELECT ?, ASD_CODE, ASD_NUM_VALUE, ASD_CHAR_VALUE, ASD_FLAG, ASD_CR_DT, ASD_CR_UID, ASD_UPD_DT, ASD_UPD_UID, ?, ?, ASD_APPR_GRP FROM PM_IL_APPR_SETUP_DET WHERE ASD_USER_ID = ? AND ASD_FM_PROD_CODE = ? AND ASD_TO_PROD_CODE = ?";
	
	String INSERT_COPY_PM_IL_END_APPR_SETUP = "INSERT INTO PM_IL_END_APPR_SETUP (EAS_AS_USER_ID, EAS_AS_FM_PROD_CODE, EAS_AS_TO_PROD_CODE, EAS_END_PROC_YN, EAS_END_APPR_YN, EAS_CR_DT, EAS_CR_UID, EAS_UPD_DT, EAS_UPD_UID, EAS_FM_END_CODE, EAS_TO_END_CODE) SELECT ?, ?, ?, EAS_END_PROC_YN, EAS_END_APPR_YN, EAS_CR_DT, EAS_CR_UID, EAS_UPD_DT, EAS_UPD_UID, EAS_FM_END_CODE, EAS_TO_END_CODE FROM PM_IL_END_APPR_SETUP WHERE EAS_AS_USER_ID = ? AND EAS_AS_FM_PROD_CODE = ? AND EAS_AS_TO_PROD_CODE = ?";
	
	String LOV_DIVISION_CODE = "SELECT DIVN_CODE, DIVN_NAME FROM PM_DIVISION WHERE ROWNUM < 25 ORDER BY 1 ASC";
	
	String LOV_DIVISION_CODE_CONDITIONAL = "SELECT DIVN_CODE, DIVN_NAME FROM PM_DIVISION WHERE DIVN_CODE LIKE ? OR DIVN_NAME LIKE ? AND ROWNUM < 25 ORDER BY 1 ASC";

	String LOV_DEPARTMENT_CODE = "SELECT DEPT_CODE,DEPT_NAME FROM PM_DEPARTMENT " +
			"WHERE DEPT_NAME IN ( SELECT A.DEPT_NAME FROM PM_DEPARTMENT A WHERE A.DEPT_COMP_CODE = '001' AND A.DEPT_FRZ_FLAG = 'N' AND A.DEPT_DIVN_CODE = ? AND A.DEPT_CODE = DEPT_CODE ) AND ROWNUM < 25 {0} order by DEPT_CODE";

	String LOV_DEPARTMENT_CODE_CONDITIONAL = "SELECT DEPT_CODE, DEPT_NAME FROM PM_DEPARTMENT WHERE DIVN_CODE LIKE ? OR DEPT_NAME LIKE ? ORDER BY 1 ASC";

	String FETCH_PM_IL_APPR_SETUP_COPY = "SELECT PM_IL_APPR_SETUP.ROWID, PM_IL_APPR_SETUP.* FROM PM_IL_APPR_SETUP WHERE AS_USER_ID = ? AND AS_FM_PROD_CODE = ? AND AS_TO_PROD_CODE = ?";
	
	String PILM039_DUPLICATE_RECORD_CHECK = "SELECT DISTINCT(1) FROM PM_IL_APPR_SETUP_DET WHERE ASD_USER_ID = ? AND ASD_FM_PROD_CODE = ? AND ASD_TO_PROD_CODE =?" ;
	
	String PM_IL_END_APPR_SETUP_PRE_UPDATE="	SELECT  'X' FROM PM_IL_END_APPR_SETUP " +
			" WHERE ( ? BETWEEN  EAS_FM_END_CODE AND EAS_TO_END_CODE " +
			" OR  " +
			"  ?  BETWEEN  EAS_FM_END_CODE AND EAS_TO_END_CODE " +
			" OR  " +
			"EAS_FM_END_CODE BETWEEN ?  AND  ?  " +
			" OR  " +
			" EAS_TO_END_CODE BETWEEN ?   AND ? )" +
			" AND " +
			"( ? BETWEEN EAS_AS_FM_PROD_CODE  AND EAS_AS_TO_PROD_CODE " +
			" OR " +
			" ?  BETWEEN EAS_AS_FM_PROD_CODE  AND EAS_AS_TO_PROD_CODE " +
			" OR " +
			" EAS_AS_FM_PROD_CODE BETWEEN  ? AND ? " +
			" OR " +
			" EAS_AS_TO_PROD_CODE BETWEEN  ? AND ? ) " +
			" AND  " +
			" EAS_AS_USER_ID  = ? AND  ROWID != ? AND  " +
			" EAS_END_PROC_YN = ? AND  EAS_END_APPR_YN  = ? ";
	
	String POST_QUERY_PM_IL_END_APPR_SETUP_CURSOR_C1="SELECT DS_CODE,DS_DESC " +
			" FROM   PM_IL_DOC_SETUP WHERE  DS_TYPE ='3'";
	
	String SELECT_PM_IL_APPR_SETUP_BY_ROW_ID="  SELECT AS_FM_PROD_CODE,AS_TO_PROD_CODE,AS_USER_ID FROM PM_IL_APPR_SETUP WHERE ROWID= ? ";
	// PREMIAGDC-0135 – new queries added, Added by: Shankar Bodduluri, Dated: 13-Mar-2009
	String IL_APPR_GRP="SELECT LIV_CODE, LIV_CODE_DESC FROM PP_LIST_ITEM_VALUES WHERE LIV_SYS_PARAM = 'IL_APPR_GRP'";
	
	String ASD_APPR_GRP_FETCH_RECORD_BASED_RIGHTS = "select TAB1.ROWID,TAB1.*, PS_CODE_DESC from PM_IL_APPR_SETUP_DET TAB1,PP_SYSTEM WHERE ASD_FLAG='2' AND PS_TYPE  = 'IL_USER_PARA' AND PS_CODE  =  ASD_CODE  AND ASD_USER_ID= ? AND ASD_FM_PROD_CODE= ? AND ASD_TO_PROD_CODE= ?  order by asd_code";
	String ASD_APPR_GRP_FETCH_RECORD_BASED_LIMITS = "select TAB1.ROWID,TAB1.*, PS_CODE_DESC from PM_IL_APPR_SETUP_DET TAB1,PP_SYSTEM WHERE ASD_FLAG='1' AND PS_TYPE  = 'IL_USER_PARA' AND PS_CODE  =  ASD_CODE  AND ASD_USER_ID= ? AND ASD_FM_PROD_CODE= ? AND ASD_TO_PROD_CODE= ?  order by asd_code";

}
