package com.iii.pel.forms.PILT017;

public interface PILT017_QUERY_CONSTANTS {
    String PILT017_PT_IL_PYMT_DTLS_WHEN_CREATE_RECORD="SELECT PD_PAY_MODE FROM PT_IL_PYMT_DTLS AND PD_TXN_SYS_ID = ? ";
    String PILT017_PT_IL_PYMT_DTLS_PRE_INSERT="SELECT PIL_PD_SYS_ID.NEXTVAL FROM  DUAL  ";
    
    String PILT017_PD_DPD_REF_ID_LOV =" SELECT DISTINCT(PD_DPD_REF_ID), BANK_NAME , ROWNUM FROM PT_IL_PYMT_DTLS, FM_BANK  WHERE {0} ROWNUM <= 20 ORDER BY PD_DPD_REF_ID ";

    String PILT017_PD_BANK_NAME_LOV =" SELECT BANK_CODE,BANK_NAME FROM FM_BANK {0} ORDER BY BANK_NAME ";
 
    String PILT017_PD_BRANCH_NAME_LOV =" SELECT DISTINCT(DPD_BRANCH_NAME), DPD_BANK_NAME, DPD_REF_ID FROM PT_IL_DEPOSIT_PYMT_DTLS WHERE DPD_REF_ID = ?{0} AND DPD_BRANCH_NAME IS NOT NULL ORDER BY DPD_BRANCH_NAME ";
    
    String PILT017_FIND_BANK_DESC ="SELECT BANK_NAME FROM FM_BANK WHERE BANK_CODE = ?";
    /*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_CURRENCY to FM_CURRENCY. Added by : Mallika.S, 01-Apr-2009 */
    String PILT017_FIND_CURRENCY_DESC = "SELECT CURR_NAME FROM FM_CURRENCY where CURR_CODE = ?";
    
    String PILT017_FETCH_QUERY = "SELECT TAB1.ROWID, TAB1.* FROM PT_IL_PYMT_DTLS TAB1 WHERE PD_TXN_TYPE = ? AND PD_TXN_SYS_ID  =  ? ORDER BY TAB1.PD_SR_NO ASC";
    
    String PILT017_PT_IL_PYMT_DTLS_RECORD_CHECK = "select 1 from PT_IL_PYMT_DTLS where PD_TXN_TYPE=? AND PD_TXN_SYS_ID  = ?";
    
    String UPDATE_QUERY_PAYDTLS="UPDATE PT_IL_PYMT_DTLS SET PD_FC_AMT=?, PD_LC_AMT=? WHERE PD_TXN_TYPE = ? AND PD_TXN_SYS_ID  =  ?";
  //[PREMIAGDC-278143-VijayAnand-27-07-2009 
    String SELECTING_POL_SYS_ID_QUERY= "SELECT POL_SYS_ID     FROM   PT_IL_POLICY     WHERE  POL_NO = ?";
  //PREMIAGDC-278143-VijayAnand-27-07-2009] 
    /*Newly added by pidugu raj dt: 24-10-2020 as suggested by abhilash*/
    String PILT017_FETCH_POL_YMT_TYPE_QUERY = "SELECT POL_PYMT_TYPE FROM PT_IL_POLICY,PT_IL_DEPOSIT WHERE  POL_NO = DEP_REF_NO AND DEP_SYS_ID = ?";
    /*End Newly added by pidugu raj dt: 24-10-2020 as suggested by abhilash*/
}
