package com.iii.pel.forms.PILT017;

public interface SqlConstants {
	
//	String SAVE_BENEFICIARY_QUERY = "INSERT INTO PT_IL_POL_BENEFICIARY(PBEN_SYS_ID, PBEN_POL_SYS_ID, PBEN_SR_NO, PBEN_BNF_TYPE, PBEN_BNF_NAME, PBEN_BNF_NAME_BL, PBEN_PERC, PBEN_RELATION_CODE, PBEN_ADDRESS_1, PBEN_ADDRESS_2, PBEN_ADDRESS_3, PBEN_ADDRESS_4, PBEN_ADDRESS_5, PBEN_ADDRESS_1_BL, PBEN_ADDRESS_2_BL, PBEN_ADDRESS_3_BL, PBEN_ADDRESS_4_BL, PBEN_ADDRESS_5_BL, PBEN_REMARKS, PBEN_REMARKS_BL, PBEN_CR_UID, PBEN_UPD_UID, PBEN_CATG_CODE, PBEN_AGE, PBEN_GUARDIAN_NAME, PBEN_DEL_FLAG, PBEN_REF_ID1, PBEN_REF_ID2) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
//	
//	String RETRIEVE_BENEFICIARY_QUERY = "SELECT PBEN_SYS_ID, PBEN_POL_SYS_ID, PBEN_SR_NO, PBEN_BNF_TYPE, PBEN_BNF_NAME, PBEN_BNF_NAME_BL, PBEN_PERC, PBEN_RELATION_CODE, PBEN_ADDRESS_1, PBEN_ADDRESS_2, PBEN_ADDRESS_3, PBEN_ADDRESS_4, PBEN_ADDRESS_5, PBEN_ADDRESS_1_BL, PBEN_ADDRESS_2_BL, PBEN_ADDRESS_3_BL, PBEN_ADDRESS_4_BL, PBEN_ADDRESS_5_BL, PBEN_REMARKS, PBEN_REMARKS_BL, PBEN_CR_UID, PBEN_UPD_UID, PBEN_CATG_CODE, PBEN_AGE, PBEN_GUARDIAN_NAME, PBEN_DEL_FLAG, PBEN_REF_ID1, PBEN_REF_ID2 FROM PT_IL_POL_BENEFICIARY WHERE PBEN_POL_SYS_ID = ?";
//	
//	String RETRIEVE_PBEN_TYPE_DESC = "SELECT PS_CODE, PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = ? ";
//	
//	String RETRIEVE_POL_SYS_ID_QUERY = "SELECT PIL_POL_SYS_ID.NEXTVAL FROM DUAL";
//	
//	String RETRIEVE_SYS_ID = "SELECT PT_IL_PBEN_SYS_ID.NEXTVAL FROM   DUAL";
	
	String RETRIEVE_PAY_MODE ="SELECT PD_PAY_MODE FROM PT_IL_PYMT_DTLS WHERE PD_TXN_SYS_ID = ? and PD_TXN_TYPE = ?";

	String RETRIEVE_ON_PAY_MODE="SELECT 'X' FROM  PT_IL_PYMT_DTLS  WHERE  PD_PAY_MODE  = ? AND PD_TXN_TYPE  = ?  AND PD_TXN_SYS_ID  = ?  AND ROWID  != ? ";
	
	String RETRIEVE_CUST_SHARE_PERC="SELECT BCSH_CUST_SHARE_PERC FROM  PM_BANK_CHARGE_SETUP_HDR  WHERE  BCSH_PAY_MODE  = ? ";

	String GET_SYS_ID="SELECT PIL_PD_SYS_ID.NEXTVAL FROM  DUAL";
	
	String RECORD_EXISTS1= "SELECT 'X' FROM PT_IL_PYMT_DTLS AND PD_BANK_NAME = ? AND PD_PAY_MODE IN ( 'C' , 'D' , 'L' , 'H' , 'O' , 'SD')";

	String RECORD_EXISTS2="SELECT 'X' FROM PT_IL_PYMT_DTLS AND PD_BANK_NAME = ? AND PD_PAY_MODE IN ( 'C' , 'D' , 'L' , 'H' , 'O' , 'SD') AND ROWID != ?";

	String RECORD_EXISTS3="SELECT 'X' FROM  PT_IL_PYMT_DTLS  WHERE  PD_SR_NO  = ?  AND PD_TXN_TYPE  = ?  AND PD_TXN_SYS_ID  = ? ";

	String RECORD_EXISTS4="SELECT 'X' FROM  PT_IL_PYMT_DTLS  WHERE  PD_SR_NO  = ?  AND PD_TXN_TYPE  =? AND PD_TXN_SYS_ID  = ?  AND ROWID  != ? ";

	String BANK_DTL_QRY= "SELECT    DECODE(? , 'ENG', BANK_NAME, BANK_NAME_BL),    BANK_BR_CODE FROM  FM_BANK  WHERE  BANK_CODE  = ? ";
	
	String LC_AMT_CHK="SELECT NVL(PTP_LC_MIN_AMT, 0),    NVL(PTP_LC_MAX_AMT, 0) FROM  PM_IL_PROD_TOPUP_PARAM,   PT_IL_POLICY  WHERE  PT_IL_POLICY.POL_PROD_CODE  = PM_IL_PROD_TOPUP_PARAM.PTP_PROD_CODE  AND PT_IL_POLICY.POL_MODE_OF_PYMT  = PM_IL_PROD_TOPUP_PARAM.PTP_MODE_OF_PYMT  AND PT_IL_POLICY.POL_NO  =?";
	
	String TOP_UP_CHK="SELECT  PROD_TOPUP_YN, NVL(PROD_TOPUP_MIN_YRS,0), PROD_TOPUP_MULTIPLE" +
			" FROM  PM_IL_PRODUCT  WHERE  PROD_CODE  =  (   SELECT POL_PROD_CODE " +
			" FROM  PT_IL_POLICY   WHERE  POL_NO  = ?  ) ";

	String POL_YRS_PRM_PAID=" SELECT NVL(POL_NO_YRS_PREM_PAID,0), POL_MODE_OF_PYMT  FROM  PT_IL_POLICY  WHERE  POL_NO  = ?";
	
}

