package com.iii.pel.forms.PILM023;




public interface PM_IL_CODES_ACCOUNT_SETUP_CONSTANTS {

	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_MODULE_NAME="PILM023";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_BLOCK_NAME="PM_IL_CODES_ACCOUNT_SETUP";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_ITEM_NAME_CACS_ASSURED_TYPE="PM_IL_CODES_ACCOUNT_SETUP.CACS_ASSURED_TYPE";

	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SYS_PARAM_CACS_ASSURED_TYPE="ASSRTYPE";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_ITEM_NAME_CACS_FIRST_PREM_YN="PM_IL_CODES_ACCOUNT_SETUP.CACS_FIRST_PREM_YN";

	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SYS_PARAM_CACS_FIRST_PREM_YN="YESNO";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_ITEM_NAME_CACS_FORCE_DEPT_YN="PM_IL_CODES_ACCOUNT_SETUP.CACS_FORCE_DEPT_YN";
	
	String	PILM023_PM_IL_CODES_ACCOUNT_SETUP_SYS_PARAM_CACS_FORCE_DEPT_YN="YESNO";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_ITEM_NAME_CACS_FORCE_DIVN_YN="PM_IL_CODES_ACCOUNT_SETUP.CACS_FORCE_DIVN_YN";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SYS_PARAM_CACS_FORCE_DIVN_YN="YESNO";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_ITEM_NAME_CACS_SETUP_FOR="PM_IL_CODES_ACCOUNT_SETUP.CACS_SETUP_FOR";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SYS_PARAM_CACS_SETUP_FOR="ILSETUPFOR";
	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_ITEM_NAME_CACS_SETUP_TYPE="PM_IL_CODES_ACCOUNT_SETUP.CACS_SETUP_TYPE";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SYS_PARAM_CACS_SETUP_TYPE="SETUPTYPE";
 	
 	int PILM023_PM_IL_CODES_ACCOUNT_SETUP_ROW_NUM_TO_DIPLAY_LESS_THEN=21;
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_PERCENTILE_FOR_SELECT_LIKE="%";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_UPTO_ZZZZ="zzzzzz";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_START_FROM="0"; 
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SETUP_TYPE_P_TYPE="IL_MISC_SET";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_P_ERR_FLAG_E="E";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_YRS_START_FROM="0";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_YRS_START_TO="9999";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_P_NAME_FLAG_N="N";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_B_DUM_DISC="Discount range";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_B_DUM_CHG="Charges range";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_B_DUM_COMM="Commission range";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_B_DUM_TAX="Tax range";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_BONUS_CODE_RANGE_LABEL="Bonus Code Range";
 	
 	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SETUP_TYPE_RANGE_LABEL="Setup type range";
 	
 	
}
