package com.iii.pel.forms.PILM023;

public interface PM_IL_CODES_ACCOUNT_SETUP_QUERY_CONSTANTS {
	
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_SRC_BUS_FM_LOV=
		"SELECT    PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'SRC_BUS_TY' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND ROWNUM<? ORDER BY 1 ASC";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_SRC_BUS_FM_LOV_LIKE=
		"SELECT    PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= 'SRC_BUS_TY' AND NVL(PC_FRZ_FLAG,'N') = 'N' AND PC_CODE LIKE ? AND ROWNUM<? ORDER BY 1 ASC";

	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_BUS_FM_LOV=
		"SELECT PS_CODE,PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_BUSINES' AND ROWNUM< ? ORDER BY 1 ASC";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_BUS_FM_LOV_LIKE=
		"SELECT PS_CODE,PS_CODE_DESC FROM PP_SYSTEM WHERE PS_TYPE = 'IL_BUSINES' AND PS_CODE  LIKE ? AND ROWNUM< ? ORDER BY 1 ASC";
	//[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DIVISION to FM_DIVISION. Added by : Shankar.B 31-Mar-2009
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_DIVN_FM_CODE_LOV=
		"SELECT DIVN_CODE,DIVN_NAME FROM FM_DIVISION WHERE DIVN_COMP_CODE = ? AND 	NVL(DIVN_FRZ_FLAG, 'N') = 'N' AND"+
		"	EXISTS (SELECT 1 FROM PM_APPR_DEPT_SETUP WHERE ADS_DIVN_CODE = DIVN_CODE  AND ADS_USER_ID = NVL(NULL,ADS_USER_ID)"+
		 " AND ADS_FRZ_FLAG = 'N') AND ROWNUM<?  ORDER BY 1 ASC ";
		
	String	PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_DIVN_FM_CODE_LOV_LIKE=
		"SELECT DIVN_CODE,DIVN_NAME FROM FM_DIVISION WHERE DIVN_COMP_CODE = ? AND 	NVL(DIVN_FRZ_FLAG, 'N') = 'N' AND"+
		"	EXISTS (SELECT 1 FROM PM_APPR_DEPT_SETUP WHERE ADS_DIVN_CODE = DIVN_CODE  AND ADS_USER_ID = NVL(NULL,ADS_USER_ID)"+
		 " AND ADS_FRZ_FLAG = 'N') AND DIVN_CODE LIKE ? AND ROWNUM<?  ORDER BY 1 ASC ";	
	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DEPARTMENT to FM_DEPARTMENT. Added by : Mallika.S, 01-Apr-2009 */
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_DEPT_FM_CODE_LOV=
		"SELECT DEPT_CODE,DEPT_NAME FROM FM_DEPARTMENT WHERE DEPT_COMP_CODE = ? AND "+
		" DEPT_DIVN_CODE = ? AND 	DEPT_FRZ_FLAG  = 'N' AND EXISTS "+
		" (SELECT 1 FROM PM_APPR_DEPT_SETUP WHERE    ADS_DIVN_CODE = DEPT_DIVN_CODE AND "+
		" ADS_DEPT_CODE = DEPT_CODE AND  ADS_USER_ID = NVL(NULL,ADS_USER_ID) AND"+
		 "   ADS_FRZ_FLAG = 'N') AND ROWNUM<? ORDER BY 1 ASC ";
	/*[BugId:TRACK_PREMIAGDC_GL.10.5-00168: modified PM_DEPARTMENT to FM_DEPARTMENT. Added by : Mallika.S, 01-Apr-2009 */
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_DEPT_FM_CODE_LOV_LIKE=
		"SELECT DEPT_CODE,DEPT_NAME FROM FM_DEPARTMENT WHERE DEPT_COMP_CODE = ? AND "+
		" DEPT_DIVN_CODE = ? AND 	DEPT_FRZ_FLAG  = 'N' AND EXISTS "+
		" (SELECT 1 FROM PM_APPR_DEPT_SETUP WHERE    ADS_DIVN_CODE = DEPT_DIVN_CODE AND "+
		" ADS_DEPT_CODE = DEPT_CODE AND  ADS_USER_ID = NVL(NULL,ADS_USER_ID) AND"+
		 "   ADS_FRZ_FLAG = 'N') AND DEPT_CODE LIKE ? AND ROWNUM<? ORDER BY 1 ASC ";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_DOC_FM_TYPE_LOV=
		"SELECT   DS_CODE,DS_DESC FROM  PM_IL_DOC_SETUP WHERE 	DS_TYPE = '2' OR DS_TYPE = NULL  AND  NVL(DS_FRZ_FLAG ,'N') ='N' AND ROWNUM<? ORDER BY 1 ASC";

	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_DOC_FM_TYPE_LOV_LIKE=
		"SELECT DS_CODE, DS_DESC FROM PM_IL_DOC_SETUP WHERE NVL(DS_TYPE,'2') = '2' AND DS_CODE LIKE ? AND  NVL (DS_FRZ_FLAG ,'N') ='N' AND ROWNUM<? ORDER BY 1 ASC";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_CUST_CLS_FM_CODE_LOV=
		"SELECT CCLAS_CODE,CCLAS_CLASS_DESC FROM PM_CUST_CLASS WHERE CCLAS_FRZ_FLAG='N' AND ROWNUM<? ORDER BY 1 ASC";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_CUST_CLS_FM_CODE_LOV_LIKE=
		"SELECT CCLAS_CODE,CCLAS_CLASS_DESC FROM PM_CUST_CLASS WHERE CCLAS_FRZ_FLAG='N'AND CCLAS_CODE LIKE ? AND ROWNUM<? ORDER BY 1 ASC";
	
	String	PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_PROD_CODE_FM_LOV=
		"SELECT PROD_CODE,PROD_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE IS NOT NULL AND ROWNUM<? ORDER BY 1 ASC";
	
	
	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_PROD_CODE_FM_LOV_LIKE=
		"SELECT PROD_CODE,PROD_DESC FROM PM_IL_PRODUCT WHERE PROD_CODE IS NOT NULL AND PROD_CODE LIKE ? AND ROWNUM<? ORDER BY 1 ASC";	

	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_COVER_CODE_FM_LOV=
		"SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE COVER_FRZ_FLAG='N' AND ROWNUM<? ORDER BY 1 ASC";
	
	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_COVER_CODE_FM_LOV_LIKE=
		"SELECT COVER_CODE,COVER_DESC FROM PM_IL_COVER WHERE COVER_FRZ_FLAG='N' AND COVER_CODE LIKE ? AND ROWNUM<? ORDER BY 1 ASC";

	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_TYPE_FM_LOV_PGLH044=
		"SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_TYPE= ? AND NVL(PC_FRZ_FLAG,'N') = 'N'"+
		" UNION SELECT PS_CODE,PS_CODE_DESC  FROM PP_SYSTEM WHERE PS_TYPE=? ORDER BY 1 ASC";
	
	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_TYPE_LOV_PILH005=
		"SELECT POL_PROP_NO,TO_CHAR(POL_ISSUE_DT) FROM PT_IL_POLICY WHERE "+
		" NVL(POL_APPRV_STATUS,'N') = 'N' AND POL_NO IS NOT NULL AND POL_DS_TYPE = '1' AND ROWNUM<? ORDER BY 1 ASC";
	
	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_TYPE_LOV_PH560_A=
		"";
	String	PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_TYPE_LOV_PH571_A=
		"";
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_TYPE_FM_LOV_PGLH044_LIKE=
		"SELECT PC_CODE,PC_DESC FROM PM_CODES WHERE PC_CODE LIKE ? AND PC_TYPE= ? AND NVL(PC_FRZ_FLAG,'N') = 'N'"+
		" UNION SELECT PS_CODE,PS_CODE_DESC  FROM PP_SYSTEM WHERE PS_TYPE=? ORDER BY 1 ASC";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_TYPE_LOV_PILH005_LIKE=
		"SELECT POL_PROP_NO,TO_CHAR(POL_ISSUE_DT) FROM PT_IL_POLICY WHERE "+
		" NVL(POL_APPRV_STATUS,'N') = 'N' AND POL_NO IS NOT NULL AND POL_DS_TYPE = '1' AND POL_PROP_NO LIKE ? AND ROWNUM<? ORDER BY 1 ASC";
	
	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_TYPE_LOV_PH560_A_LIKE=
		"";
	String	PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_TYPE_LOV_PH571_A_LIKE=
		"";
	
	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_MAIN_ACNT_CODE=
	"SELECT MAIN_ACNT_CODE,MAIN_ACNT_NAME FROM FM_MAIN_ACCOUNT WHERE NVL(MAIN_FRZ_FLAG,'N') = 'N' AND ROWNUM<? ORDER BY 1 ASC";
	
	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_MAIN_ACNT_CODE_LIKE=
	"SELECT MAIN_ACNT_CODE,MAIN_ACNT_NAME FROM FM_MAIN_ACCOUNT WHERE NVL(MAIN_FRZ_FLAG,'N') = 'N'" +
	" AND (MAIN_ACNT_CODE LIKE ? OR  MAIN_ACNT_NAME LIKE ?) AND ROWNUM<? ORDER BY 1 ASC";
	
	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_SUB_ACNT_CODE=
	"SELECT SUB_ACNT_CODE,SUB_ACNT_NAME FROM FM_SUB_ACCOUNT WHERE "+
	" SUB_ACNT_CODE IN (SELECT MS_SUB_ACNT_CODE FROM  FM_MAIN_SUB "+
	" WHERE MS_MAIN_ACNT_CODE = ?) AND NVL(SUB_FRZ_FLAG,'N') = 'N' AND ROWNUM<? ORDER BY 1 ASC";
		
	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_SUB_ACNT_CODE_LIKE=
		"SELECT SUB_ACNT_CODE,SUB_ACNT_NAME FROM FM_SUB_ACCOUNT WHERE "+
		" SUB_ACNT_CODE IN (SELECT MS_SUB_ACNT_CODE FROM  FM_MAIN_SUB "+
		" WHERE MS_MAIN_ACNT_CODE = ?) AND NVL(SUB_FRZ_FLAG,'N') = 'N' AND SUB_ACNT_CODE LIKE ? AND ROWNUM<? ORDER BY 1 ASC";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_ANLY_CODE_1=
	"SELECT ANLY_CODE,ANLY_NAME FROM FM_ANALYSIS WHERE ANLY_HEAD_NO = '1' AND NVL(ANLY_FRZ_FLAG,'N') = 'N' AND ROWNUM< ? ORDER BY 1 ASC";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_ANLY_CODE_1_LIKE=
		"SELECT ANLY_CODE,ANLY_NAME FROM FM_ANALYSIS WHERE "+ 
		"ANLY_HEAD_NO = '1' AND NVL(ANLY_FRZ_FLAG,'N') = 'N' AND ANLY_CODE LIKE ? ROWNUM< ? ORDER BY 1 ASC";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_ANLY_CODE_2=
		"SELECT ANLY_CODE,ANLY_NAME FROM FM_ANALYSIS WHERE "+ 
		"ANLY_HEAD_NO = '2' AND NVL(ANLY_FRZ_FLAG,'N') = 'N' AND ROWNUM< ? ORDER BY 1 ASC";
		
		String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_ANLY_CODE_2_LIKE=
			"SELECT ANLY_CODE,ANLY_NAME FROM FM_ANALYSIS WHERE "+ 
			"ANLY_HEAD_NO = '2' AND NVL(ANLY_FRZ_FLAG,'N') = 'N' AND ANLY_CODE LIKE ? ROWNUM< ? ORDER BY 1 ASC";

		String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_ACTY_CODE=
	"SELECT AVAL_CODE,AVAL_VALUE_NAME FROM FM_ACTY_VALUE WHERE "+ 
	" AVAL_ACTY_CODE=? AND ROWNUM<? ORDER BY 1 ASC";	
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_CACS_ACTY_CODE_LIKE=
		"SELECT AVAL_CODE,AVAL_VALUE_NAME FROM FM_ACTY_VALUE WHERE "+ 
		" AVAL_ACTY_CODE=? AND AVAL_CODE LIKE ? AND ROWNUM<? ORDER BY 1 ASC";	
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SEARCH_PAGE_QUERY = 
		"SELECT CACS_MAIN_ACNT_CODE, CACS_SUB_ACNT_CODE, CACS_DIVN_CODE, ROWID FROM PM_IL_CODES_ACCOUNT_SETUP ";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_NAVIGATE_TO_MAIN_QUERY=
		"SELECT ROWID,CACS_SETUP_TYPE,CACS_BUS_FM_CODE,CACS_BUS_TO_CODE,CACS_DIVN_FM_CODE,CACS_DIVN_TO_CODE,CACS_DEPT_FM_CODE," +
		" CACS_DEPT_TO_CODE,CACS_DOC_FM_TYPE,CACS_DOC_TO_TYPE,CACS_TYPE_FM_CODE,CACS_TYPE_TO_CODE,CACS_FORCE_DIVN_YN," +
		" CACS_FORCE_DEPT_YN,CACS_MAIN_ACNT_CODE,CACS_SUB_ACNT_CODE,CACS_DIVN_CODE,CACS_DEPT_CODE,CACS_ANLY_CODE_1," +
		" CACS_ANLY_CODE_2,CACS_ACTY_CODE_1,CACS_ACTY_CODE_2,CACS_FRZ_FLAG,CACS_SETUP_FOR," +
		" CACS_ASSURED_TYPE,CACS_SRC_BUS_FM,CACS_SRC_BUS_TO,CACS_PROD_CODE_FM,CACS_PROD_CODE_TO," +
		" CACS_COVER_CODE_FM,CACS_COVER_CODE_TO,CACS_FIRST_PREM_YN,CACS_CUST_CLS_FM_CODE,CACS_CUST_CLS_TO_CODE,CACS_YRS_FM,CACS_YRS_TO" +
		" FROM PM_IL_CODES_ACCOUNT_SETUP WHERE ROWID=?";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SELECT_PS_CODE_DESC_FOR_PS_TYPE_AND_CODE=
	"SELECT PS_CODE_DESC FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'IL_MISC_SET'  AND PS_CODE  = ? ";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SELECT_MAIN_ACTY_CODE_1_AND_2_FOR_MAINACNT_CODE=
	"SELECT MAIN_ACTY_CODE_1, MAIN_ACTY_CODE_2 FROM  FM_MAIN_ACCOUNT  WHERE  MAIN_ACNT_CODE  = ? ";

	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SELECT_ACTY_NAME_FOR_UI_M_ACTY_1=
		"SELECT ACTY_NAME FROM  FM_ACTIVITY  WHERE  ACTY_CODE  = ? ";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SELECT_ACTY_NAME_FOR_UI_M_ACTY_2=
		"SELECT ACTY_NAME FROM  FM_ACTIVITY  WHERE  ACTY_CODE  = ? ";
	
	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SELECT_SELECT_MAIN_ACNT_DETAILS_MAIN_ACNT_CODE=
	"SELECT    MAIN_CTL_ACNT_FLAG,    MAIN_ACTY_CODE_1,    MAIN_ACTY_CODE_2 FROM  FM_MAIN_ACCOUNT  WHERE  MAIN_ACNT_CODE  = ? ";

	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_DUPLICATE_CHECK=
		" SELECT ROWID "+
		"  FROM   PM_IL_CODES_ACCOUNT_SETUP "+
		"  WHERE  (NVL(?,'0') BETWEEN NVL(CACS_BUS_FM_CODE,'0') AND NVL(CACS_BUS_TO_CODE,'ZZZZZZ')"+
		"   OR NVL(?,'ZZZZZZ') BETWEEN NVL(CACS_BUS_FM_CODE,'0') AND NVL(CACS_BUS_TO_CODE,'ZZZZZZ')"+
		"   OR NVL(CACS_BUS_FM_CODE,'0') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ')"+
		"   OR NVL(CACS_BUS_TO_CODE,'ZZZZZZ') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ'))"+
		  
		"  AND    (NVL(?,'0') BETWEEN NVL(CACS_DIVN_FM_CODE,'0')   AND NVL(CACS_DIVN_TO_CODE,'ZZZZZZ')"+
		"  OR NVL(?,'ZZZZZZ') BETWEEN NVL(CACS_DIVN_FM_CODE,'0') AND NVL(CACS_DIVN_TO_CODE,'ZZZZZZ')"+
		"  OR NVL(CACS_DIVN_FM_CODE,'0') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ')"+
		"  OR NVL(CACS_DIVN_TO_CODE,'ZZZZZZ') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ'))"+
		  
		"  AND    (NVL(?,'0') BETWEEN NVL(CACS_DEPT_FM_CODE,'0')   AND NVL(CACS_DEPT_TO_CODE,'ZZZZZZ')"+
		"  OR NVL(?,'ZZZZZZ') BETWEEN NVL(CACS_DEPT_FM_CODE,'0') AND NVL(CACS_DEPT_TO_CODE,'ZZZZZZ')"+
		"  OR NVL(CACS_DEPT_FM_CODE,'0') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ')"+
		"  OR NVL(CACS_DEPT_TO_CODE,'ZZZZZZ') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ'))"+
		  
		" 	AND    (NVL(?,'0')   BETWEEN NVL(CACS_DOC_FM_TYPE,'0')   AND NVL(CACS_DOC_TO_TYPE,'ZZZZZZ')"+
		"	OR NVL(?,'ZZZZZZ') BETWEEN NVL(CACS_DOC_FM_TYPE,'0') AND NVL(CACS_DOC_TO_TYPE,'ZZZZZZ')"+
		"   OR NVL(CACS_DOC_FM_TYPE,'0') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ')"+
		"   OR NVL(CACS_DOC_TO_TYPE,'ZZZZZZ') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ'))"+
		  
		"  AND    (? = CACS_SETUP_TYPE)"+

		"  AND    (? = CACS_SETUP_FOR)"+
		  
		"  AND    (NVL(?,'0') BETWEEN NVL(CACS_TYPE_FM_CODE,'0') AND NVL(CACS_TYPE_TO_CODE,'ZZZZZZ')"+
		"  OR NVL(?,'ZZZZZZ') BETWEEN NVL(CACS_TYPE_FM_CODE,'0') AND NVL(CACS_TYPE_TO_CODE,'ZZZZZZ')"+
		"  OR NVL(CACS_TYPE_FM_CODE,'0') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ')"+
		"  OR NVL(CACS_TYPE_TO_CODE,'ZZZZZZ') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ'))"+

		"  AND    (NVL(?,0) BETWEEN NVL(CACS_YRS_FM,0) AND NVL(CACS_YRS_TO,9999)"+
		"  OR NVL(?,9999) BETWEEN NVL(CACS_YRS_FM,0) AND NVL(CACS_YRS_TO,9999)"+
		"  OR NVL(CACS_YRS_FM,0)   BETWEEN NVL(?,0) AND NVL(?,9999)"+
		"  OR NVL(CACS_YRS_TO,9999) BETWEEN NVL(?,0) AND NVL(?,9999))"+
		  
		"  AND    (NVL(?,'0') BETWEEN NVL(CACS_SRC_BUS_FM,'0')   AND NVL(CACS_SRC_BUS_TO,'ZZZZZZ')"+
		"  OR NVL( ?,'ZZZZZZ') BETWEEN NVL(CACS_SRC_BUS_FM,'0') AND NVL(CACS_SRC_BUS_TO,'ZZZZZZ')"+
		"  OR NVL(CACS_SRC_BUS_FM,'0') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ')"+
		"  OR NVL(CACS_SRC_BUS_TO,'ZZZZZZ') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ'))"+     
		  
		"  AND    (NVL(?,'0') BETWEEN NVL(CACS_CUST_CLS_FM_CODE,'0')   AND NVL(CACS_CUST_CLS_TO_CODE,'ZZZZZZ')"+   //          -- ADDED BY ABHINAV FOR STM
		"         OR NVL( ?,'ZZZZZZ') BETWEEN NVL(CACS_CUST_CLS_FM_CODE,'0') AND NVL(CACS_CUST_CLS_TO_CODE,'ZZZZZZ')"+
		"	      OR NVL(CACS_CUST_CLS_FM_CODE,'0') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ')"+
		"         OR NVL(CACS_CUST_CLS_TO_CODE,'ZZZZZZ') BETWEEN NVL(?,'0') AND NVL(?,'ZZZZZZ')) "+    

		"  AND    (? BETWEEN CACS_PROD_CODE_FM   AND CACS_PROD_CODE_TO"+
		"         OR ? BETWEEN CACS_PROD_CODE_FM AND CACS_PROD_CODE_TO"+
		"         OR CACS_PROD_CODE_FM BETWEEN ? AND ?"+
		"         OR CACS_PROD_CODE_TO BETWEEN ? AND ?)"+              
		  
		"  AND    (? BETWEEN CACS_COVER_CODE_FM   AND CACS_COVER_CODE_TO"+
		"         OR ? BETWEEN CACS_COVER_CODE_FM AND CACS_COVER_CODE_TO"+
		"         OR CACS_COVER_CODE_FM BETWEEN ? AND ?"+
		"         OR CACS_COVER_CODE_TO BETWEEN ? AND ?)"+ 
		 
		"  AND    CACS_ASSURED_TYPE = ?"+
		  
		"  AND    CACS_FIRST_PREM_YN = ?";


	String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SELECT_DETAILS_FOR_MAIN_ACNT_CODE=
	"SELECT    MAIN_CTL_ACNT_FLAG,    MAIN_ACTY_CODE_1,    MAIN_ACTY_CODE_2 " +
	"FROM  FM_MAIN_ACCOUNT  WHERE  MAIN_ACNT_CODE  = ? ";
		
	String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_SELECT_MAIN_ACNT_DETAILS_FOR_MAIN_ACNT_CODE=
	"SELECT    MAIN_ACTY_CODE_1,    MAIN_ACTY_CODE_2 FROM  FM_MAIN_ACCOUNT  WHERE  MAIN_ACNT_CODE  = ?";
	
	/*String  PILM023_PM_IL_CODES_ACCOUNT_SETUP_SELECT_ACTY_NAME_FOR_UI_M_ACTY_1=
	"SELECT ACTY_NAME FROM  FM_ACTIVITY  WHERE  ACTY_CODE  = ? ";*/
    
	/*String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SELECT_ACTY_NAME_FOR_UI_M_ACTY_2=
    "SELECT ACTY_NAME FROM  FM_ACTIVITY  WHERE  ACTY_CODE  = ?";*/
    String PILM023_PM_IL_CODES_ACCOUNT_SETUP_SELECT_DETAILS_FOR_PS_CODE=
    "SELECT    PS_CODE_DESC,    PS_VALUE FROM  PP_SYSTEM  WHERE  PS_TYPE  = 'IL_MISC_SET'" +
    "  AND PS_CODE  = ? ";

}


